### ISSUE TITLE
typo : the class ReactiveDiscoveryClientServiceInstanceListSupplier don't exist

### ISSUE THREAD

**Issue by huayaoyue6** [spring-cloud/spring-cloud-commons#1001]
**Describe the bug**

While when I reading doc , I find there may be a typo  in tip section : " (such as the ReactiveDiscoveryClientServiceInstanceListSupplier provided by us)" . But there is no one class named "ReactiveDiscoveryClientServiceInstanceListSupplier " in this repository even in the whole github except in "docs/src/main/asciidoc/spring-cloud-commons.adoc" . Do you mean "DiscoveryClientServiceInstanceListSupplier"?

**Comment by huayaoyue6** [comment]
Also , the property name "spring.cloud.loadbalancer.repeat-health-check" should rename to "spring.cloud.loadbalancer.health-check.repeat-health-check"

**Comment by OlgaMaciaszek** [comment]
@huayaoyue6 Thanks for pointing this out. That class changed the name between release trains but the docs were not updated. Will fix it now.
