### ISSUE TITLE
In HealthCheckServiceInstanceListSupplier services without health checks should be ignored

### ISSUE THREAD

**Issue by chenzhiguo** [spring-cloud/spring-cloud-commons#1005]
**Is your feature request related to a problem? Please describe.**
When I use `HealthCheckServiceInstanceListSupplier`, but no health check is configured for a certain service, the call will fail. I think `HealthCheckServiceInstanceListSupplier` should ignore the service instance that does not set up a health check because they don't mean not available.
Or allow the user to configure whether it is forced to check.

**Comment by robertmcnees** [comment]
Can you clarify what you mean by 'no health check is configured for a certain service'?  What does the code look like when the user does not setup a health check?

**Comment by chenzhiguo** [comment]
In Cloud Native Service Mesh scene, some services are not published by Spring Cloud, which may not set heartbeat. @robertmcnees
