### ISSUE TITLE
new spring cloud version , "spring cloud load balanced"module put into "spring-cloud-commons" module ??

### ISSUE THREAD

**Issue by startjava** [spring-cloud/spring-cloud-commons#1014]
new spring cloud version , "spring cloud load balanced"module put into "spring-cloud-commons" module ??

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
