### ISSUE TITLE
spring-cloud-test-support missing in spring-cloud-dependencies BOM

### ISSUE THREAD

**Issue by breun** [spring-cloud/spring-cloud-commons#1017]
I am importing the `spring-cloud-dependencies` BOM to import dependency management for Spring Cloud artifacts. I also want to use `spring-cloud-test-support` in my application, but that artifact is not included in `spring-cloud-dependencies`, so I manually need to manage the version for that artifact in my application.

**Comment by spencergibb** [comment]
It would be added here https://github.com/spring-cloud/spring-cloud-commons/blob/main/spring-cloud-commons-dependencies/pom.xml

**Comment by StitzL** [comment]
I have added the dependency org.springframework.cloud:spring-cloud-test-support. 

I have not provided any test for this change. If you require one, please let me know how that might be achieved. Also, I'm looking forward to any feedback - even for such a small change. Thanks! 😄
