### ISSUE TITLE
LoadBalancerRetryContext should not be package-private

### ISSUE THREAD

**Issue by ajschutte** [spring-cloud/spring-cloud-commons#1038]
**Describe the bug**
The LoadBalancerRetryContext type is passed as a parameter in the LoadBalancerRetryPolicy, which is supposed to be implemented for custom policies. Being package-private makes that rather difficult. 

**Sample**
Any custom implementation of LoadBalancerRetryPolicy outside the LoadBalancerRetryContext package should be able to reproduce the problem.

**Comment by OlgaMaciaszek** [comment]
Makes sense @ajschutte .
