### ISSUE TITLE
Multiple RestTemplate example doesn't work

### ISSUE THREAD

**Issue by OrangeDog** [spring-cloud/spring-cloud-commons#104]
Looking at the documentation here: http://projects.spring.io/spring-cloud/spring-cloud.html#_multiple_resttemplate_objects

> If you want a `RestTemplate` that is not load balanced, create a `RestTemplate` bean and inject it as normal. To access the load balanced `RestTemplate` use the provided `@LoadBalanced` Qualifier:

However the non-balanced `RestTemplate` injection doesn't work:

    [ERROR] [main] 12:28:08.312 SpringApplication - Application startup failed
    ...
    Caused by: org.springframework.beans.factory.NoUniqueBeanDefinitionException:
      No qualifying bean of type [org.springframework.web.client.RestTemplate] is defined:
        expected single matching bean but found 2: restTemplate,loadBalancedRestTemplate

**Comment by spencergibb** [comment]
To access the non-loadbalanced `RestTemplate` you need to use the `@Primary` qualifier.

**Comment by spencergibb** [comment]
See the updated documentation here: http://cloud.spring.io/spring-cloud-static/spring-cloud.html#_multiple_resttemplate_objects
