### ISSUE TITLE
When a low-priority configuration uses '{cipher}' encryption, a high-priority unencrypted configuration will be overwritten.

### ISSUE THREAD

**Issue by aqier** [spring-cloud/spring-cloud-commons#1040]
https://github.com/spring-cloud/spring-cloud-commons/blob/d639552fb8629d6e4dfbeab2353517266d68ccf4/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/encrypt/AbstractEnvironmentDecrypt.java#L74

https://github.com/spring-cloud/spring-cloud-commons/blob/d639552fb8629d6e4dfbeab2353517266d68ccf4/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/encrypt/EnvironmentDecryptApplicationInitializer.java#L125

for example: 
application.yaml -- low priority
token: '{cipher}xxxxxxxxx'

https://config-center.spring.org -- high-priority 
token: '1234'

the low priority config will overwritten the high-priority config

**Comment by ryanjbaxter** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by aqier** [comment]
I uploaded an example at: 
[https://github.com/aqier/issues4spring-cloud-commons-1040](url)

The following are the key logs:

2021-11-17 12:13:01.161  INFO 12156 --- [           main] c.a.s.c.c.i.CustomizedConfigCenter       : A high-priority customized config center: {token=1234}

2021-11-17 12:13:02.584  INFO 12156 --- [           main] c.a.s.c.c.issues1040.DemoApplication     : token = '1111', but the correct value should be '1234'.

**Comment by aqier** [comment]
AbstractEnvironment.java:456
        @Override
	public void merge(ConfigurableEnvironment parent) {
		for (PropertySource<?> ps : parent.getPropertySources()) {
			if (!this.propertySources.contains(ps.getName())) {
				this.propertySources.addLast(ps);
			}
		}

**Comment by aqier** [comment]
The problem has been resolved in the latest version.
