### ISSUE TITLE
Spring Cloud app with docker daemon

### ISSUE THREAD

**Issue by rogerhill01234** [spring-cloud/spring-cloud-commons#105]
I am deploying a simple Spring Cloud Consul application on a machine that has docker daemon running. I am NOT running Spring application IN the docker VM - i am running it as a standalone Spring Boot application. I am trying to get this application to register with Consul. The problem is this application is registering with the private app address of docker0 network interface. The issue is in the class org.springframework.cloud.util.InetUtils. The method getFirstNonLoopbackAddress returns the first non-loopback interface's address. Obviously, this will not work when you are running a docker daemon that installs a docker bridge which creates a virtual network interface card "docker0". Is there anyway to make it work other than fixing the code in InetUtils to skip "docker*" when getting first non-loopback interfaces?

**Comment by spencergibb** [comment]
There is a property to skip interfaces: `spring.cloud.inetutils.ignoredInterfaces`.  See https://github.com/spring-cloud/spring-cloud-commons/blob/f29198bee18adece9699746740b8804080c7d973/docs/src/main/asciidoc/spring-cloud-commons.adoc#ignore-network-interfaces

**Comment by rogerhill01234** [comment]
Thanks for the prompt response. I have added spring.cloud.inetutils.ignoredInterfaces=docker0 to my application.properties file but still docker0 is getting picked up. I am using Spring Cloud Commons 1.1.0.M4 version and I do not see any code in InetUtils to consider this property.

**Comment by spencergibb** [comment]
The latest is 1.1.0.RC1

**Comment by rogerhill01234** [comment]
Thanks Spencer. The latest version of commons does not seem to work with the other consul libraries. The latest version of spring-cloud-starter-consul (which is dependent on spring-cloud-commons) does work as it is not updated to use the latest API (the packaging has changed in the new commons lib). Is there anytime line for making it compatible?

**Comment by spencergibb** [comment]
Right, commons is at RC2. You really should be using the starters and not managing the individual dependencies yourself.
