### ISSUE TITLE
Warn log LoadBalancerCaffeineWarnLogger is not obvious

### ISSUE THREAD

**Issue by Aloren** [spring-cloud/spring-cloud-commons#1050]
**Is your feature request related to a problem? Please describe.**
When I start application with spring-cloud-loadbalancer in classpath I get the following log:
```
WARN 52773 --- [           main] iguration$LoadBalancerCaffeineWarnLogger : Spring Cloud LoadBalancer is currently working with the default cache. You can switch to using Caffeine cache, by adding it and org.springframework.cache.caffeine.CaffeineCacheManager to the classpath.
```
This log does not look very obvious to me. It seems like I have some misconfiguration and using default cache with concurrenthashmap is bad and it is better to use caffeine.

**Describe the solution you'd like**
If this is a suggestion, then it seems that INFO level is sufficient. If this really a WARNING, it would be nice to describe what are the issues with using default cache or why would I prefer to switch to caffeine instead.

**Comment by OlgaMaciaszek** [comment]
@Aloren it's a warning as the default implementation is a simple map-with-ttl-based solution. It lacks the full set of functionality of a proper caching solution such as Caffeine that we would recommend for use in production. I will add some more details in the log.

**Comment by Aloren** [comment]
Thanks @OlgaMaciaszek for the quick reply. I am just thinking what can be a problem with using map-based solution in production. I understand that is not configurable and customizable the same way as Caffeine, but this is only about additional features. Are you thinking about some issues that can not be handled by map solution like too big size of cache leading to OOM? Any other cases? I am asking just to know for which cases this is a must to use Caffeine cache. Thanks!

**Comment by OlgaMaciaszek** [comment]
I would say Caffeine has definitely been much more used and tested in production, while the default solution, which at this point is Evictor, is a solution based on a `ConcurrentMap` implemented as a hash-map with added TTL support.  I would recommend using Caffeine in a production application.  However, if you would like to stick to the default solution, you would need to consider if based on the predicted cache entry volume and the TTL settings that you would be applying, a concurrent `HashMap` would be enough.

**Comment by Aloren** [comment]
>I would say Caffeine has definitely been much more used and tested in production
> you would need to consider if based on the predicted cache entry volume and the TTL settings that you would be applying, a concurrent HashMap would be enough.

Thanks, exactly what I was thinking about, but just wanted to get confirmation from your side. 👍
