### ISSUE TITLE
LoadBalancerClientConfiguration.reactorServiceInstanceLoadBalancer method > name Advice is to use by default

### ISSUE THREAD

**Issue by jounzhang** [spring-cloud/spring-cloud-commons#1055]
`org.springframework.cloud.loadbalancer.annotation.LoadBalancerClientConfiguration.reactorServiceInstanceLoadBalancer` method: 

`String name = environment.getProperty(LoadBalancerClientFactory.PROPERTY_NAME);`

`name` advice is to use by default value `spring.application.name`
when didn't get to

ref:
```
	@Bean
	@ConditionalOnMissingBean
	public ReactorLoadBalancer<ServiceInstance> reactorServiceInstanceLoadBalancer(Environment environment,
			LoadBalancerClientFactory loadBalancerClientFactory) {
		String name = environment.getProperty(LoadBalancerClientFactory.PROPERTY_NAME);
		return new RoundRobinLoadBalancer(
				loadBalancerClientFactory.getLazyProvider(name, ServiceInstanceListSupplier.class), name);
	}
```
to:
```
	@Bean
	@ConditionalOnMissingBean
	public ReactorLoadBalancer<ServiceInstance> reactorServiceInstanceLoadBalancer(Environment environment,
			LoadBalancerClientFactory loadBalancerClientFactory) {
		String name = environment.getProperty(LoadBalancerClientFactory.PROPERTY_NAME);
                name = name != null ? name : environment.getProperty("spring.application.name");
		return new RoundRobinLoadBalancer(
				loadBalancerClientFactory.getLazyProvider(name, ServiceInstanceListSupplier.class), name);
	}
```

3ks!

**Comment by OlgaMaciaszek** [comment]
Hello, @jounzhang  - thanks for submitting the issue. 
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

The idea for this is that the `name` corresponds to the `serviceId` of the application the requests are being directed to and the application they are going out of, so that would not be useful.
