### ISSUE TITLE
SameInstancePreferenceServiceInstanceListSupplier doesn't support get serviceinstances from Registry?

### ISSUE THREAD

**Issue by steverao** [spring-cloud/spring-cloud-commons#1056]
**Describe the bug**
When I see the code of  Spring Cloud LoadBalancer 3.1.0, it seems can't work in scenes of serviceInstances from Registry because of the discoveryClient will get NEW serviceInstaces object from Registry each time.

![image](https://user-images.githubusercontent.com/25423978/146643558-b5f5c388-a738-4bcd-9c4f-80807d955b4d.png)

**Comment by guerlab** [comment]
if use Nacos, the instance list is always obtained from the server. This is the characteristic of Nacos.
You can switch to other registration services.

**Comment by OlgaMaciaszek** [comment]
Yes, we operate on the list of returned instances. If the Service Registry implementation in question, returns a set of instances that contains the previously used instance (various SR implementations will do it), it will be selected. If not, a different one will be used.

**Comment by steverao** [comment]
ok, thanks!



---- 回复的原邮件 ----
| 发件人 | Olga ***@***.***> |
| 日期 | 2021年12月23日 19:35 |
| 收件人 | ***@***.***> |
| 抄送至 | Steve ***@***.******@***.***> |
| 主题 | Re: [spring-cloud/spring-cloud-commons] SameInstancePreferenceServiceInstanceListSupplier doesn't support get serviceinstances from Registry? (Issue #1056) |

Yes, we operate on the list of returned instances. If the Service Registry implementation in question, returns a set of instances that contains the previously used instance (various SR implementations will do it), it will be selected. If not, a different one will be used.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
