### ISSUE TITLE
Opt out of new actuator features

### ISSUE THREAD

**Issue by OrangeDog** [spring-cloud/spring-cloud-commons#106]
Using spring-cloud adds [new actuator endpoints](http://projects.spring.io/spring-cloud/spring-cloud.html#_endpoints).
While they can be disabled individually, this is fiddly. Is there a way to disable all of them with one command?

More importantly, there is no way to disable the new POST method for /env, or make it sensitive while the GET is not.

There's also no way to disable the RefeshScopeHealthIndicator.

Related: [spring-cloud-netflix#936](https://github.com/spring-cloud/spring-cloud-netflix/issues/936).

**Comment by dsyer** [comment]
I believe you can disable the POST to /env with `endpoints.env.enabled=false`. I'll add a conditional to the health indicator.

**Comment by OrangeDog** [comment]
But `endpoints.env.enabled=false` also disables the GET.
Being able to see the environment isn't nearly as sensitive as being able to change it.

**Comment by OrangeDog** [comment]
Testing RC3 now and while b54c8e8 works, 1824a96 does not.

**Comment by dsyer** [comment]
> 1824a96 does not.

Meaning what exactly?

**Comment by OrangeDog** [comment]
Meaning I set `management.health.refresh.enbled: false` and it is still included in the health report.

**Comment by OrangeDog** [comment]
Oh.

**Comment by dsyer** [comment]
`enbled`?

**Comment by OrangeDog** [comment]
Exactly.

**Comment by dsyer** [comment]
Probably could be fixed in IntelliJ. Manual fix is here: bda78f5
