### ISSUE TITLE
Documentation query:  To put @Configuration or not for class defined in @LoadBalancerCLient

### ISSUE THREAD

**Issue by hanct** [spring-cloud/spring-cloud-commons#1065]
Hi,
According to https://docs.spring.io/spring-cloud-commons/docs/current/reference/html/#webclinet-loadbalancer-client, 
it stated "The classes you pass as @LoadBalancerClient or @LoadBalancerClients configuration arguments should either not be annotated with @Configuration or be outside component scan scope."

But according to https://spring.io/guides/gs/spring-cloud-loadbalancer,   the SayHelloConfiguration.class passed to the @LoadBalancerClient is annotated with @Configuration and  is within component scan scope

I am basically confused.  So do we put @Configuration or not.

**Comment by OlgaMaciaszek** [comment]
Hello, @hanct. Thanks for reporting it. The annotation should not be there. [Have fixed it](https://github.com/spring-guides/gs-spring-cloud-loadbalancer/commit/494bb7144b5b10b71ed1df383c09f4068dee63bc).
