### ISSUE TITLE
Adding spring-cloud dependency changes logback-spring.xml custom configuration behavior

### ISSUE THREAD

**Issue by ssherwood** [spring-cloud/spring-cloud-commons#107]
## Moving from https://github.com/spring-projects/spring-boot/issues/5639 per @snicoll request

I am attempting to use the logback-spring.xml to configure a custom appender with a parameterized name using the springProperty tag in order to leverage profile configuration in the application.yml.  Everything works as expected until I add a Spring Cloud dependency (in my case spring-cloud-starter-hystrix).

It appears that the the lifecycle changes introduced by Spring Cloud cause the properties that were formerly provided via the application.yml to be null/empty at the point that Spring Cloud is initializing.  After Cloud bootstraps, it looks like logback is re-initialized with the expected configuration.  In my demo application, this yields two distinct log files (one with logback's logfile_IS_UNDEFINED.log clearly indicating that null was provided).

Later, I realized that I could move the properties that I needed to the bootstrap.yml, but its clear that this still has some initialization issues: https://github.com/ssherwood/spring-boot-logging-withcloud

In my specific case, we have a custom appender that needs a server configuration per profile and the undefined case is preventing the app from starting up (when it works just fine without the cloud dependency).  It seems like this behavior needs to be more consistent.

**Comment by spencergibb** [comment]
Once you put the settings in `bootstrap.yml` they do not need to be in `application.yml`. Can you try with the property only in `bootstrap.yml`?

**Comment by ssherwood** [comment]
Yes, making sure the custom logback properties are only in bootstrap.yml appears to resolve my issue.

May I suggest some kind of documentation in either the Spring Boot Logging section or Spring Cloud that makes it clear that this needs to be done when including Cloud dependencies?  This behavior actually surprised me at first since I went from a working Boot app to a NPE during startup with the addition of one dependency.

**Comment by QIvan** [comment]
@ssherwood  thank you for the issue! I've had the same problem and  I've found the solve here ) 
@dsyer where can I find documentation about keeping logback.xml on cloud-server side ?

**Comment by ryanjbaxter** [comment]
@dsyer @spencergibb is this true of any spring boot logging properties?

**Comment by dsyer** [comment]
Logging is initialized during bootstrap (it has to be, in case there are components that want to log something). It is then re-initialized in the main context if anything changed IIRC, so I expect if all log configuration is done in Spring Boot (i.e. not with `logback.xml`) then  it will work fine. It's fairly obvious (to me) that `bootstrap.properties` is needed for any log configuration if you want it to happen for all events. Documentation might be the best approach.

**Comment by ryanjbaxter** [comment]
Closed via 466a2ff
