### ISSUE TITLE
RetryAwareServiceInstanceListSupplier should not log with level 'warn'

### ISSUE THREAD

**Issue by dagerber** [spring-cloud/spring-cloud-commons#1070]
org.springframework.cloud.loadbalancer.core.RetryAwareServiceInstanceListSupplier logs a warning, if only one instance is available.
For smaller projects, it's common to have just one instance of a service, even if retry is configured.

if (LOG.isWarnEnabled()) {
  LOG.warn(String.format(
    No instances found after removing previously used service instance from the search (%s). Returning all found instances.", previousServiceInstance));
}

I suggest to log with level debug or do not log anything.

**Comment by OlgaMaciaszek** [comment]
Hi @dagerber, thanks for reporting this:

> For smaller projects, it's common to have just one instance of a service, even if retry is configured.

For these kinds of services, there's not much sense using the `RetryAwareServiceInstanceListSupplier`. If you enable it, the assumption is you expect to be able to retry on different service instances. If you have a use case where that makes sense, please provide more information.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
