### ISSUE TITLE
Whether the loadbalancer has the function of monitoring the offline change of the registration center node

### ISSUE THREAD

**Issue by weihubeats** [spring-cloud/spring-cloud-commons#1071]
**Describe the bug**
When I call the restarted service, the client-side cache service list will cause the call to the offline service. Is there a function like monitoring the registry service changes and automatically refreshing the local cache?
I currently have client side caching disabled,thanks
spring.cloud.loadbalancer.cache.enabled:false
version: spring cloud :2020.0.1
**Sample**
no Sample

**Comment by OlgaMaciaszek** [comment]
@weihubeats Yes, there is. Please take a look at the [docs](https://docs.spring.io/spring-cloud-commons/docs/current/reference/html/#instance-health-check-for-loadbalancer).
