### ISSUE TITLE
`RoundRobinLoadBalancer` will raise `ArrayIndexOutOfBoundsException` when position positive overflow

### ISSUE THREAD

**Issue by jizhuozhi** [spring-cloud/spring-cloud-commons#1074]
**Describe the bug**
`RoundRobinLoadBalancer` is using an `AtomicInteger` to represent current position, when positive overflow, we are just using `Math.abs` to fix it, it will raise `ArrayIndexOutOfBoundsException`. 

**Sample**
It's to hard to reproduce this issue in production environment, so I using jshell to reproduce it.
```jshell
jshell> import java.util.concurrent.atomic.AtomicInteger
jshell> var instances = Arrays.asList("1", "2", "3", "4", "5")
jshell> var position = new AtomicInteger(Integer.MAX_VALUE)
jshell> var pos = Math.abs(position.incrementAndGet())
pos ==> -2147483648
jshell> var instance = instances.get(pos % instances.size())
|  java.lang.ArrayIndexOutOfBoundsException：Index -3 out of bounds for length 5
|        at Arrays$ArrayList.get (Arrays.java:4165)
|        at do_it$Aux (#5:1)
|        at (#5:1)
```
It as same as [the source code](https://github.com/spring-cloud/spring-cloud-commons/blob/main/spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/RoundRobinLoadBalancer.java#L102)

**Comment by jizhuozhi** [comment]
@OlegDokuka Hello?

**Comment by jizhuozhi** [comment]
@OlgaMaciaszek Hello?

**Comment by guerlab** [comment]
This problem is caused by the overflow of int type. The maximum value of int type is 2147483647 and the minimum value is - 2147483648, math abs(-2147483648) => -2147483648

**Comment by jizhuozhi** [comment]
> This problem is caused by the overflow of int type. The maximum value of int type is 2147483647 and the minimum value is - 2147483648, math abs(-2147483648) => -2147483648

Absolutely right. In the doc of `Math.abs` we could see 
> Note that if the argument is equal to the value of Integer.MIN_VALUE, the most negative representable int value, the result is that same value, which is negative. In contrast, the absExact(int) method throws an ArithmeticException for this value.

**Comment by OlgaMaciaszek** [comment]
Hello @jizhuozhi, thanks for reporting the issue. Will take a look this week.

**Comment by jizhuozhi** [comment]
@OlgaMaciaszek Thank you for your reply, I opened a PR to fix her, can I take some of your time to review it?

**Comment by OlgaMaciaszek** [comment]
Yes, @jizhuozhi - thank. Will review it.

**Comment by OlgaMaciaszek** [comment]
Fixed.
