### ISSUE TITLE
Spring Cloud InfoEndpoint incompatible with Spring Boot 1.4 Actuator

### ISSUE THREAD

**Issue by poznachowski** [spring-cloud/spring-cloud-commons#108]
Due to the method signature change in [InfoEndpoint](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/endpoint/InfoEndpoint.java) (`invoke()` returns Info instead of Map) I'm unable to start application (Spring Boot 1.4.0.M2):
```
java.lang.NoSuchMethodError: org.springframework.boot.actuate.endpoint.InfoEndpoint.invoke()Ljava/util/Map;
	at org.springframework.cloud.autoconfigure.RefreshEndpointAutoConfiguration$InfoEndpointRebinderConfiguration.infoEndpoint(RefreshEndpointAutoConfiguration.java:170)
```

Without actuator dependency application starts fine.

**Comment by dsyer** [comment]
We kind of want to get Spring Boot 1.4 working with Brixton, but it might not be in the first release. Thanks for the explanation of why it isn't working yet.
