### ISSUE TITLE
Spring cloud config server on refresh -> logback config springProperty can not get

### ISSUE THREAD

**Issue by FUCKU** [spring-cloud/spring-cloud-commons#1083]
Project configuration is strictly regulated.
The common package contains the bootstrap.yml file, which defines the address information for the configServer.

The common package contains the logback-spring.xml file, and other microservices use the same configuration as Common.

The other microservices start normally, and the log gets the spring.application.name correctly, However, when the refresh 
endpoint is called, the log does not get the correct spring.application.name after the configuration is updated.
the log shows that XXX IS UNDEFINED.

To be exact, anything like   <springProperty scope="context" ....../> does not get the value correctly.

Is this a bug? Or what exactly am I going to do?
I tried several schemes, including changing the logback-spring.xml  file to something else and loading it in the application.yml file, but nothing worked.
Versions:
<spring-boot.version>2.5.10</spring-boot.version>
<spring-cloud.version>2020.0.5</spring-cloud.version>

I'm going to give you a demo

**Comment by guerlab** [comment]
Hello @FUCKU , please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by guerlab** [comment]
I use Nacos as the configuration center and update the configuration to invoke the refresh endpoint. The log can output normally.

logback-spring.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <springProperty scop="context" name="spring.application.name" source="spring.application.name" defaultValue=""/>

    <property name="APP_NAME" value="${spring.application.name}"/>

    <property name="CONSOLE_LOG_PATTERN" value="%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] [%level] [%logger{36}] - %msg%n"/>

    <appender name="ConsoleAppender" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>${APP_NAME}-${CONSOLE_LOG_PATTERN}</pattern>
            <charset>UTF-8</charset>
        </encoder>
    </appender>

    <root level="debug">
        <appender-ref ref="ConsoleAppender" />
    </root>

</configuration>
```

**Comment by FUCKU** [comment]
@guerlab  unfortunately, we do not have Nacos, just only configServer,i will provide it later.

**Comment by FUCKU** [comment]
@guerlab  here is Example
https://github.com/FUCKU/cloudSampleProjects
