### ISSUE TITLE
SpringCloud-LoadBalancer: How to get Header from Request?

### ISSUE THREAD

**Issue by FaustPipeDream** [spring-cloud/spring-cloud-commons#1090]
I'm using SpringCloud-LoadBalancer and want to code a loadBalancer which select instance by header "x-area".Here is the code:
```
public class CustomLoadBalancer extends RoundRobinLoadBalancer{
...
...
    @Override
    public Mono<Response<ServiceInstance>> choose(Request request){
        DefaultRequestContext requestContext = (DefaultRequestContext) request.getContext();
        RequestData clientRequest = (RequestData) requestContext.getClientRequest();
        HttpHeaders headers = clientRequest.getFirst("x-area");
        .....
    }
...
...
}
```
But the requestContext.getClientRequest() cannot cast to RequestData,and here is the debug info:
![捕获](https://user-images.githubusercontent.com/31834360/161376921-effbee45-3d48-4af9-b5a1-e4d587da779e.PNG)

The `LoadBalancerRequestFactory$lambda` cannot cast to `RequestData`,But the `arg$2` is what I need,how can I get It? or There is another way which can get header?

**Comment by OlgaMaciaszek** [comment]
Hello @FaustPipeDream , that might or might not work depending on the `RequestContext` implementation used in the scenario. 
Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue and I'll be able to verify this for you.

**Comment by FaustPipeDream** [comment]
[LoadBalancerTest](https://github.com/FaustPipeDream/LoadBalancerTest) Here is the project can reproduces  this issue.
And I found I can get Header when using Feign,But cannot get Header when using RestTemplate.
