### ISSUE TITLE
SpringCloud-LoadBalancer: Passing My Own Spring Cloud LoadBalancer Configuration

### ISSUE THREAD

**Issue by FaustPipeDream** [spring-cloud/spring-cloud-commons#1091]
SpringCloud-LoadBalancer Specifying custom configuration for load balanced services is possible through the use the `LoadBalancerClient` & `LoadBalancerClients` annotations as below.[custom-loadbalancer-configuration](https://docs.spring.io/spring-cloud-commons/docs/current/reference/html/#custom-loadbalancer-configuration)

It works fine , but I think it's not a good practice in my progect.I have to bind loadBalancer configuration to all service by myself using  `LoadBalancerClients` though they using same config (see code below) .What's more,the services can increase dynamically and I don't want to keep modifying code to add them , in this case I have to rebuild all project.
```
@Configuration
@LoadBalancerClients({@LoadBalancerClient(value = "ServiceA", configuration = CustomLoadBalancerClientConfiguration.class), @LoadBalancerClient(value = "ServiceB", configuration = CustomLoadBalancerClientConfiguration.class)})
public class MyConfiguration {

    @Bean
    @LoadBalanced
    public RestTemplate restTemplate() {
        return new RestTemplate();
    }
}
```

Is there a better way that I can get ServiceList dynamically  and custom the same config to all service?
I'm using Consul as the discovey client.

**Comment by OlgaMaciaszek** [comment]
Hello, @FaustPipeDream , the `@LoadBalancerClients` has a `defaultConfiguration` field that you can use instead.
