### ISSUE TITLE
Fix ReactiveDiscoveryClient probe() method default implementation

### ISSUE THREAD

**Issue by trajano** [spring-cloud/spring-cloud-commons#1105]
**Describe the bug**

the `.probe` method is defined as

    default void probe() {
        getServices();
    }

and `getServices()` also returns a Flux, since Flux don't do anything without a subscribe this is practically a no-op

Perhaps the interface should be defined as returning `Mono<Void>` as in

    default Mono<Void> probe() {
        return getServices()
          .then();
    }

**Comment by OlgaMaciaszek** [comment]
Hi @trajano, thanks for reporting it. This is right, however, it's actually done on purpose. The assumption is that the concrete implementations should override it, for example: https://github.com/spring-cloud/spring-cloud-consul/blob/main/spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/discovery/ConsulDiscoveryClient.java#L104 .

**Comment by OlgaMaciaszek** [comment]
Right, that was probably not the best example. There are implementations of `ReactiveDiscoveryClient` in various projects, such as `SimpleReactiveDiscoveryClient` and `SimpleReactiveDiscoveryClient` and that is where appropriate implementation should be added.

**Comment by OlgaMaciaszek** [comment]
Thanks, @trajano - that's right. Makes sense. Will mark it as a bug.

**Comment by trajano** [comment]
That change would likely trigger a lot of problems especially for those that made custom implementations already.
I would recommend at least just mark the existing method as deprecated first and have a default implementation like

```
default Mono<Void> reactiveProbe() {
  return Mono.fromRunnable(this::probe);
}
```
