### ISSUE TITLE
Wish for a way to set the state of `ServiceInstance` to implement stateful `LoadBalancer`

### ISSUE THREAD

**Issue by jizhuozhi** [spring-cloud/spring-cloud-commons#1113]
**Is your feature request related to a problem? Please describe.**
I would like to have a more general and efficient way to set the state of `ServiceInstance`.

**Describe the solution you'd like**
And two methods to `ServiceInstance` interface, to get and set the value of state with given name

```Java
	default Map<String, Object> getStates() {
		return Collections.emptyMap();
	}
```

**Additional context**

There are too many load balancing algorithms besides `RoundRobin` and `Random`, and some of them are stateful.

Before now I have an opened PR to implement `WeightedLoadBalancer` (#1111). In this PR, I added a method to the interface to get and record the current weight, but other algorithms can't always record the state this way. And now I want to implement some performance-directed load balancing algorithms that rely on the past performance state of the instance, and some load balancing algorithms may rely on multi-dimensional state.

In order to implement these load balancing algorithms, I would like to have a more general and efficient way to set the state.

**Comment by OlgaMaciaszek** [comment]
Hello, @jizhuozhi  - there already is a place where instance state is being kept - it's the `metadata` map. While we could imagine setting state programmatically in a number of formats, any state that we want to put into a service instance must be transferrable back and forth while updating and retrieving instances in Service Discovery. Therefore, a format that will be supported by a number of Service Registry solutions available in the market must be used.  The `metadata` filled is such a data container with existing service registry support.

**Comment by jizhuozhi** [comment]
In my opinion, all client-side instances are copies of the data in the registry, and the data obtained from the registry must retain the original snapshot and be immutable throughout the life cycle of the instance. So I need to avoid modifying these copies.

But the state context is different. It represents the different states of the current instance at different times in the entire life cycle of the client. It is strongly related to the client, and the instance can reset its state at any time. without considering possible inconsistencies with other clients.

**Comment by jizhuozhi** [comment]
This is the problem I expressed, what I need is a way to record the state of the instance on the client side, not a global state that requires constant interaction with the registry.

**Comment by OlgaMaciaszek** [comment]
@jihuozhi, please provide more details on what client-specific state you would like to store here.

**Comment by jizhuozhi** [comment]
> @jizhuozhi, please provide more details on what client-specific state you would like to store here.

For example, #1111 using `currentWeight` to hold the dynamic priority and the `currentWeight` is updated each time `choose` is called. And in the future, I will implement a dynamic load balancer named `EwmaLoadBalancer` which using the moving average of latency related with service instance.

They have the common characteristic that they are dynamic, non-global, client-specific.

**Comment by jizhuozhi** [comment]
Hi, @OlgaMaciaszek . The current implementation stores instance-related state in the context where the state needs to be used (such as load balancing), but I still think it makes sense to store generalized state to the instance. 

Storing the state separately from the instance will bring additional life cycle management problems. When the instance ends its life cycle due to factors such as caching, the state of the independent storage cannot be cleaned up on time, and there is a potential risk of memory leaks.

**Comment by OlgaMaciaszek** [comment]
I think this should be considered based on specific use-cases and possibly implemented as specialised subclasses on a use-case-to-use-case basis, such as the `WeightedServiceInstance` that's being discussed in https://github.com/spring-cloud/spring-cloud-commons/pull/1111.
