### ISSUE TITLE
Provide additional documentation (details) on security implications when actuator endpoints are enabled

### ISSUE THREAD

**Issue by olegz** [spring-cloud/spring-cloud-commons#1125]
Review and provide additional details on security implications of exposed actuator endpoint that gives access to Environment variables

**Comment by omernaci** [comment]
Hi @olegz, I would happy to contribute to the updating of the document. 

 I have prepared the following paragraph for the relevant part. if it is convenient, I can create a PR.

NOTE: While enabling the `POST` method for `/actuator/env` endpoint can provide flexibility and convenience in managing your application environment variables, it's critical to ensure that the endpoint is secured and monitored to prevent potential security risks. Add a `spring-boot-starter-security` dependency to configure access control for the actuator’s endpoint.

**Comment by ryanjbaxter** [comment]
A PR would be great!
