### ISSUE TITLE
Migrate org.springframework.security:spring-security-rsa to spring-security 5.x

### ISSUE THREAD

**Issue by bellidori** [spring-cloud/spring-cloud-commons#1126]
**Is your feature request related to a problem? Please describe.**
org.springframework.security:spring-security-rsa looks to be [end of life](https://github.com/spring-attic/spring-security-oauth/commit/0344de8cc75055742f638b1e476a646a6f5891d9).

**Describe the solution you'd like**
use spring-security 5 in spring-cloud-starter instead of org.springframework.security:spring-security-rsa:1.0.11.RELEASE

**Comment by OlgaMaciaszek** [comment]
Hello, @bellidori, that is a different project: https://github.com/dsyer/spring-security-rsa.
