### ISSUE TITLE
Child Application Context AOT Support

### ISSUE THREAD

**Issue by lgklein** [spring-cloud/spring-cloud-commons#1130]
I'm opening this Feature Request to go with https://github.com/spring-projects-experimental/spring-native/issues/766 and https://github.com/spring-projects/spring-framework/issues/28486 cases and see 
if we have any estimate of when we will have a compatible version.

**Comment by lgklein** [comment]
Any news about the ongoing of this case?

**Comment by OlgaMaciaszek** [comment]
This has already been implemented for the use-case that is present in SC Commons, which is load-balancing, within [this PR](https://github.com/spring-cloud/spring-cloud-commons/pull/1135).
