### ISSUE TITLE
RequestData add constructors so that we can set attributes 

### ISSUE THREAD

**Issue by liubao68** [spring-cloud/spring-cloud-commons#1141]
see https://github.com/spring-cloud/spring-cloud-gateway/issues/2720
   and https://github.com/spring-cloud/spring-cloud-gateway/pull/2721

**Comment by OlgaMaciaszek** [comment]
Already done with https://github.com/spring-cloud/spring-cloud-commons/commit/e1061af545d428a7ed426795d0151e6cc7dce90c.
