### ISSUE TITLE
request-based-sticky-session interferes with round robin balancer resulting in uneven load distribution

### ISSUE THREAD

**Issue by icguy** [spring-cloud/spring-cloud-commons#1144]
Take this scenario for instance: I use round robin balancing and [withRequestBasedStickySession](https://github.com/spring-cloud/spring-cloud-commons/blob/68d43a177ed8f2367674fff58b8aedc2e05591ce/spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/RequestBasedStickySessionServiceInstanceListSupplier.java#L40) with just two service instances. In the following scenario all requests will be sent to the same instance:

1. request: no instance preference cookie, gets sent to first instance
2. request: cookie is set to prefer the first instance, gets sent to first instance
3. request: no instance preference cookie, gets sent to first instance again.

The third request should be sent to the second service instance to allow for more evenly distributed load.

The round robin balancer [uses an internal counter](https://github.com/spring-cloud/spring-cloud-commons/blob/66b295529e138a528bbc6db36b8da25f4b94bf3b/spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/RoundRobinLoadBalancer.java#L105-L107) to keep track of which service to choose, it will increment the counter after each call and take the modulo to choose the instance. The problem is that even though the second request explicitly required to be forwarded to the specified instance the counter still gets incremented.

**Comment by jizhuozhi** [comment]
Hello, @icguy and @OlgaMaciaszek . I think there is no need to move position in `RoundRobinLoadBalancer` when there is only 1 instance, I will submit a Pull Request to fix this issue.
