### ISSUE TITLE
WARN: RefreshScope uses convention-based annotation attribute  overrides

### ISSUE THREAD

**Issue by mmoayyed** [spring-cloud/spring-cloud-commons#1148]
**Describe the bug**

- Spring Cloud 4.0.0 M4
- Spring Boot 3.0.0-M5
- Spring 6.0.0-M6

```
WARN [org.springframework.core.annotation.AnnotationTypeMapping] - <Support for convention-based annotation attribute 
overrides is deprecated and will be removed in Spring Framework 6.1. Please annotate the 'proxyMode' attribute in 
@org.springframework.cloud.context.config.annotation.RefreshScope with an appropriate @AliasFor declaration -- for example, 
@AliasFor(annotation = org.springframework.context.annotation.Scope.class).>
```

Guess the relevant issue is here:
https://github.com/spring-projects/spring-framework/issues/28760

I don't know if the suggestion is valid, but I can submit a pull request if you find this to be appropriate. 

Thank you.

**Comment by sbrannen** [comment]
> I don't know if the suggestion is valid

Yes, the suggestion is valid.

We do exactly that for `@RequestScope` in the core Spring Framework.

https://github.com/spring-projects/spring-framework/blob/6cb131ac7629cfda489d4d2367a36d44ee7b5ed2/spring-web/src/main/java/org/springframework/web/context/annotation/RequestScope.java#L61

**Comment by mmoayyed** [comment]
Thank you. @spencergibb would you be OK with a pull request to remove the warning?

**Comment by spencergibb** [comment]
PR would be welcome @mmoayyed
