### ISSUE TITLE
Forcing spring.application.name property to 'bootstrap' breaks Logback config

### ISSUE THREAD

**Issue by aantono** [spring-cloud/spring-cloud-commons#115]
If using `spring.application.name` property inside `logback-spring.xml` config to define the `<contextName>` element like this:

```
<springProperty scope="context" name="appName" source="spring.application.name"/>
<contextName>${appName}</contextName>
```

causes Logback initialization error:

```
ERROR in ch.qos.logback.classic.joran.action.ContextNameAction - Failed to rename context [bootstrap] as [spring-boot-admin] java.lang.IllegalStateException: Context has been already given a name
    at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:151)
    at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:72)
    at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:50)
    at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:106)
    at org.springframework.boot.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:277)
    at org.springframework.boot.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:255)
    at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:224)
    at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:200)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:121)
    at org.springframework.boot.context.event.EventPublishingRunListener.publishEvent(EventPublishingRunListener.java:111)
    at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:65)
    at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
    at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:330)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1191)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1180)
    ... 6 more
```

The cause of the issue lies here: https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/BootstrapApplicationListener.java#L123

During bootstrap initialization, the logback logger gets initialized the first time, and since the context is persistent within JVM, the name gets set to `bootstrap`, and the later entry in `application.yml` to the real application name causes the issue when the logback initialization takes place for the second time, attempting to reinitialize the context and changing its name, which is forbidden. :(

Can the `spring.application.name` not be hardcoded/set during the bootstrap process, or can the real application name be somehow extracted and set, to not cause Logback to blow up?  

Logback uses `default` as a context name, which does allow renaming, so maybe create a custom logging config for bootstrap context, by setting `logging.config` property to a custom file - `logback-bootstrap.xml` with the following content:

```
<?xml version="1.0" encoding="UTF-8" ?>
<configuration scan="true" scanPeriod="3 seconds">
    <include resource="org/springframework/boot/logging/logback/base.xml" />
</configuration>
```

and later unsetting/removing it to allow custom/default logback.xml config to take place?

(Any other solution to this issue?)

**Comment by spencergibb** [comment]
Try setting `spring.application.name` in `bootstrap.yml`

**Comment by aantono** [comment]
That seems to work.  Maybe it would help to emphasize the MUST of setting `spring.application.name` in `bootstrap.yml` otherwise things might get dicy. :)

BTW, I think that a custom `logging.config` for bootstrap might be appropriate, as it still tries to load `logback-spring.xml` from the classpath, as a default config file for bootstrap, which might not be quite ready for configuring during bootstrap. (otherwise much more application-specific config would have to be moved into `bootstrap.yml`)

**Comment by spencergibb** [comment]
If you are using spring-cloud-config, then you need to set it in `bootstrap.yml`.

**Comment by spencergibb** [comment]
https://github.com/spring-cloud/spring-cloud-commons/blob/master/docs/src/main/asciidoc/spring-cloud-commons.adoc#the-bootstrap-application-context

**Comment by aantono** [comment]
I guess maybe making this more prescriptive.  The current wording makes it sound totally optional as it is now:
```It is a good idea to set the spring.application.name (in bootstrap.yml or application.yml) if your application needs any application-specific configuration from the server.```

I would remove the `or application.yml` part, as it makes it sound like one does not have to put the name in `bootstrap.yml` even if that file exists, which was exactly my problem.  I've migrated a non-cloud app to use Spring Cloud, but didn't know that the name really must be moved to stay consistent.  Just a suggestion...

**Comment by spencergibb** [comment]
Yeah, that's a weird sentence.

**Comment by dsyer** [comment]
You don't have to use bootstrap.yml in order to get config from the server. What you need at different parts of the lifecycle is not transparent from the developers point of view, but there isn't much we can do about that. I like the idea of using a different logging config in bootstrap,  but for reasons beyond our control logging is a static singleton effectively so you have one good chance to configure it properly. The context name in logback is particularly resistant to being set twice. Other things work OK.

**Comment by hocklo** [comment]
Hi all,

I do it using the property resource, at startup if logback doesn't found the resource doesn't crash only ignore this resource.

But when you try to instance the  property name it's necessary set a default value like "propertyKey**:-**<defaultValue>"

```
<!-- Properties resources -->
<property resource="bootstrap.properties" />
<property resource="application.properties" />

<!-- Name of microservice -->
<property name="msName" value="${spring.application.name:-undefined}" />
```

**Comment by spencergibb** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.

**Comment by Qsimple** [comment]
Hi dear all:
  I meet another exception:  

exception
```
ERROR in ch.qos.logback.classic.joran.action.ContextNameAction - Failed to rename context [olap-registry] as [UNKNOW_APP] java.lang.IllegalStateException: Context has been already given a name
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:166)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:79)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:59)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:117)
```

logback-spring.xml

```xml
	<springProperty scope="context" name="appName"
					source="spring.application.name" defaultValue="UNKNOW_APP" />
```

as you can see, logback got the context name from `spring.application.name` in bootstrap.properties in bootstrap phase，and then want to reset it to a default value in "application" phase. I found the logback-spring.xml has been loaded twice and first time got the `spring.application.name`  and second not. Because the method getValue can't get the `spring.application.name` in following code snapshot。
org.springframework.boot.logging.logback.SpringPropertyAction: 61
```java
	@Override
	public void begin(InterpretationContext context, String elementName, Attributes attributes) throws ActionException {
		String name = attributes.getValue(NAME_ATTRIBUTE);
		String source = attributes.getValue(SOURCE_ATTRIBUTE);
		Scope scope = ActionUtil.stringToScope(attributes.getValue(SCOPE_ATTRIBUTE));
		String defaultValue = attributes.getValue(DEFAULT_VALUE_ATTRIBUTE);
		if (OptionHelper.isEmpty(name) || OptionHelper.isEmpty(source)) {
			addError("The \"name\" and \"source\" attributes of <springProperty> must be set");
		}
		ActionUtil.setProperty(context, name, getValue(source, defaultValue), scope);
	}

	private String getValue(String source, String defaultValue) {
		if (this.environment == null) {
			addWarn("No Spring Environment available to resolve " + source);
			return defaultValue;
		}
		String value = this.environment.getProperty(source);
		if (value != null) {
			return value;
		}
		int lastDot = source.lastIndexOf('.');
		if (lastDot > 0) {
			String prefix = source.substring(0, lastDot + 1);
			return this.environment.getProperty(prefix + source.substring(lastDot + 1), defaultValue);
		}
		return defaultValue;
	}
```

and, I use those spring dependency

```
spring-aop-5.1.8.RELEASE.jar
spring-beans-5.1.8.RELEASE.jar
spring-boot-2.1.6.RELEASE.jar
spring-boot-autoconfigure-2.1.6.RELEASE.jar
spring-boot-starter-2.1.6.RELEASE.jar
spring-boot-starter-jdbc-2.1.6.RELEASE.jar
spring-boot-starter-json-2.1.6.RELEASE.jar
spring-boot-starter-logging-2.1.6.RELEASE.jar
spring-boot-starter-tomcat-2.1.6.RELEASE.jar
spring-boot-starter-web-2.1.6.RELEASE.jar
spring-cloud-commons-2.1.1.RELEASE.jar
spring-cloud-context-2.1.1.RELEASE.jar
spring-cloud-starter-2.1.1.RELEASE.jar
spring-context-5.1.8.RELEASE.jar
spring-core-5.1.8.RELEASE.jar
spring-expression-5.1.8.RELEASE.jar
spring-jcl-5.1.8.RELEASE.jar
spring-jdbc-5.1.8.RELEASE.jar
spring-tx-5.1.8.RELEASE.jar
spring-web-5.1.8.RELEASE.jar
spring-webmvc-5.1.8.RELEASE.jar
```
