### ISSUE TITLE
ConfigurationPropertiesRebinder#rebind()  works in wrong result by deleting the cofniguration

### ISSUE THREAD

**Issue by winjaychan** [spring-cloud/spring-cloud-commons#1161]
the code like this:
```
@Data
@ToString
@ConfigurationProperties(value = MonitorPluginConfiguration.PREFIX)
public class MonitorPluginConfiguration {
    public static final String PREFIX = "monitor";
    private Map<String, String> plugins;
}
```

the yaml configuration in nacos:

```
monitor:
  plugins:
    p1: 1
    p2: 2
    p3: 3
    p4: 4
```
if i delete the key-value  `p4: 4` in the configuration from nacos ，the value for field MonitorPluginConfiguration#plugins will not be deleted.

the changed configuration in nacos after delete the  the key-value  `p4: 4`
```
monitor:
  plugins:
    p1: 1
    p2: 2
    p3: 3
```

I trace the code , i find the method in **`org.springframework.boot.context.properties.bind.MapBinder#merge`**，
```
        @Override
	protected Map<Object, Object> merge(Supplier<Map<Object, Object>> existing, Map<Object, Object> additional) {
		Map<Object, Object> existingMap = getExistingIfPossible(existing);
		if (existingMap == null) {
			return additional;
		}
		try {
			existingMap.putAll(additional);
			return copyIfPossible(existingMap);
		}
		catch (UnsupportedOperationException ex) {
			Map<Object, Object> result = createNewMap(additional.getClass(), existingMap);
			result.putAll(additional);
			return result;
		}
	}
```
the parmater `additional `value is `{p1=1, p2=2, p3=3}`
![image](https://user-images.githubusercontent.com/80143987/197964925-3bed5f46-ccfd-4d8d-975b-b7ca6ef16639.png)

and the variable `existingMap` value is` {p1=1, p2=2, p3=3, p4=4}`
![image](https://user-images.githubusercontent.com/80143987/197965577-920e7b2e-dacf-4a4a-bef6-c73a5e091d1e.png)

for the code `existingMap.putAll(additional)`, it will save the original value ` {p1=1, p2=2, p3=3, p4=4}`.
so the result is bad.
I think that it is good to execute `existingMap.clear()` before  executing the code `existingMap.putAll(additional)`
The code like this:

```
        @Override
	protected Map<Object, Object> merge(Supplier<Map<Object, Object>> existing, Map<Object, Object> additional) {
		Map<Object, Object> existingMap = getExistingIfPossible(existing);
		if (existingMap == null) {
			return additional;
		}
		try {
			existingMap.clear(); // add this line
			existingMap.putAll(additional);
			return copyIfPossible(existingMap);
		}
		catch (UnsupportedOperationException ex) {
			Map<Object, Object> result = createNewMap(additional.getClass(), existingMap);
			result.putAll(additional);
			return result;
		}
	}
```

this issue I have raise at https://github.com/spring-projects/spring-boot/issues/32877, but I got the reply like this

![image](https://user-images.githubusercontent.com/80143987/197993509-144839d4-a675-47b1-9c37-bc3d951c8cf2.png)

**Comment by winjaychan** [comment]
debug tracing like this,
 

- org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder#rebind(), 
- org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder#rebind(java.lang.String)
- org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory#initializeBean(java.lang.Object, java.lang.String)
- ......
- the last action org.springframework.boot.context.properties.bind.MapBinder#merge 

![image](https://user-images.githubusercontent.com/80143987/197971354-2027ba21-7774-49e1-b14b-6ed9bc4695fa.png)
![image](https://user-images.githubusercontent.com/80143987/197972206-f619ebde-6b2a-4d7c-93c8-f132e14617f8.png)
![image](https://user-images.githubusercontent.com/80143987/197972334-bfb6e6a7-1da3-4aa3-a754-bdd9cb21da5c.png)

**Comment by ryanjbaxter** [comment]
Here is the issue in Spring Boot https://github.com/spring-projects/spring-boot/issues/32877

**Comment by ryanjbaxter** [comment]
As discussed in https://github.com/spring-cloud/spring-cloud-commons/issues/818 there is nothing we can do from a Spring Cloud perspective to address this.  The best we can do is update the documentation to add a note about this limitation when performing a refresh.
