### ISSUE TITLE
Adding Bootstrap Starter Breaks Native Image

### ISSUE THREAD

**Issue by akefirad** [spring-cloud/spring-cloud-commons#1164]
**Describe the bug**
I'm not sure if this is a bug or lack of documentation (couldn't find anything regarding how to make this work).
Having a simple Spring Boot application, if you add Cloud Bootstrap Starter (to make use of `bootstrap.yml` file) it would break the native image (generated via `./gradlew nativeCompile`):
```
❯ ./build/native/nativeCompile/demo
2022-10-27T17:29:14.908+02:00  INFO 94346 --- [           main] wepromise.boot.ApplicationKt             : The following 1 profile is active: "local"
2022-10-27T17:29:14.909+02:00  WARN 94346 --- [           main] w.s.c.ServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server
2022-10-27T17:29:14.910+02:00 ERROR 94346 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Web application could not be started as there was no org.springframework.boot.web.servlet.server.ServletWebServerFactory bean defined in the context.

Action:

Check your application's dependencies for a supported servlet web server.
Check the configured web application type.
```
Is this related to parent/child context? If so the issue is resolved. Let me know if more information is needed. Thanks.

**Sample**
Download [this](https://start.spring.io/#!type=gradle-project&language=kotlin&platformVersion=3.0.0-RC1&packaging=jar&jvmVersion=17&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=native,web) from start.spring.io.
And add the dependency:
```
    implementation("org.springframework.cloud:spring-cloud-starter-bootstrap:2022.0.0-M5")
```

**Comment by akefirad** [comment]
I just found a note in Speing Native (experimental) saying “Spring Cloud Bootstrap is no longer supported.” Is that the answer to this issue?

**Comment by HaojunRen** [comment]
I also met this kind of issue. When I add `spring-cloud-starter-bootstrap`, it will be failed with following exception
```java
2022-12-24 21:48:50.798 ERROR 20940 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   :

***************************
APPLICATION FAILED TO START
***************************

Description:

Web application could not be started as there was no org.springframework.boot.web.servlet.server.ServletWebServerFactory bean defined in the context.

Action:

Check your application's dependencies for a supported servlet web server.
Check the configured web application type.
```

But it is fine with non-native-image, only in native mode. Is that really for  “Spring Cloud Bootstrap is no longer supported.”?
