### ISSUE TITLE
Endpoints instances created even though they are disabled

### ISSUE THREAD

**Issue by hocklo** [spring-cloud/spring-cloud-commons#117]
Hi,

I'll try to disable /pause, /resume and /restart endpoint but always instanced .

endpoints.pause.enabled=false
endpoints.restart.enabled=false
endpoints.resume.enabled=false

If you disable this endpoints, is necessary load this endpoints(Objects) at memory?

It's only for improve the performance at startup.

I opened the same issue in other repository (my mistake) I attach the link : [https://github.com/spring-cloud/spring-cloud-config/issues/420](url)

@spencergibb said me that it's better if I'll open the issue here.

Thank you for your time.

**Comment by dsyer** [comment]
If you can prove there's a performance issue caused by these specific beans then I guess we can take a closer look (I'm sceptical). The rationale for the current behaviour is that the endpoints can be enabled again at runtime, so you have to create the bean even if you don't use it.

**Comment by hocklo** [comment]
After checked the code, i saw  the control on the ConfigurableApplicationContext to enable or disable this endpoints at runtime. I created a fork to study this functionality, whether It going to get some improvement, It going to be shared to you.

**Comment by matosf** [comment]
I have the same issue, when using:
```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-aws</artifactId>
    <version>Dalston.RELEASE</version>
</dependency>
```

Some management endpoints will be created:
http://cloud.spring.io/spring-cloud-static/spring-cloud.html#_endpoints

I would like to disable them using configuration properties, like for Spring Boot endpoints, but cannot for most of them.

Only /refresh and /env can be disabled using:
```
endpoints.refresh.enabled=false 
endpoints.env.post.enabled=false
```

But all others (i.e. /restart, /pause, /resume) cannot.

I would expect existing properties for this:
```
endpoints.restart.enabled=false
endpoints.pause.enabled=false
endpoints.resume.enabled=false
```

I was also expect that these endpoints respected the generic way to disable all management endpoints in Spring Boot:
```
endpoints.enabled=false
```

That is not the case.


From [additional-spring-configuration-metadata.json](https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/resources/META-INF/additional-spring-configuration-metadata.json) and [LifecycleMvcAutoConfigurationTests.java](https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/test/java/org/springframework/cloud/autoconfigure/LifecycleMvcAutoConfigurationTests.java) it seems that this properties where though, but never implemented in [RefreshEndpointAutoConfiguration.java](https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/autoconfigure/RefreshEndpointAutoConfiguration.java) and [LifecycleMvcEndpointAutoConfiguration.java](https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/autoconfigure/LifecycleMvcEndpointAutoConfiguration.java).

**Comment by dsyer** [comment]
@matosf I think you are confusing about what is the actual issue here. The flags exist (now at least) and do actually disable the endpoints, they just don't prevent them from being created.

**Comment by matosf** [comment]
@dsyer You are correct, but its still confusing to see those endpoints on the startup logs. :)
So I created a PR with my shot into fixing it. Please have a look.

**Comment by dsyer** [comment]
The PR is #208. Thanks.
