### ISSUE TITLE
[document] Single-page HTML link error

### ISSUE THREAD

**Issue by dfjfj** [spring-cloud/spring-cloud-commons#1180]
The  [Single-page HTML](https://docs.spring.io/spring-cloud/docs/2021.0.5/reference/htmlsingle) link of documentation-overview.html is error.

**Comment by ryanjbaxter** [comment]
Yes this is know, try using https://docs.spring.io/spring-cloud/docs/2021.0.5/reference/htmlsingle/spring-cloud.html
