### ISSUE TITLE
Print Sensitive Data in Log

### ISSUE THREAD

**Issue by kyyung** [spring-cloud/spring-cloud-commons#1214]
https://github.com/spring-cloud/spring-cloud-commons/blob/80643ef3edb08f4b5c365508b23687bb2db97168/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/config/PropertySourceBootstrapConfiguration.java#L108

When using Spring Cloud K8S to load secrets with bootstrap enabled, this line of code will print the secret loaded from K8S to the log if root logger level is set to INFO.

**Comment by ryanjbaxter** [comment]
What version of Spring Cloud are you using?

Wouldn't this be true of any property source not just the ones from K8S?

Can you provide an example of what it prints?

The `toString` of `SecretsPropertySource` just prints the property source name and classname
https://github.com/spring-cloud/spring-cloud-kubernetes/blob/2.1.x/spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/config/SecretsPropertySource.java#L47

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
