### ISSUE TITLE
Bump spring-boot-starter dependency version to 2.7.10 for Java 20 support

### ISSUE THREAD

**Issue by faucct** [spring-cloud/spring-cloud-commons#1222]

**Comment by OlgaMaciaszek** [comment]
Just set the starter in your project. For compatibility reasons, we build `3.1.x` against Boot `2.6.x`, but we support Boot `2.7.x` as well.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
