### ISSUE TITLE
load balancing - get(Request request) should be called on delegates 

### ISSUE THREAD

**Issue by thewmo** [spring-cloud/spring-cloud-commons#1227]
I have a load balancing configuration that combines zone awareness with a method that need access to the request context/headers (sticky session):

```
@Bean
public ServiceInstanceListSupplier discoveryClientServiceInstanceListSupplier(ConfigurableApplicationContext context) {
    return ServiceInstanceListSupplier.builder()
            // get the service instances from the discovery client (Eureka in our case)
            .withDiscoveryClient()
            // if the request specifies an instance, filter for it
            .withRequestBasedStickySession()
            // of the survivors, pick one that's in our availability zone, if any
            .withZonePreference()
            .build(context);
}
```

The comments make clear the desired logic - I want same-zone routing, *unless* the sc-lb-instance-id cookie specifies the ID of an instance in a different zone. Consequently withZonePreference() is specified after request based sticky session. Otherwise it will only ever be possible to "stick" to an instance in the same zone.

However, in debugging this, it appears the ZonePreferenceServiceInstanceListSupplier is only implementing the get() method that does not take a request, and consequently the request is not propagated to the downstream delegate (in this case, the sticky session mechanism). It seems the ZonePreferenceServiceInstanceListSupplier should also implement `Flux<List<ServiceInstance>> get(Request request)` and propagate the request to the delegate.

https://github.com/spring-cloud/spring-cloud-commons/blob/51ee78555d7ae614e1d4f1ecbdaff515aa55304c/spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/ZonePreferenceServiceInstanceListSupplier.java#L53

While the documentation does not show any examples of combining ServiceInstanceListSuppliers like this, nothing I found in the docs suggest the list suppliers were not intended to be composable in this way.

**Comment by thewmo** [comment]
Potential/proposed fix in https://github.com/spring-cloud/spring-cloud-commons/commit/16ecfa10190bca07ae3b558b576da6818cd040c4

**Comment by Linzyoo** [comment]
I need this too. When and which branch will it be merged into?

**Comment by OlgaMaciaszek** [comment]
Thanks for reporting the issue @thewmo. Will discuss this with the team and get back to you.

**Comment by OlgaMaciaszek** [comment]
We agree that this makes sense. I will be marking at as an enhancement. We should update all the suppliers accordingly. The plan would be to make it `default` on `main` and opt-in in other branches. Will get it done in July.

**Comment by OlgaMaciaszek** [comment]
Done, thanks for yuor input @thewmo.  @Linzyoo, it's on all the branches, but it's by default in`main` and in `3.1.x` and `4.0.x`, you'll need to swap a property. Have added info to docs.
