### ISSUE TITLE
Bean name "commonFeatures" could have a better naming

### ISSUE THREAD

**Issue by junyongz** [spring-cloud/spring-cloud-commons#1229]
```
"org.springframework.cloud.client.CommonsClientAutoConfiguration$ActuatorConfiguration",
"org.springframework.cloud.client.CommonsClientAutoConfiguration$DiscoveryLoadBalancerConfiguration",
"discoveryClientHealthIndicator",
"discoveryCompositeHealthContributor",
"commonsFeatures",
"spring.cloud.discovery.client.health-indicator-org.springframework.cloud.client.discovery.health.DiscoveryClientHealthIndicatorProperties",
"org.springframework.cloud.client.CommonsClientAutoConfiguration",
"org.springframework.cloud.client.ReactiveCommonsClientAutoConfiguration",
 "org.springframework.cloud.client.loadbalancer.LoadBalancerDefaultMappingsProviderAutoConfiguration",
```

Comparing this `commonFeatures` bean names with others in spring cloud portfolio, it could be better.

https://github.com/spring-cloud/spring-cloud-commons/blob/51ee78555d7ae614e1d4f1ecbdaff515aa55304c/spring-cloud-commons/src/main/java/org/springframework/cloud/client/CommonsClientAutoConfiguration.java#L78

**Comment by omernaci** [comment]
I would also like to make a suggestion. It can be updated as follows: `getCommonsClientFeatures` . This name could be more descriptive than original method name. The purpose of the method to specifically identify the set of features related to client-side load balancing and service discovery.
