### ISSUE TITLE
Config client failed when profile specific file contains include property

### ISSUE THREAD

**Issue by Ferioney** [spring-cloud/spring-cloud-commons#1238]
After update from Spring Cloud 2022.0.2 to 2022.0.3 I have an issue with `spring.profiles.include` property.

I use Spring Cloud Config Client with [discovery-first-bootstrap](https://docs.spring.io/spring-cloud-config/docs/current/reference/html/#discovery-first-bootstrap) and with system properties:
```
spring.cloud.bootstrap.enabled=true
spring.cloud.config.discovery.enabled=true
spring.cloud.config.discovery.serviceId=MY-CONFIGURATION-SERVICE"
```

Config Service has the next configuration files for the service:
- application.yml
- application-prod.yml
`application-prod.yml` has `spring.profiles.include` property:
`spring.profiles.include=prodDb,prodKafka`

I run the application with an active profile `spring.profiles.active=prod`.

With Spring Cloud 2022.0.2 it works. But with Spring Cloud 2022.0.3 I have an issue:
```
org.springframework.boot.context.config.InvalidConfigDataPropertyException: Property 'spring.profiles.include' imported from location
```

It was changed in [Support for profile specific config data loading](https://github.com/spring-cloud/spring-cloud-config/pull/2260). Before that config client worked with the property `spring.profiles.include` in profile-specific configuration files.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by Ferioney** [comment]
After an update to the Spring Cloud 2022.0.4, with the same configuration as described in the first comment, I found that the application started without issues. Looks like Spring Cloud Client Config can handle the `spring.profiles.include` property as previously.

And now I see the next situation for minor versions:
- Spring Cloud 2022.0.2. `spring.profiles.include` property allowed
- Spring Cloud 2022.0.3. `spring.profiles.include` property not allowed (validation error)
- Spring Cloud 2022.0.4. `spring.profiles.include` property allowed (again :))

In three versions we have a different behaviour. It's very difficult to plan and upgrade applications to the next version of Spring Cloud. 

@ryanjbaxter Could you please describe how Spring Cloud Config Client should handle this property? And what plans for the future. Are you going to change current behaviour?
