### ISSUE TITLE
"Service Registry Actuator Endpoint URL" in doc is wrong

### ISSUE THREAD

**Issue by Pengfei-Lu** [spring-cloud/spring-cloud-commons#1240]
**Describe the bug**
The "Service Registry Actuator Endpoint URL" described in [doc](https://docs.spring.io/spring-cloud-commons/docs/current/reference/html/#service-registry-actuator-endpoint) is out-of-dated.

After the [PR](https://github.com/spring-cloud/spring-cloud-commons/pull/701) has been merged, the The "Service Registry Actuator Endpoint URL" should be `serviceregistry` instead of `service-registry`.

**Sample**
![image](https://github.com/spring-cloud/spring-cloud-commons/assets/7485400/9457dfae-1735-43b3-850c-41d8c6927b45)

![image](https://github.com/spring-cloud/spring-cloud-commons/assets/7485400/dd8891bc-db2d-4fe7-9e5f-637136699a3b)

**Comment by spencergibb** [comment]
Closing in favor of #1241
