### ISSUE TITLE
In SpringBoot3 is not eligible for getting processed by all BeanPostProcessors

### ISSUE THREAD

**Issue by SELiOTe** [spring-cloud/spring-cloud-commons#1246]
**Describe the bug**

It is normally at SpringBoot2.
After upgrade to SpringBoot3, when I start up my application, I can see those log at gateway

```
Bean 'org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration' of type [org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
Bean 'org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration$ReactorDeferringLoadBalancerFilterConfig' of type [org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration$ReactorDeferringLoadBalancerFilterConfig] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
Bean 'reactorDeferringLoadBalancerExchangeFilterFunction' of type [org.springframework.cloud.client.loadbalancer.reactive.DeferringLoadBalancerExchangeFilterFunction] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
```

And all feign client also `is not eligible for getting processed by all BeanPostProcessors`

**Comment by OlgaMaciaszek** [comment]
Hello, @SELiOTe. I believe these are just warnings? This is related to additional post-processing we're introducing and should not cause any issues.

**Comment by SELiOTe** [comment]
> Hello, @SELiOTe. I believe these are just warnings? This is related to additional post-processing we're introducing and should not cause any issues.

Yep, It just a info level log, but those alway show when start up, i just dont known it will cause any problem or not

**Comment by OlgaMaciaszek** [comment]
Right, it's just informational. It won't cause any issues.
