### ISSUE TITLE
spring-cloud-starter-archaius pulls commons-logging as transitive dependency

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-commons#126]
With SpringCloud `Brixton.SR5`, dependency tree:
```
 +- org.springframework.cloud:spring-cloud-starter-archaius:jar:1.1.5.RELEASE:compile
 |  |  +- commons-configuration:commons-configuration:jar:1.8:compile
 |  |  |  \- commons-logging:commons-logging:jar:1.1.1:compile
```

**Comment by spencergibb** [comment]
As far as I can tell, [`commons-configuration` depends](https://commons.apache.org/proper/commons-configuration/dependencies_1_10.html) on `commons-logging`. Do you want us to exclude it? Couldn't that cause potential problems?

**Comment by brenuart** [comment]
`commons-logging:commons-logging` and `commons-logging:commons-logging-api` are forbidden in the SpringBoot platform, hence the reason why they are excluded from all transitive dependencies in `spring-boot-dependencies`.

It is replaced by `org.slf4j:jcl-over-slf4j` to redirect all calls to the SLF4J façade. Having both on the classpath will make SpringBoot’s logging system complain at startup.

 

So yes, that dependency should be excluded. And no, as per SpringBoot design, it shouldn’t cause any problem.

**Comment by brenuart** [comment]
BTW, `commons-logging` has already been excluded from most transitive dependencies in `spring-cloud-netflix`...

**Comment by spencergibb** [comment]
Thanks for the spring boot lesson!

**Comment by brenuart** [comment]
Sorry, but you surprised me with your question... Anyway, that "lesson" could be useful for others reading the post ;-)

**Comment by spencergibb** [comment]
Closed via https://github.com/spring-cloud/spring-cloud-netflix/commit/c93a80f550a2f630c655d58509dc7faeb1e7b3b0
