### ISSUE TITLE
`maven-resolver-transport-http` 1.1.1 from `spring-cloud-test-support` affected by several CVEs

### ISSUE THREAD

**Issue by scordio** [spring-cloud/spring-cloud-commons#1260]
I'm using `spring-cloud-contract-wiremock` 4.0.4 which transitively pulls `maven-resolver-transport-http` 1.1.1 from `spring-cloud-test-support`.

`maven-resolver-transport-http` 1.1.1 is affected by [several CVEs](https://mvnrepository.com/artifact/org.apache.maven.resolver/maven-resolver-transport-http/1.1.1), including https://github.com/advisories/GHSA-7r82-7xv7-xcpj. Although none of these CVEs pose a concrete security risk for my use case, they still get reported in tools like GitHub Dependabot.

Would you consider upgrading the Maven Resolver artifacts to a more recent version?

**Comment by OlgaMaciaszek** [comment]
@scordio; thanks for reporting this. Fixed by https://github.com/spring-cloud/spring-cloud-commons/commit/e7702a458e6fa911810221a4008459f3ed92b159.
