### ISSUE TITLE
Move to spring-boot 3.2.0

### ISSUE THREAD

**Issue by davidkarlsen** [spring-cloud/spring-cloud-commons#1299]
**Is your feature request related to a problem? Please describe.**
Have latest spring-boot release.

**Describe the solution you'd like**
Support 3.2.x

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ryanjbaxter** [comment]
https://github.com/spring-cloud/spring-cloud-release/milestones
