### ISSUE TITLE
Meta annotation ala @SpringBootApplication

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-commons#13]
From this twitter conversation: https://twitter.com/danveloper/status/558046646765125633

The biggest question is name.  Some options:

* `@SpringCloudApplication`: fits with `@SpringBootApplication`
* `@MicroserviceApplication`: more descriptive?
* `@EnableMicroservice`

```
@EnableDiscoveryClient
@EnableCircuitBreaker
@SpringBootApplication
public @interface NewAnnotationName {
}
```

@dsyer @philwebb @joshlong @mstine @dussab

**Comment by philwebb** [comment]
The reason I went with `@SpringBootApplication` rather than an `@Enable...` name was the `@ComponentScan` and `@Configuration` meta-annotations. These pushed it beyond regular `@Enable` functionality in my mind.

Perhaps you should go with two annotations:

```java
@EnableDiscoveryClient
@EnableCircuitBreaker
@EnableXXX
@EnableYYY
public @interface EnableCloudServices {
}

@SpringBootApplication
@EnableCloudServices
public @interface SpringCloudApplication {
}

That way people still get something useful if they don't want component scanning.
```

**Comment by mstine** [comment]
I think I like @philwebb's suggestion.

**Comment by spencergibb** [comment]
:+1: for @philwebb's idea

**Comment by joshlong** [comment]
`@SpringCloudMicroservice` or `@SpringCloudApplication`

**Comment by joshlong** [comment]
I'm not sure if i like the idea of not having component scanning, though. 

Component scanning is only the enemy if you've got a BAZILLION components. (doesn't sound very microservice-y, to me). 

If the bean definition doesn't have a stereotype annotation on it, it won't get picked up anyway. 

I understand that you're trying to get symmetry with (`@EnableAutoConfiguration / @ComponentScan / @Configuration`) vs `@SpringBootApplication`, but if they really don't want component-scanning, then let 'em just type `@SpringBootApplication @EnableDiscoveryClient  @EnableDiscoveryClient @EnableCircuitBreaker..` individually. Do we need another annotation? another piece of API surface area that you can never take back?

**Comment by spencergibb** [comment]
@joshlong do you mean "if they really want component-scanning"?  `@SpringBootApplication` has that already

**Comment by philwebb** [comment]
I think he means he can't see why you wouldn't want component scanning.

**Comment by joshlong** [comment]
yah, thanks Phil. heh. and if they _really_ don't, then just break down @SpringBootApplication into its constituent parts (sans `@ComponentScan`.. don't see the need for what amounts to yet-another-type-alias, an annotation macro)

**Comment by philwebb** [comment]
Some reasons why I'm keen on `@SpringCloudApplication` vs `@SpringCloudMicroservice`:
* `@SpringCloudApplication` has parity with `@SpringBootApplication`.
* Microservice feels like an architectural choice. You might well use Spring Cloud but not microservices
* Microservices seem a bit buzz-wordy at the moment. I think we might see microservice fatigue soon :)
* There is less overlap with the existing `@Service` annotation.

**Comment by joshlong** [comment]
`@SpringCloudApplication` sounds nice too. More apparent  - like all Spring names.

OTOH, what would you use Spring Cloud for besides microservices (cloud-native, microservice-style services)? Why isn't this stuff just part of Spring Boot, then? 

good point about teh collision between it and `@Service`, though. OTOH, `@Service` is more documentational than opinionated. You could for 99% of cases interchange `@Component` w/ `@Service` w/ no ill-effects. It's a true (UML) stereotype.  SC & SB are opinionated. What's SC's opinion? that your microservice needs certain supporting services, like discovery and the circuit breaker

**Comment by spencergibb** [comment]
I like "cloud native" better than microservice.  I think its more descriptive and doesn't have the awkwardness of having "micro" in the name.

**Comment by mstine** [comment]
That would be exactly the reason why my book was about cloud-native apps
and not microservices.

If it's @SpringCloudApplication then I'd go all in with it be
@SpringBootApplication + cloud goodness.

Please no one suggest @SpringCloudNativeApplication. ;-)

On Friday, February 13, 2015, Spencer Gibb <notifications@github.com> wrote:

> I like "cloud native" better than microservice. I think its more
> descriptive and doesn't have the awkwardness of having "micro" in the name.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spring-cloud/spring-cloud-commons/issues/13#issuecomment-74352401>
> .
>


-- 
Matt Stine
Senior Product Manager
Pivotal
901-493-5546 | Skype: mstine1978 | mstine@pivotal.io

**Comment by dussab** [comment]
I like Phil's suggestion of @SpringCloudApplication and I definitely think that SpringCloud can cover a wide range of cloud-native architectures (microservices just being one of many types of cloud architectures).
