### ISSUE TITLE
 SLF4JBridgeHandler is removed after (POST) /refresh

### ISSUE THREAD

**Issue by philwebb** [spring-cloud/spring-cloud-commons#131]
Originally raised on [the Spring Boot issue tracker](https://github.com/spring-projects/spring-boot/issues/6885):

> We just started to use spring cloud config and i've realized that after a (POST) /refresh request every logging using JUL goes to the void. I did some debugging and i saw the LoggingSystem.cleanUp() get's called after the context got refreshed which removes the JUL bridge.

**Comment by ssi-hu-adam-balazs** [comment]
thx ^^

**Comment by dsyer** [comment]
Seems like it's an issue with `LoggingSystem.cleanUp()` to me (or more likely with JUL, but we don't control that). I tried it with the latest Boot and Cloud combo because of https://github.com/spring-cloud/spring-cloud-commons/issues/125, but it's still broken.

**Comment by dsyer** [comment]
Actually I haven't managed to test this with #125 yet. It looks like it ought to be fixed, but I'm having some issues getting the dependency management to work.

**Comment by dsyer** [comment]
Should be fixed in d4fd2b7a
