### ISSUE TITLE
Bean is not eligible for getting processed by all BeanPostProcessors

### ISSUE THREAD

**Issue by JaroslawDembek** [spring-cloud/spring-cloud-commons#1332]
After migration to:
`spring-cloud-commons/loadbalancer:4.1.0`
`spring-boot:3.2.2`
`spring-webflux:6.1.3`
from:
`spring-cloud-commons/loadbalancer:4.0.4`
`spring-boot:3.1.8`
`spring-webflux:6.0.16`

We experience many warnings for different beans from:
`logger:"o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker"`
Some examples:
Bean 'reactorDeferringLoadBalancerExchangeFilterFunction' of type [org.springframework.cloud.client.loadbalancer.reactive.DeferringLoadBalancerExchangeFilterFunction] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected into a currently created BeanPostProcessor [`loadBalancerWebClientBuilderBeanPostProcessor`]? Check the corresponding BeanPostProcessor declaration and its dependencies.

Bean 'defaultsBindHandlerAdvisor' of type [org.springframework.cloud.commons.config.DefaultsBindHandlerAdvisor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected into a currently created BeanPostProcessor [`lbRestClientPostProcessor`]? Check the corresponding BeanPostProcessor declaration and its dependencies.

General funtionality of loadbalancer is intact.

I believe it is continuation of:
https://github.com/spring-cloud/spring-cloud-commons/issues/1246
It is a little bit like Spring-Cloud goes against Spring.
At first it looks like app problem when one use bean post processing. These kind of warnings are for a reason - ignoring them could lead to issues that are very, very hard to debug.
IMO ignoring this, and I reckon adding new warnings (RestClient) is a risky direction.

**Comment by OlgaMaciaszek** [comment]
Hello @JaroslawDembek, thanks for reporting the issue. It won't be there any longer for `RestClient`. We've changed the implementation from `4.1.1`. When it comes to the `DeferringLoadBalancerExchangeFilterFunction`, the warning just informs, it's not eligible for auto-proxying. For that function, we don't need it to be.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by ichenfeng** [comment]
[WARN ] [2024-04-15 15:11:22.900] [main] [o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker:429] -  Bean 'org.springframework.cloud.client.loadbalancer.LoadBalancerAutoConfiguration$DeferringLoadBalancerInterceptorConfig' of type [org.springframework.cloud.client.loadbalancer.LoadBalancerAutoConfiguration$DeferringLoadBalancerInterceptorConfig] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). The currently created BeanPostProcessor [lbRestClientPostProcessor] is declared through a non-static factory method on that class; consider declaring it as static instead. 
[WARN ] [2024-04-15 15:11:22.906] [main] [o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker:437] -  Bean 'deferringLoadBalancerInterceptor' of type [org.springframework.cloud.client.loadbalancer.DeferringLoadBalancerInterceptor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected into a currently created BeanPostProcessor [lbRestClientPostProcessor]? Check the corresponding BeanPostProcessor declaration and its dependencies.

**Comment by OlgaMaciaszek** [comment]
Yes, that's just a warning. We are aware of it. We do not want this bean to be further post-processed.
