### ISSUE TITLE
Warning log at startup : AnnotationBeanNameGenerator - Support for convention-based stereotype names is deprecated and will be removed in a future version of the framework

### ISSUE THREAD

**Issue by GuiF007** [spring-cloud/spring-cloud-commons#1347]
At startup, we have this log :
[WARN] 10:07:19 [ANON][] o.s.context.annotation.AnnotationBeanNameGenerator - Support for convention-based stereotype names is deprecated and will be removed in a future version of the framework. Please annotate the 'value' attribute in @org.springframework.cloud.loadbalancer.annotation.LoadBalancerClient with @AliasFor(annotation=Component.class) to declare an explicit alias for @Component's 'value' attribute.
 
when using @LoadBalancerClient annotation.

This warning has been added from Spring Framework 6.1.5 :
https://github.com/spring-projects/spring-framework/commit/bfd918d16c4042c2dbfcecaea4c5b063b11d63a5

**Comment by OlgaMaciaszek** [comment]
Hello @GuiF007, thanks for reporting the issue. This should not be a problem for us since we register corresponding beans manually anyhow.
