### ISSUE TITLE
Broken "Try This Tutorial" link on the https://spring.io/cloud

### ISSUE THREAD

**Issue by snicoll** [spring-cloud/spring-cloud-commons#1353]
See https://github.com/spring-projects/spring-framework/issues/32762

**Comment by ryanjbaxter** [comment]
The link is actually located here https://github.com/spring-io/spring-website/blob/main/src/templates/cloud-template.tsx#L261.  I will open an issue there and will try and figure out where this should point to.

https://github.com/spring-io/spring-website/issues/299
