### ISSUE TITLE
FileSystemProvider/FileSystem Loading Issues

### ISSUE THREAD

**Issue by ulmermark** [spring-cloud/spring-cloud-commons#136]
I am wondering where to start looking for solving the following issue I am seeing:

SpringBoot application using ( full gradle build attached)

- 		springBootVersion = '1.4.0.RELEASE'
- 		springCloudVersion = 'Brixton.RELEASE'

Application has a CommandLineRunner implementation that "starts" a class on application startup.

The "start" method uses java.nio.file classes to "guarantee" the file system provider is available based on configured file ( file:///, s3:///, etc..) based on the application yml.

I use a 3rd party java.nio..FileSystemProvider implementation (for S3) when running in "mycloud" profile.  

I use the native java nio file system provider ( file:///) when running in "default" profile (no eureka and no config server) 

When running in default profile and with the application configured to use "file:///....." to store a file all works well using the java.nio.file library.

When I run in profile "mycloud" , I configure the application to use "s3:///bucket/..." ( via an application yml in the config server) and now the code throws the following even though the JAR for the s3 provider is located in the FAT jar for the application

**_Caused by: java.nio.file.ProviderNotFoundException: Provider "s3" not found_**

Code uses the following calls to verify and get the file system:  Where schema is based on configured file location ( file:///, s3:///, .....)

_this.fs = FileSystems.getFileSystem(new URI(scheme+":///"));		
this.fs = FileSystems.newFileSystem(new URI(scheme+":///"), new HashMap<String,Object>(), Thread.currentThread().getContextClassLoader());_
	

I add a bit of code to insure the 3rd party FileSystemProvider is loaded in a static{} block in a class that is loaded via the Spring Context, and the application now finds the 3rd party FileSystemProvider when the class is "started" from a CommandLineRunner implementation.  All's good..

I now run the application in "default" profile ( no Eureka, no ConfigServer and using a file system of file:///.....)  and the application fails to start with the following.  The application can not find the native "file" FileSystemProvider

**_Caused by: java.nio.file.ProviderNotFoundException: Provider "file" not found_**

There are definitely behavior differences in the application when running standalone vs running with Eureka and ConfigServer in the mix.

Any thoughts on where to start looking?

[gradle.txt](https://github.com/spring-cloud/spring-cloud-commons/files/503448/gradle.txt)

**Comment by spencergibb** [comment]
So it works with eureka and config server, but not otherwise? Not sure that we can offer much help without seeing a sample project.

**Comment by ulmermark** [comment]
Aplogies,

I have been able to replicate the issue minus eureka and config server all
together.  Must be an issue of loading a custom FileSystemProvider
implementation from a jar inside of the FAT jar.

Please close this issue.

Regards.

Mark Ulmer
