### ISSUE TITLE
Hint-Based Load-Balancing only supported for WebClient-backed load-balancing?

### ISSUE THREAD

**Issue by emilnkrastev** [spring-cloud/spring-cloud-commons#1368]
Hello,

I would like to get some clarity regarding the Hint-based Load Balancing:
Is it only supported for WebClient-Backed load balancing? 

I'm unable to make it work with blocking clients.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
