### ISSUE TITLE
@ConfigurationProperties Beans are not Re-bound on Context Refresh

### ISSUE THREAD

**Issue by AdrianDiemerDev** [spring-cloud/spring-cloud-commons#1372]
The [documentation](https://docs.spring.io/spring-cloud-commons/reference/spring-cloud-commons/application-context-services.html#environment-changes) states that `@ConfigurationProperties` are supposed to be re-bound on environment changes.

As far as I can tell, that's not what's happening, though. Since updates to ConfigurationProperties seem to only be working when using setters (#1547), I think the ConfigurationProperties aren't actually re-bound but only modified which is different from the way the documentation describes it as well as how other beans are handled.

Changing the behavior from modifying to rebinding would also resolve the issue mentioned further down in the documentation that deleted properties are not going to be updated in the ConfigurationProperties beans.

Is this a change that would be accepted as a contribution to the project if we came up with a solution for it?

* Spring Version: 6.1.11
* Spring Boot Version: 3.2.8
* Spring Cloud Version: 2023.0.2

**Comment by ryanjbaxter** [comment]
My mistake, I thought this should be supported but it looks as well it is not.  I have added a note to our docs stating such

**Comment by AdrianDiemerDev** [comment]
Your note in the documentation only covers records but classes that use constructor binding are affected as well.

Also, I don't feel like a note in the documentation fixes the issue. In my opinion, this is a fundamental flaw in the refresh mechanism. As you can see in the table below, only 2 out of 9 scenarios are supported by the refresh:

|  | Constructor-Bound Class | Record | Setter-Bound Class |
|--------|--------|--------|--------|
| Create Property | no | no | yes |
| Update Property | no | no | yes |
| Delete Property | no | no | no |

All of this could be fixed by actually reinitializing the object (just like any other bean) instead of relying on setters.

My original question was whether such a change would be accepted as a contribution since there seem to be some maintainers that feel that this (in my opionion broken) behavior is by design.

**Comment by ryanjbaxter** [comment]
We would certainly take a look at a PR that would support this can consider the enhancement.

**Comment by MenschNestor** [comment]
I think the recent change in #1680 has exacerbated the fact that constructor binding beans are not really supported by the context refresh: They don't usually have a default constructor. Our logs are now flooded with warnings about beans that cannot be reset.

I think either
* the documentation needs to clearly state that you cannot use constructor binding in Spring Boot if you want to have a working context refresh, or
* the context refresh needs to be able to reset configuration properties beans that use constructor binding.

**Comment by quaff** [comment]
> the documentation needs to clearly state that you cannot use constructor binding in Spring Boot if you want to have a working context refresh

See GH-1466

**Comment by ryanjbaxter** [comment]
@MenschNestor I think this PR addresses the logging issue
https://github.com/spring-cloud/spring-cloud-commons/pull/1701
