### ISSUE TITLE
Add Devcontainer Support

### ISSUE THREAD

**Issue by samuelj90** [spring-cloud/spring-cloud-commons#1373]
**Is your feature request related to a problem? Please describe.**
I would like to propose adding devcontainer support to the Spring Cloud Commons repository. Currently, setting up the development environment can be cumbersome for new contributors, leading to inconsistencies and potential issues across different machines.

**Describe the solution you'd like**
 I propose adding a devcontainer.json configuration file to enable developers to easily set up a consistent development environment using Visual Studio Code's Remote Development feature. Here is a basic example of what the devcontainer.json file  
 
**Describe alternatives you've considered**
I don't find any alternative solutions but with this setting up and running the project will be quick and easy.

**Additional context**
Adding devcontainer support would simplify the onboarding experience for new developers and ensure a consistent development environment. I believe this enhancement would be beneficial for both current contributors and future ones.

**Comment by samuelj90** [comment]
In setting up a development environment to contribute to the Spring Cloud Commons project. I faced few challenges Here are some of those and added some more hypothetically

**Incomplete  Documentation**
The README file does not generated properly https://github.com/spring-cloud/spring-cloud-commons

**Test Setup**
Understanding how to run tests effectively and interpret the results

 **Environment Configuration / dependency**
I don't find any idea on how to configure the environment and tools required mostly related to first point

**Tools Version changes**
With change of java version / other tools and compatibility it will be easier to switch if we using this approach

**Comment by ryanjbaxter** [comment]
> The README file does not generated properly https://github.com/spring-cloud/spring-cloud-commons

We can fix this that.

> Understanding how to run tests effectively and interpret the results

These will be run as part of the maven build.

> I don't find any idea on how to configure the environment and tools required mostly related to first point

That should be made clean once the README is fixed
https://github.com/spring-cloud/spring-cloud-build/blob/main/docs/modules/ROOT/partials/contributing.adoc

> With change of java version / other tools and compatibility it will be easier to switch if we using this approach

Meaning you need to change Java versions on your machine?
`

**Comment by samuelj90** [comment]
Yes Switching java versions for different projects managing through IDE but dev container will work with code space and all for quick fixes

**Comment by ryanjbaxter** [comment]
I have fixed the readme that that should make things easier.  

I don't think we are going to use dev containers.  If the instructions in the readme are not clear please open a separate issue so we can address it.

**Comment by samuelj90** [comment]
I know that this is not in priority or not in the roadmap but I believe some key value additions that can be brought to our ecosystem. can I start work on this based on my availability?

**Comment by ryanjbaxter** [comment]
You can submit a PR but like I said above and I can discuss with the team if it is something we would like to incorporate, but I would not count on us merging it if we feel like supporting it and maintaining it adds more work in the long run.
