### ISSUE TITLE
EnvironmentDecryptApplicationInitializer has unreachable branch

### ISSUE THREAD

**Issue by kuipercm** [spring-cloud/spring-cloud-commons#139]
In `EnvironmentDecryptApplicationInitializer` it appears that a branch of code is unreachable: the else if at line 229. This is due to the fact that `CompositePropertySource` is a subclass of `EnumerablePropertySource` and so the first branch is always followed. 

See https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/encrypt/EnvironmentDecryptApplicationInitializer.java#L229

**Comment by spencergibb** [comment]
Besides  the branch that isn't executed, is there an issue?

**Comment by kuipercm** [comment]
As it turns out no: I was working with an incorrectly synched git branch of a fork of the repo. I had trouble with some of the unit tests (which failed) and tried to find out what was going on. At first I thought that the code branch was the culprit, but it turned out git had messed up something. I'll close the issue
