### ISSUE TITLE
setup gh-pages and project page on spring.io

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-commons#141]

**Comment by bilak** [comment]
maybe [gitter](https://gitter.im/spring-projects/home) group would be also helpful

**Comment by spencergibb** [comment]
@bilak I have no idea what your comment means

**Comment by bilak** [comment]
oh sorry I was thinking I'm in spring cloud netflix. It would be nice to have some group in gitter like spring boot does to have better abilities for discussion with community.

**Comment by spencergibb** [comment]
https://gitter.im/spring-cloud/spring-cloud

**Comment by spencergibb** [comment]
Closed via 491bc49d0a4f1e5791549b0a0d175664e9e60737
