### ISSUE TITLE
When do you plan to release version supporting spring Spring Boot 3.4.x

### ISSUE THREAD

**Issue by awarum** [spring-cloud/spring-cloud-commons#1434]
CompatibilityVerifierProperties in 4.1.5
at the moment supports
private List<String> compatibleBootVersions = List.of("3.2.x", "3.3.x");

I am looking for 3.4.x support (which I can see is already implemented) but not yet released.

**Comment by OlgaMaciaszek** [comment]
Hello @awarum, as you can see in[ the release calendar](https://spring.io/projects#release-calendar), the start of the `2024.0.0` Spring Cloud release is planned for today.

**Comment by awarum** [comment]
Thank you for the answer. This is excellent news! 🎉😊 I couldn’t have wished for anything better. 💯
