### ISSUE TITLE
When Can Spring cloud support spring boot v1.5 ?

### ISSUE THREAD

**Issue by billho** [spring-cloud/spring-cloud-commons#150]
For some reason, I have to upgrade to spring boot  1.5.0 , but found that  the latest version of spring cloud  do not support spring boot 1.5.0 . I just wonder when .

**Comment by shakuzen** [comment]
The Dalston release train will be compatible with Spring Boot 1.5. You can check the tentative release schedule at the [spring-cloud-release milestones](https://github.com/spring-cloud/spring-cloud-release/milestones)

**Comment by spencergibb** [comment]
See https://github.com/spring-cloud/spring-cloud-build/blob/master/pom.xml#L26
