### ISSUE TITLE
Better mock-ability for InetUtils.HostInfo

### ISSUE THREAD

**Issue by sirianni** [spring-cloud/spring-cloud-commons#151]
The `InetUtils.HostInfo` class is both `final` and has a package-private constructor.  This makes it impossible to use for JUnit testing.  

Most Spring code I've dealt with in the past does not use final classes, so I'm hoping the design philosophy has not changed.

**Comment by spencergibb** [comment]
What are you trying to do with it?

**Comment by sirianni** [comment]
I am using `InetUtils.findFirstNonLoopbackHostInfo()` in my application code:
```java
    private InternetDomainName parentDomain;

    @Inject
    void setInetUtils(InetUtils inetUtils) {
        HostInfo hostInfo = inetUtils.findFirstNonLoopbackHostInfo();
        parentDomain = InternetDomainName.from(hostInfo.getHostname()).parent();
    }
```

I then have code that uses the `parentDomain` to construct URLs.   I want to test this URL construction with a known version of `HostInfo`.  I am trying to write a JUnit test that does the following:
```java
@RunWith(SpringRunner.class)
@ContextConfiguration(classes = { MyClass.class, InetUtils.class, InetUtilsProperties.class })
public class MyTest {

    @Mock
    private InetUtils inetUtils;

    // Doesn't work since HostInfo is final
    @Mock
    private HostInfo mockHostInfo;

    @Before
    public void setup() {
        when(inetUtils.findFirstNonLoopbackHostInfo())
            // Preferred approach - doesn't work since HostInfo has package-private constructor
            .thenReturn(new HostInfo("mytest.mycompany.com"));
            // Second best approach - doesn't work since HostInfo cannot be mocked (see above)
            .thenReturn(mockHostInfo);
    }
}
```

**Comment by spencergibb** [comment]
`findFirstNonLoopbackHostInfo` is meant as a best guess for finding an address to register with service discovery. I don't see why we could have the public constructor.

**Comment by sirianni** [comment]
>I don't see why we could have the public constructor.

I assume you mean "could not have".  

Yes, I am aware of the use case within the framework.  It seems reasonable to use the utility class outside the framework however.  The Spring philosophy seems to have always been to design for extensibility and limited usage of internal framework classes.  I have no expectations of backwards compatibility here.

Thanks for considering the change.

**Comment by spencergibb** [comment]
PR is welcome.
