### ISSUE TITLE
Endpoints /pause, /resume and /restart not disable with endpoints.enabled = false

### ISSUE THREAD

**Issue by lburgazzoli** [spring-cloud/spring-cloud-commons#158]
I'll try to selective enable the endpoints and in a standard spring-boot application it can be achieved by:

```
endpoints.enabled = false
endpoints.health.enabled = true
```

The above configuration does not work when spring-cloud is added to the mix as endpoints like pause, restart and resume are still enabled and one needs to disable them one by one like:

```
endpoints.pause.enabled = false
endpoints.resume.enabled = false
endpoints.restart.enabled = false
endpoints.env.enabled = false
endpoints.env.post.enabled = false
```

Would it be possible for spring-cloud to respect the global property ```endpoints.enabled``` ?

**Comment by developmentMLPN** [comment]
I'm also affected by this problem as I only want to expose the health endpoint and nothing more.

**Comment by spencergibb** [comment]
I think that would be fine.

**Comment by spencergibb** [comment]
See PR #158
