### ISSUE TITLE
can't read log4j2-dev.xml or logback-dev.xml

### ISSUE THREAD

**Issue by liuxinglanyue** [spring-cloud/spring-cloud-commons#166]
application.properties
`spring.profiles.active=dev`

application-dev.properties
`logging.config=classpath:log4j2-dev.xml`

BootstrapApplicationListener  only read bootstrap.properties

but evn is  spring.cloud.bootstrap.name=application  OK

**Comment by spencergibb** [comment]
You can't given much detail on what is going on. Can you elaborate more on what the problem is and what you are trying to accomplish?

**Comment by liuxinglanyue** [comment]
application.properties
`spring.profiles.active=dev`

application-dev.properties
`logging.config=classpath:log4j2-dev.xml`

unused spring-cloud ,  log4j2-dev.xml  is  effective
use spring-cloud , log4j2-dev.xml is noneffective

but evn is spring.cloud.bootstrap.name=application OK

**Comment by spencergibb** [comment]
thats the same thing you said before.

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
