### ISSUE TITLE
bootstrap context not compatible with spring-boot-starter-web-reactive

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-commons#168]
Since it starts an application context with auto-configuration, spring-boot-starter-web-reactive can't find a `ReactiveHttpServerFactory` in the bootstrap context. I have to set `spring.cloud.bootstrap.enabled=false` [here](https://github.com/spencergibb/spring-cloud-gateway/blob/master/src/test/java/org/springframework/cloud/gateway/test/GatewayTestApplication.java#L12) to work.

/cc @dsyer @rstoyanchev

**Comment by dsyer** [comment]
Could be the same as this: https://github.com/markfisher/spring-cloud-function/issues/12

**Comment by spencergibb** [comment]
Sounds like it. Likely need a change upstream to be able to disable that ch

**Comment by dsyer** [comment]
It's a Spring Boot issue really (the reactive starter should only start if `webEnvironment=true`, and currently it is the opposite because that `webEnvironment=true` implies a servlet container).

**Comment by spencergibb** [comment]
I believe this is fixed
