### ISSUE TITLE
Commons rebinder and aspects erases type of config properties

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-commons#175]
Copied from https://github.com/spring-cloud/spring-cloud-sleuth/issues/514#issuecomment-279384660

Sample application: https://github.com/kimsaabyepedersen/slueth-bug

Run `mvn clean install` and it will fail (this one has sleuth on the path but the same is related to any other cloud lib e.g. `feign` ).

If you open the `pom.xml` and comment out sleuth. Run again and then it prints out as expected that the class is Integer.

cc @kimsaabyepedersen 

I've confirmed that this never worked (checked Camden and Brixton)

**Comment by spencergibb** [comment]
Is this related https://github.com/spring-projects/spring-boot/issues/8277#issuecomment-279381865

**Comment by marcingrzejszczak** [comment]
If I understand properly it might be a little bit different cause over there we're seeing a JDK proxy whereas here you have a CGLIB one.

**Comment by dsyer** [comment]
This seems like a big thing in Spring Boot 1.5 (because we create proxies there routinely for `@Validated` beans). Up to 1.4 it's a corner case (no-one *needs* a proxy for `@ConfigurationProperties`). I'm not really sure what we need to do about it yet, but I'm going to assume it has to be done for Dalston (1.2).

**Comment by kimsaabyepedersen** [comment]
Hi Dave. 

With regards to your comment (no-one needs a proxy for @ConfigurationProperties). I agree. But that is not what I am doing. I am actually doing this:
https://github.com/spring-cloud/spring-cloud-sleuth/issues/514#issuecomment-279406350

Which IMHO is a valid use case for an aspect (add some logic around some rest endpoints). 

Kind regards 
Kim

**Comment by dsyer** [comment]
It's not necessary to intercept calls to `@ConfigurationProperties` if what you need is to add logic around rest endpoints. So there's probably a bug in your pointcut.

I think there's a workaround, BTW, which is to put your `@ConfigurationProperties` bean in `@RefreshScope`.

**Comment by kimsaabyepedersen** [comment]
This is the pointcut, the final && should make sure it only applies to classes annotated with RestController, don't you agree? - yet it also interferes with the @ConfigurationProperties:
```java
@Before("execution(public * *(..)) && within(com.example..*) && @target(org.springframework.web.bind.annotation.RestController))")
```

**Comment by dsyer** [comment]
`@target` is applied lazily, so you get a proxy, even though the pointcut never applies to the `@ConfigurationProperties` bean. How about explicitly excluding the `@ConfigurationProperties` somehow? Or using `@ControllerAdvice` instead off an aspect?

**Comment by kimsaabyepedersen** [comment]
Ok then, I guess I haven't read the @target documentation well enough (can't seem to find it either on the spring aop docs). Sure I can work around it by using @ControllerAdvise or just putting the controllers in a package and then specify that in within(xxx).

So then maybe this is not a but at all then.
