### ISSUE TITLE
Bootstrap configurations sorting does not work

### ISSUE THREAD

**Issue by rterentiev** [spring-cloud/spring-cloud-commons#176]
Looks like BootstrapApplicationListener has typo:
```
125            List<Class<?>> sources = new ArrayList<>();
               ...
136            builder.sources(sources.toArray(new Class[sources.size()]));
137            AnnotationAwareOrderComparator.sort(sources);
138            final ConfigurableApplicationContext context = builder.run();
```

Another problem is that AnnotationAwareOrderComparator is from spring core and does not know anything about AutoConfigureBefore/After annotations. I found AutoConfigurationSorter in spring-boot-autoconfigure project, but it has package level protection.

**Comment by spencergibb** [comment]
What typo? 

`AutoConfigureBefore/After` are unrelated to bootstrap configuration, so I wouldn't expect them to be involved here.

**Comment by rterentiev** [comment]
> What typo?

Sources is set to builder (line 136), before sorting (line 137).

> AutoConfigureBefore/After are unrelated to bootstrap configuration, so I wouldn't expect them to be involved here.
Ok, thank you.

**Comment by spencergibb** [comment]
Ok. Thanks for the clarification. To me, a typo is a misspelling. That just looks like a bug :-)
