### ISSUE TITLE
EnvironmentDecryptApplicationInitializer.insert(...) infinite loop possibility

### ISSUE THREAD

**Issue by larrywest** [spring-cloud/spring-cloud-commons#178]
The ApplicationContext overload of insert ([currently at line 124](https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/encrypt/EnvironmentDecryptApplicationInitializer.java#L124)) has a while loop that looks like it could get stuck.

This probably can't happen in reality, but it's easy to fix, just move the 
```
				parent = parent.getParent();
````
one line down, **outside** the if-instance-of block:
```
		while (parent != null) {
			if (parent.getEnvironment() instanceof ConfigurableEnvironment) {
				ConfigurableEnvironment mutable = (ConfigurableEnvironment) parent
						.getEnvironment();
				insert(mutable.getPropertySources(), propertySource);
			}
			parent = parent.getParent();
		}
```

**Comment by bijukunjummen** [comment]
Doubt it @larrywest unless I am missing here - `parent.getParent()` would get the parent application context which would ultimately be null when it hits the root context and the loop will terminate. The only way this can go wrong is if the parent of a context is itself, I am assuming that there is logic somewhere to prevent such a thing.

**Comment by larrywest** [comment]
@bijukunjummen Well... that would be true with my suggested change (above), but in the existing code (below), I don't see how `parent` would ever change its value if `parent.getEnvironment()` were to return something not an instance of `ConfigurableEnvironment`:

```
		while (parent != null) {
			if (parent.getEnvironment() instanceof ConfigurableEnvironment) {
				ConfigurableEnvironment mutable = (ConfigurableEnvironment) parent
						.getEnvironment();
				insert(mutable.getPropertySources(), propertySource);
				parent = parent.getParent();
			}
		}
```

**Comment by bijukunjummen** [comment]
Ah ! yes, missed that. You are right, it does look like a bug.
