### ISSUE TITLE
Support watching keys and services directory 

### ISSUE THREAD

**Issue by avthart** [spring-cloud/spring-cloud-commons#18]
With Consul and other solutions like etcd, it is possible to watch for changes within services and keys directories. The current Spring Cloud API does not support this kind of functionality. Are there any plans to support this?

"Watches are a way of specifying a view of data (e.g. list of nodes, KV pairs, health checks) which is monitored for updates. "

See also: http://www.consul.io/docs/agent/watches.html

**Comment by spencergibb** [comment]
I could see this with events, so consul could use watches and some other system could poll.

**Comment by spencergibb** [comment]
X-Ref https://github.com/spring-cloud/spring-cloud-commons/issues/18

**Comment by dsyer** [comment]
This isn't really a Spring Cloud Commons feature. I believe it belongs with the individual config service implementations. E.g. Spring Cloud Config supports refresh via web hooks (such as provided by Github etc.).
