### ISSUE TITLE
Deprecate logging rebinder

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-commons#185]
Since spring boot added a [logging actuator](https://github.com/spring-projects/spring-boot/pull/7086), do we need to support this anymore since the functionality overlaps?

/cc @dsyer

**Comment by dsyer** [comment]
Spring Boot only supports log level changes. We also support reinitializing the whole logging system (and I think we need to, in case a config server or a consul has global config for a file path or format pattern).

**Comment by spencergibb** [comment]
OK
