### ISSUE TITLE
keyStore location only in camel case

### ISSUE THREAD

**Issue by mixaaaa** [spring-cloud/spring-cloud-commons#191]
Hey,

like Dave mentioned in [Issue#375](https://github.com/spring-cloud/spring-cloud-config/issues/375) at spring-cloud-config it seems to be a bug that in `EncryptionBootstrapConfiguration` at method `getMatchOutcome()` that the check for the key store is online looking for camel case written **keyStore**.

`if (hasProperty(environment, "encrypt.keyStore.location")) {`

I encountered it because intelliJ auto completion only wanted me to have the hyphen written value.

Thanks,
Uwe

**Comment by spencergibb** [comment]
Thanks,

The fix will be to use a relaxed property resolver in `KeyCondition.getMatchOutcome()`.

**Comment by mixaaaa** [comment]
Thanks for fixing :)

**Comment by albertoaflores** [comment]
Just came across this. Thanks for fixing it. Is this going to be part of the Camden release train? I'm using Camdem.SR6 and noticed that the spring-cloud-context is not yet release.

**Comment by spencergibb** [comment]
This hasn't been fixed yet

**Comment by spencergibb** [comment]
Closed via 7744b639aff84a753b524c1321629bfe96539f6b
