### ISSUE TITLE
InetUtils.convertAddress returns localhost for a non-loopback address if DNS is slow

### ISSUE THREAD

**Issue by avandermeyden** [spring-cloud/spring-cloud-commons#192]
Issue #55 changed the InetUtils.convertAddress to make the hostname request to the DNS timeout in 1 second, and that made it faster, but the fall-back value is "localhost".  

**Impacts:**
* **Broken high-availability:** Services that register with the Eureka server will have a non-loopback IP, but a loopback host name, and since services prefer the hostname over the IP address, this means a slow DNS breaks high-availability.  
* Web page redirection using Eureka will break - If Eureka is used to redirect to another web page, the "localhost" value will break things even if there is only one node.  Of course a better design there is to use Zuul, but still, the "localhost" value is going to be a problem with a micro-service architecture, especially in the cloud.

Wouldn't a better fall-back value be the IP address?

**Comment by avandermeyden** [comment]
I ran some PowerShell script tests to time my DNS, and I've not seen more than 130ms (averages ~80ms), which doesn't seem that slow, so I'm wondering if my service might be CPU-bound at the time of registration in this test environment, and so the DNS request may not even be made, or the DNS request may be made, but the response is not processed before the timeout.

**Comment by spencergibb** [comment]
I don't think we should be setting the hostname value to an ip address. All of the other services have an option to prefer ip address over hostnames. This is just a facility to guess. If it's not working, it's best to explicitly configure.

**Comment by avandermeyden** [comment]
Even in this fall-back situation?

The problem is that the IP address is at least more correct and usable.  Localhost as a substitute hostname is only usable in a single-node situation, and that isn't what Eureka is for.  Assuming the DNS cannot always be fast enough (we are often at the mercy of our customer's network infrastructure), would you recommend adding a background thread that identifies bad (localhost) hostnames and re-resolves the hostname based on IP?

**Comment by spencergibb** [comment]
If the ip address is more correct and useable for your situation, configure your discovery client to prefer the IP address.
