### ISSUE TITLE
Document disable auto registration by property spring.cloud.service-registry.auto-registration.enabled

### ISSUE THREAD

**Issue by nekperu15739** [spring-cloud/spring-cloud-commons#196]
I'm trying to disable the auto registration by default using the configuration file with the property:
```
spring:
  cloud:
    discovery:
      enabled: false
```

However it doesn't work. The problem stars with the new version Dalston.RC1, the version Camden.SR6 works fine. I also try with the @EnableDiscoveryClient(autoRegister=false) in that case doesn't register even when I set the property on true.

**Comment by spencergibb** [comment]
In dalston, the property is `spring.cloud.service-registry.auto-registration.enabled=false`.
