### ISSUE TITLE
private method: insertPropertySources  issue in class PropertySourceBootstrapConfiguration 

### ISSUE THREAD

**Issue by xiuzhishang** [spring-cloud/spring-cloud-commons#202]
in class PropertySourceBootstrapConfiguration , the code [PropertySourceBootstrapProperties remoteProperties = new PropertySourceBootstrapProperties()] in  method insertPropertySources make me confused.
First i config the properties in the zookeeper,when i want to override the zookeeper properties with local bootstrap-dev. properties,I set spring.cloud.config.overrideNone=true but it does not work.
then I found this code :PropertySourceBootstrapProperties remoteProperties = new PropertySourceBootstrapProperties(),it alway use the default value, that cause the config spring.cloud.config.overrideNone=true does not work. I think here this object remoteProperties  shoud be autowired .  actually i am not sure about ,i I was afraid i  use it incorrectly, so l came here for help.

**Comment by spencergibb** [comment]
Can you explain what you are trying to do without looking at internal details?

**Comment by xiuzhishang** [comment]
thanks for your reply, I got it.
