### ISSUE TITLE
InetUtils doesn't get the right hostname

### ISSUE THREAD

**Issue by JWThewes** [spring-cloud/spring-cloud-commons#203]
We had a strange issue where the eureka client always sent their IP as the hostname. Prefer IP-Adress was set to false in the config.
After some debugging I found out that the problem is located somewhere in the InetUtils.
EurekaInstanceConfigBean calls findFirstNonLoopbackHostInfo and get's back a HostInfo with the wrong Hostname. We're on Spring Cloud Dalston.RELEASE

If you need any further information feel free to ask anytime.

Currently I resolved the issue by getting the hostname via:
Inet4Address.getLocalHost().getHostName();

Wouldn't this be a better solution instead of the current logic?

Kind regards,
Jan

**Comment by JWThewes** [comment]
Moved from https://github.com/spring-cloud/spring-cloud-netflix/issues/1882 after @spencergibb said it belongs to commons.

**Comment by ryanjbaxter** [comment]
Does the machine have multiple network interfaces?  It looks like we will iterate through the interfaces looking for a hostname.

**Comment by shivamgoel** [comment]
There should be a way to assign the preference for network interface to be used, if available more than one.

**Comment by spencergibb** [comment]
@JWThewes I would think that the localhost hostname likely isn't right most of the time either.

@shivamgoel see https://github.com/spring-cloud/spring-cloud-commons/blob/master/docs/src/main/asciidoc/spring-cloud-commons.adoc#ignore-network-interfaces for ways to ignore or prefer networks.

**Comment by spencergibb** [comment]
@JWThewes why do you think it was the 'wrong' hostname?

**Comment by JWThewes** [comment]
@spencergibb I'll explain it a bit further:
We're running the application using Docker Swarm (real SwarmMode > 1.12). The application has a port mapping and uses the swarm ingress network. What happens is he doesn't get a hostname when iterating over the interfaces. And then it picks 0.0.0.0.
For me using the localhost totally fixed it. I don't know in which cases this shouldn't work?
I'm totally willing to help on this one!

**Comment by spencergibb** [comment]
@JWThewes if localhost fixed it, can't you just set the `eureka.instance.hostname` to localhost?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by trajano** [comment]
I'm on Docker Swarm mode as well.  Can't this just use the environment value of `HOSTNAME`  if it is set?

**Comment by ryanjbaxter** [comment]
HOSTNAME might not be set in all cases

**Comment by trajano** [comment]
Agreed, but can it be used as a fallback if it is set?

**Comment by ryanjbaxter** [comment]
You can open an issue if you would like.  However since it is not causing any issues it will be lower priority.

**Comment by trajano** [comment]
In docker swarm, I also think that it is setting an additonal network IP address in 172.x block which is not considered local loopback address but that entry is not in the /etc/hosts file
