### ISSUE TITLE
Conflicting/ confusing statements in documentation 

### ISSUE THREAD

**Issue by fahimfarookme** [spring-cloud/spring-cloud-commons#206]
I was reading through [here](http://cloud.spring.io/spring-cloud-static/Camden.SR5/#_the_bootstrap_application_context) and [here](http://cloud.spring.io/spring-cloud-static/Camden.SR5/#_application_context_hierarchies) and found below conflicting/ confusing statements.

> Bootstrap properties are added with high precedence, so they cannot be overridden by local configuration, by default.

> They have lower precedence than the application.yml (or properties) and any other property sources that are added to the child as a normal part of the process of creating a Spring Boot application.

However as I have tested the precedence is: properties on config server > application.properties > bootstrap.properties

**Comment by spencergibb** [comment]
I think what is confusing is "bootstrap properties" mean "properties on config server", not bootstrap.properties.
