### ISSUE TITLE
Refreshed property gets overridden with XML bean definitions

### ISSUE THREAD

**Issue by fahimfarookme** [spring-cloud/spring-cloud-commons#207]
It's true that spring-boot promotes Java configuration over XML. However support for 'refresh' scope in XML bean definitions is required in order to ease migrating legacy spring applications into spring boot / spring cloud. Unfortunately the scope="refresh" in XML is not working as expected if the bean properties are injected in XML bean definition itself. i.e.

Consider the following configurations

1. Injecting property in XML bean definition. i.e. **property name="message" value="${message}"** -
 (Not working).
```
public class XMLBean {
	private String message;	
	public String getMessage() {...}
	public void setMessage(String message) {...}
}
```
```
	<bean name="xmBean" class="me.fahimfarook.xml.XMLBean" scope="refresh">
		<aop:scoped-proxy proxy-target-class="true" />
		<property name="message" value="${message}" />
	</bean>
```
In this case after each /refresh, the XMLBean is instantiated, but the 'message' property holds the initial value.

2. Using **@Value** annotation instead of **property name="message" value="${message}"** - (Working)

```
public class XMLBean {
        @Value("${message}")
	private String message;	
	public String getMessage() {...}
	public void setMessage(String message) {...}
}
```
```
	<bean name="xmlValueBean" class="me.fahimfarook.xml.XMLValueBean" scope="refresh">
		<aop:scoped-proxy proxy-target-class="true" />
	</bean>
```

**Analysis**
In the first scenario;
- the new property value of "message" is injected into the bean (expected) by AutowiredAnnotationBeanPostProcessor. (see DefaultListableBeanFactory::populateBean())
- After that at AbstractAutowireCabaleBeanFactory::applyPropertyValues(), the new value injected above (for message') is overridden by the older value. This is because _PropertyValues_ parameter is not empty. 
- Since the properties are resolved before invoking GenericScope, not sure this could be addressed with spring cloud commons?

@dsyer  @spencergibb Could you please check this?

**Comment by fahimfarookme** [comment]
Just realized that the scope was registered in a BeanFactoryPostProcessor, hence  scope="refresh" should already be working.

**Comment by fahimfarookme** [comment]
Unfortunately XML configuration with 'refresh' scope is not working.

```
	<bean name="xmlBean" class="me.fahimfarook.xml.XMLBean" scope="refresh">
		<property name="message" value="${message}" />
	</bean>
```

**Comment by dsyer** [comment]
I think you are correct that we cannot fix this here. The XML `<property ... value="${message}"/>` placeholder is evaluated when the bean definition is parsed, not when the bean is instantiated.

You can always use `@ConfigurationProperties` or `@Value` instead (still works with XML as you pointed out).

**Comment by fahimfarookme** [comment]
Thanks. Unfortunately we still needs the support for  XML `<property ... value="${message}"/>` to define beans for classes that we do not have access to source codes.

**Comment by dsyer** [comment]
You don't have to use XML though do you? Or you could use an EL expression to refer to a bean property that you set in your own code.

Anyway, like I said, there's nothing we can do here. Open a JIRA ticket against the Framework.
