### ISSUE TITLE
Calling the DiscoveryClient in a round-robin fashion

### ISSUE THREAD

**Issue by helpermethod** [spring-cloud/spring-cloud-commons#212]
Hi,

I'm integrating Spring Cloud into one of our starters by using the `DiscoveryClient` abstraction to resolve service instances without being tied to a specific Service Discovery provider.

The implementation looks something like this

```java
        List<ServiceInstance> instances = discoveryClient.getInstances(uri.getHost());
        ServiceInstance instance = instances.get(index.getAndIncrement() % instances.size());
```

where `index` is an `AtomicInteger` which is used to loadbalance requests.

Can the `DiscoveryClient` used that way?

**Comment by spencergibb** [comment]
This is the function of the [`LoadBalancerClient`](https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerClient.java). `DiscoveryClient` has no contract to the ordering of the instances.

**Comment by helpermethod** [comment]
Oh, that makes sense. Is it possible to use an exisiting LoadBalancerClient implementation (e.g. RibbonLoadBalancerClient) to only resolve the servicename? 
We are not using RestTemplate in our application, and would like to not modify the HttpCliebt directly.

**Comment by spencergibb** [comment]
`LoadBalancerClient.choose('myservice')` returns a `ServiceInstance` that has a host and port.

**Comment by helpermethod** [comment]
Thanks, works perfectly!
