### ISSUE TITLE
Endpoints /env and /env/reset (POST) not disabled when global endpoints.enabled=false

### ISSUE THREAD

**Issue by JorgenRingen** [spring-cloud/spring-cloud-commons#213]
Almost a duplicate of #158 , but the /env and /env/reset endpoints (org.springframework.cloud.context.environment.EnvironmentManagerMvcEndpoint) is not adhering to the global endpoints.enabled=false property.

Also, is it possible to exclude the /env, /restart, /refresh, /resume and /pause-endpoints from showing up in the log when starting up the application? They show up in the log even though endpoints.enabled=false, but it's not possible to invoke them (solved by #158)

**Comment by spencergibb** [comment]
Duplicates #117
