### ISSUE TITLE
Make use of `@EnableDiscoveryClient` optional.

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-commons#218]
More devs are putting it on a profile enabled configuration. In all impls it just creates a marker bean and then auto configuration kicks in. I don't see why this couldn't be  just auto configuration and properties. Would blend better with sidecar proxies. @dsyer, @ryanjbaxter

**Comment by dsyer** [comment]
I think you are right: it's time to pack this one off to autoconfig. Edgware?

**Comment by ryanjbaxter** [comment]
Should we continue to support `@EnableDiscoveryClient(autoRegister=false)`?  To me it seems to make more sense, and be more consistent, if we had a property that disabled auto registration rather than keep `@EnableDiscoveryClient` around for just that purpose.  Thoughts?
