### ISSUE TITLE
Test failing on JDK 1.7.0_55 on Windows machine

### ISSUE THREAD

**Issue by karolkalinski** [spring-cloud/spring-cloud-commons#22]
Test is failing on Oracle JDK 1.7.0_55 on Windows machine. It is green on Travis. Git revision: 964550b
 BootstrapConfigurationTests.pickupExternalBootstrapProperties:78 expected:<[externalPropertiesInfoName]> but was:<[child]>

**Comment by dsyer** [comment]
Is this still an issue (it's quite old now)?

**Comment by karolkalinski** [comment]
It seems, that the building is not even starting on windowds machine with message: 
```[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.3.2:exec (i
mports) on project spring-cloud-commons-parent: Command execution failed. Cannot
 run program "egrep" (in directory "D:\Users\workspace\RanD\spring-cloud-commons
"): CreateProcess error=2, The system cannot find the file specified -> [Help 1]```

**Comment by dsyer** [comment]
Any chance you can look into why that is broken? There's a profile in the parent pom(https://github.com/spring-cloud/spring-cloud-build/blob/master/spring-cloud-build/pom.xml#L251) that should switch that off in windows.

**Comment by karolkalinski** [comment]
So issue with profile seems to be a bug in apache-maven-3.2.1, that treats <activation> block as a list of OR. But tests are still failing:
```Tests in error:
  BootstrapOrderingAutoConfigurationIntegrationTests.normalPropertiesDecrypted ▒ IllegalState
  BootstrapOrderingAutoConfigurationIntegrationTests.bootstrapPropertiesExist ▒ IllegalState
  BootstrapOrderingAutoConfigurationIntegrationTests.bootstrapPropertiesDecrypted ▒ IllegalState
  EncryptionBootstrapConfigurationTests.rsaKeyStore:21 ▒ IllegalArgument Unable ...

Tests run: 43, Failures: 0, Errors: 4, Skipped: 0
```

**Comment by dsyer** [comment]
The docs say: "you need to install the Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files". Did you do that?

**Comment by karolkalinski** [comment]
Installing JCE seems to solve the problem. Thanks for help and sorry for any inconvenience.

**Comment by dsyer** [comment]
No problem. Good to know about the Maven bug.
