### ISSUE TITLE
Composite Discovery should be created only if there are more than 1 Disc clients

### ISSUE THREAD

**Issue by bijukunjummen** [spring-cloud/spring-cloud-commons#226]
I wanted to clarify the changed behavior expected from an implementation of Composite Discovery Client. 

Currently a `CompositeDiscoveryClient` and a `SimpleDiscoveryClient` is **always** created and aggregates any other Discovery Client implementations(Eureka Discovery Client or User provided say). 

The new behavior expected is that a `CompositeDiscoveryClient` should be created if and only if there are more than 1 Discovery clients available - say User provided + Eureka. A Simple Discovery Client will be created only if there is no other Discovery Client available.

@spencergibb, @ryanjbaxter, @dsyer does this capture the slack chat discussion.

**Comment by spencergibb** [comment]
After some discussion, since `SimpleDiscoveryClient` is always created, we're ok with `CompositeDiscoveryClient` being the default.
