### ISSUE TITLE
Fluent API for accessing HTTP resources

### ISSUE THREAD

**Issue by karolkalinski** [spring-cloud/spring-cloud-commons#23]
I am working on Java implementation of [ServiceRestClient.groovy](https://github.com/4finance/micro-infra-spring/blob/master/micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/resttemplate/fluent/ServiceRestClient.groovy) into spring-cloud. I would like to know, what features of the API are welcome.

My initial idea is to implement features, that would allow to rewrite _locate_ method[ConfigServicePropertySourceLocator](https://github.com/spring-cloud/spring-cloud-config/blob/master/spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServicePropertySourceLocator.java)

I am going to place my code into **new** package _org.springframework.cloud.client.fluentresttemplate_.

Thanks in advance for any ideas and remarks.

**Comment by spencergibb** [comment]
how about `org.springframework.cloud.client.web`?

**Comment by spencergibb** [comment]
@karolkalinski any news?

**Comment by karolkalinski** [comment]
The enhancement was part of my part of my R&D program sponsored by my current employer. As it was frozen due to urgent business project, I have no time to continue it.

**Comment by spencergibb** [comment]
@karolkalinski thanks. There will probably be some work in spring-framework 5 with the reactive http client.

**Comment by marcingrzejszczak** [comment]
Done via `WebClient` in Spring 5
