### ISSUE TITLE
how to get service detail by native method?

### ISSUE THREAD

**Issue by ExtremeYu** [spring-cloud/spring-cloud-commons#233]
![image](https://user-images.githubusercontent.com/16620268/28771491-9b0c7230-7615-11e7-945e-a2e3a4591875.png)
i  want to get infomation like the photo ,but i don‘t know how to get it,i need get it in service it self

**Comment by ryanjbaxter** [comment]
What is "photo"?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
