### ISSUE TITLE
Cannot mix encrypted and unencrypted properties in lists

### ISSUE THREAD

**Issue by sergiuo** [spring-cloud/spring-cloud-commons#235]
initially added it here: https://github.com/spring-projects/spring-boot/issues/9943

Steps:

create a yaml configuration file with a list of objects each containing both encrypted and unencrypted properties
define a corresponding bean, try to initialize it from yaml file using ConfigurationProperties
Observed:
only encrypted properties are set, unencrypted are ignored

Debug info:
PropertySourcesPropertyValues first adds the encrypted value. When the next unencrypted property comes in
org.springframework.boot.bind.PropertySourcesPropertyValues#putIfAbsent
the existing collectionOwner is "SystemEnvironmentPropertySource [name='decrypted']" and the "collectionOwner <> source".

Code:

```
@Component
@ConfigurationProperties(prefix = "Root.Config")
public class TestConfig {
    private List<Server> servers = new ArrayList<GraphServer>();

    public List<Server> getServers() {
        return servers;
    }

    public void setServers(List<Server> servers) {
        this.servers = servers;
    }
}
```
yaml:

```
---
Root:
  Conf:
    Servers:
    - Url: "htpt://server1"
      Username: "username"
      Password: "{cipher}AQB6LulUNRD4Sj5fGWv.............="
```

**Comment by ryanjbaxter** [comment]
So is this different than spring/spring-boot#9137?

**Comment by sergiuo** [comment]
Well, the current behavior is definitively a bug. The data comes from the same source and are split by the spring-cloud-context. The spring-boot then disregards the unencrypted properties. If it cannot be fixed/changed in spring boot then the org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer#initialize needs to be fixed to replace encrypted values with decryped in the same PropertySource.

**Comment by TYsewyn** [comment]
Closing this issue. It's covered in the tests and not reproducible.
