### ISSUE TITLE
Usage of @EnableCircuitBreaker

### ISSUE THREAD

**Issue by asgs** [spring-cloud/spring-cloud-commons#247]
can this annotation be targeted at `METHOD`s as well? A `@SpringBootApplication` can enclose (or reference) multiple services, so applying this annotation to select services could make better sense.

Maybe I misunderstood what this annotation is meant for?

**Comment by ryanjbaxter** [comment]
No it is just to be used on classes or interfaces
https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-commons/src/main/java/org/springframework/cloud/client/circuitbreaker/EnableCircuitBreaker.java#L33

Also we will no longer be requiring this annotation at some point in the future, see #246

**Comment by asgs** [comment]
yes, I looked at the src code first and that's why the question being asked. Is there any reason it does not apply to METHODs?

I understand this annotation is not going to be used in the future, but I'm looking to understand the rationale behind the `ElementType`s it's being `TARGET`ed at

**Comment by spencergibb** [comment]
It doesn't make any sense to have it on a method since it's only meant to
be used once.

Spencer Gibb

**Comment by asgs** [comment]
Oh, so this annotation is like a flag for Spring to know whether the circuit breaker feature needs to be enabled or not? That is, it applies to the entire application?

**Comment by spencergibb** [comment]
That is correct
