### ISSUE TITLE
BootstrapApplicationListener overrides defaultProperties of SpringApplication

### ISSUE THREAD

**Issue by Aloren** [spring-cloud/spring-cloud-commons#259]
We are currently using [Gauge](https://github.com/getgauge/gauge-java) for integration tests. To setup spring context we need to start it manually like that:
```
        context = new SpringApplicationBuilder(Configuration)
                .web(false)
                .profiles(profile1, profile2)
                .properties("environment.type="+environment.type)
                .run()
```
We are using this custom setting `environment.type` in our custom `EnvironmentPostProcessor`. 
Now when our `EnvironmentPostProcessor` gets executed:
```
public void postProcessEnvironment(ConfigurableEnvironment environment, SpringApplication application) {
        String type = environment.resolvePlaceholders("environment.type");
```
variable `type` is empty.

After debugging `BootstrapApplicationListener` I found out that `SpringApplication` is recreated here like that:
```
SpringApplicationBuilder builder = new SpringApplicationBuilder()
.profiles(environment.getActiveProfiles()).bannerMode(Mode.OFF)
.environment(bootstrapEnvironment)
.properties("spring.application.name:" + configName)
.registerShutdownHook(false).logStartupInfo(false).web(false);
```
and then it is run:
```
final ConfigurableApplicationContext context = builder.run();
```
So `DefaultProperties` from my original `SpringApplicationBuilder` are not provided to `EnvironmentPostProcessor` and the only property I see in `defaultProperties` is: `spring.application.name`.

As a workaround we need to set this property via `System.setProperty`.

**Comment by spencergibb** [comment]
I think your workaround is fine and this is an edge case that I don't think we want to deal with. Comment if you think otherwise.

**Comment by Aloren** [comment]
I think that is not obvious. `SpringApplicationBuilder` is public API for creating application and adding `spring-cloud` dependencies breaks initial feature: adding custom properties to context. 
Could you please explain why custom properties from initial builder can not be copied to the new builder?

**Comment by spencergibb** [comment]
That particular builder only builds the bootstrap property source. We don't want duplicate properties.

**Comment by spencergibb** [comment]
Are you doing something specific in the bootstrap phase?

**Comment by Aloren** [comment]
No, we do not have custom bootstrap logic. 
We've been using:
```
new SpringApplicationBuilder(StepsConfiguration).web(false)
            .profiles(profile1, profile2)                
            .properties("property1=value1", "property2=value2")
            .run()
```
after integration with `spring-cloud-starter` dependencies -- setup was broken due to missing custom properties.

**Comment by spencergibb** [comment]
I don't understand. Those properties get put in the environment, just like bootstrap. Can you show the output of /env?

**Comment by samjoseph** [comment]
We have a custom Environment Class which extends StandardEnvironment - We do resolution of credentials through custom conventions that we have defined.

It would be good if there is a way to specify a custom environment class to be instantiated instead of the StandardEnvironment (done in BootstrapApplicationListener.java Line#152 StandardEnvironment bootstrapEnvironment = new StandardEnvironment();) .
