### ISSUE TITLE
PropertySourceBootstrapConfiguration: Would it be possible to allow the override of any property from the config server

### ISSUE THREAD

**Issue by bstick12** [spring-cloud/spring-cloud-commons#26]
The current implementation of the PropertySourceBootstrapConfiguration. Only allows the overriding of values from the bootstrap configured PropertySources by source before the System Environment Property source. Would it be possible to allow the overriding from any property source e.g standard application.properties

Also the configuration properties to allow overriding

```
spring.cloud.config.allowOverride
spring.cloud.config.overrideSystemProperties
```

Look like they must come from the bootstrap configured sources as the standard bootstrap property source is removed before calling `PropertySourceBootstrapConfiguration.insertPropertySources()`.

Would be nice if these value if present in the bootstrap.yaml or bootstrap.properties were respected.

**Comment by dsyer** [comment]
Sorry, I'm not 100% with you. Can you give a concrete example of a property that you want to override, and where the data lives?

**Comment by bstick12** [comment]
Sorry I had put some comments on the pull request that probably better explained it- https://github.com/spring-cloud/spring-cloud-commons/pull/27

We have a custom property source that we are using the via the bootstrap mechanism. The PropertySource is based on trees of Properties in ZooKeeper.

We want to be able to set this PropertySource as the last PropertySource rather than the default which is first. 

We basically want to be able to override these bootstrap properties in local property files e.g. the application.properties.
