### ISSUE TITLE
Support configuration of back-off policy in RetryLoadBalancerInterceptor

### ISSUE THREAD

**Issue by jakub-plichta** [spring-cloud/spring-cloud-commons#262]
`RetryLoadBalancerInterceptor` is internally using `RetryTemplate` that is created for each intercepted request but there seems to be no way how to configure back-off policy. As a result requests are retried immediately which is not very fortunate.

**Comment by ryanjbaxter** [comment]
Similar issue in Spring Cloud Netflix https://github.com/spring-cloud/spring-cloud-netflix/issues/2195

**Comment by jakub-plichta** [comment]
I suppose that https://github.com/spring-cloud/spring-cloud-commons/pull/270 implements this feature request.

**Comment by ryanjbaxter** [comment]
Yup!
