### ISSUE TITLE
Configuration in active profile .yml file ignored

### ISSUE THREAD

**Issue by Juliet-Unsilo** [spring-cloud/spring-cloud-commons#273]
The active profile, localhost, which is set in the bootstrap.ym, is not used to load the configuration in the application-localhost.yml. 

I have created 2 demo applications - the only difference between them being the spring boot version as well as the spring cloud version. 

The old version (using spring boot 1.5.7.RELEASE and Dalston.SR4) overrides the default server port correctly, while the new version (using 2.0.0.M6 and Finchley.M3) uses the default server port, ignoring the server port configuration in application-localhost.yml

Both have the following 2 dependencies: 

```
dependencies {
	compile('org.springframework.boot:spring-boot-starter-web')

	compile('org.springframework.cloud:spring-cloud-starter-config')
}
```
Both use the same configuration:

bootstrap.yml:

```
spring:
  profiles:
    active: localhost
```
application-localhost.yml

```
server:
  port : 9041

```

[demo-old_working.zip](https://github.com/spring-cloud/spring-cloud-commons/files/1470533/demo-old_working.zip)

[demo-new_not_working.zip](https://github.com/spring-cloud/spring-cloud-commons/files/1470531/demo-new_not_working.zip)

Output from old:

> 10:42:23 AM: Executing external task 'bootRun'...
> :compileJava
> :processResources
> :classes
> :findMainClass
> :bootRun
> 2017-11-14 10:42:27.149  INFO 12137 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@158da8e: startup date [Tue Nov 14 10:42:27 CET 2017]; root of context hierarchy
> 2017-11-14 10:42:27.432  INFO 12137 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'configurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$fb67c076] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
> 
>   .   ____          _            __ _ _
>  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
> ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
>  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
>   '  |____| .__|_| |_|_| |_\__, | / / / /
>  =========|_|==============|___/=/_/_/_/
>  :: Spring Boot ::        (v1.5.7.RELEASE)
> 
> 2017-11-14 10:42:27.765  INFO 12137 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at: http://localhost:8888
> 2017-11-14 10:42:27.839  WARN 12137 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/application/localhost": Connection refused (Connection refused); nested exception is java.net.ConnectException: Connection refused (Connection refused)
> 2017-11-14 10:42:27.842  INFO 12137 --- [           main] com.example.demo.DemoApplication         : **The following profiles are active: localhost**
> 2017-11-14 10:42:27.858  INFO 12137 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@61f05988: startup date [Tue Nov 14 10:42:27 CET 2017]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@158da8e
> 2017-11-14 10:42:28.349  INFO 12137 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=628b0c9b-6df0-3c65-b836-82053b126ea9
> 2017-11-14 10:42:28.410  INFO 12137 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$fb67c076] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
> 2017-11-14 10:42:28.692  INFO 12137 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 9041 (http)
> 2017-11-14 10:42:28.704  INFO 12137 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
> 2017-11-14 10:42:28.706  INFO 12137 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.20
> 2017-11-14 10:42:28.824  INFO 12137 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
> 2017-11-14 10:42:28.824  INFO 12137 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 966 ms
> 2017-11-14 10:42:28.929  INFO 12137 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Mapping servlet: 'dispatcherServlet' to [/]
> 2017-11-14 10:42:28.932  INFO 12137 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
> 2017-11-14 10:42:28.933  INFO 12137 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
> 2017-11-14 10:42:28.933  INFO 12137 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpPutFormContentFilter' to: [/*]
> 2017-11-14 10:42:28.933  INFO 12137 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
> 2017-11-14 10:42:29.264  INFO 12137 --- [           main] s.w.s.m.m.a.RequestMappingHandlerAdapter : Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@61f05988: startup date [Tue Nov 14 10:42:27 CET 2017]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@158da8e
> 2017-11-14 10:42:29.340  INFO 12137 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
> 2017-11-14 10:42:29.342  INFO 12137 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
> 2017-11-14 10:42:29.371  INFO 12137 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
> 2017-11-14 10:42:29.372  INFO 12137 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
> 2017-11-14 10:42:29.414  INFO 12137 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
> 2017-11-14 10:42:29.654  INFO 12137 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
> 2017-11-14 10:42:29.661  INFO 12137 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'configurationPropertiesRebinder' has been autodetected for JMX exposure
> 2017-11-14 10:42:29.662  INFO 12137 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'environmentManager' has been autodetected for JMX exposure
> 2017-11-14 10:42:29.662  INFO 12137 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'refreshScope' has been autodetected for JMX exposure
> 2017-11-14 10:42:29.664  INFO 12137 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'environmentManager': registering with JMX server as MBean [org.springframework.cloud.context.environment:name=environmentManager,type=EnvironmentManager]
> 2017-11-14 10:42:29.674  INFO 12137 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'refreshScope': registering with JMX server as MBean [org.springframework.cloud.context.scope.refresh:name=refreshScope,type=RefreshScope]
> 2017-11-14 10:42:29.680  INFO 12137 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'configurationPropertiesRebinder': registering with JMX server as MBean [org.springframework.cloud.context.properties:name=configurationPropertiesRebinder,context=61f05988,type=ConfigurationPropertiesRebinder]
> 2017-11-14 10:42:29.767  INFO 12137 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : **Tomcat started on port(s): 9041 (http)**
> 2017-11-14 10:42:29.769  INFO 12137 --- [           main] com.example.demo.DemoApplication         : Started DemoApplication in 3.039 seconds (JVM running for 3.353)
> 

Output from new:

> 10:42:50 AM: Executing external task 'bootRun'...
> :compileJava
> :processResources UP-TO-DATE
> :classes
> :bootRun
> 2017-11-14 10:42:56.650  INFO 12265 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@192c3f1e: startup date [Tue Nov 14 10:42:56 CET 2017]; root of context hierarchy
> 2017-11-14 10:42:57.033  INFO 12265 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'configurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$5b4943a1] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
> 
>   .   ____          _            __ _ _
>  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
> ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
>  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
>   '  |____| .__|_| |_|_| |_\__, | / / / /
>  =========|_|==============|___/=/_/_/_/
>  :: Spring Boot ::             (v2.0.0.M6)
> 
> 2017-11-14 10:42:57.475  INFO 12265 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at: http://localhost:8888
> 2017-11-14 10:42:57.579  WARN 12265 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/application/localhost": Connection refused (Connection refused); nested exception is java.net.ConnectException: Connection refused (Connection refused)
> 2017-11-14 10:42:57.582  INFO 12265 --- [           main] com.example.demo.DemoApplication         : **The following profiles are active: localhost**
> 2017-11-14 10:42:57.595  INFO 12265 --- [           main] ConfigServletWebServerApplicationContext : Refreshing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@1d8062d2: startup date [Tue Nov 14 10:42:57 CET 2017]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@192c3f1e
> 2017-11-14 10:42:58.158  INFO 12265 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=f596886d-78b4-360f-9d89-ee4fc5178d2f
> 2017-11-14 10:42:58.227  INFO 12265 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$5b4943a1] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
> 2017-11-14 10:42:58.516  INFO 12265 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
> 2017-11-14 10:42:58.530  INFO 12265 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
> 2017-11-14 10:42:58.531  INFO 12265 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.23
> 2017-11-14 10:42:58.553  INFO 12265 --- [ost-startStop-1] o.a.catalina.core.AprLifecycleListener   : The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/home/juliet/.local/share/umake/ide/idea/bin::/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib]
> 2017-11-14 10:42:58.647  INFO 12265 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
> 2017-11-14 10:42:58.648  INFO 12265 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1053 ms
> 2017-11-14 10:42:58.759  INFO 12265 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Mapping servlet: 'dispatcherServlet' to [/]
> 2017-11-14 10:42:58.763  INFO 12265 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
> 2017-11-14 10:42:58.764  INFO 12265 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
> 2017-11-14 10:42:58.764  INFO 12265 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpPutFormContentFilter' to: [/*]
> 2017-11-14 10:42:58.764  INFO 12265 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
> 2017-11-14 10:42:59.121  INFO 12265 --- [           main] s.w.s.m.m.a.RequestMappingHandlerAdapter : Looking for @ControllerAdvice: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@1d8062d2: startup date [Tue Nov 14 10:42:57 CET 2017]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@192c3f1e
> 2017-11-14 10:42:59.211  INFO 12265 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
> 2017-11-14 10:42:59.212  INFO 12265 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
> 2017-11-14 10:42:59.251  INFO 12265 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
> 2017-11-14 10:42:59.251  INFO 12265 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
> 2017-11-14 10:42:59.302  INFO 12265 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
> 2017-11-14 10:42:59.556  INFO 12265 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
> 2017-11-14 10:42:59.565  INFO 12265 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'configurationPropertiesRebinder' has been autodetected for JMX exposure
> 2017-11-14 10:42:59.566  INFO 12265 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'environmentManager' has been autodetected for JMX exposure
> 2017-11-14 10:42:59.567  INFO 12265 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'refreshScope' has been autodetected for JMX exposure
> 2017-11-14 10:42:59.570  INFO 12265 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'environmentManager': registering with JMX server as MBean [org.springframework.cloud.context.environment:name=environmentManager,type=EnvironmentManager]
> 2017-11-14 10:42:59.680  INFO 12265 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'refreshScope': registering with JMX server as MBean [org.springframework.cloud.context.scope.refresh:name=refreshScope,type=RefreshScope]
> 2017-11-14 10:42:59.691  INFO 12265 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'configurationPropertiesRebinder': registering with JMX server as MBean [org.springframework.cloud.context.properties:name=configurationPropertiesRebinder,context=1d8062d2,type=ConfigurationPropertiesRebinder]
> 2017-11-14 10:42:59.877  INFO 12265 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : **Tomcat started on port(s): 8080 (http)**
> 2017-11-14 10:42:59.880  INFO 12265 --- [           main] com.example.demo.DemoApplication         : Started DemoApplication in 3.765 seconds (JVM running for 4.074)
>

**Comment by dsyer** [comment]
This change broke it: ed91ad84. I added a test.
