### ISSUE TITLE
RefreshAutoConfiguration should have a ConditonalOnProperty

### ISSUE THREAD

**Issue by twicksell** [spring-cloud/spring-cloud-commons#276]
The proxy behavior of RefreshAutoConfiguration occasionally gets in the way, and it is currently difficult to disable this feature without resorting to excluding the autoconfiguration. It would be helpful to have a property to enable/disable this feature.

**Comment by spencergibb** [comment]
Closed via 259aa43

**Comment by twicksell** [comment]
Hey @spencergibb Sorry to come late to this issue but checking it out I think we may still be missing a conditional. I'm seeing failures from `LifecycleMvcEndpointAutoConfiguration`, which depends on `EnvironmentManager`, which is defined in `RefreshAutoConfiguration`. Looks like if you disable the `RefreshAutoConfiguration` you still get the `LifecycleMvcEndpointAutoConfiguration` and then a BeanNotFound for `EnvironmentManager`. Seems like your test just missed it because it is set to not be a web test, which excludes `LifecycleMvcEndpointAutoConfiguration.

```
SpringApplicationBuilder(configuration).web(false) ... 
```
