### ISSUE TITLE
Load balanced RestTemplate should be created LAZY

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-commons#28]
When auto configuration is enabled, a load balanced RestTemplate is *always* created even if not required by any other components in the application context. When used together with `spring-cloud-netflix` for instance, it pulls other dependencies as well...

Why not marking `LoadBalancerAutoConfiguration.loadBalancedRestTemplate()` @LAZY?

For instance, `RestTemplate` is not used in a Feign/Ribbon/Eureka scenario.

**Comment by spencergibb** [comment]
I'm not keen on doing this.  Only **one** `RestTemplate` is created, not **one for each** client like the problem with `RestClient`.  What other dependencies are a problem?  I may consider disabling creation of the `RestTemplate` bean based on configuration.  Pull requests welcome.
