### ISSUE TITLE
The back-off strategy at retry can be parameterized

### ISSUE THREAD

**Issue by holy12345** [spring-cloud/spring-cloud-commons#282]
Hello @ryanjbaxter  I have an idea about retry, the details are as follows:

- When I read the source code I found that the reversion strategy was fixed (` NoBackOffPolicy` ) when using ` spring-retry`  as the retry mechanism. I know that spring-retry provides many Back-off strategy (such as ` FixedBackOffPolicy` , ` UniformRandomBackOffPolicy` , ` ExponentialBackOffPolicy` , etc.) The decision of which retry strategy to retry can be made by the user based on their actual business decisions, not the unchangeable ` NoBackOffPolicy` .

- When using  `spring-retry ` as a retry mechanism, can we add a parameter that indicates which request types need to be retried ( `GET `,  `POST `,  `PUT `,  `DELETE `, etc.) The current code does not have this parameter, When using the Ribbon, we only use the  `OkToRetryOnAllOperations ` parameter as the basis for this determination (if  `OkToRetryOnAllOperations ` is false and the request type is  `GET `, then the retry will be done as well. I think because the  `GET ` request is idempotent).

Conclusion：

- Add a parameter to allow users to decide which Back-off retry strategy to use based on their business situation.

- Add a parameter to allow users to decide according to their own business what kind of request can complete the retry

The above is my idea, maybe I understand is not very correct. If you think I'm right, I'm very willing to submit a PR to add this functionality. best wishes！

**Comment by ryanjbaxter** [comment]
I delivered the backoff policy already 
https://github.com/spring-cloud/spring-cloud-commons/pull/270

I think more fine grained control over whether a request is retried might be OK.  We already support retrying on specific response codes.  The HTTP method might make sense as well.  However I imagine some one might say that they also want to retry a request based on headers (either request or response headers) or any number of other properties.  Maybe if we can think of an extensible way of doing this is might make sense.
