### ISSUE TITLE
RefreshScope updates configuration properties only once

### ISSUE THREAD

**Issue by vbasem** [spring-cloud/spring-cloud-commons#290]
I have been  struggling with refresh scope updating my properties only once and after that it will not replace them any longer, although getting the properties via actuator/env shows that the value has been correctly fetched.

This has been around for a while but I am reporting this with M5.

I have attached a project with a config client and server to demonstrate the issue.
[refreshscope.zip](https://github.com/spring-cloud/spring-cloud-commons/files/1548679/refreshscope.zip)

To run this test:

1. in config server application yaml update the search location to point to the correct location of the config-server

2. run both apps, and call localhost:8080/get    --> should get the value 7

3. update application.yml in demo_config_server/config-repo to any value and call localhost:8080/actuator/refresh

4. repeat (2) --> shows new value

5. repeat (3) with a new value 

6. repeat (2) --> still value from step (3)

7. check under actuator localhost:8080/actuator/env?pattern=mrm.*   --> value from (5) is there

Please let me know if you need more details

**Comment by spencergibb** [comment]
run both apps? I only see one.

**Comment by vbasem** [comment]
the zip file contains 2 spring apps, demo_app and demo_config_server

**Comment by vbasem** [comment]
@spencergibb  the zip file contains 2 spring apps, demo_app and demo_config_server

**Comment by vbasem** [comment]
some debugging and it seems that the context used in the biding on the 2nd run and onwards is different and does not contain any sources!

**Comment by vbasem** [comment]
It shames me to say this, but any workaround would be nice for this issue as it is affecting my production system.

**Comment by spencergibb** [comment]
@vbasem do you know Finchley and Boot milestones are not recommended for production?

**Comment by vbasem** [comment]
@spencergibb yes I do. I started working on Spring boot 2 and Cloud counterpart roughly 9 Months ago from early beta phases, as part of my contribution towards the project. I could test and give feedback and report bugs. I still stand by my decision as it does what it should. It has bugs, which I either report or add a fix that will live until upstream has caught up.

My general observation is that the beta program has very little real world testing involved and most of it comes from sandboxed tests. Hope reporting issues based on real applications out there  works for you too.

**Comment by vadimv82** [comment]
@spencergibb Will this issue be fixed in 2.0.0.RC1, 2.0.0.RC2 or 2.0.0.RELEASE ?
I also ran against it and can confirm such a problem.

**Comment by spencergibb** [comment]
It's currently not scheduled, but we'll get to it.

**Comment by GreenAsh** [comment]
Same issue with boot - 2.0.0.M7 and cloud - Finchley.M6

**Comment by spencergibb** [comment]
See https://github.com/spring-projects/spring-boot/issues/12451

**Comment by spencergibb** [comment]
This issue will be fixed by [Spring Boot 2.0.1](https://github.com/spring-projects/spring-boot/milestone/97) due Mar 29. That should be what Finchley.RC1 builds upon.

**Comment by krolen** [comment]
Wanted to add for those who will struggle to understand why properties are not refreshed at all (might make sense to add to documentation?).

Issue might be more connected to spring than to spring cloud, however:
apparently if you are using embedded spring config server, native profile and configure config file location with '_classpath_:' prefix (for example: _search-locations: classpath:config_
i.e. _ClassPathResource_) then in a case of default spring boot web application resources will be loaded using Tomcat's class loader which **caches** resources.
And in this case property source values are **not** refreshed at all.

**Comment by spencergibb** [comment]
No, it was a specific bug in spring boot

**Comment by spencergibb** [comment]
@vbasem can you confirm 2.0.1 fixed your issue?

**Comment by vbasem** [comment]
@spencergibb sorry for the late reply, I am migrating the code to 2.0.1 and Finchley M9 and will report back. Sadly with webflux there were breaking changes and it is taking me longer than anticipated.

**Comment by vbasem** [comment]
@spencergibb thank you for the update once again. It does indeed solve the issue at hand. I am able to reload the config and get the updated values.

**Comment by qwertukg** [comment]
Still have this issue with
```
<spring-boot.version>2.3.3.RELEASE</spring-boot.version>
<spring-cloud.version>Hoxton.SR8</spring-cloud.version>
```
