### ISSUE TITLE
/resume start() the context, including `Lifecycle` beans

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-commons#292]
When the application is started with `SpringApplication.run()`, the context is just *refreshed* but not *started*. The difference between the two is clearly explained in @snicoll 's post here: https://github.com/spring-projects/spring-boot/issues/6021#issuecomment-222088281

My first understanding was a `/pause` followed by `/resume` would bring my application back up and running in the same state as it was before being paused. 

This is not the case: `/resume` is nothing more than a `context.start()`. Consequence is _all `Lifecycle` *AND* `SmartLifecycle` beans_ will be (re-)started when only the latter were originally started (provided they were in autostart mode).

My understanding is I should probably have called `start()` on the context myself if I want to use the pause/resume feature. Or did I miss something ?

Anyway, the documentation should probably mention the fact that `/resume` starts the context and `SpringApplication.run()` does a simple `refresh()` together with the potential differences as explained in issue #6021.

**Comment by marcingrzejszczak** [comment]
Is it still a problem with Finchley?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
