### ISSUE TITLE
make spring.cloud.client.hostname in HostInfoEnvironmentPostProcessor configurable

### ISSUE THREAD

**Issue by remmeier** [spring-cloud/spring-cloud-commons#303]
Bug report

InetUtils.findFirstNonLoopbackHostInfo has come up a number of times. On development machines with plenty of network interfaces (docker, vmware, real ones, etc.), that method can cause severe performance issues (10 second start delay).  One could set preferredNetworks. But this might be different for each developer machine. Configuration something non-existing returns the rather random InetAddress.getLocalHost.

To simplify things, it should be possible to configure that host name directly. InetUtils already has a defaultHostname, similarly it could have a hostName. For Devleopment that could then be set to localhost or 127.0.0.1 as well and avoid any dns reverse lookups and network interface selections.
  
since everything is implemented as EnvironmentPostProcessor and processed early on startup, it seems also not possible(?) to override, disable or fully reconfigure it. e.g. an application-<profile->.yaml seems not yet processed and is not taking into account when evaluating its properties.

**Comment by spencergibb** [comment]
`spring.cloud.client.hostname` is meant to be a default used by a discovery system. There are also default host and ip address. Maybe it could just be disabled altogether and just return the defaults.
