### ISSUE TITLE
Make CompositeDiscoveryClient use ordered DiscoveryClient instances

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-commons#304]
Using `AnnotationAwareOrderComparator.sort()`

**Comment by ezraroi** [comment]
Hi @spencergibb, order will not be enough in our use case. As we define our own 'ConsulDiscoveryClient` (MultiZonesConsulDiscoveryClient) which brings services from several DCs and adds latency information. Even if we will set our bean with higher order, the `CompositeDiscoveryClient` will also class the `ConsulDiscoveyClient` and we will end up having every services twice. 

```java
@Override
	public List<String> getServices() {
		LinkedHashSet<String> services = new LinkedHashSet<>();
		if (this.discoveryClients != null) {
			for (DiscoveryClient discoveryClient : discoveryClients) {
				List<String> serviceForClient = discoveryClient.getServices();
				if (serviceForClient != null) {
					services.addAll(serviceForClient);
				}
			}
		}
		return new ArrayList<>(services);
	}
```

Can we have a way to disable the composition in anyway?

**Comment by spencergibb** [comment]
Exclude `CompositeDiscoveryClientAutoConfiguration`

**Comment by ezraroi** [comment]
I am not sure this will help as the `ConsulDiscoveryClient` is mark as @Primary

**Comment by ezraroi** [comment]
OK, after looking on the `getInstances` of the `CompositeDiscoveryClient`, looks like once they will be ordered it will be fine as it is stopping on the first one
