### ISSUE TITLE
provide some way to influence HTTP requests with the load-balancer context

### ISSUE THREAD

**Issue by joshlong** [spring-cloud/spring-cloud-commons#305]
As per a remarkably productive discussion with @spencergibb , it would be nice to be able to influence the `RestTemplate` or `WebClient` HTTP calls made as a result of client-side loadbalancing with Ribbon. This way, given a Ribbon `Server`, we could customize the outgoing HTTP request to do things like contribute HTTP headers.   

Please provide some sort of callback interface giving the current HTTP request (before it's been made) and the Ribbon `Server`

**Comment by spencergibb** [comment]
I think this may be already done for `RestTemplate` https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerRequestTransformer.java
