### ISSUE TITLE
Bean registered through BeanDefinitionRegistryPostProcessor are not getting refreshed on cloud config changes

### ISSUE THREAD

**Issue by JagmohanSharma** [spring-cloud/spring-cloud-commons#308]
I've a BeanDefinitionRegistryPostProcessor class that registers beans dynamically. we are setting scope as "refresh". However, when the cloud configuration Environment is changed, such beans are not being refreshed. Need some help around this.

**Comment by dsyer** [comment]
It would be a lot easier if you would put the code in a runnable sample in github

**Comment by JagmohanSharma** [comment]
Please find basic required files here. https://github.com/JagmohanSharma/SpringCloudRefreshScopeIssue. This includes test which shows the issue occurring.

**Comment by JagmohanSharma** [comment]
I tried creating bean without FactoryBean by using init method in PropertyBasedDynamicBeanDefinitionRegistrar as
```
private AbstractBeanDefinition preparePropertyConsumerBeanDefinition(String propBeanName, String beanPropertyFieldName) {
		BeanDefinitionBuilder bdb = BeanDefinitionBuilder.genericBeanDefinition(propertyConsumerBean);
		bdb.addPropertyReference(beanPropertyFieldName, propBeanName);
		bdb.setInitMethodName("getObject");
		if (isRefreshScopeEnabled()) {
			bdb.setScope("refresh");
		}
		return bdb.getBeanDefinition();
	}
```

But still this is not getting refreshed on cloud config changes. Would it not correct way to use init() method here for initialising the bean.

**Comment by dsyer** [comment]
I don't really follow what this code is doing. Can we go back to the basics? What do you actually want to achieve?

**Comment by JagmohanSharma** [comment]
here we are using BDRPP for dynamically initialising Property beans and dependent consumer. 
E.g., lets consider
we want to create RestTemplate object then we can provide 
TEST_PROP_KEY=service1

and if we provide suffix for consumer and property beans as
```
private static final String REST_TEMPLATE_BEAN_SUFFIX = "RestTemplate";
private static final String REST_TEMPLATE_PROPERTY_BEAN_SUFFIX = "RestTemplateConf";
```
then this code will give us two beans with name as `service1RestTemplate` and `service1RestTemplateConf` if we are not providing any prefix.

```
@Bean
    public PropertyBasedDynamicBeanDefinitionRegistrar restTemplateRegistrar() {
        PropertyBasedDynamicBeanDefinitionRegistrar registrar = new PropertyBasedDynamicBeanDefinitionRegistrar(TestProperties.class, null, TEST_PROP_KEY);
        registrar.setPropertyConsumerBean(CustomRestTemplate.class, null, "testProperties");
        registrar.setConsumerBeanNameSuffix(REST_TEMPLATE_BEAN_SUFFIX);
        registrar.setPropertyBeanNameSuffix(REST_TEMPLATE_PROPERTY_BEAN_SUFFIX);
        return registrar;
    }
```

Required property bean and consumer bean definition are being registered using `PropertyBasedDynamicBeanDefinitionRegistrar`. and CustomRestTemplate is used as FactoryBean which provide us object of RestTemplate type as:

```
public class CustomRestTemplate implements FactoryBean<RestTemplate> {


    private TestProperties testProperties;

    @Override
    public RestTemplate getObject() throws Exception {
        return customRestTemplate();
    }

    @Override
    public Class<RestTemplate> getObjectType() {
        return RestTemplate.class;
    }

    @Override
    public boolean isSingleton() {
        return true;
    }

    private RestTemplate customRestTemplate() {
        RestTemplate restTemplate = new RestTemplate(customRestClientHttpRequestFactory());
        return restTemplate;
    }

    private HttpComponentsClientHttpRequestFactory customRestClientHttpRequestFactory() {
       
    }

    public void setTestProperties(TestProperties testProperties) {
        this.testProperties = testProperties;
    }

}
```

So this basically give us rest template object as `service1RestTemplate` which we use.
```
public class TestClass {

    @Resource(name = "service1RestTemplate")
    private RestTemplate service1RestTemplate;


}
```

so we are able to refresh this bean at change in cloud consul config only when we put @RefreshScope on `TestClass` , but this should be done without this as original service1RestTemplate is also set as scope `refresh`.

**Comment by JagmohanSharma** [comment]
We are setting refresh scope for bean `service1RestTemplate` which is a product of FactoryBean(CustomRestTemplate), not for FactoryBean itself.

**Comment by JagmohanSharma** [comment]
@dsyer I have now updated https://github.com/JagmohanSharma/SpringCloudRefreshScopeIssue github sample where we can reproduce the issue. Readme document is updated as well.

We can see here that issue is not with FactoryBean but the bean which is being registered using BDRPP is itself not getting refreshed even after setting scope as `refresh`.

**Comment by JagmohanSharma** [comment]
This issue can be resolved by creating Scoped proxies for bean definitions being registered in `BeanDefinitionRegistryPostProcessor `. As `@RefreshScope` annotation does it for you if you use `@Configuration`. So below code can be used to fix:
```
BeanDefinitionHolder property = new BeanDefinitionHolder(beanDefinition,
                propBeanName);
        BeanDefinitionHolder holder = ScopedProxyUtils.createScopedProxy(property,
                beanDefRegistry, true);
        beanDefRegistry.registerBeanDefinition(holder.getBeanName(),
                holder.getBeanDefinition());
```
