### ISSUE TITLE
Service-registry endpoint doesn't work as expected

### ISSUE THREAD

**Issue by andreasevers** [spring-cloud/spring-cloud-commons#310]
Hey,

Actually two issues in one, but very related:

1. Finchley.M5 still [documents](http://cloud.spring.io/spring-cloud-static/Finchley.M5/single/spring-cloud.html#_service_registry_actuator_endpoint) `/service-registry/instance-status` while `instance-status` is [now gone](https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-commons/src/main/java/org/springframework/cloud/client/serviceregistry/endpoint/ServiceRegistryEndpoint.java).
2. When adding `org.springframework.cloud:spring-cloud-starter-eureka:2.0.0.M2` to a basic Spring Boot application (without any service registry configuration), the registration obviously fails:
> TransportException: Cannot execute request on any known server

Works as expected, since there is no discovery server anywhere. But what is really odd is that the `/service-registry` endpoint on the Spring Boot application returns the following successful info:

`{
  "overriddenStatus": "UNKNOWN",
  "status": "UP"
}`

**Comment by ryanjbaxter** [comment]
Have you tried using the latest Finchley release, M5?

**Comment by andreasevers** [comment]
I'm actually using the following dependency:

```
<parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>2.0.0.BUILD-SNAPSHOT</version>
	<relativePath/> <!-- lookup parent from repository -->
</parent>
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-netflix</artifactId>
            <version>2.0.0.M5</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
<dependencies>
    <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-eureka</artifactId>
    </dependency>
</dependencies><repositories>
    <repository>
        <id>spring-milestones</id>
        <name>Spring Milestones</name>
        <url>https://repo.spring.io/libs-milestone</url>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
    </repository>
</repositories>
```

**Comment by andreasevers** [comment]
Switching the BOM from `spring-cloud-netflix:2.0.0.M5` to `spring-cloud-dependencies:Finchley.M5` doesn't change a lot, except that it forces me to explicitly declare a version for `spring-cloud-starter-eureka`. Odd, since the `spring-cloud-dependencies` BOM has transitive dependency on the `spring-cloud-netflix:2.0.0.M5` BOM I used above.

Now I have the following:

```
<parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>2.0.0.M7</version>
</parent>
<dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-dependencies</artifactId>
			<version>Finchley.M5</version>
			<type>pom</type>
			<scope>import</scope>
		</dependency>
	</dependencies>
</dependencyManagement>
<dependencies>
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter</artifactId>	
	</dependency>
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-web</artifactId>
	</dependency>
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-actuator</artifactId>
	</dependency>
	<dependency>
		<groupId>org.springframework.cloud</groupId>
		<artifactId>spring-cloud-starter-eureka</artifactId>
		<version>2.0.0.M2</version>
	</dependency>
</dependencies>
<repositories>
	<repository>
		<id>spring-milestones</id>
		<name>Spring Milestones</name>
		<url>https://repo.spring.io/libs-milestone</url>
		<snapshots>
			<enabled>false</enabled>
		</snapshots>
	</repository>
</repositories>
```

Still the same result on the `/service-registry` endpoint.

To reproduce, simply put the above configuration in an empty spring boot application's POM (along with pluginmanagement) and execute with the following command:
`mvn clean spring-boot:run -Dmanagement.endpoints.web.expose=*`

**Comment by spencergibb** [comment]
Should be spring-cloud-starter-netflix-eureka-client, that one was deprecated in edgware and removed in Finchley.

**Comment by andreasevers** [comment]
Oh yes of course, my bad.

Nevertheless, with dependency `org.springframework.cloud:spring-cloud-starter-netflix-eureka-client` and BOM `spring-cloud-dependencies:Finchley.M5`, the output of the `/actuator/service-registry` endpoint remains `{ "overriddenStatus": "UNKNOWN", "status": "UP" }`.
Could it be that this is expected behaviour? I could imagine the semantics of an `UP` status to be something along the lines of "Application would have status `UP` *if* it could connect to the service registry". Somehow this kinda feels weird since it's the service-registry endpoint for eureka which can't be reached. An unsuccessful message would be more suited I suppose.

**Comment by andreasevers** [comment]
Noticed another reference to `/instance-status` in the meantime:
http://cloud.spring.io/spring-cloud-static/Finchley.M5/single/spring-cloud.html#_instance_status

**Comment by andreasevers** [comment]
I did some more digging, and the `GET` endpoint seems to be kind of static.
Consider the following example which - as opposed to the scenario in my previous comments - there is in fact a Eureka server present:

**Client application:**
`spring-boot-starter-parent:2.0.0.BUILD-SNAPSHOT`
`spring-cloud-dependencies:Finchley.BUILD-SNAPSHOT`

**Eureka server:**
`spring-boot-starter-parent:2.0.0.BUILD-SNAPSHOT`
`spring-cloud-dependencies:Finchley.M5`
*Using Finchley.BUILD-SNAPSHOT throws exception on startup:*
```
Parameter 0 of method traceFilterRegistration in org.springframework.cloud.netflix.eureka.server.EurekaServerAutoConfiguration required a bean of type 'javax.servlet.Filter' that could not be found.
	- Bean method 'applicationContextIdFilter' not loaded because @ConditionalOnProperty (management.add-application-context-header=true) did not find property 'add-application-context-header'
	- Bean method 'resourceUrlEncodingFilter' in 'FreeMarkerServletWebConfiguration' not loaded because @ConditionalOnEnabledResourceChain did not find class org.webjars.WebJarAssetLocator
```

Registration of the client app is successful:
In Client App logs:
> DiscoveryClient_DEMO-APP/192.168.0.219:demo-app - registration status: 204

In Eureka Server logs:
> Registered instance DEMO-APP/192.168.0.219:demo-app with status UP (replication=true)

Calling the `service-registry` endpoint results in the logical response:
```
$ http localhost:8080/actuator/service-registry
HTTP/1.1 200 
Content-Type: application/vnd.spring-boot.actuator.v2+json;charset=UTF-8
Date: Sat, 27 Jan 2018 11:35:53 GMT
Transfer-Encoding: chunked

{
    "overriddenStatus": "UNKNOWN",
    "status": "UP"
}
```

Now if we try to override the status and bring it `DOWN`:
```
$ http POST localhost:8080/actuator/service-registry overridenStatus=DOWN status=DOWN
HTTP/1.1 200 
Content-Length: 0
Date: Sat, 27 Jan 2018 11:39:01 GMT
```
*Interestingly the change to the new Spring Boot Actuator `@Endpoint` also changed the semantics of the HTTP method. The [documentation](http://cloud.spring.io/spring-cloud-static/Finchley.M5/single/spring-cloud.html#_instance_status) [tells us](http://cloud.spring.io/spring-cloud-static/Finchley.M5/single/spring-cloud.html#_service_registry_actuator_endpoint) to use a `String` body, while now Json is expected.*

In Eureka Server logs:
> Status updated: DEMO-APP - 192.168.0.219:demo-app - DOWN

In Eureka Server UI:
> DEMO-APP | n/a (1) | (1) | DOWN (1) - 192.168.0.219:demo-app

This is great, now we can also easily solve the blue-green routing problem I described 2 years ago:
https://stackoverflow.com/questions/31313170/how-to-route-in-between-microservices-using-spring-cloud-netflix-oss

Interestingly enough, the `service-registry` endpoint still reports the `UNKNOWN` and `UP` status. 
```
$ http localhost:8080/actuator/service-registry
HTTP/1.1 200 
Content-Type: application/vnd.spring-boot.actuator.v2+json;charset=UTF-8
Date: Sat, 27 Jan 2018 11:42:11 GMT
Transfer-Encoding: chunked

{
    "overriddenStatus": "UNKNOWN",
    "status": "UP"
}
```

**Comment by spencergibb** [comment]
Thanks for all the details @andreasevers!

**Comment by spencergibb** [comment]
https://github.com/spring-cloud/spring-cloud-netflix/commit/eb0681f9c25c62c15b368674a2e0bf082663923c takes care of the stale status in eureka.

This issue should stay open for documentation updates.

**Comment by andreasevers** [comment]
Awesome, thanks for the quick fixes!
I can launch a pull request for documentation polish next week (if it ain't done yet before that of course).

**Comment by spencergibb** [comment]
Awesome! I'll look for the PR.

**Comment by andreasevers** [comment]
Fixed the issues and did some polishing here and there.
The only thing I still wonder about is whether the `/service-registry` endpoint can't be a bit more user friendly.

Right now to change the status of the service we have to POST to `/service-registry` with both `overriddenStatus` and `status` fields, with the same value filled in. Doesn't having to only pass the `overriddenStatus` field sound more appropriate and user friendly?

**Comment by spencergibb** [comment]
I don't think `overriddenStatus` is required (or even used anywhere).

**Comment by andreasevers** [comment]
You're right! Changing the docs!
