### ISSUE TITLE
Duplicate interface `RestTemplateCustomizer`

### ISSUE THREAD

**Issue by ezraroi** [spring-cloud/spring-cloud-commons#322]
Looks like the interface `RestTemplateCustomizer` is being redefined in `spring-cloud-commons`. The interface is the same as the `RestTemplateCustomizer` that comes from spring-boot  jar.

Is this on purpose?

**Comment by spencergibb** [comment]
It was there before the one in spring boot

**Comment by ezraroi** [comment]
So we should use the one in boot?

**Comment by spencergibb** [comment]
I don't know. We use it for `@Loadbalanced`. The boot ones are applied to all of them. I don't think it will work.

**Comment by ezraroi** [comment]
thanks
