### ISSUE TITLE
Fix breaking upstream ConfigurationBeanFactoryMetadata bean name change

### ISSUE THREAD

**Issue by philwebb** [spring-cloud/spring-cloud-commons#324]
[This commit](https://github.com/spring-projects/spring-boot/commit/1d83e87bcdcd0a70680ac834900ddd3821cc65b9) in Spring Boot is going to break [this part](https://github.com/spring-cloud/spring-cloud-commons/blob/e77a3fd498888272b6b93fe918197b18926ea330/spring-cloud-context/src/main/java/org/springframework/cloud/autoconfigure/ConfigurationPropertiesRebinderAutoConfiguration.java#L52) of the `ConfigurationPropertiesRebinderAutoConfiguration`.

You can now use [ConfigurationBeanFactoryMetadata.BEAN_NAME](https://github.com/spring-projects/spring-boot/blob/1d83e87bcdcd0a70680ac834900ddd3821cc65b9/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/properties/ConfigurationBeanFactoryMetadata.java#L45) instead. There is also a `ConfigurationPropertiesBindingPostProcessor.BEAN_NAME`, but I don't think you'll need that any more.

**Comment by apottere** [comment]
Can `2.0.0.M7` be released?  Spring-boot 2.0.0 is now GA and the latest milestone of spring-cloud is incompatible because of this issue.

**Comment by spencergibb** [comment]
happened 4 hrs ago.

**Comment by apottere** [comment]
Awesome, thanks!  mvnrepository.com just hadn't indexed it yet.

**Comment by Natoshka** [comment]
Hello, dears!
When will it appear on the mvnrepository.com?

**Comment by ryanjbaxter** [comment]
This is has been in a release for more than a month now

**Comment by Natoshka** [comment]
@ryanjbaxter where can I download the release?
@spencergibb I don't want to sound boring, but the 2.0.0.M2-2.0.0.M6 versions are located in the maven repository :)

**Comment by spencergibb** [comment]
@Natoshka I have no control over what mvnrepository indexes, but 2.0.0.x is NOT in maven central https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-commons-dependencies/

It is here http://repo.spring.io/milestone/org/springframework/cloud/spring-cloud-commons-dependencies/ where we've announced it for every milestone.

**Comment by Natoshka** [comment]
Sorry for the stupid question, but maybe you can help me ...
I'm trying to migrate my project from version spring boot 2.0.0.RC1 to 2.0.0.RELEASE.
In one of the modules, I use the dependency 
```
<groupId>org.springframework.cloud</groupId>
<artifactId>spring-cloud-starter-openfeign</artifactId>
<version>2.0.0.M6</version>
```
but it contains dependency spring-cloud-context 2.0.0.M6, which contains the bag "java.lang.NoSuchFieldError: BINDER_BEAN_NAME"

I try to do this in my pom:

    ```
<dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
            <version>2.0.0.M6</version>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.cloud</groupId>
                    <artifactId>spring-cloud-commons</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.springframework.cloud</groupId>
                    <artifactId>spring-cloud-context</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.springframework.cloud</groupId>
                    <artifactId>spring-cloud-starter</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-commons</artifactId>
            <version>2.0.0.M7</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-context</artifactId>
            <version>2.0.0.M7</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter</artifactId>
            <version>2.0.0.M7</version>
        </dependency>
    </dependencies>

    <repositories>
        <repository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>https://repo.spring.io/libs-milestone-local</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>
```

but when I try to start application, I have the error:
2018-04-03 09:04:15.201 ERROR 16824 --- [main] o.s.boot.SpringApplication               : Application run failed
java.lang.NoClassDefFoundError: org/springframework/cloud/context/named/NamedContextFactory$Specification

What am I doing wrong?

**Comment by Natoshka** [comment]
@ryanjbaxter Thank you, it helps.
