### ISSUE TITLE
KeyProperties has a hard dependency on RsaAlgorithm despite trying to make it optional

### ISSUE THREAD

**Issue by wilkinsona** [spring-cloud/spring-cloud-commons#334]
This was originally reported in https://github.com/spring-projects/spring-boot/issues/12408. 

[Here's a sample](https://github.com/spring-cloud/spring-cloud-commons/files/1794146/key-properties-bug.zip) that produces one variant of the problem. Reproducing the other variant (to do with the verifier during class loading) will require the use of a different JVM I believe. The problem's the same as [this one that we fixed in Spring Boot a while ago](https://github.com/spring-projects/spring-boot/commit/c0a2c88da10822cebdbc5e28ff48df1dc4b04295).

**Comment by spencergibb** [comment]
We include it in the starter:
https://github.com/spring-cloud/spring-cloud-commons/blob/ec11d4bbfe317aab9bef7adc02e034104233dbfa/spring-cloud-starter/pom.xml#L34-L37

@dsyer made the change. https://github.com/spring-cloud/spring-cloud-commons/commit/aef42a65f3d1ee20e5c8b86eced1cba93a35fe81

Either we need to go back to `String` or make `spring-security-rsa` not optional.

**Comment by dsyer** [comment]
I think that was a mistake on my part. We can revert to a string.

**Comment by ryanjbaxter** [comment]
I was playing with this last night, I moved `Rsa` into its own class and made it conditional on `RsaAlgorithm`, it seemed to fix the problem.  I will create a PR later this morning so you guys can take a look.
