### ISSUE TITLE
Springboot 2 gives issues with using placeholders in bootstrap.properties

### ISSUE THREAD

**Issue by RishuK** [spring-cloud/spring-cloud-commons#335]
Error - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'propertySourceBootstrapConfiguration'

Spring dependency:

 

  ```
       <parent>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-parent</artifactId>
            <version>2.0.0.RELEASE</version>
            <relativePath/> <!-- lookup parent from repository -->
        </parent>
```

Spring-cloud dependency:

             ```
   <dependency>
                    <groupId>org.springframework.cloud</groupId>
                    <artifactId>spring-cloud-dependencies</artifactId>
                    <version>Finchley.M8</version>
                    <type>pom</type>
                    <scope>import</scope>
                </dependency>
```

Complete Error on startup - 

    `2018-03-09 19:41:35.096  WARN 97916 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'propertySourceBootstrapConfiguration': Unsatisfied dependency expressed through field 'propertySourceLocators'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'configServicePropertySource' defined in org.springframework.cloud.config.client.ConfigServiceBootstrapConfiguration: Unsatisfied dependency expressed through method 'configServicePropertySource' parameter 0; nested exception is org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'configClientProperties': Could not bind properties to 'ConfigClientProperties' : prefix=spring.cloud.config, ignoreInvalidFields=false, ignoreUnknownFields=true; nested exception is org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'spring.cloud.config.password' to java.lang.String`

bootstrap.properties:

```
    spring.cloud.config.failFast=true
    spring.profiles.active=${ACTIVE_PROFILES:dev}
    spring.cloud.config.uri=${CLOUD_CONFIG_URL:http://domainname/cloud-config}
    spring.cloud.config.username=${CLOUD_CONFIG_USERNAME}
    spring.cloud.config.password=${CLOUD_CONFIG_PASSWORD}
```

**Comment by RishuK** [comment]
Figured this out. We need a colon at the end - 
    spring.cloud.config.username=${CLOUD_CONFIG_USERNAME:}

**Comment by RishuK** [comment]
This used to work earlier though

**Comment by spencergibb** [comment]
it's not a function of spring-cloud-commons, just spring boot. The `:` signifies a default, in your case, empty.

**Comment by mehtakaran9** [comment]
This still doesn't resolve the issue though, why is the property coming as null when it is obviously defined. I am facing the same issue. 

Adding ':' just signifies the default value to be taken when the primary placeholder resolver gives null.

**Comment by spencergibb** [comment]
@mehtakaran9 without a sample of what isn't working I'm afraid I can't help.

**Comment by mehtakaran9** [comment]
Please look at this issue: [https://github.com/spring-cloud/spring-cloud-commons/issues/748](https://github.com/spring-cloud/spring-cloud-commons/issues/748) for more details @spencergibb
