### ISSUE TITLE
How cloud @Autowire work with @RefreshScope

### ISSUE THREAD

**Issue by leiy88** [spring-cloud/spring-cloud-commons#336]
To make my application cloud update configuration on the fly. I annotate some of beans with @RefreshScope in configuration class. However these beans cannot use @Autowire to inject into other beans.

```
@Configuration
public class SomeConfiguration {
    @Bean
    @RefreshScope
    public Object someBean() {
        return new SomeBean();
    }
}
```

```
@Component
public class OtherComponent {
    @Autowire
    SomeBean someBean;
}
```

The code above will get an error message:
`
required a bean of type 'SomeBean' that could not be found.
`

I know that was because the bean annotated with @RefreshScope will be replaced by a proxy class. But i don't want to modify the code already existed. 

Some advices? Thanks

**Comment by spencergibb** [comment]
`public SomeBean someBean()`. Return type matters

**Comment by leiy88** [comment]
@spencergibb 
Wow, embarrassed. Thanks, that's worked!
