### ISSUE TITLE
Support MetaData registration in Discovery

### ISSUE THREAD

**Issue by Salaboy** [spring-cloud/spring-cloud-commons#341]
When using Eureka @DiscoveryClient annotation you can also do:

```
@Component public class DynamicMetadataReporter {      
  @Autowired    
  private ApplicationInfoManager aim;      
  @PostConstruct    
  public void init() {       
            Map<String, String> map = aim.getInfo().getMetadata();       
            map.put("dynamic-s1", "value_2");    
  }
}
```

The problem is that ApplicationInfoManager is not an abstraction layer is an Eureka Netflix specific class. 
It will be great to have a ServiceMetadata abstraction which delegates to the ApplicationInfoManager depending on which discovery client is in the classpath.

We are working on spring-cloud-kubernetes-discovery, which makes it evident that we need an abstraction to register metadata in a similar fashion across Eureka, Kubernetes and any other ServiceRegistry. 

I can provide a simple abstraction as a PR, but I want to confirm that this makes sense for spring-cloud-commons.

**Comment by spencergibb** [comment]
I think this duplicates #204

**Comment by Salaboy** [comment]
So let's close this one.. I will follow up the conversation in the other one.

**Comment by spencergibb** [comment]
I want to make sure it's the same thing, but it seems to be from my point of view.

**Comment by spencergibb** [comment]
@Salaboy you can already add metadata to eureka at registration time via `eureka.instance.metadata-map`. I think it may just be adding support for it directly in s-c-k8s.

**Comment by spencergibb** [comment]
I'm going to go ahead and close this. Any further discussion should be on #204
