### ISSUE TITLE
getRsa() is undefined for the type KeyProperties inside EncryptionBootstrapConfiguration.java 

### ISSUE THREAD

**Issue by Joby81** [spring-cloud/spring-cloud-commons#344]
Question

The method getRsa() is undefined for the type KeyProperties inside EncryptionBootstrapConfiguration.java  after the merge 

Bug report

Merge branch '1.3.x'

 master
@spencergibb
spencergibb committed 23 hours ago  Verified
2 parents ec11d4b + ee5034e commit 384a576c4e61cd99582a759c5bf7045e15788f92

**Comment by ryanjbaxter** [comment]
Yeah it was removed, can you provide more details?  How about a project that reproduces the error?

**Comment by Joby81** [comment]
Please do a maven build

Thanks

**Comment by ryanjbaxter** [comment]
The build is passing.  It passed locally as well as in Jenkins.  Maybe you have some cached jars or something in your maven repo....
https://jenkins.spring.io/job/spring-cloud-commons-1.3.x-ci/
https://circleci.com/gh/spring-cloud/spring-cloud-commons/tree/1.3.x

**Comment by Joby81** [comment]
I got an error in spring-cloud-config-server project.

**Comment by spencergibb** [comment]
Should have opened it there.	

Closed via https://github.com/spring-cloud/spring-cloud-config/commit/71d8df14c7b88470feaa2fc0f97cc8d474d9728d
