### ISSUE TITLE
Possibility to send metrics from resource apps actuator to an AMQP Broker

### ISSUE THREAD

**Issue by joaoevangelista** [spring-cloud/spring-cloud-commons#35]
Since with Spring Cloud and all microservice stuff we might have many JVM, and Spring Boot applications running, couldn't we have a way to send the metrics and/or other actuator information via AMQP Broker in a "real-time way" ? So developers can build a Admin App, link the Hystrix Dashboard (if desired) and show the metrics received from the broker on the same ui, within the same application.

We could have a configuration, getting exchange and queues names from external configuration (`application.properties`) or fallback to default ones, each application will have one queue, to not conflict and have a message producer per instance on a scale enviroment, we could append the some UUID from the cloud provider like `blogAWS12`

I got the base idea from a question on *Debug and Maintain your Spring Boot App* Webnair, sorry I don't remember who asked. 

IMHO, it's a good thing to have, just the support, no UI, because microservices are coupled with DevOps and what is more fancy then colorful gauges on the screen on a DevOps enviroment ?(just kidding).

Maybe not something important right now, but I think it's a valid thing.

PS: Sorry if this isn't the way to request something new, or if this is the right project to ask for it, seemed to be the less wrong one

**Comment by dsyer** [comment]
Metrics are a Spring Boot feature (unless you are specifically talking about Hystrix, which we already support with AMQP). An AMQP exporter sounds like a fine idea (and very easy to implement if you want to take a crack at it), but please open an issue there rather than here (https://github.com/spring-projects/spring-boot).
