### ISSUE TITLE
How to check whether the configuration takes effect in real time?

### ISSUE THREAD

**Issue by nibaohua** [spring-cloud/spring-cloud-commons#351]
spring boot项目的端口，数据源等好像不能实时生效

**Comment by ryanjbaxter** [comment]
Sorry but we need an english translation.

**Comment by spencergibb** [comment]
Via Google translate

Spring boot project port, data source, etc. does not seem to take effect in real time

**Comment by spencergibb** [comment]
Is this a spring cloud question?

**Comment by chengchen** [comment]
@ryanjbaxter @spencergibb I guess what he means is:

The application port, data source bean doesn't seem to have newly-bound values after context refreshing, which is a spring cloud question actually.

**Comment by spencergibb** [comment]
server.port doesn't make sense to refresh since the server can not act upon it. A data source needs to be marked as @RefreshScope.
