### ISSUE TITLE
Standard actuator endpoints override should be qualified

### ISSUE THREAD

**Issue by snicoll** [spring-cloud/spring-cloud-commons#354]
Spring Cloud has an override of the standard `Environment` endpoint. To avoid clashes and deactivating standard Spring Boot features, bean names should at least be qualified. I'd actually recommend not to name the extension in such a generic fashion.

[`EnvironmentWebEndpointExtension`](https://github.com/spring-cloud/spring-cloud-commons/blob/78b11c35ff8ccc5782f2cb663ccec5bd19cc35fe/spring-cloud-context/src/main/java/org/springframework/cloud/context/environment/EnvironmentWebEndpointExtension.java#L35) is a `EndpointWebExtension` (that was renamed after this class was introduced, hence why the name pattern is probably inconsistent).

We do have an extension in Spring Boot that is named the same way. If you fix the naming of the class (and the bean name) you'll effectively override our behaviour with this one.

Actually, we forgot to rename the bean name when we renamed the base concept so this is the case right now, see https://github.com/spring-projects/spring-boot/issues/12827

I'd recommend renaming the class (and the bean name) to reflect what the extension does on top of the standard endpoint.

**Comment by snicoll** [comment]
So this effectively breaks `Finchley.RC1` with Spring Boot `2.0.2.RELEASE` as we've renamed our bean for consistency and Spring Cloud no longer overrides it (by accident as described above).

You can't have two extensions for the same endpoint. IMO, this is consistent with the endpoint model that mandates that the operations of an endpoint are defined in one class. The fact Spring Cloud uses a web extension to add its operation feels suspicious to me.

I can see two ways out:

1. Override our extension and use the same name so that we have one extension in the context. If you got down that route, please add integration tests to validates that the standard Spring Boot behaviour is still available
2. Override our endpoint (which IMO would be more consistent) and adding your operation with the high level API. You can't do that with 2.0.2 because of https://github.com/spring-projects/spring-boot/issues/13082

My preference would be that this feature is in a dedicated endpoint, rather than extending from ours (and I know that's unrealistic at this point).

**Comment by snicoll** [comment]
@sanderino666 a PR was merged in #368 and is available in `Finchley.BUILD-SNAPSHOT` already.

@dsyer the milestone information is missing so I've just added it.

**Comment by sanderino666** [comment]
@snicoll Thanks!

**Comment by illingtonFlex** [comment]
Is this issue expected to be resolved in Finchley.RC2? Because I am still seeing this issue using SpringBoot 2.0.2 and Finchley.RC2.



> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pathMappedEndpoints' defined in class path resource [org/springframework/boot/actuate/autoconfigure/endpoint/web/WebEndpointAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.endpoint.web.PathMappedEndpoints]: Factory method 'pathMappedEndpoints' threw exception; nested exception is java.lang.IllegalStateException: Found multiple extensions for the endpoint bean environmentEndpoint (environmentEndpointWebExtension, environmentWebEndpointExtension)
> 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:587) ~[spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1254) ~[spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1103) ~[spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:541) ~[spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:501) ~[spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE]
> 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228) ~[spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE]
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760) ~[spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE]
> 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869) ~[spring-context-5.0.6.RELEASE.jar:5.0.6.RELEASE]
> 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.0.6.RELEASE.jar:5.0.6.RELEASE]
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.2.RELEASE.jar:2.0.2.RELEASE]
> 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) [spring-boot-2.0.2.RELEASE.jar:2.0.2.RELEASE]
> 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395) [spring-boot-2.0.2.RELEASE.jar:2.0.2.RELEASE]
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.2.RELEASE.jar:2.0.2.RELEASE]
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255) [spring-boot-2.0.2.RELEASE.jar:2.0.2.RELEASE]
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243) [spring-boot-2.0.2.RELEASE.jar:2.0.2.RELEASE]
> 	at com.quikq.service.infrastructure.authentication.AuthenticationServiceApplication.main(AuthenticationServiceApplication.java:12) [classes/:na]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
> 	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-2.0.2.RELEASE.jar:2.0.2.RELEASE]
> Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.endpoint.web.PathMappedEndpoints]: Factory method 'pathMappedEndpoints' threw exception; nested exception is java.lang.IllegalStateException: Found multiple extensions for the endpoint bean environmentEndpoint (environmentEndpointWebExtension, environmentWebEndpointExtension)
> 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE]
> 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:579) ~[spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE]
> 	... 23 common frames omitted
> Caused by: java.lang.IllegalStateException: Found multiple extensions for the endpoint bean environmentEndpoint (environmentEndpointWebExtension, environmentWebEndpointExtension)
> 	at org.springframework.boot.actuate.endpoint.annotation.EndpointDiscoverer.convertToEndpoint(EndpointDiscoverer.java:199) ~[spring-boot-actuator-2.0.2.RELEASE.jar:2.0.2.RELEASE]
> 	at org.springframework.boot.actuate.endpoint.annotation.EndpointDiscoverer.convertToEndpoints(EndpointDiscoverer.java:184) ~[spring-boot-actuator-2.0.2.RELEASE.jar:2.0.2.RELEASE]
> 	at org.springframework.boot.actuate.endpoint.annotation.EndpointDiscoverer.discoverEndpoints(EndpointDiscoverer.java:124) ~[spring-boot-actuator-2.0.2.RELEASE.jar:2.0.2.RELEASE]
> 	at org.springframework.boot.actuate.endpoint.annotation.EndpointDiscoverer.getEndpoints(EndpointDiscoverer.java:116) ~[spring-boot-actuator-2.0.2.RELEASE.jar:2.0.2.RELEASE]
> 	at org.springframework.boot.actuate.endpoint.web.PathMappedEndpoints.lambda$getEndpoints$1(PathMappedEndpoints.java:69) ~[spring-boot-actuator-2.0.2.RELEASE.jar:2.0.2.RELEASE]
> 	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608) ~[na:1.8.0_151]
> 	at org.springframework.boot.actuate.endpoint.web.PathMappedEndpoints.getEndpoints(PathMappedEndpoints.java:68) ~[spring-boot-actuator-2.0.2.RELEASE.jar:2.0.2.RELEASE]
> 	at org.springframework.boot.actuate.endpoint.web.PathMappedEndpoints.<init>(PathMappedEndpoints.java:62) ~[spring-boot-actuator-2.0.2.RELEASE.jar:2.0.2.RELEASE]
> 	at org.springframework.boot.actuate.autoconfigure.endpoint.web.WebEndpointAutoConfiguration.pathMappedEndpoints(WebEndpointAutoConfiguration.java:120) ~[spring-boot-actuator-autoconfigure-2.0.2.RELEASE.jar:2.0.2.RELEASE]
> 	at org.springframework.boot.actuate.autoconfigure.endpoint.web.WebEndpointAutoConfiguration$$EnhancerBySpringCGLIB$$d18c3235.CGLIB$pathMappedEndpoints$2(<generated>) ~[spring-boot-actuator-autoconfigure-2.0.2.RELEASE.jar:2.0.2.RELEASE]
> 	at org.springframework.boot.actuate.autoconfigure.endpoint.web.WebEndpointAutoConfiguration$$EnhancerBySpringCGLIB$$d18c3235$$FastClassBySpringCGLIB$$1b86e66c.invoke(<generated>) ~[spring-boot-actuator-autoconfigure-2.0.2.RELEASE.jar:2.0.2.RELEASE]
> 	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-5.0.6.RELEASE.jar:5.0.6.RELEASE]
> 	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361) ~[spring-context-5.0.6.RELEASE.jar:5.0.6.RELEASE]
> 	at org.springframework.boot.actuate.autoconfigure.endpoint.web.WebEndpointAutoConfiguration$$EnhancerBySpringCGLIB$$d18c3235.pathMappedEndpoints(<generated>) ~[spring-boot-actuator-autoconfigure-2.0.2.RELEASE.jar:2.0.2.RELEASE]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
> 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE]
> 	... 24 common frames omitted

**Comment by snicoll** [comment]
The name of the extension has changed so perhaps you're not using `Finchley.RC2`?

**Comment by illingtonFlex** [comment]
I believe I am.

Here is my log file: https://www.dropbox.com/s/2naiovbnlidx2b9/startupLog1.log?dl=0

And here is my Gradle file.

```
buildscript {
    ext {
        springBootVersion = '2.0.2.RELEASE'
    }
    repositories {
        jcenter()
        maven {
            url 'https://plugins.gradle.org/m2/'
        }
    }
    dependencies {
        classpath "org.jfrog.buildinfo:build-info-extractor-gradle:4+"
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
        classpath 'net.researchgate:gradle-release:2.6.0'
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'eclipse'
    apply plugin: 'idea'
    apply plugin: 'org.springframework.boot'
    apply plugin: 'io.spring.dependency-management'
    apply plugin: 'com.jfrog.artifactory'
    apply plugin: 'maven-publish'
    apply plugin: 'net.researchgate.release'

    sourceCompatibility = 1.8
    targetCompatibility = 1.8

    artifactory {
        contextUrl = "${artifactory_contextUrl}"
        publish {
            repository {
                repoKey = 'gradle-dev-local'
                username = "${artifactory_user}"
                password = "${artifactory_password}"
                maven = true
            }
            defaults {
                publications ('mavenJava')
            }
        }
        resolve {
            repository {
                repoKey = 'gradle-dev'
                username = "${artifactory_user}"
                password = "${artifactory_password}"
                maven = true
            }
        }
    }

    publishing {
        publications {
            mavenJava(MavenPublication) {
                from components.java
            }
        }
    }

    artifactoryPublish {
        dependsOn assemble
    }

    dependencyManagement {
        imports {
            mavenBom 'org.springframework.cloud:spring-cloud-dependencies:Finchley.RC2'
        }
    }

    repositories {
        maven {
            url 'https://repo.spring.io/libs-milestone'
        }
    }

    afterReleaseBuild.dependsOn artifactoryPublish

    dependencies {
        compile('org.springframework.boot:spring-boot-starter-actuator')
        compile('org.springframework.boot:spring-boot-starter-security')
        compile('org.springframework.boot:spring-boot-starter-web')
        compile('org.springframework.cloud:spring-cloud-starter-sleuth')
        testCompile('org.springframework.boot:spring-boot-starter-test')
    }

    bootJar {
        launchScript()
    }
}
```

**Comment by spencergibb** [comment]
Actually, the names are different `environmentWebEndpointExtension` in [cloud](https://github.com/spring-cloud/spring-cloud-commons/commit/bf5de108e26fcdcb5348ec98248cf10422ea27f8#diff-62252e623bef8f519b1d5649859cd975R57) and `environmentEndpointWebExtension` in [boot](https://github.com/spring-projects/spring-boot/blob/105105db3e6d5cdecbc15afdb4458cb20f2e48de/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/env/EnvironmentEndpointAutoConfiguration.java#L64)
