### ISSUE TITLE
Support Ribbon in AsyncRestTemplate

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-commons#36]
See https://github.com/spring-cloud/spring-cloud-netflix/issues/233

see [MyfeedAutoConfig.java#L68-L83](https://github.com/spencergibb/myfeed/blob/master/myfeed-core/src/main/java/myfeed/MyfeedAutoConfig.java#L68-L83) and [RibbonAsyncClientHttpRequestFactory](https://github.com/spencergibb/myfeed/blob/master/myfeed-core/src/main/java/myfeed/RibbonAsyncClientHttpRequestFactory.java)

Not as straight forward as the standard synchronous `RestTemplate` because there is no concept of interceptors and URI resolution happens in various implementations of `AsyncClientHttpRequestFactory`

**Comment by spencergibb** [comment]
Would be much simpler if https://github.com/spring-projects/spring-framework/pull/912 was merged.

**Comment by jonekdahl** [comment]
Having an easy way of doing async, load-balanced rest calls would be very useful (and it looks like spring-projects/spring-framework#912 has been merged, so that should help).

**Comment by spencergibb** [comment]
Yup, we're waiting on that. So that will trickle down to boot 1.4 then here in the Camden release.

**Comment by jonekdahl** [comment]
Got it, thanks.

**Comment by chkpnt** [comment]
This feature isn't already implemented, is it?

**Comment by spencergibb** [comment]
@chkpnt no, you would see activity here if it were.

**Comment by 1sadus** [comment]
Any guess estimate on this one, we are waiting for it as well.

**Comment by spencergibb** [comment]
No. PRs welcome.

**Comment by rworsnop** [comment]
I'm working on this. It's working, but I need to do some refactoring, tests etc, before I submit a PR.

**Comment by rworsnop** [comment]
https://github.com/spring-cloud/spring-cloud-commons/pull/149
https://github.com/spring-cloud/spring-cloud-netflix/pull/1507

**Comment by anataliocs** [comment]
@rworsnop When your PR gets accepted is there a general timeline on when this change would be available on the release train?

**Comment by rworsnop** [comment]
That would be a question for a member of the Spring Cloud team.

**Comment by spencergibb** [comment]
@anataliocs see https://github.com/spring-cloud/spring-cloud-release/milestones
