### ISSUE TITLE
/refresh endpoint didn't close parent application context(cause memory leak)

### ISSUE THREAD

**Issue by sunnykaka** [spring-cloud/spring-cloud-commons#371]
When i request `/refresh` endpoint, spring cloud will create a application context(ContextA) to load properties.  Due to `BootstrapApplicationListener` , a parent context(ContextB) will be created.

The ContextA will be closed in `ContextRefresher.addConfigFilesToEnvironment` method. But ContextB will never be closed!!!

In my app I called /refresh thousands of times,  so I get thousands of ContextA.

I need help.

**Comment by spencergibb** [comment]
What version are you using? We've made some fixes regarding this already

**Comment by sunnykaka** [comment]
Dalston.SR4

**Comment by sunnykaka** [comment]
I found this:
[https://github.com/spring-cloud/spring-cloud-commons/pull/267]()
The issue was resolved after upgrade version to SR5, thx.
