### ISSUE TITLE
Potential bug: Generic Scope interferes with configuration property injection in @Configuration classes

### ISSUE THREAD

**Issue by davidgoate** [spring-cloud/spring-cloud-commons#373]
# Environment
* Spring Boot 2.0.2
* java version "10.0.1" 2018-04-17 Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10), Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
* OSX 10.13.4
* Finchley.RC1
* Cloud 1.2.1.RELEASE

# Code

## application-local.properties:

```properties
s3.bucketName=test-bucket
```

## Configuration Properties

```java
    @Validated
    @ConfigurationProperties(prefix = "s3")
    public class S3ConfigurationProperties {
    
        @NotBlank
        private String bucketName;
    
        public String getBucketName() {
            return bucketName;
        }
    
        public void setBucketName(final String bucketName) {
            this.bucketName = bucketName;
        }
    }
```

## Configuration Class

```java
    @Configuration
    @Profile("local")
    @EnableConfigurationProperties(S3ConfigurationProperties.class)
    public class LocalS3Configuration {
    
        @Autowired
        private S3ConfigurationProperties properties;
    
        @Value("${s3.bucketName}")
        private String bucket;
    
        @Bean(destroyMethod = "shutdown")
        public AmazonS3 amazonS3(@Value("${local.s3.endpoint}") final String s3Endpoint, @Value("${s3.bucketName}") final String bucketName) {
            // use properties...
            final String bucketInjectedToMethod = bucketName; // works
            final String bucketInjectedViaProperties = properties.getBucketName(); // null
            final String bucketInjectedInClass = bucket; // null
            
        }
    }
```

# Observed Behaviour

If I inject the `S3ConfigurationProperties` as a field to the configuration class or an argument to the `amazonS3` method the instance is `non-null`, but the `bucketName` property within it is `null`. **This appears to work fine before adding spring cloud to the mix** Could this have anyting to do with `org.springframework.cloud.context.scope.GenericScope`

Injecting the string to the class via `@Value` is also `null`.

The only way I can get it to work is to use the method argument annotated as `@Value` with a string. 

Is this expected behaviour or possibly a bug?

**Comment by spencergibb** [comment]
I don't think so. This is similar to what we do many places in the spring cloud codebase. Can you provide a project that recreates the problem?

**Comment by davidgoate** [comment]
@spencergibb https://github.com/davidgoate/spring-cloud-configuration-issue

Note: must be run with the `local` profile to demo the issue.
If you go to the `pom.xml` and comment out the spring cloud lines that I highlighted it all works ok

**Comment by marcingrzejszczak** [comment]
Is it still a problem with Finchley.RELEASE?

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by davidgoate** [comment]
I can confirm that updating to Finchley SR 1 and spring boot 2.0.5 fixes this bug.
