### ISSUE TITLE
@RefreshScope annotation isnt working

### ISSUE THREAD

**Issue by gurtejkochhar** [spring-cloud/spring-cloud-commons#375]

**Comment by spencergibb** [comment]
Please add a description

**Comment by gurtejkochhar** [comment]
Sorry, i think i missed

@RefreshScope
@RestController
class MessageRestController {

	@Value("${msg:Hello world - Config Server is not working..pelase check}")
	private String msg;

	@RequestMapping("/msg")
	String getMsg() {
		return this.msg;
	}
}

and when i do a curl
curl -X POST http://localhost:8080/refresh
{"timestamp":"2018-06-01T20:11:06.444+0000","status":404,"error":"Not Found","message":"No message available","path":"/refresh"}

**Comment by spencergibb** [comment]
Nothing to do with the refresh scope annotation. If you're using boot 2 you need to enable the endpoints (I'm on mobile, see boot docs) and then use /actuator/refresh

**Comment by gurtejkochhar** [comment]
Thanks @spencergibb
