### ISSUE TITLE
Why DiscoveryClient offers so few APIs and so little information

### ISSUE THREAD

**Issue by Eduardo95** [spring-cloud/spring-cloud-commons#376]
I see SpringCloud Eureka encapsulates Netflix Eureka, and the DiscoveryClient interface in Springcloud Eureka provides a function getInstances() to get ServiceInstances. But ServiceInstance sheilds the InstanceInfo class, in which people can see node status and other information. Why do you guys do that? Why not allow users to see node status? Thanks.

**Comment by ryanjbaxter** [comment]
I would assume because that information is not available in all implementations
