### ISSUE TITLE
Spring Boot support: use annotation processor org.springframework.boot.autoconfigureprocessor.AutoConfigureAnnotationProcessor in builds

### ISSUE THREAD

**Issue by YannCebron** [spring-cloud/spring-cloud-commons#377]
It seems Spring Cloud is currently not using above AP which generates additional metadata in `META-INF/spring-autoconfigure-metadata.properties`, storing a number of annotations/attributes for auto-configuration classes.

This information can be used both by Spring Boot to avoid classloading on startup by reading this metadata instead of loading/inspecting annotations of all autoconfiguration classes.
Furthermore, this metadata is already used by tools (e.g. IntelliJ IDEA's Spring support) to achieve a similar goal.

Given the large total # of autoconfiguration classes across all Spring Cloud -* projects, this seems a worthwhile step to improve performance.

PS: I'm unsure whether this is the correct subproject, but obviously it should be applied _across all_ Spring Cloud projects providing autoconfiguration classes.

**Comment by ryanjbaxter** [comment]
Reading through
https://docs.spring.io/spring-boot/docs/current/reference/html/configuration-metadata.html#configuration-metadata-annotation-processor

Sounds like we just need to add 
```
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-configuration-processor</artifactId>
	<optional>true</optional>
</dependency>
```
to our POMs

**Comment by snicoll** [comment]
@ryanjbaxter that's the annotation processor generating configuration keys metadata. What @YannCebron means is the annotation processor that generates metadata on auto-configuration so that we don't have to parse the load/parse the class at runtime. 

The correct dependency is

```xml
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-autoconfigure-processor</artifactId>
	<optional>true</optional>
</dependency>
```

It should be added in any project that has a `spring.factories` with registered auto-configurations.

**Comment by snicoll** [comment]
I've added [a note to the ref guide](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#boot-features-custom-starter-module-autoconfigure) as well.

**Comment by ryanjbaxter** [comment]
@snicoll thanks. We will try this for Finchley.

**Comment by ryanjbaxter** [comment]
@snicoll when I added this to spring-cloud-netflix it looks like it generated a file called `spring-autoconfigure-metadata.properties`.  The documentation said it should be a json file, is this OK?

**Comment by snicoll** [comment]
Thanks for the feedback. I made a typo and will fix the doc. Thank you!

**Comment by ryanjbaxter** [comment]
@snicoll would anything go wrong if this dependency was present and there was no `spring.factories` in that project?

**Comment by snicoll** [comment]
No, it will generate metadata for the `@Configuration` class that it finds. We have plans to use that information in the future. However, I'd advise to explicitly add the dependency where that makes sense (vs. adding that dependency in a parent or something if that's what you have in mind).
