### ISSUE TITLE
Slow application start time due to reload of the Logging Framework

### ISSUE THREAD

**Issue by benkiefer** [spring-cloud/spring-cloud-commons#38]
We are seeing some unusually slow start times (from 10 seconds to 60 seconds) in all of our Boot apps after upgrading from the 1.0.0.RC version of spring-cloud-netflix-core to a full release version (including the current 1.0.2.RELEASE). This project is transitively pulling spring-cloud-context in (1.0.1.RELEASE), and we traced down our slow start time to the BootstrapApplicationListener inside.

The specific problem is that the BootstrapApplicationListener triggers SpringApplication.run twice. This caused a reload of logback (LogbackLoggingSystem.initialize) due to the firing of a second ApplicationEnvironmentPreparedEvent. The initialize method then goes through a shutdown and restart of logging, which cost us the speed we were seeing before.

We fixed the issue by excluding spring-cloud-context as a dependency of the netflix core project, but that only worked because we weren't using anything from that module.

Are any other folks seeing this problem? Is this the right place for the issue, or should it with the logging support in spring?

**Comment by spencergibb** [comment]
I think this is the place for this if your workaround is to remove spring-cloud-contex

**Comment by benkiefer** [comment]
Good deal. A couple more pieces of information then:

Spring Boot 1.2.4.RELEASE
Logback 1.1.3

**Comment by benkiefer** [comment]
Turns out that we have a custom Logback appender that was waiting for some activity to finish up before it could shutdown. So, the speed issue was on our end.

**Comment by spencergibb** [comment]
Thanks for the further investigation @benkiefer! We appreciate the community involvement.
