### ISSUE TITLE
Make ContextRefresher fields available for sub-classes

### ISSUE THREAD

**Issue by weirui** [spring-cloud/spring-cloud-commons#382]
Question : I'm not extend the ContextRefesh ,because this variable is  protected. I should that  if keys is empty ，refresh  action not should do.

Bug report  

ContextRefresh.class

	public synchronized Set<String> refresh() {
		Map<String, Object> before = extract(
				this.context.getEnvironment().getPropertySources());
		addConfigFilesToEnvironment();
		Set<String> keys = changes(before,
				extract(this.context.getEnvironment().getPropertySources())).keySet();
		this.context.publishEvent(new EnvironmentChangeEvent(context, keys));
		this.scope.refreshAll();
		return keys;
	}

Enhancement

**Comment by ryanjbaxter** [comment]
Want to submit a pull request?

**Comment by marcingrzejszczak** [comment]
How is it going @weirui ?

**Comment by weirui** [comment]
i am sorry,because of busy work,i has forgot the thing.In our company project,i extend some function for special purpose by interceptor,but i don't like the way.the following ,i'll finish coding as soon as possible. @marcingrzejszczak
