### ISSUE TITLE
In tomcat container,Consul could not listening WebServerInitializedEvent.so,consul could not discover service

### ISSUE THREAD

**Issue by zhengzehou** [spring-cloud/spring-cloud-commons#390]
In spring-cloud 2.0, project start in tomcat,but consul can't find the service,because could not Listening to WebServerInitializedEvent 

In tomcat could not Listening to WebServerInitializedEvent ，so consul register method is not executed

who product WebServerInitializedEvent?why int tomcat not happend?
My current solution is listening ContextRefreshedEvent and call consulAutoServiceRegistration.start ().It works.

**Comment by marcingrzejszczak** [comment]
Can you please replicate this in a test so that we can see whether it's a problem or not?

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
