### ISSUE TITLE
Replace about  getLocalServiceInstance

### ISSUE THREAD

**Issue by jorrellz** [spring-cloud/spring-cloud-commons#399]
In Dalston.SR1 version ,has a funtion  getLocalServiceInstance() .
But  after Finchley.M8 version ,this funtion has Deprecated and disappeared 
How can I use it ？

```java
package org.springframework.cloud.client.discovery;

import java.util.List;
import org.springframework.cloud.client.ServiceInstance;

public interface DiscoveryClient {
    String description();

    /** @deprecated */
    @Deprecated
    ServiceInstance getLocalServiceInstance();

    List<ServiceInstance> getInstances(String var1);

    List<String> getServices();
}
```

**Comment by spencergibb** [comment]
Since the `ServiceRegistry` interface was introduced, there should be a bean of type `Registration` that would play a similar role to `getLocalServiceInstance()`. `Registration` extends `ServiceInstance`.

**Comment by jorrellz** [comment]
Thanks @spencergibb
