### ISSUE TITLE
Ordering issue with discovery client configuration

### ISSUE THREAD

**Issue by mbenson** [spring-cloud/spring-cloud-commons#40]
Was: DiscoveryCompositeHealthIndicatorTests#testHealthIndicator() fails with Spring 4.2.x

While researching https://github.com/spring-cloud/spring-cloud-commons/issues/19, I encountered a bug in `spring-boot` that causes `BootstrapConfigurationTests#pickupExternalBootstrapProperties()` to fail on Windows. To address that failure, I have opened https://github.com/spring-projects/spring-boot/pull/3299 . However, when I subsequently modify `spring-cloud-build` to use `spring-boot 1.3.0.BUILD-SNAPSHOT` it pulls in `spring-beans-4.2.0.BUILD-SNAPSHOT` which interprets the configuration of `DiscoveryCompositeHealthIndicatorTests` such that `DiscoveryCompositeHealthIndicatorTests.Config#discoveryHealthIndicator()` obscures `CommonsClientAutoConfiguration#discoveryHealthIndicator()`. So far I have determined that it's not simply a matter of the method name being duplicated, but I can't be sure whether the problem lies with `spring-beans` or `spring-cloud-commons`.

**Comment by snicoll** [comment]
Hey, I am not sure that I understand what this problem is all about. We're about to release `4.2.0.RC2` so any feedback on that would be helpful .

**Comment by mbenson** [comment]
It has been several versions back since I was fairly familiar with the
startup process of a Spring `ApplicationContext`, but I will be continuing
to step through this test using both 4.1.6 and 4.2.0 today. I can tell you
that the `CommonsClientAutoConfiguration#discoveryHealthIndicator()` method
does not seem to be showing up, but it may have been a bit of a red herring
for me to say the one "producer method" *obscures* (by which I meant
*shadows*) the other; the results are no different if I rename the method
in the test case configuration, but I have not yet determined where the
divergence in behavior begins.

**Comment by mbenson** [comment]
It has been several versions back since I was fairly familiar with the
startup process of a Spring `ApplicationContext`, but I will be continuing
to step through this test using both 4.1.6 and 4.2.0 today. I can tell you
that the `CommonsClientAutoConfiguration#discoveryHealthIndicator()` method
does not seem to be showing up, but it may have been a bit of a red herring
for me to say the one "producer method" *obscures* (by which I meant
*shadows*) the other; the results are no different if I rename the method
in the test case configuration, but I have not yet determined where the
divergence in behavior begins.

**Comment by mbenson** [comment]
AFAICT the fault does not lie in `spring-context`, but the failure occurs due to the sorting of the config beans added in https://github.com/spring-projects/spring-framework/commit/f5b4e18209c45c948ab6bce6d166ef17b3f5b25d . `CommonsClientAutoConfiguration` is declared with `@Order(0)` but `DiscoveryCompositeHealthIndicatorTests.Config` has no `@Order` defined, and the former depends, by way of `@ConditionalOnBean(DiscoveryClient.class)`, on the latter, which it knows nothing about once these orders (`0` vs. `LOWEST_PRECEDENCE`) are taken into account. If I add `@Order(-1)` to `DiscoveryCompositeHealthIndicatorTests.Config`, the container starts up and I encounter a legitimate test failure (as opposed to a startup error) due to receiving `Health` `Status.UP` when `Status.UNKNOWN` was expected, but first things first. It seems like it would kind of suck to have to change, for example, every `Configuration` that provides a `DiscoveryClient` to have a high-priority `@Order` but since the absence of an `@Order` annotation yields `LOWEST_PRECEDENCE` as a default the problem seemingly can't just be solved by changing the `@Order` of `CommonsClientAutoConfiguration`. Any options I haven't considered?

**Comment by snicoll** [comment]
Thanks a lot for tracking this down. I think we need to understand why `@ CommonsClientAutoConfiguration` has an `@Order` declaration in the first place.

**Comment by mbenson** [comment]
It depends on beans, specifically implementations of spring-cloud-commons'
DiscoveryClient interface, that are supplied by artifacts which are "lower"
in the dependency graph, i.e. they depend on spring-cloud-commons.

**Comment by wilkinsona** [comment]
This can be addressed by using `@AutoConfigureOrder` rather than `@Order` on auto-configuration classes. It's new in Boot 1.3 and was added in [this commit](https://github.com/spring-projects/spring-boot/commit/7a73c5883f857f7dfb56d73410af96eae04a0e63).

**Comment by spencergibb** [comment]
@wilkinsona thanks! This will be part of spring-cloud support for boot 1.3.

**Comment by mbenson** [comment]
I can confirm that this solves the reported issue, and echo thanks to @wilkinsona.

**Comment by dsyer** [comment]
Fixed in daf2b8f2f72
