### ISSUE TITLE
Keeping around old bean on RefreshScope refreshAll?

### ISSUE THREAD

**Issue by andrew-yang** [spring-cloud/spring-cloud-commons#403]
Hello! I want to use RefreshScope + Spring Consul Config to handle Dynamic Config for our server application. After testing, it seems that even when "bad config" is applied, the old bean is thrown away so all I have left is an error that is saved in RefreshScope. Is there any way we can keep the old bean around so that we can gracefully handle config that breaks the creation of an underlying refreshscoped bean? (Allows me to save the error but keep using an old functioning bean, so I can keep things working properly?) 

My understanding is that refreshes cause RefreshScope to throw away items in its cache completely. T_T

Thoughts?

**Comment by spencergibb** [comment]
There's currently no way to do that. What are you trying to do with refresh scope?

**Comment by andrew-yang** [comment]
Just want to refresh application configuration on dynamic changes, but want to be able to handle misconfiguration gracefully.

**Comment by spencergibb** [comment]
If you're just updating configuration, there's no need for refresh scope. @configurationproperties get updated using /actuator/refresh

**Comment by andrew-yang** [comment]
Clarification, there is initialization logic that has to happen as well, therefore RefreshScope and recreation of the underlying bean is my best bet no?

**Comment by spencergibb** [comment]
That's why I asked. Your best bet is to respond to a EnvironmentChangedEvent and deal with the logic yourself.

**Comment by andrew-yang** [comment]
Do you mean to validate incoming config on EnvironmentChangedEvent?

**Comment by spencergibb** [comment]
Yes
