### ISSUE TITLE
springcloud中eureka，指定eureka.instance.hostname

### ISSUE THREAD

**Issue by 15036900300** [spring-cloud/spring-cloud-commons#406]
springcloud中eureka，指定eureka.instance.hostname=本机域名，但是在注册中心注册的依然是ip，如何解决该问题？

**Comment by ryanjbaxter** [comment]
Can you provide the English translation?

**Comment by 15036900300** [comment]
@ryanjbaxter I use Spring Eureka and set eureka.instance.hostname with the server hostname，but it‘s still ip in the center；
For example：eureka.instance.hostname=bigdataXXX.server.org，the server hostname is bigdataXXX.server.org；
How should I solve this problem?

**Comment by 15036900300** [comment]
@ryanjbaxter The center shows ip like 10.171.162.141:nemdp-web:8080

**Comment by ryanjbaxter** [comment]
Do you have `spring.application.name` set?  `10.171.162.141:nemdp-web:8080` looks like the instance id to me.  What problem is this causing?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by 15036900300** [comment]
@ryanjbaxter I want instance id (10.171.162.141:nemdp-web:8080) to be shown as (bigdataXXX.server.org:nemdp-web:8080)

**Comment by spencergibb** [comment]
The instance id just has to be unique. It's not what is registered as the host in eureka
