### ISSUE TITLE
kafka-Serializer/Deserializer config not work if i put it in boostrap.yml,but worked in application.yml

### ISSUE THREAD

**Issue by celesky** [spring-cloud/spring-cloud-commons#409]
kafka-Serializer/Deserializer config not work if i put it in boostrap.yml,but worked in application.yml
It's very confusing,because other properties all effective except the serde properties.
eg:
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

test case:
https://github.com/celesky/spring-cloud-demo/tree/master/bus-kafka

just run it to reproduce this ~ 
thanks~

**Comment by ryanjbaxter** [comment]
I think you should report this in https://github.com/spring-projects/spring-kafka.  If they determine it is really a problem  with Spring Cloud than we can reopen this.
