### ISSUE TITLE
Consider adopting @ConditonalOnRefreshScope from spring-cloud-netflix

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-commons#411]
`spring-cloud-netflix` defines two very useful annotations to test for the RefreshScope feature: `@ConditionalOnRefreshScope` and `@ConditionalOnMissingRefreshScope`.

These annotations are currently defined in `EurekaClientAutoConfiguration` at https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/EurekaClientAutoConfiguration.java#L320-L364

It would be nice if these annotations were incorporated into commons so they could easily be reused by others.

See https://github.com/spring-cloud/spring-cloud-sleuth/issues/1086 for a first use case.

**Comment by brenuart** [comment]
Want a PR for this? And maybe another against `spring-cloud-netflix` ?

**Comment by spencergibb** [comment]
@brenuart yes

**Comment by spencergibb** [comment]
See comment here https://github.com/spring-cloud/spring-cloud-commons/pull/413#issuecomment-437901998
