### ISSUE TITLE
DiscoveryClientLoadBalancerClient is missing in spring cloud commons

### ISSUE THREAD

**Issue by gdubya** [spring-cloud/spring-cloud-commons#414]
While investigating [a Spring Cloud Gateway issue](https://github.com/spring-cloud/spring-cloud-gateway/issues/532), @spencergibb mentioned that SCC is missing a Load Balancer Client for the SimpleDiscoveryClient.

This issue is for the creation / inclusion of this client.

**Comment by spencergibb** [comment]
Actually, just based on `DiscoveryClient`

**Comment by OlgaMaciaszek** [comment]
This feature is now available via `RoundRobinLoadBalancer` + `DiscoveryClientServiceInstanceListSupplier` - we will not be adding any additional Ribbon-based implementation since Spring Cloud Netflix Ribbon is now in maintenance.
