### ISSUE TITLE
encrypt.key property no longer accepts single line input after issue 323

### ISSUE THREAD

**Issue by gioeleashman** [spring-cloud/spring-cloud-commons#418]
**Context**

* Bug Report: encrypt.key single line values (PEM text with header/footer on one line) no longer work. 
* Impacted version: spring-cloud-starter-config:2.0.1.RELEASE
* Related to issue [enhancement] #323, multi-line encrypt.key values

**TEST**
This test can be added to EncryptorFactoryTests in the spring-cloud-context project:

```
public void testRsaPrivateKeyOnOneLineLike() throws Exception {

		String key = StreamUtils.copyToString(
				new ClassPathResource("/example-test-rsa-private-key").getInputStream(),
				Charset.forName("ASCII"));

		String keyOnOneLine = key
				.replaceAll("\\n", "")
				.replaceAll("\\r", "");

		new EncryptorFactory().create(keyOnOneLine);
	}
```
That test will throw an exception with message:  "-----END RSA PRIVATE KEY not found", even though the encrypt.key is valid, it's just on a single line. Since 2.X, newly added Bouncycastle pem normalizing apparently requires input PEM text to be multiline.

**Problem**
* The intention of adding multiline support, didn't seem to imply removing existing functionality
* This gets really tedious and difficult to manage when you are copy/pasting and inputting the encrypt.key into a third party system, via a web form, for example, there can be deformation/removal of the line feeds/carriage returns causing things like that confusing exception from the noted unit test.

**Comment by ryanjbaxter** [comment]
OK, thanks for the clarification.  I guess it warrants looking into given it worked in 2.0.0.

**Comment by gioeleashman** [comment]
Thanks a lot. A note and my apologies, I mentioned the issue was introduced in 2.0.1.RELEASE, it should have been 2.0.0.M7. My previous comment has been edited.

**Comment by ryanjbaxter** [comment]
> You are right though that a regression has been introduced but considering that it is a major version change for s-c-commons, fixing a previously incorrect behavior should be acceptable?

I believe so.
