### ISSUE TITLE
Support spring-boot 1.3.0

### ISSUE THREAD

**Issue by mbenson** [spring-cloud/spring-cloud-commons#42]
This is caused by improper handling of absolute filesystem paths on Windows by `spring-boot` which is addressed by https://github.com/spring-projects/spring-boot/pull/3299 and thus requires version `1.3.0.BUILD-SNAPSHOT` in `spring-cloud-build`. However, `spring-boot 1.3.0` depends on `spring-context 4.2.0` and introduces https://github.com/spring-cloud/spring-cloud-commons/issues/40 .

**Comment by spencergibb** [comment]
I'm going to change this to a general support boot 1.3.0, similar to https://github.com/spring-cloud/spring-cloud-netflix/issues/326

**Comment by spencergibb** [comment]
Configuration ordering "can be addressed by using @AutoConfigureOrder rather than @Order on auto-configuration classes. It's new in Boot 1.3 and was added in this [commit](https://github.com/spring-projects/spring-boot/commit/7a73c5883f857f7dfb56d73410af96eae04a0e63)".

**Comment by shakuzen** [comment]
:+1: for this. I would love to be able to use Spring Boot 1.3 and Spring Cloud as soon as possible.

**Comment by dsyer** [comment]
Spring Boot 1.3 is there now. We have some issues with the CI because of a Java 8/7 incompatibility. You should be able to build with Java 8 though until we get that sorted.
