### ISSUE TITLE
How to set BackOffPolicy since LoadBalancedBackOffPolicyFactory is no longer available 

### ISSUE THREAD

**Issue by ChrisDeBruyne** [spring-cloud/spring-cloud-commons#423]
According to the current documentation, http://cloud.spring.io/spring-cloud-static/Finchley.RELEASE/single/spring-cloud.html#_backoff_policies ,I should be able to use a LoadBalancedBackOffPolicyFactory.

This class was available through spring-cloud-commons 1.3.x (https://github.com/spring-cloud/spring-cloud-commons/blob/1.3.x/spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancedBackOffPolicyFactory.java)

In the current version this class is no longer available and it seems there is no replacement for it.

What is the current solution to set the BackOffPolicy when retrying requests?

**Comment by ryanjbaxter** [comment]
Nice catch, we need to update the documentation.  You want to create a bean of type `LoadBalancedRetryFactory`.  There is a method there to return a backoff policy.

https://github.com/spring-cloud/spring-cloud-commons/blob/2.0.x/spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancedRetryFactory.java

**Comment by ChrisDeBruyne** [comment]
Thanks Ryan for the clarification.

The bean is being picked up, but now I stumbled upon the next problem.

We are using OpenFeign through spring-cloud-starter-openfeign with Ribbon.
So RibbonAutoConfiguration sets up the RibbonLoadBalancedRetryFactory;
This RetryFactory returns null from the createBackOffPolicy method.
It is here I would want to add a BackOffPolicy.

It looks like the only way to achieve this is to copy the implementation of RibbonLoadBalancedRetryFactory to my own bean and add the BackOffPolicy in there.

But this feels a bit off.
Am I missing something here or is this really the way to go?

Wouldn't it be better if there was a way to inject a BackOffPolicy?

**Comment by ryanjbaxter** [comment]
You can extend `RibbonLoadBalancedRetryFactory` and then just override `createBackOffPolicy`,

**Comment by ryanjbaxter** [comment]
Fixed via 575fb31
