### ISSUE TITLE
Lost "mainApplicationClass" property while starting up using the "SpringBootServletInitializer" way

### ISSUE THREAD

**Issue by 391861737** [spring-cloud/spring-cloud-commons#425]
**knock knock**

I recently found that my customed `EnvironmentPostProcessor#postProcessEnvironment` throws a `NullPointerException` when calling `application.getMainApplicationClass().getName()` when I deployed my web application in a tomcat server (in which application boots from `ServletContainerInitializer` under **Servlet 3.0** and invokes `SpringBootServletInitializer#onStartup` to initialize), but it works fine while I boot it using default springboot's main method.

As I traced, `org.springframework.cloud.bootstrap.BootstrapApplicationListener` listens on the `ApplicationEnvironmentPreparedEvent` and then build a different `SpringApplicationBuilder`(`#bootstrapServiceContext`) when creating the [Bootstrap Application Context](https://cloud.spring.io/spring-cloud-static/Finchley.SR1/single/spring-cloud.html#_the_bootstrap_application_context) where a new `SpringApplication` instance is created using it's constructor which deduces mainApplicationClass by searching stackTraces for the "main" method (`org.springframework.boot.SpringApplication#deduceMainApplicationClass`).
That "main" method is unfortunately absence while booting inside a tomcat server using `ServletContainerInitializer`. Hence my customed `EvnProcessor#postProcessEnvironment`'s second argument `SpringApplication`  which deduces none mainApplicationClass produces a `NullPointerException`.

After all, mainApplicationClass is really useful, and deploying in some web containers and booting from `ServletContainerInitializer` is somehow unavoidable.

Here is a demo which can reproduce this problem as you package it using different profile defined inside this demo, then run it [demo.zip](https://github.com/spring-cloud/spring-cloud-commons/files/2477535/demo.zip).
Different way to run different packages are as follows:
1. jar:   run it directly using `java -jar`.
2. war: run it in a web container (tomcat for instance). this will produce the NullPointerException I mentioned above.

**Comment by ryanjbaxter** [comment]
Closed via bbc82b4
