### ISSUE TITLE
Configuration Propery management.endpoint.env.post.enabled does not work in spring-cloud-context 2.x

### ISSUE THREAD

**Issue by germm** [spring-cloud/spring-cloud-commons#432]
The `WritableEnvironmentEndpoint` can no longer be disabled with the Configuration Property `management.endpoint.env.post.enabled=false` in spring-cloud-commons 2.x

According to the [Spring Cloud Documentation](https://cloud.spring.io/spring-cloud-static/Finchley.RELEASE/single/spring-cloud.html#_appendix_compendium_of_configuration_properties) and [spring-cloud-context Configuration Metadata](https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/resources/META-INF/additional-spring-configuration-metadata.json), the Configuration Property `management.endpoint.env.post.enabled` can be used to enable or disable changing the Environment through a POST to /env.

**Comment by spencergibb** [comment]
Those keys need to be removed from the additional metadata, as that is no longer the right way to enable or disable.

**Comment by germm** [comment]
Many thanks for your answer. What is the right way to disable the `WritableEnvironmentEndpoint`?

**Comment by spencergibb** [comment]
good question. @wilkinsona or @snicoll any way to officially disable an extension without disabling the original endpoint?

**Comment by wilkinsona** [comment]
There's nothing in Boot that'll provide that functionality without something here to enable it. If you want to be able to enable or disable an extension based on a property, I think I'd make the extension's bean `@ConditionalOnProperty`.

**Comment by spencergibb** [comment]
I think that's fine considering it's `management.endpoint.post.enabled=true` for the normal one.
