### ISSUE TITLE
@ConditionalOnClass evaluation fails on missing classes on Java 11

### ISSUE THREAD

**Issue by mp911de** [spring-cloud/spring-cloud-commons#438]
Bootstap configurations that declare class-based conditions use `StandardAnnotationMetadata` . 
Absent classes cause a `ClassNotFoundException` because Java 11 changed slightly its behavior.

Bootstrap configuration should rather use ASM-based metadata parsing to avoid this issue.

Spring Cloud Commons version: 2.1 M1
Java version: 11

This ticket results from investigation in Spring Boot (see https://github.com/spring-projects/spring-boot/issues/14873) and Spring Cloud Vault (https://github.com/spring-cloud/spring-cloud-vault/issues/254#issuecomment-434064379).

**Comment by spencergibb** [comment]
@mp911de in the two cases I see us using `AnnotationMetadata` it is with classes that implement `DeferredImportSelector` and `ImportBeanDefinitionRegistrar` and `AnnotationMetadata` is just passed in. How would we switch to ASM-based metadata parsing?

**Comment by wilkinsona** [comment]
There's a stacktrace in [this comment on the Boot issue](
https://github.com/spring-projects/spring-boot/issues/14873#issuecomment-434072039) that shows where it's going wrong.

**Comment by wilkinsona** [comment]
When the exception isn't thrown, the class is added directly as a source: https://github.com/spring-cloud/spring-cloud-commons/blob/5eb23a8c3c2c2669e6343720664ce2c656e4c88d/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/BootstrapApplicationListener.java#L207.

That's what causes `StandardAnnotationMetadata` to be used. You'd need to change that source registration mechanism to switch to ASM-based metadata.

**Comment by wilkinsona** [comment]
I think you'll need to move the handling of the `BootstrapConfiguration` sources into an `ImportSelector` that returns their class names in the `String[]`. Switching from `Class` to `String` to represent the sources that should be used, will mean that Framework switches to ASM-based metadata.

**Comment by spencergibb** [comment]
We already have the names as strings. Is there a different way to set sources on a `SpringApplicationBuilder`?

**Comment by wilkinsona** [comment]
Not that will get Framework to go down the path of using ASM-based metadata. AFAIK, you need to use an `ImportSelector` for that.
