### ISSUE TITLE
Bootstrap context is not closed in case of main context startup failure

### ISSUE THREAD

**Issue by robotmrv** [spring-cloud/spring-cloud-commons#440]
Hi!
I've found that in case of the main context start failure its bootstrap context were not closed and disposable beans were not disposed.
This behavior is observed if bootstrap context has bean which creates its own non daemon thread.
I think this issue is similar to https://github.com/spring-cloud/spring-cloud-commons/issues/333 .

Here the example app
https://github.com/robotmrv/no-close-on-start-failure
com.example.nocloseonstartfailure.bootstrap.MyBootstrapConfig#myDisposableBean  - emulates such disposable bean.
com.example.nocloseonstartfailure.main.NoCloseOnStartFailureApplication#badBean - emulates bean which cannot be instantiated.

Test Case:
1. Try to start application 

Expected result: 
application start fails and java process is finished

Actual result: 
application start fails and java process is NOT finished

**Comment by spencergibb** [comment]
This is very specific to non-daemon threads. Changing the thread in your sample to deamon and the java process ends.

**Comment by spencergibb** [comment]
I think what you want to say in "Expected result" is: application start fails, bootstrap context is closed and java process is finished.

**Comment by spencergibb** [comment]
@dsyer any thoughts on this?

**Comment by spencergibb** [comment]
See https://github.com/spring-cloud/spring-cloud-commons/pull/450
Uses similar workaround but in the BootstrapApplicationListener.

**Comment by zhanwh9** [comment]
When will this listener get invoked?
Before the CloseContextOnFailureApplicationListener is added to SpringApplication listeners, EventMulticaster has been created and has its copy of application listeners.
Thus the newly added CloseContextOnFailureApplicationListener will not be seen and invoked.

I'm using 1.2.5.RELEASE and trying to pick this fix.
