### ISSUE TITLE
bootstrap-xxx.yml is not loaded with spring.profiles.active=xxx

### ISSUE THREAD

**Issue by OlgaMaciaszek** [spring-cloud/spring-cloud-commons#441]
Issue can be reproduced with brewery zookeeper samples in zuul app setup: https://github.com/spring-cloud-samples/brewery/tree/master/zuul
The `technical/proxy` application name is not retrieved in `serviceInstanceRegistration(...)` in `ZookeeperAutoServiceRegistrationAutoConfiguration` as `bootstrap-deps.yml` is not included in `propertySources`.

**Comment by mp911de** [comment]
This issue sounds vague related to https://github.com/spring-cloud/spring-cloud-vault/issues/260 where `Environment.getActiveProfiles()` called during `BootstrapConfiguration` returns different active profiles than called in the Spring Boot application context (note: no changes to active profile during bootstrap). 

Can you have also a look at this one?

**Comment by OlgaMaciaszek** [comment]
Sure @mp911de when we work on this issue, we will also have a look at the other one.

**Comment by spencergibb** [comment]
@OlgaMaciaszek the problem is `spring.application.name` is defined in two places `bootstrap-deps.yml` and `application.yml`. `application.yml` has higher precedence and therefor sets the name to `proxy`.
