### ISSUE TITLE
AbstractAutoServiceRegistration won't start with SpringBoot 2.1.0

### ISSUE THREAD

**Issue by flystar32** [spring-cloud/spring-cloud-commons#446]
When using spring boot 2.1.0.RELEASE and spring-cloud-commons 2.0.2.RELEASE, both are the latest version.

The method "start" of AbstractAutoServiceRegistration’s subclass won't be invoke because can't receive WebServerInitializedEvent.

The root cause is the package name of the subclass which extends AbstractAutoServiceRegistration start with "org.springframework", so it won't receive WebServerInitializedEvent.

Refer to https://github.com/spring-projects/spring-framework/blob/1d59e52f118fe36b1321bc51e58759d8cd93c377/spring-context/src/main/java/org/springframework/context/event/EventListenerMethodProcessor.java#L145

Will AbstractAutoServiceRegistration modify start method invoke condition to fix this?

**Comment by ryanjbaxter** [comment]
> When using spring boot 2.1.0.RELEASE and spring-cloud-commons 2.0.2.RELEASE, both are the latest version

These are incompatible, please use Greenwich.BUILD-SNAPSHOT

**Comment by flystar32** [comment]
How can I get Greenwich.BUILD-SNAPSHOT?  found no resources here.
http://repo.spring.io/libs-snapshot/org/springframework/cloud/spring-cloud-commons/

**Comment by spencergibb** [comment]
Greenwich is the release train Bill of Materials (BOM) which contains all the compatible versions of spring cloud projects.

**Comment by spencergibb** [comment]
http://repo.spring.io/libs-snapshot/org/springframework/cloud/spring-cloud-dependencies/

**Comment by flystar32** [comment]
Greenwich.BUILD-SNAPSHOT works well
