### ISSUE TITLE
Support multiple AutoServiceRegistrations in AutoServiceRegistrationAutoConfiguration

### ISSUE THREAD

**Issue by ScienJus** [spring-cloud/spring-cloud-commons#448]
When we have defined multiple `AutoServiceRegistration`, `AutoServiceRegistrationAutoConfiguration` reports an error:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Field autoServiceRegistration in org.springframework.cloud.client.serviceregistry.AutoServiceRegistrationAutoConfiguration required a single bean, but 2 were found:
	- consulAutoServiceRegistration: defined by method 'consulAutoServiceRegistration' in class path resource [com/my/project/config/ConsulServiceAliasRegistrationConfiguration.class]
	- consulAutoServiceAliasRegistration: defined by method 'consulAutoServiceAliasRegistration' in class path resource [com/my/project/config/ConsulServiceAliasRegistrationConfiguration.class]


Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed
```

If it only need to check an `AutoServiceRegistration` exists, i think the better way is to use `ObjectProvider<List<AutoServiceRegistrationAutoConfiguration>>.getIfAvailable` instead of field injection.

What do you think? I'd like to create a pull request if you agree with this :)

**Comment by ryanjbaxter** [comment]
Why would you need more than one?

**Comment by ScienJus** [comment]
@ryanjbaxter We need to register an application as multiple services in consul.

**Comment by ryanjbaxter** [comment]
I dont think we have ever supported this.  It would need to be a separate app.

**Comment by spencergibb** [comment]
You can also manually register others manually.

**Comment by ScienJus** [comment]
@ryanjbaxter @spencergibb 

In fact, AutoServiceRegistration is always supported multiple registrations as multiple spring beans. 

So it's in version 1.3.x, specifically before [this commit](https://github.com/spring-cloud/spring-cloud-commons/commit/1829d370bad904ef59185d938367641e6c8c4513#diff-fbeb159d8b726eb0e5d4670e100c10), it is working fine.

I think that if AutoServiceRegistration already supports multiple spring beans, and AutoServiceRegistrationAutoConfiguration just wants to ensure that at least one AutoServiceRegistration exists, it should not report an error.

**Comment by spencergibb** [comment]
It was never designed for multiple auto registrations. It was designed for one and then to allow the user to register more programmatically if desired.

**Comment by spencergibb** [comment]
We make assumptions in multiple places that assume a single registration.

**Comment by ryanjbaxter** [comment]
I don’t but I am going to close this issue for now
