### ISSUE TITLE
Endpoint ID 'service-registry' contains invalid characters

### ISSUE THREAD

**Issue by liuzhongkai** [spring-cloud/spring-cloud-commons#458]
2018-12-19 11:11:42.598  WARN 13196 --- [           main] o.s.boot.actuate.endpoint.EndpointId     : Endpoint ID 'service-registry' contains invalid characters, please migrate to a valid format.

**Comment by liuzhongkai** [comment]
spring-boot-starter-actuator 2.1.1.RELEASE

**Comment by spencergibb** [comment]
It is only a warning that can be ignored for now.

**Comment by tanuja3088** [comment]
Facing same issue also unable to register my service to eureka it remains in STARTING status

**Comment by aflaifel** [comment]
facing the same issue and can't inject any values from application.yml file

**Comment by nintha** [comment]
if `EndpointId` includes '-' or '.', it prints this warning.

```
// org.springframework.boot.actuate.endpoint.EndpointId.java
private static final Pattern WARNING_PATTERN = Pattern.compile("[\\.\\-]+");
// ...
// other codes
// ...
if (WARNING_PATTERN.matcher(value).find()) {
    logWarning(value);
}
// ...
// lots of other codes
// ...
private static void logWarning(String value) {
    if (logger.isWarnEnabled() && loggedWarnings.add(value)) {
        logger.warn("Endpoint ID '" + value + "' contains invalid characters, please migrate to a valid format.");
    }
}
```

**Comment by spencergibb** [comment]
> It is only a warning that can be ignored for now.

**Comment by nintha** [comment]
> > It is only a warning that can be ignored for now.
Thanks for your reply. However, it is wired WARNING_PATTERN. Will it be fixed in the next version?

**Comment by linux5396** [comment]
> > It is only a warning that can be ignored for now.
exc. why I see an Instance from eureka website after set register-with-eureka and fetch-registry into false?

**Comment by antonkhvorov** [comment]
Any updates?

**Comment by spencergibb** [comment]
No

**Comment by ryanjbaxter** [comment]
There is an issue open in Boot to help address this problem https://github.com/spring-projects/spring-boot/issues/18148

**Comment by ryanjbaxter** [comment]
We have communicated with the Boot team and they have decided that they will not remove support for ids with invalid characters until the next major release.  At that point we will migrate the ids to avoid any breaking changes in a minor release.

**Comment by JWThewes** [comment]
Still not resolved with Hoxton...any plans on fixing this. I don't like warnings in my startup log ;)

**Comment by spencergibb** [comment]
No current plans until a major release as it would be a breaking change

**Comment by ionutincau** [comment]
I don't mind about the warning but I am using spring-cloud-starter-kubernetes 1.1.1.RELEASE and I want to see the available services with Spring Admin over the discoveryClient actuator endpoint

**Comment by ramazansakin** [comment]
Still the same warning :/

**Comment by spencergibb** [comment]
@ramazansakin saying that without saying what version you are using isn't very helpful

**Comment by ramazansakin** [comment]
Cloud : Hoxton.SR9
spring : 2.2.12

any other info ? @spencergibb

**Comment by spencergibb** [comment]
This was only fixed in 2020.0.0 and will not be fixed in hoxton because it is a breaking change

**Comment by ArberChang** [comment]
> 
> 
> Still not resolved with Hoxton...any plans on fixing this. I don't like warnings in my startup log ;)

me too

**Comment by spencergibb** [comment]
@ArberChang see the comment above yours. Since it's a breaking change it will NOT be fixed in hoxton.
