### ISSUE TITLE
String Array Type Property from yml is works differently.

### ISSUE THREAD

**Issue by sjkim2322** [spring-cloud/spring-cloud-commons#460]
It seems to use [ConfigFileApplicationListener](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/config/ConfigFileApplicationListener.java#L371
) to read spring's profile from file of application- "profile" .yml type except for the Spring cloud normally.
Bind the profile list to the String [] from the environment (using Binder)
Here, the best case is as follows.
```yml
spring.profiles.include:
      - far
      - boo
```
However, the following comma seperated forms work well.
```yml
spring.profiles.include: far,boo
```
Even comma seprated forms, including white space, work well.
```yml
spring.profiles.include: far, boo
```
However, in the case of comma seprated with white space, [PropertySourceBootstrapConfiguration](https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/config/PropertySourceBootstrapConfiguration.java#L235)
Does not seem to work normally when updating the profile at.
In this configuration, StringUtils is used to bind to Object to String array without using Binder.
Since we do not trim the white space here, the final result will be generated as follows.
```text
The following profiles are active:  far,boo,far
```
The format of yml, including white space, is not a regular method, but should not the behavior in PropertySourceBoottsrapConfiguration and ConfigFileApplicationListener work together?

**Comment by ryanjbaxter** [comment]
I dont see this locally.  
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.
