### ISSUE TITLE
Different behavior of spring.cloud.bootstrap.location since Spring Boot 2

### ISSUE THREAD

**Issue by srempfer** [spring-cloud/spring-cloud-commons#466]
I noticed a different behavior of the property `spring.cloud.bootstrap.location` since Spring Boot 2.x

**Behavior in Spring Boot 1.x:**

- Build in bootstrap.properties file inside the JAR *is* regarded
- Specified bootstrap.properties file is regarded

**Behavior in Spring Boot 2.x:**

- Build in bootstrap.properties file inside the JAR *is not* regarded
- Specified bootstrap.properties file is regarded

Reason is that since Spring Boot 2 the behavior of the `spring.config.location configuration` has been fixed and the property `spring.cloud.bootstrap.location` works now also as desired.

See https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#configuration-location

I restored the origin behavior by adding the default search locations to the property in addition `spring.cloud.bootstrap.location=classpath:/,classpath:/config/,file:./,file:./config/,file:/my/special/search/location`

It would be great to introduce also a new property `spring.cloud.bootstrap.additional-location` like the `spring.config.additional-location`.

See also https://stackoverflow.com/questions/54204333/different-behavior-of-spring-cloud-bootstrap-location-since-spring-boot-2

I'll try to provide a pull-request in the next days for that.

**Comment by ryanjbaxter** [comment]
closed via 70129ec
