### ISSUE TITLE
Why Dependency Inject ObjectProvider ? 

### ISSUE THREAD

**Issue by xiejiashuai** [spring-cloud/spring-cloud-commons#467]
## Desc
When I read the source code of spring cloud ,eg `open feign` ,`spring cloud commons loadbalancer` and so on,I find a very interesting thing that some spring bean use` ObjectProvider<T>` to dependency inject eg `LoadBalancerAutoConfiguration`.

## Question
Why not dependency inject the target bean ? eg `di` `List<LoadBalancerClientSpecification>` not `ObjectProvider<List<LoadBalancerClientSpecification>>` in `LoadBalancerAutoConfiguration`.

- I was puzzled ，can help me ?

**Comment by ryanjbaxter** [comment]
Because `ObjectProvider` provides us a way to account for when there are no `LoadBalancerClientSpecification` beans.

**Comment by xiejiashuai** [comment]
> Because `ObjectProvider` provides us a way to account for when there are no `LoadBalancerClientSpecification` beans.

But we cat use the following 
```java
public class XXX{
   
@Autowired(required=fasle)
private YYY yyy;


}
```
or 
```java
public class XXX{
   
@Autowired
private Optional<T> optianl;

}
```
or 
```java
public class XXX{
   
@Autowired
@NullAble
private private YYY yyy;

}
```
to do this. 

so what is difference the above samples with `ObjectProvider ` ?

**Comment by ryanjbaxter** [comment]
It eliminates the need for the `@autowired` private variable.  Unless this is causing a bug I dont see why this issue is opened.

**Comment by spencergibb** [comment]
For a framework that's an internal decision. We try not to autowire fields. And in many situations it allows us also to do lazy injection.
