### ISSUE TITLE
MapPropertySources created by EnvironmentPostProcessor run twice and 2nd run wins

### ISSUE THREAD

**Issue by jxblum** [spring-cloud/spring-cloud-commons#476]
In a nutshell, when the `org.springframework.cloud:spring-cloud-services-starter-service-registry` dependency is added to the CLASSPATH of a _Spring Boot_, Pivotal GemFire `ClientCache` application deployed to PCF, connected to PCC, the dependency loses critical, contextual information stored in the `Environment` by _Spring Boot for Pivotal GemFire_ ([SBDG](https://github.com/spring-projects/spring-boot-data-geode)) using a custom `PropertySource`.

As a result, the _Spring Boot_, Pivotal GemFire `ClientCache` application (based on SBDG) is unable to authenticate and connect to the PCC instance deployed in PCF.

You can successfully reproduce this issue by doing the following:

1. Clone the [SBDG](https://github.com/spring-projects/spring-boot-data-geode) project.

2. Create a _topic branch_ from `1.0.0.M3` ([here](https://github.com/spring-projects/spring-boot-data-geode/tree/1.0.0.M3)).

> NOTE: You cannot simply branch from the HEAD of `master` since I have already checked in a "workaround" to this issue in [commit 2e26325](https://github.com/spring-projects/spring-boot-data-geode/commit/2e263257f2500adb204cd07ce24927d9a8eb4810).

3. Add the `org.springframework.cloud:spring-cloud-services-starter-service-registry` to the CLASSPATH of the SBDG `spring-geode-autoconfigure` module (for [example](https://github.com/spring-projects/spring-boot-data-geode/blob/master/spring-geode-autoconfigure/spring-geode-autoconfigure.gradle#L32-L34)).

4.  Then, run the [`AutoConfiguredCloudSecurityContextIntegrationTest`](https://github.com/spring-projects/spring-boot-data-geode/blob/master/spring-geode-autoconfigure/src/test/java/org/springframework/geode/boot/autoconfigure/security/auth/cloud/AutoConfiguredCloudSecurityContextIntegrationTests.java) class and see the test fail!

Without the `org.springframework.cloud:spring-cloud-services-starter-service-registry` dependency on the CLASSPATH, the `AutoConfiguredCloudSecurityContextIntegrationTest` passes as expected.

After in-depth analysis, my debugging revealed the main culprit in this issue involves the [`BootstrapApplicationListener`](https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/BootstrapApplicationListener.java) class.

In summary...

The `BootstrapApplicationListener`, as its name implies, creates a new (temporary) "bootstrap" `ApplicationContext` along with a new (also, temporary) `Environment` object.  This "bootstrap" context becomes the "parent" of the main `ApplicationContext` started/initialized by the _Spring Boot_ application on startup.  The `BootstrapApplicationListener` additionally copies/removes critical information (e.g. a SBDG custom `PropertySource`) from the main `Environment` to the "bootstrap" `Environment` object, which is later discarded from the "bootstrap" `Environment`.  This "bootstrap" `Environment` is somehow passed to the SDG Security configuration handling classes, thus causing the underlying SDG `@Configuration` class used to authenticate the GemFire `ClientCache` app instance with PCC in PCF to not have the necessary Security (auth) credentials available to it upon inspecting the `Environment`, leading to an eventual authentication error.

Anyway, I tracked the beginning of this issue down to this [snippet of code](https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/BootstrapApplicationListener.java#L253).  
Because SBDG used a `PropertiesPropertySource` to capture the Security (auth) credentials from the VCAP environment into a custom named `PropertySource`, and the _Spring_ `PropertiesPropertySource` is an `EnumerablePropertySource`, this is how the SBDG custom name `PropertySource` gets copied and lost, unlike other `PropertySources`, which _Spring Boot_ adds, that won't get lost because they are not `EnumerablePropertySources`. :(

Additional details for this problem may/will be provided below, in follow up comments, as necessary.

**Comment by scottfrederick** [comment]
> 3. Add the org.springframework.cloud:spring-cloud-services-starter-service-registry to the CLASSPATH of the SBDG spring-geode-autoconfigure module (for example).

I was able to follow the steps above but add this Spring Cloud dependency instead of the Spring Cloud Services dependency: 

```
testRuntime("org.springframework.cloud:spring-cloud-starter-netflix-eureka-server:2.0.2.RELEASE") {
	exclude group: "org.springframework.boot", module: "spring-boot-starter-logging"
}
```

This also reproduces the problem, and reduces the surface area a bit to Spring Cloud OSS libs.

**Comment by spencergibb** [comment]
This in fact is the minimum required
```
testRuntime("org.springframework.cloud:spring-cloud-starter:2.0.2.RELEASE")
```

**Comment by spencergibb** [comment]
See https://github.com/spring-cloud/spring-cloud-commons/commit/12b9bfbe for the original commits of related functionality.

**Comment by spencergibb** [comment]
I am unable to reproduce this in a small standalone project. I added `VCAP_APPLICATION` and `VCAP_SERVICES` locally and it works fine. Something about running in PCF and John's test makes the problem occurr (In john's test the env post processor runs 4 times, all my tests run it just twice). If anyone can help repdocuce this locally, that would help. /cc @wxlund

**Comment by wxlund** [comment]
Why isn't the test case described by @jxblum adequate for confirming the bug where the PCC/PCF env is mocked?  We know the test case of pushing to the app to PCF breaks every time its executed and this bug caused a lot of lost time in discovering and isolating.

**Comment by spencergibb** [comment]
@wxlund I need a way to reproduce it locally so we can find a fix (we still don't know why it happens in john's test vs locally) and test against regression.

**Comment by smanukyan** [comment]
@spencergibb - we have seen this issue consistently on local as well as in PCF, here is the github code to replicate the issue https://github.com/wxlund/spring-boot-for-gemfire-geode-samples

**Comment by spencergibb** [comment]
@smanukyan That is the project I was using locally.

**Comment by spencergibb** [comment]
@smanukyan a local geode.

**Comment by smanukyan** [comment]
@spencergibb - can you please confirm, you can replicate the issue when your local app is connected to PCC running in PCF?

**Comment by spencergibb** [comment]
I don't know how to do that

**Comment by spencergibb** [comment]
https://github.com/spring-projects/spring-boot-data-geode/pull/22

**Comment by jxblum** [comment]
And then... https://github.com/spring-projects/spring-boot-data-geode/pull/22#issuecomment-462470763

**Comment by jxblum** [comment]
Additionally, my [test](https://github.com/spring-projects/spring-boot-data-geode/blob/master/spring-geode-autoconfigure/src/test/java/org/springframework/geode/boot/autoconfigure/security/auth/cloud/AutoConfiguredCloudSecurityContextIntegrationTests.java) is local, FTR.  It only mocks a PCF (with PCC) environment.

**Comment by jxblum** [comment]
Finally, I would also add... 1) why does SCS's `BootstrapApplicationListener` only care about `EnumerablePropertySource` objects (?) and, 2) why does this class remove `EnumerablePropertySource` objects from the main `Environment` object (which it copied to the `bootstrapEnvironment`) when it finishes its work?

**Comment by jxblum** [comment]
1 more thing... I wrote a example/test Spring Boot application with Spring Cloud on the classpath reproducing the issue.  This example/test does not use SBDG.

See here for more details: https://github.com/jxblum/spring-boot-cloud-example

**Comment by smanukyan** [comment]
thank you for fixing the bug! we are currently using spring-cloud-commons  version: 2.1.0.M1  , will this issue be fixed there as well? or we will need to fall back to 2.0.3.RELEASE?

**Comment by spencergibb** [comment]
why are you using a milestone?  This will be part of 2.0.3.RELEASE and 2.1.1.RELEASE

**Comment by markpollack** [comment]
FWIW, I ran into the same issue with environmentpostprocessors for the new java-cfenv project and didn't report it since it was tied up in a larger project.  Does this mean env-post-processors will no longer run twice?

**Comment by spencergibb** [comment]
@markpollack no it doesn't.
