### ISSUE TITLE
Manage okhttp3 in commons

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-commons#477]
Use bom

https://search.maven.org/artifact/com.squareup.okhttp3/okhttp-bom/3.12.1/pom

We have different versions around spring cloud.

**Comment by OlgaMaciaszek** [comment]
@ManasviGoyal is working on the issue.

**Comment by ManasviGoyal** [comment]
I am getting error, what can be the reason?

**Comment by spencergibb** [comment]
I think this might have been needed in hoxton, but spring-boot manages this since boot 2.4.

https://github.com/spring-projects/spring-boot/blob/3e0829cd476f5fe856b4ec66a1e37edeb40c3bb6/spring-boot-project/spring-boot-dependencies/build.gradle#L1243-L1257

I don't think this is needed anymore.

**Comment by ManasviGoyal** [comment]
> I think this might have been needed in hoxton, but spring-boot manages this since boot 2.4.
> 
> https://github.com/spring-projects/spring-boot/blob/3e0829cd476f5fe856b4ec66a1e37edeb40c3bb6/spring-boot-project/spring-boot-dependencies/build.gradle#L1243-L1257
> 
> I don't think this is needed anymore.

so i need to remove this part of code?

**Comment by spencergibb** [comment]
I'm saying the PR and this issue are no longer needed. spring cloud vault should just remove it's dependency management of okhttp3

**Comment by mp911de** [comment]
FWIW, spring Cloud Vault uses okhttp3 as an optional dependency without managing it through `spring-cloud-vault-dependencies`. HTTP connector discovery happens at the level of Spring Vault so we don't need to define it in Spring Cloud Vault anymore.

**Comment by OlgaMaciaszek** [comment]
Closing the issue based on comments from @spencergibb and @mp911de .
