### ISSUE TITLE
Dry run for context refresh

### ISSUE THREAD

**Issue by tdanylchuk** [spring-cloud/spring-cloud-commons#479]
Hello spring cloud community! 

Currently I'm working on a problem of refreshing configs on all instances of particular service.
We have here obvious 2 pretty similar approaches:
1. Call **_/refresh_** on each instance (get all instances for some service registry, e.g. Eureka)
2. Integrate spring bus, and call **_/bus-refresh/{service-name}_**

Since I have cloud configs being retrieved from spring cloud service, on each refresh my services tries to fetch newest configs from **config-server**. Unfortunately we live in not ideal world where ppl tend to make mistakes, and having malformatted edits of cloud configs is not an exception.

So in case if some bad properties were added to cloud config source we will have instances with down state, since ```@ConfigurationProperties``` validation (e.g. ```@Min(10)``` and ```property=9```) will throw exception during refreshing spring context and ```RefreshScopeHealthIndicator``` will go down, means whole cluster after being updated via bus will be kicked out of service registry due to ```DOWN``` status.

I'm trying to figure out how we can omit such unfortunate case, and so far best idea, is to implement some kind of ```refresh(dryRun=true)``` method. Using this we can try invoke **_/refresh?dryRun=true_** on one node (which will try to re-create all refresh scoped beans or at least only configuration properties and re-fetch all cloud configuration, but **not applying it to context** and have some feedback about issues with validation if such). And based on this, we can decide whether we can proceed forward with whole cluster _**/refresh?dryRun=false**_ .

I've surfed the code base and it seems to be not so easy to implement, but maybe there is another approach how we can check whether refresh could go well or not?

**Comment by spencergibb** [comment]
There are 3 things happening:
1- properties are fetched and applied to spring environment
2- `@ConfigurationProperties` are re-bound
3- refresh scope is cleared, so next access to beans marked as such we be recreated

All of those things are live. They can be separated (/refresh does all three). A dry run would be exceptionally difficult.

I'd suggest testing changes in a staging environment and/or a production canary

**Comment by tdanylchuk** [comment]
As for you suggestion, it also was considered by me, but it's not that easy to run separate instance just for check whether configs are ok or not due to:
1. Running canary just for this makes this flow very complicated, since it requires additional CICD flow changes.
2. Configuration refresh should be easy and fast as possible (IMHO) and this approach is not getting us to that point.

In any case thx for reply, I just wanted to see whether we can have some kind a backdoor w\o changing a lot, seems like we don't have =)

**Comment by spencergibb** [comment]
> Maybe copy environment + update it from cloud + get only ConfigurationProperties from context to create copy of them instead of re-bound real one won't be that hard?)

Yes, that all happens in Spring Boot, we just trigger it.

One thing that I think would fit the bill here is the ability to roll back the configuration to the previous version from config server, but that a feature for config server specifically. I have some ideas on that for the future.

**Comment by spencergibb** [comment]
https://github.com/spring-cloud/spring-cloud-config/issues/1248

**Comment by tusharnitharwal** [comment]
> > Maybe copy environment + update it from cloud + get only ConfigurationProperties from context to create copy of them instead of re-bound real one won't be that hard?)
> 
> Yes, that all happens in Spring Boot, we just trigger it.
> 
> One thing that I think would fit the bill here is the ability to roll back the configuration to the previous version from config server, but that a feature for config server specifically. I have some ideas on that for the future.

Any update on this? I'm specifically looking for a production level solution for handling rollbacks
