### ISSUE TITLE
Potentially move BootstrapApplicationListener to EnvironmentPostProcessor

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-commons#48]
Look at https://github.com/spring-projects/spring-boot/commit/e370b592d66ad9b01ff2bfff4b5991f0ac3a9751 and see if it makes sense to migrate. /cc @dsyer

**Comment by dsyer** [comment]
Not sure that makes sense. `BootstrapApplicationListener` is actually an aggregator of `ApplicationContextInitializers` (not restricted to `Environment` processing),and it offers the ability to do DI into the things it aggregates. An `EnvironmentPostProcessor` is much dumber - created by `spring.factories` using a default constructor. We have already migrated to use `EnvironmentPostProcessor` where appropriate (and necessary) - basically anywhere the old `ConfigFileApplicationListener` was used explicitly.

**Comment by spencergibb** [comment]
NP, if it doesn't make sense, let's close this.
