### ISSUE TITLE
Collection and Map are not updated correctly when refresh is triggered

### ISSUE THREAD

**Issue by RaphC** [spring-cloud/spring-cloud-commons#485]
Hi, 
I'm facing an issue with /refresh when my @ConfigurationProperties bean has a typed Collection attribute.
I'm using spring-boot 1.5.19.RELEASE and spring-cloud Edgware.SR5.

Here is a way to reproduce : 

I have an application.yml file which contains

example:
  myList: 
    - A
    - H
    - P

This property is binding with my @ConfigurationProperties bean

     @ConfigurationProperties("example")
     @RefreshScope
     @Validated
     public class MyApplicationConfigurationProperties {

	List<String> myList;

	public List<String> getMyList() {
		return myList;
	}

	public void setMyList(List<String> myList) {
		this.myList = myList;
	}
     }

I exposes a @RestController which return this list

     @SpringBootApplication
     @EnableConfigurationProperties(MyApplicationConfigurationProperties.class)
     @RestController
     @EnableAutoConfiguration
     public class SpringCloudConfigIssue421Application {
	
	@Autowired
	private MyApplicationConfigurationProperties configurationProperties;
	
	public static void main(String[] args) {
		SpringApplication.run(SpringCloudConfigIssue421Application.class, args);
	}
	
	@GetMapping(produces="application/json", value="/mylist")
	public List<String> getMyListe(){
		return configurationProperties.getMyList();
	}
     }

I launch my app (mvn spring-boot:run) and invoke /mylist endpoint. So the application returns

     ["A","H","P"]

So then, I change my application.yml file with the following content

example:
  myList: 
    - H
    - P
... and call POST /refresh endpoint. Everything seems fine

["example.myList[0]","example.myList[2]","example.myList[1]"]

... finally a call again /mylist endpoint and the application returns

     ["H","P","P"]

The last item is not removed from the property.

Here is a repo from which you can reproduce the bug https://github.com/RaphC/spring-cloud-refresh

**Comment by ryanjbaxter** [comment]
Can you try with Greenwich.RELEASE?

**Comment by RaphC** [comment]
Hi @ryanjbaxter , I'll try it.

**Comment by RaphC** [comment]
Hi @ryanjbaxter , I've just tested with Greenwich.RELEASE. It works ! Thank you

**Comment by ryanjbaxter** [comment]
Would you mind trying Finchley.SR2?  I am wondering if this is really just a problem in Spring Boot.

**Comment by RaphC** [comment]
Hi @ryanjbaxter , I've just tested with Finchley.SR2 and spring-boot 2.1.3.RELEASE. It works.

**Comment by ryanjbaxter** [comment]
> Finchley.SR2 and spring-boot 2.1.3.RELEASE

Finchley.X is not compatible with boot 2.1.x. Can you try Finchley.SR3 with boot 2.0.8?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
