### ISSUE TITLE
config-client no need @RefreshScope 

### ISSUE THREAD

**Issue by laxiwang** [spring-cloud/spring-cloud-commons#487]
clould : Finchley.RELEASE
boot : 2.0.2.RELEASE
refreshing configuration files at the receiving end without no need @RefreshScope annotation

this is my public git address ： https://git.imooc.com/wmy/private-error-order.git
contain eureka config-server(config) config-client(order)
demo url in order project http://192.168.0.118:9002 /girl/print
configuration file use order-dev.yml in https://gitee.com/halfroom/config-repo.git
!!!!!! manually refresh bus address after configuration change
http://192.168.0.118:9091/actuator/bus-refresh

**Comment by spencergibb** [comment]
Configuration properties have never needed the refresh scope annotation.

**Comment by laxiwang** [comment]
in Finchley.M2  version need it not? 
i have a demo   need  the refresh scope annotation  in   Finchley.M2  version

**Comment by spencergibb** [comment]
M2 is a milestone. Try SR3

**Comment by laxiwang** [comment]
非常感谢
