### ISSUE TITLE
Remove or replace deprecated usages

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-commons#488]
Spring Boot 2.1 deprecated some stuff that we are still using. So it is breaking apps that use 2.2 snapshots, when the deprecations have been removed. It would be best really to avoid using such deprecated code, but we might be able to ask for a reprieve if we really need it. Example here is `DiscoveryCompositeHealthIndicator`.

**Comment by spencergibb** [comment]
I did fix this on master

**Comment by dsyer** [comment]
I see that now. Did we get them all? Not sure why I didn't get that in the snapshot build I was using - maybe the Hoxton BOM isn't referencing master yet.

Probably a good idea to fix in 2.1 though (Greenwich)?

**Comment by spencergibb** [comment]
Probably both

**Comment by spencergibb** [comment]
Done in #592 & #610
