### ISSUE TITLE
Get spring cloud version

### ISSUE THREAD

**Issue by SoftwareKing** [spring-cloud/spring-cloud-commons#489]
I want to get spring cloud version, how to get it? get spring boot version,as follows

```java
SpringBootVersion.getVersion();
```
I want to get spring cloud version,Is there any way?

**Comment by shakuzen** [comment]
Duplicate of #421

**Comment by SoftwareKing** [comment]
Duplicate of #421，Repeat for a long time, when to support？@shakuzen @royclarkson

**Comment by SoftwareKing** [comment]
Close directly? When will it be settled? @ryanjbaxter

**Comment by spencergibb** [comment]
Please follow #421. It is not scheduled.
