### ISSUE TITLE
ConfigurationPropertiesRebinder should return false if beanName is null

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-commons#49]
In some cases the beanName maybe null.  
Currently ConfigurationPropertiesRebinder throws an Assert for a null bean name when it tries to get the bean definition.  This was found when attempting to enable the cloud config for spring cloud data and the Yarn Client's yarnConfiguration (which has null for the bean name ) failed during the ConfigurationPropertiesRebinder BPP. 
The proposed change would have isRefreshScoped return false if the beanName is null.  I will be submitting a PR

**Comment by dsyer** [comment]
Fixed in #50
