### ISSUE TITLE
Disable the bootstrap context in a smarter way

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-commons#493]
It's quite fast to start the bootstrap context, but sometimes an app will be more than happy to start without it - especially when running locally in an IDE, where you want it to be as fast as possible. It only takes 50-100ms, which isn't much, but these days people are starting to care with app startup times down to 1000ms. As a user you can always set `spring.cloud.bootstrap.enabled=false`, but maybe the framework can figure out when that is a reasonable default.

**Comment by dsyer** [comment]
I'm not sure 50-100ms is accurate. I see it down to 10ms in many apps. It must depend on what is actually being done in there. Property decryption is probably the most expensive operation.

**Comment by spencergibb** [comment]
also config client going over a network likely isn't fast.

**Comment by spencergibb** [comment]
bootstrap is disabled by default now.
