### ISSUE TITLE
BootstrapConfigurationTests.includeProfileFromBootstrapProperties() fails with boot 2.2.x

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-commons#494]
Maybe something changed with profiles

**Comment by ryanjbaxter** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-commons/commit/8b57f1995bea54ff317194b13b7eeae3e5aea773#diff-fd0e7a07e090929815704ed67fbc20fa
