### ISSUE TITLE
what is feature

### ISSUE THREAD

**Issue by springAppl** [spring-cloud/spring-cloud-commons#495]
I am watching 1.3.x branch code. Could add some annotations for Feature and other classes.
![41552622234_ pic_hd](https://user-images.githubusercontent.com/22255152/54407631-86a18e80-4719-11e9-9d31-71254f5a8c9d.jpg)
Authough hasFeatures is not required, I want to know where to insert element into it.

**Comment by ryanjbaxter** [comment]
Please elaborate on your use case.

**Comment by springAppl** [comment]
I am writing a blog。I want to explain the use of  FeaturesEndpoint.   The hasFeatures is empty in the picture。where the hasFeatures is inserted values in the code。

**Comment by spencergibb** [comment]
See https://github.com/spring-cloud/spring-cloud-netflix/blob/805818941cf4ad8208dba1d57fca0b450e6c6f77/spring-cloud-netflix-eureka-server/src/main/java/org/springframework/cloud/netflix/eureka/server/EurekaServerAutoConfiguration.java#L109-L113
