### ISSUE TITLE
Multi-tenant situation,Dynamic construction DiscoveryClient

### ISSUE THREAD

**Issue by SoftwareKing** [spring-cloud/spring-cloud-commons#512]
Use Spring Boot Admin in multi-tenant situations，How to Realize Dynamic Construction DiscoveryClient，Support dynamic handover to connect different registries。

https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server-cloud/src/main/java/de/codecentric/boot/admin/server/cloud/discovery/InstanceDiscoveryListener.java

```java

private final DiscoveryClient discoveryClient;

protected void discover() {
        Flux.fromIterable(discoveryClient.getServices())
            .filter(this::shouldRegisterService)
            .flatMapIterable(discoveryClient::getInstances)
            .flatMap(this::registerInstance)
            .collect(Collectors.toSet())
            .flatMap(this::removeStaleInstances)
            .subscribe(v -> { }, ex -> log.error("Unexpected error.", ex));
    }

```

**Comment by ryanjbaxter** [comment]
I am not sure what you are asking, can you provide a better description?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
