### ISSUE TITLE
ribbon always use not secure port

### ISSUE THREAD

**Issue by chenjie901** [spring-cloud/spring-cloud-commons#554]
@Override
	public ServiceInstance choose(String serviceId) {
		Server server = this.getLoadBalancer().chooseServer(serviceId);
		if (server != null) {
			return new RibbonLoadBalancerClient.RibbonServer(serviceId, server);
		}
		return null;
	}

after selected a server ribbon always use none secure port

this problem cause ribbon can not make request for https server

2.0.0.RELEASE

**Comment by ryanjbaxter** [comment]
How is Ribbon getting the list of servers?  Also please use the latest Finchley release (SR4).

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
