### ISSUE TITLE
How to make my EnvironmentChangeEvent listener execute only after ConfigurationPropertiesRebinder?

### ISSUE THREAD

**Issue by leason805** [spring-cloud/spring-cloud-commons#555]
[Question]

I have a requirement that once i got the properties refreshed, i need to handle some logic base on the updated properties.
So i implemented an EnvironmentChangeEvent listener, but i found that no matter how i changed the precedence, ConfigurationPropertiesRebinder always execute after my listener.
As i check the source code of ConfigurationPropertiesRebinder, it may use the default precedence , which the same as my listener, how can i set my listener's precedence after ConfigurationPropertiesRebinder?

Source code for reference

==============================

@Order(Ordered.LOWEST_PRECEDENCE)
public class MyEnvironmentChangeListener implements ApplicationListener<EnvironmentChangeEvent> {

	@Autowired
	private MyProperties myProperties;
	
	@Override
	public void onApplicationEvent(EnvironmentChangeEvent event) {
		for(String key : event.getKeys()){
			if(key.startsWith("my-prefix")){
				//do something with updated myProperties
				//but i saw the myProperties still not update at this moment
				//and i have to manually trigger the rebind by ConfigurationPropertiesRebinder.rebind("MY_PROPERTY_BEAN") ,which will cause rebind twice
			}
		}
	}
}

@ConfigurationProperties("my-prefix")
public class MyProperties {

	private String name;
}

**Comment by spencergibb** [comment]
https://github.com/spring-cloud/spring-cloud-commons/blob/236de036382bbeb1b8812ac038f0f74f7a5adee8/spring-cloud-context/src/main/java/org/springframework/cloud/context/properties/ConfigurationPropertiesRebinder.java#L124-L130

Is also a listener.

Why do you use `LOWEST_PRECEDENCE`. That means last. Try `HIGHEST_PRECEDENCE`.

**Comment by leason805** [comment]
Hi, thank you for your prompt response.
Actually, what i want is, after myProperties updated, i will do some logic base on the updated object.
My understanding is HIGHEST_PRECEDENCE means MyEnvironmentChangeListener will be listed on the top of the listener list, which it will be executed b4 ConfigurationPropertiesRebinder, so i still can not get the updated myProperties at that moment.

**Comment by spencergibb** [comment]
The ordering is a framework concern. Maybe there is another event, `ConfigurationPropertiesRebound`?

**Comment by leason805** [comment]
i hope so, but no luck. ~_~
Maybe the only way is to check how the framework load the listners into the list when start up, and try to make my listener at the bottom of the list. Anyway, thank you so much!

**Comment by typik89** [comment]
The proposed solution with @Order doesn't work for me. I've found interesting effect that: if I inject ConfigurationPropertiesRebinder to my listener then its onApplicationEvent method is executed after @ConfigurationProperties classes was updated.
```
@Component
class RefreshBeanPostProcessor: ApplicationListener<EnvironmentChangeEvent> {
    @Autowired
    private lateinit var configurationPropertiesRebinder: ConfigurationPropertiesRebinder

    override fun onApplicationEvent(event: EnvironmentChangeEvent) {
		//do something
	}
}
```

BUT I'm sure it's not a good solution, because I don't fully understand how it works and what exactly could change this behaviour.

SO I decided to inject ConfigurationPropertiesRebinder to my listener and call ConfigurationPropertiesRebinder.onApplicationEvent in my handler:

    override fun onApplicationEvent(event: EnvironmentChangeEvent) {
               configurationPropertiesRebinder.onApplicationEvent(event)
		//do something
	}

Yes, I will have double update of configurationproperties classes but I'm sure that there will no big impact on something.
