### ISSUE TITLE
[Discuss] About HeartbeatEvent Design

### ISSUE THREAD

**Issue by mercyblitz** [spring-cloud/spring-cloud-commons#560]
Hello, @spencergibb  and @dsyer 

The `HeartbeatEvent` class is a Spring Cloud event used in `DiscoveryClient`, the official implementation gives three scenarios:
- Eureka
- Zookeeper
- Consul

Whether one of the above scenarios can't identify which service has been changed or not.

If I am right, I'm a little confused that what's the propose of this `HeartbeatEvent`? does just notify the listeners? And how to know precisely which service is changed?

**Comment by ryanjbaxter** [comment]
I believe the purpose of the `HearbeatEvent` it to just notify the service discovery server that the instance is still "alive".

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
