### ISSUE TITLE
Exception occurred when LoggingSystem is set to "none"

### ISSUE THREAD

**Issue by dasun** [spring-cloud/spring-cloud-commons#563]
Can someone please clarify what is the use of the following line when we set -Dorg.springframework.boot.logging.LoggingSystem=none

https://github.com/spring-cloud/spring-cloud-commons/blob/10e93d3ef740a3a4c7d67283f5f275823fafcbb5/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/config/PropertySourceBootstrapConfiguration.java#L130

This is always producing an exception in an application where the following parameter was given -Djava.util.logging.config.file=C:/logging.properties"

**Comment by ryanjbaxter** [comment]
Can you provide the exception?

**Comment by dasun** [comment]
This is the exception occurred.

> java.io.FileNotFoundException: /-Djava.util.logging.config.file=/home/test/logging.properties (No such file or directory)
> 	at java.io.FileInputStream.open0(Native Method)
> 	at java.io.FileInputStream.open(FileInputStream.java:195)
> 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
> 	at java.io.FileInputStream.<init>(FileInputStream.java:93)
> 	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
> 	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
> 	at java.net.URL.openStream(URL.java:1045)
> 	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.reinitializeLoggingSystem(PropertySourceBootstrapConfiguration.java:126)
> 	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:110)
> 	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:649)
> 	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:373)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
> 	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:157)
> 	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:137)
> 	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:91)
> 	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:171)
> 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5245)
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
> 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1423)
> 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1413)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
>

**Comment by 391861737** [comment]
It can not find the specified file: `/-Djava.util.logging.config.file=/home/test/logging.properties`, you might need to check the `/` which have made the JVM to consider your option expression as a path.

**Comment by dasun** [comment]
There is no / in the actual parameter. It only appears when Spring get the value of the parameter. My point is, when we set logging system to none in Spring, we should not try to load logging configuration file.

**Comment by spencergibb** [comment]
How are you setting the logging config file?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
