### ISSUE TITLE
@RefreshScope and @Scheduled

### ISSUE THREAD

**Issue by anpu2018** [spring-cloud/spring-cloud-commons#567]
When I use the @RefreshScope annotation to dynamically refresh the internal private properties of the class, if the @scheduled annotation is used in this class or the SchedulingConfigurer interface is used to define the scheduled task, the scheduled task will be invalidated while the property is refreshed. The current guess is because of RefreshScope. Will generate a proxy class, affecting the thread pool required for the running of scheduled tasks, how should this problem be solved?

**Comment by fathersson** [comment]
@anpu2018 here's how we workaround that: https://stackoverflow.com/questions/50440468/refreshscope-stops-scheduled-task/56397421#56397421

**Comment by anpu2018** [comment]
First of all, thank you for sharing, but in fact, this method only monitors the application environment and makes the timed task effective. @Scheduled annotation requires a separate thread pool, but this does not make the cron expression dynamically refresh, timing The task still runs in the old rules. ps: I only tried to use the @Scheduled annotation for the time being. I didn't try to implement the ScheduledConfigurer interface to create a scheduled task. I hope to communicate again, thank you.

**Comment by anpu2018** [comment]
> @anpu2018 here's how we workaround that: https://stackoverflow.com/questions/50440468/refreshscope-stops-scheduled-task/56397421#56397421

First of all, thank you for sharing, but in fact, this method only monitors the application environment and makes the timed task effective. @Scheduled annotation requires a separate thread pool, but this does not make the cron expression dynamically refresh, timing The task still runs in the old rules. ps: I only tried to use the @Scheduled annotation for the time being. I didn't try to implement the ScheduledConfigurer interface to create a scheduled task. I hope to communicate again, thank you.

**Comment by anpu2018** [comment]
> @anpu2018 here's how we workaround that: https://stackoverflow.com/questions/50440468/refreshscope-stops-scheduled-task/56397421#56397421

After my attempt again, using the method of implementing the SchedulingConfigurer interface to create a timed task, still can not achieve dynamic refresh of the cron expression, but the console does show refresh changes, so that your method can only guarantee that my timed task can Running, there is no guarantee that it will be refreshed

**Comment by ask4gilles** [comment]
@anpu2018 See my answer https://stackoverflow.com/a/56523860/4161816

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by anpu2018** [comment]
> @anpu2018 See my answer https://stackoverflow.com/a/56523860/4161816

Thank you very much, I feel that the existing solutions are against the programming specifications, so I abandoned the springcloud package and directly use the configuration center to read. Most configuration centers support the polling method to update the configuration.

**Comment by anpu2018** [comment]
> @anpu2018 See my answer https://stackoverflow.com/a/56523860/4161816

In my opinion, the practice of creating a scheduled task by implementing the SchedulingConfigurer interface is obsolete and brings maintenance complexity.

**Comment by rowi1de** [comment]
https://stackoverflow.com/q/50440468
@ryanjbaxter any change to get the issue fixed? The example in the initial post describes the biggest issues: `@RefreshScope` on a class that has `@Scheduled` will stop the tasks on refresh and don’t re-create.
