### ISSUE TITLE
@load balanced rest Template  404 issue with Eureka

### ISSUE THREAD

**Issue by anikatiyar** [spring-cloud/spring-cloud-commons#569]
Hi Team,

We are facing issues with @loadbalanced restTemplate defined as below with default configuration as below
 @Bean
    @LoadBalanced
    @Primary
    RestTemplate getRestTemplate() {
        return new RestTemplate();
    }
	
settings:
spring boot :1.5.11.RELEASE
spring-cloud-dependencies:Dalston.SR1

url1:10 instances 
url2:10 instances
url3:10 instances	

Scenario:we are calling multiple rest Service registered in Eureka service registry as below
	
	public class RestCallService {

	@Autowired
	RestTemplate restTemplate;
	
	public String post1(String url1){
		ResponseEntity<String> result = restTemplate.postForEntity(url1, entity, String.class);
		return result.getBody();
	}
	
	public String post2(String url2){
		ResponseEntity<String> result = restTemplate.postForEntity(url2, entity, String.class);
		return result.getBody();
	}
	
	public String post3(String url3){
		ResponseEntity<String> result = restTemplate.postForEntity(url3, entity, String.class);
		return result.getBody();
	}
	
	}
	
	{\"timestamp\":1558530921431,\"status\":404,\"error\":\"Not Found\",\"message\":\"No message available\",\"path\":\"/abc/d/xyz\" 
	
it is observed that 5% of these call giving us 404 not found in prod.! What could be the reason for this.Any suggestion would be appreciated.

**Comment by ryanjbaxter** [comment]
We no longer support the Dalston release train.
https://spring.io/blog/2018/06/19/spring-cloud-finchley-release-is-available#lifecycle-announcements-for-release-train-versions

Please use Edgware.SR6 and try again.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
