### ISSUE TITLE
spring-cloud-context vs spring-cloud-config conflict

### ISSUE THREAD

**Issue by gregorej** [spring-cloud/spring-cloud-commons#57]
Hi!

In most of our applications we've been using ``spring-cloud-config`` dependency. Then for one of them we added Hystrix support via ``spring-cloud-starter-hytrix``. Running this application via spring boot (``gradle bootRun``) works fine but when we deploy it in Tomcat the configuration is no longer fetched from property sources (we load configuration on bootstrap). What we found is that there are a lot of duplicated classes between ``spring-cloud-config`` and ``spring-cloud-context`` dependencies (for example ``org.springframework.cloud.bootstrap.BootstrapConfiguration``). Excluding ``spring-cloud-context`` dependency from ``spring-cloud-starter-hystrix`` solved the issue for us. 

However I am still wondering why are there so many duplications between these dependencies? Which one should we be using?

**Comment by spencergibb** [comment]
@gregorej there are no duplicated classes. We moved classes between versions. Sounds like you have mixed versions. What versions of each are you using?

**Comment by gregorej** [comment]
``spring-cloud-starter-hystrix:1.0.3``
``spring-cloud-config-client:1.0.0.RELEASE``

**Comment by spencergibb** [comment]
and does it happen if you sync versions?

**Comment by gregorej** [comment]
Haven't tried that but I will. Thanks for the hint!

**Comment by gregorej** [comment]
The change will be more complex that I thought because, as I can see now, event packages have changed (i.e. ``PropertySourceLocator`` interface changed package)

**Comment by gregorej** [comment]
OK, downgrading to ``spring-cloud-starter-hystrix:1.0.0.RELEASE`` helped. Thanks.
