### ISSUE TITLE
what @EnableDiscoveryClient do if spring-cloud-netflix-eureka-client is on classpath

### ISSUE THREAD

**Issue by zpflyyer** [spring-cloud/spring-cloud-commons#573]
it's just a question, not a bug report or anything else.
As the title, having spring-cloud-netflix-eureka-client on the classpath and configure registry server url are enough to register service, what @EnableDiscoveryClient do?  i see it imported 
org.springframework.cloud.client.serviceregistry.AutoServiceRegistrationConfiguration, what does this @Configuration class do? i found it was already in the org.springframework.boot.autoconfigure.EnableAutoConfiguration factory, what if without this configuration if i didn't have @EnableDiscoveryClient on my application?

**Comment by zpflyyer** [comment]
i noticed that @EnableDiscoveryClient is not needed and @EnableEurekaClient is optional now, what if i have @EnableDiscoveryClient on my application and what will this annotation do?

**Comment by ryanjbaxter** [comment]
It won't do anything since it is optional
