### ISSUE TITLE
pause enpoint is not available

### ISSUE THREAD

**Issue by shubhanshushukla** [spring-cloud/spring-cloud-commons#577]
Hi All,
I am using Finchley.SR1 with following cloud dependency

		
```
<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-sleuth</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-sleuth-zipkin</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-commons</artifactId>
		</dependency>
```
 
I have enabled pause config like this in application.yml

```
 endpoints:
  restart:
    enabled: true    
  pause:
    enabled: true  
```
Still no pause and resume endpoint available is actuator like before 

`{"_links":{"self":{"href":"http://localhost:18182/actuator","templated":false},"archaius":{"href":"http://localhost:18182/actuator/archaius","templated":false},"auditevents":{"href":"http://localhost:18182/actuator/auditevents","templated":false},"beans":{"href":"http://localhost:18182/actuator/beans","templated":false},"health":{"href":"http://localhost:18182/actuator/health","templated":false},"conditions":{"href":"http://localhost:18182/actuator/conditions","templated":false},"configprops":{"href":"http://localhost:18182/actuator/configprops","templated":false},"env-toMatch":{"href":"http://localhost:18182/actuator/env/{toMatch}","templated":true},"env":{"href":"http://localhost:18182/actuator/env","templated":false},"info":{"href":"http://localhost:18182/actuator/info","templated":false},"loggers":{"href":"http://localhost:18182/actuator/loggers","templated":false},"loggers-name":{"href":"http://localhost:18182/actuator/loggers/{name}","templated":true},"heapdump":{"href":"http://localhost:18182/actuator/heapdump","templated":false},"threaddump":{"href":"http://localhost:18182/actuator/threaddump","templated":false},"metrics":{"href":"http://localhost:18182/actuator/metrics","templated":false},"metrics-requiredMetricName":{"href":"http://localhost:18182/actuator/metrics/{requiredMetricName}","templated":true},"scheduledtasks":{"href":"http://localhost:18182/actuator/scheduledtasks","templated":false},"httptrace":{"href":"http://localhost:18182/actuator/httptrace","templated":false},"mappings":{"href":"http://localhost:18182/actuator/mappings","templated":false},"refresh":{"href":"http://localhost:18182/actuator/refresh","templated":false},"features":{"href":"http://localhost:18182/actuator/features","templated":false},"service-registry":{"href":"http://localhost:18182/actuator/service-registry","templated":false},"bindings-name":{"href":"http://localhost:18182/actuator/bindings/{name}","templated":true},"bindings":{"href":"http://localhost:18182/actuator/bindings","templated":false},"channels":{"href":"http://localhost:18182/actuator/channels","templated":false}}`

**Comment by spencergibb** [comment]
Please don't cross post.
 Closing in favor of https://stackoverflow.com/questions/56921072/pause-enpoint-is-not-available

**Comment by shubhanshushukla** [comment]
I don't this is a new bug or feature, That's why posted on both side
