### ISSUE TITLE
@Loadbalanced "WebClient" does not have spring-retry LoadBalancer support just like "RestTemplate.

### ISSUE THREAD

**Issue by abjimmypro** [spring-cloud/spring-cloud-commons#579]
Question?
@Loadbalanced "WebClient" does not have spring-retry LoadBalancer support just like "RestTemplate.
ReactiveLoadBalancerAutoConfiguration does not have any implementation of Spring RetryTemplate just like LoadBalancerAutoConfiguration.

Can you please help to understand if this feature is missed or do we have any other approach to handle LB retry for WebClient?

If there is a different way to handle Spring RetryTemplate with @LoadBalanced WebClient; then please let me know? 
And,
If this feature is a miss; then please confirm the same and also what would be the plan to include this?
Thanks!!

**Comment by spencergibb** [comment]
Project Reactor has retry functionality built in

**Comment by abjimmypro** [comment]
Thanks @spencergibb for a quick reply. so you are suggesting to implement retry feature of Reactor framework with @Loadbalanced WebClient and not using Spring RetryTemplate.
And,
because Project Reactor has retry functionality, Spring RetryTemplate is not implemented with WebClient LB.

Correct??

**Comment by spencergibb** [comment]
Spring retry hasn't been updated to be reactive, so yes, that is what I'm suggesting

**Comment by abjimmypro** [comment]
Thanks!!
I have additional questions on this:
1. Is there any plan to implement Project Reactor retry feature with @Loadbalanced WebClient?
2. As @Loadbalanced is Ribbon based; so do we have any plan to have retry feature available with @LoadBalancerClient (which is recommended as Ribbon is in maintenance mode) for reactive starter?

**Comment by spencergibb** [comment]
The retry features are not based on ribbon, but spring retry. We don't currently have plans for configurations driven retry for webclient when retry is built in to the Reactor api.

**Comment by abjimmypro** [comment]
Thanks for all these details.

**Comment by csabakos** [comment]
@spencergibb With the reactor built-in `Mono.retry()` feature, I believe that the `LoadBalancerExchangeFilterFunction` does not get re-applied on retries. That means that it keeps retrying with the same host, which isn't great since the host might be having issues, while other hosts might be just fine.

If my understanding is correct, I suggest reopening the ticket and implementing a higher level reactive retry feature that does go through `LoadBalancerExchangeFilterFunction` on each try.

**Comment by Anusien** [comment]
What I'm observing is that the WebClient code goes through the filters *synchronously* and then delegates the HTTP connections asnychronously. So if you re-subscribe via `retry()`, you're not going back through the filters.
