### ISSUE TITLE
spring.cloud.loadbalancer.retry.enabled  no avail

### ISSUE THREAD

**Issue by cpf1040287889** [spring-cloud/spring-cloud-commons#594]
Question：
I use feign requets,  and  config   spring.cloud.loadbalancer.retry.enabled=false
but it continue to retry

Enhancement：
spring-cloud-commons

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
