### ISSUE TITLE
Uncouple NoopDiscoveryClient and configuration from Eureka

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-commons#6]
Perhaps use a default in the `ImportSelector`

**Comment by spencergibb** [comment]
Using `ImportSelector` won't work.  The only time the import selector is run is if `@EnableDiscoveryClient` is used, we want `NoopDiscoveryClient` to be created when the annotation is _missing_.

**Comment by spencergibb** [comment]
Using the `EnableDiscoveryClientImportSelector` won't work, but an `ImportSelector` that is always run will.

**Comment by dsyer** [comment]
The case I was hoping to cover was where you wanted to use `@EnableZuulProxy` without Eureka (or any discovery). Does that still work with your change?

**Comment by spencergibb** [comment]
Yes, that is what my change does.

**Comment by dsyer** [comment]
Probably safe to commit then. We need integration tests for these classpath combination scenarios.

**Comment by spencergibb** [comment]
closed via d3c2f8904973b7e11312339b8edc2ac0ff6e5254

**Comment by dsyer** [comment]
@spencergibb here's a test project that's failing: https://github.com/spring-cloud-samples/tests/tree/master/zuul-proxy. It's trying to do `@EnableZuulProxy` with the minimum of dependencies. Can we fix that and keep your change in this issue?

**Comment by spencergibb** [comment]
fixed via 3596e67e1141f5bb074703a0f1a2eadd433756fb
