### ISSUE TITLE
Rework PropertySourceBootstrapConfiguration to update the environment during environment post-processing and before ApplicationEnvironmentPreparedEvent is published

### ISSUE THREAD

**Issue by wilkinsona** [spring-cloud/spring-cloud-commons#608]
At the moment, `PropertySourceBootstrapConfiguration` is triggered by `BootstrapApplicationListener` on `ApplicationEnvironmentPreparedEvent` at which point it makes changes to the `Environment`. This breaks the expected lifecycle of the environment as no changes are expected after the environment has been prepared. It will hopefully be possible to correct this by switching to an `EnvironmentPostProcessor`. This should fix https://github.com/spring-projects/spring-boot/issues/18191. It should also allow the code that reinitialises the logging system – something that has caused numerous bugs over the years – to be removed.

If there's anything we can do in Boot or any assistance we can provide on the Cloud side to help to make this happen, please let us know.

**Comment by spencergibb** [comment]
Ping @dsyer

**Comment by dsyer** [comment]
Makes sense to look at it. I have a feeling that an `ApplicationListener` might need to be retained to do some sloshing of parent-child context relationships, but the bulk of the work with the `Environment` could go into an `EnvironmentPostProcessor`.

**Comment by cschockaert** [comment]
Any update on this ticket? we are missing that feature a lot

**Comment by spencergibb** [comment]
No

**Comment by snicoll** [comment]
As part of fixing this issue, please document how a custom `EnvironmentPostProcessor` can run after the service configuration has been loaded from the config server. It should boil down to providing a sensible order value for it (perhaps Spring Boot itself would also have to clarify the ones that run by default). 

As far as I can see, it is impossible to write an `EnvironmentPostProcessor` that takes a decision based on what the user has configured when using the config server.

**Comment by spencergibb** [comment]
This has been superseded by #703 which uses an EnvironmentPostProcessor. Bootstrap will now be opt in via `spring.config.use-legacy-processing=true`.

**Comment by wilkinsona** [comment]
Awesome! Thanks, Spencer.

**Comment by hnibbrig** [comment]
Hi. The linked issue [LoggerContext changes when using Spring Cloud, eliminating Logback metrics spring-projects/spring-boot#13077](https://github.com/spring-projects/spring-boot/issues/13077) was not resolved by the fix in #703 
Same for [LoggerContext changes when using Spring Cloud #564](https://github.com/micrometer-metrics/micrometer/issues/564).
@spencergibb should this be reopened or should I create a new issue?

**Comment by wuguanyu** [comment]
> Hi. The linked issue [LoggerContext changes when using Spring Cloud, eliminating Logback metrics spring-projects/spring-boot#13077](https://github.com/spring-projects/spring-boot/issues/13077) was not resolved by the fix in #703 Same for [LoggerContext changes when using Spring Cloud #564](https://github.com/micrometer-metrics/micrometer/issues/564). @spencergibb should this be reopened or should I create a new issue?

I also encountered this issue

![wecom-temp-da975f7e8db2bf6261b95edfb72c00b8](https://user-images.githubusercontent.com/24486917/141451531-4416e983-af63-4016-9912-89b2d34c832d.png)
