### ISSUE TITLE
Multiple Restart endpoint invocations may cause OutOfMemory

### ISSUE THREAD

**Issue by Toparvion** [spring-cloud/spring-cloud-commons#613]
I have a Spring (Boot+Cloud) web application that gets periodically soft-restarted with `/actuator/restart` request. As time passes, the application falls with `java.lang.OutOfMemoryError`. I've noticed that probability of the error depends not on up-time but on the number of restarts. 
Further analysis of application's heap dumps showed a set of `DefaultListableBeanFactory` objects with their number growing with the number of restarts.

### Steps to reproduce

1. [Initialize](https://start.spring.io/#!type=gradle-project&language=java&platformVersion=2.1.8.RELEASE&packaging=jar&jvmVersion=11&groupId=tech.toparvion.sample&artifactId=restart&name=restart&description=Sample%20project%20for%20Spring%20Cloud%20restart%20memory%20footprint&packageName=tech.toparvion.sample.restart&dependencies=cloud-starter,web,actuator) a new application with Spring Boot 2.1.8 (Web, Cloud Bootstrap and Actuator).
2. Add the following lines to `application.properties` file:
```
management.endpoints.web.exposure.include=*
management.endpoint.restart.enabled=true
```
3. Set memory constraints, e.g. `-Xmx64m -XX:MaxMetaspaceSize=64m`
4. Launch the application (preferably with monitoring attached, e.g. Visual VM)
5. Execute the following HTTP request several times (with a few seconds interval) and observe the application memory consumption after each request:
```
POST http://localhost:8080/actuator/restart
```

As the requests perform, the monitoring should indicate increasing memory consumption. An example follows.

### Observations
The following observations were done on the sample application described above and obtained with the help of Eclipse Memory Analyzing Tool.

0. When sample application just starts, there are only 2 beans of type `DefaultListableBeanFactory`. 
![image](https://user-images.githubusercontent.com/12630412/65935172-51a12300-e442-11e9-8644-76e018bac591.png)
One of them (`0xf8647658`) is significant memory consumer but not the leader.

1. After 1 restart total memory footprint increases from 13 to 15 MB. There are already 4 beans of type `DefaultListableBeanFactory` and 2 of them dominates in memory distribution at whole:
![image](https://user-images.githubusercontent.com/12630412/65935530-911c3f00-e443-11e9-80d8-a12a175e3db2.png)

The `(b)` bean factory is the same one (`0xf8647658`) that was mentioned before. I've expected it to be garbage-collected after context recreation during restart but it did not happen. Instead there are &approx;170 paths to it from GC roots. But if I merge them and exclude all phantom/soft/weak/etc. references then there is only 1 such path: 
![image](https://user-images.githubusercontent.com/12630412/65936024-4dc2d000-e445-11e9-98bb-4f863a249d33.png)

I've found &approx;20 such redundant bean factories in my production application and most of them have the same merged path to GC root starting from `DefaultListableBeanFactory` itself to `parent` field in `AnnotationConfigApplicationContext` class. Perhaps, this is the main reason of keeping the factories alive.

10. After 10 restarts (for example) the picture gets close to failure as there are 22 `DefaultListableBeanFactory` objects occupying 63% of total 36 MB of allocated memory:
![image](https://user-images.githubusercontent.com/12630412/65936483-f58ccd80-e446-11e9-8bf3-86ae900e5346.png)

I suppose this issue can be related not only to Spring Cloud. If so, please let me know where to submit it.

**Comment by spencergibb** [comment]
@dsyer thoughts?

**Comment by dsyer** [comment]
I haven't tried to measure it in this much detail. A quick and dirty test seems to show that there is a leak with tomcat but not with Netty/Webflux. So it could be to do with the way Spring Boot creates the classloader for Tomcat.

**Comment by dsyer** [comment]
Looked into it a bit more. There is a [Micrometer issue](https://github.com/micrometer-metrics/micrometer/issues/1424), but even when that is fixed or worked around we still have a leak. Still digging...
