### ISSUE TITLE
Consider adding a user-provided-list-based ServiceInstanceListSupplier implementation

### ISSUE THREAD

**Issue by OlgaMaciaszek** [spring-cloud/spring-cloud-commons#615]
Would work similarly to `listOfServers` in Ribbon, getting the list of instances from properties.

**Comment by OlgaMaciaszek** [comment]
Alternatively, set up the Spring Cloud LoadBalancer autoconfiguration to provide a `SimpleDiscoveryClient` instance if no other discovery client found.

**Comment by spencergibb** [comment]
I think `SimpleDiscoveryClient` already is auto-configured.

**Comment by spencergibb** [comment]
I believe this is covered by SimpleDiscoveryClient. @OlgaMaciaszek will open a new issue for something to verify instances are up.
