### ISSUE TITLE
ReactiveDiscoveryClient.getInstances("...") returns an empty Flux

### ISSUE THREAD

**Issue by juergenzimmermann** [spring-cloud/spring-cloud-commons#617]
Using _Spring Cloud Hoxton.M3_ (spring-cloud-starter-config, spring-cloud-starter-consul-discovery which includes spring-cloud-starter-loadbalancer) and _Consul 1.6.1_ the following Kotlin fragment yields a Flux with 3 items:

- _consul_: i.e. Consul itself
- _config_: a registered config server with _Spring Cloud Config_
- _kunde_: a homegrown microservice _kunde_.

```
@Bean
fun discoveryClient(discoveryClient: ReactiveDiscoveryClient) = CommandLineRunner {
    val logger = ...
    discoveryClient.services
        .subscribe { service -> logger.warn("Registered Service: $service") }
}
```

However, the following Kotlin fragment results in an empty Flux when querying for the *existing* service _kunde_:

```
@Bean
fun discoveryClientKunde(discoveryClient: ReactiveDiscoveryClient) = CommandLineRunner {
    val logger = ...
    discoveryClient.getInstances("kunde")
        .collectList() // converts (empty) Flux to Mono with (empty) List
        .subscribe { instances -> logger.warn("Instances: $instances") }
}
```

When I use the injected non-reactive `DiscoveryClient` everything works fine.

Providing a testcase might be cumbersome (Consul, Config, microservice, ...). Please guide me to give you additional information.

**Comment by juergenzimmermann** [comment]
Closed because the issue belongs to spring-cloud-consul: https://github.com/spring-cloud/spring-cloud-consul/issues/593

**Comment by TYsewyn** [comment]
As mentioned in spring-cloud/spring-cloud-consul#593 the issue appears to reside in `ReactiveCompositeDiscoveryClient`, specifically in `return Flux.first(serviceInstances);`.
Therefor I'll reopen this issue and close the other one.

> `Flux.first` will return the first flux in the list of serviceInstances that emits any signal (onNext/onError/onComplete). Since the `SimpleReactiveDiscoveryClient` is being bootstrapped by default too and there is currently no way of en-/disabling this via properties, you will always end up having no instances (except if you have instances added to your properties file).

**Comment by juergenzimmermann** [comment]
@TYsewyn ok, now I understand why I don't get an instance of a registered microservice.

Consequently _Spring Cloud CircuitBreaker_ (as anounced by @ryanjbaxter) doesn't work as expected and _always_ invokes the fallback function because the "CircuitBreaker object" doesn't find a service instance for a loadbalanced WebClient via `ReactiveDiscoveryClient`.

**Comment by TYsewyn** [comment]
Thanks for the heads-up @juergenzimmermann! You can disable the reactive discovery client by setting `spring.cloud.discovery.reactive.enabled=false`. The downside is that you’ll need to create your own reactive discovery client beans, but that might solve your problem. We also made sure that the load balancer will use the blocking client in a reactive way.

**Comment by juergenzimmermann** [comment]
@TYsewyn I just tried the snapshot of spring-cloud-commons: it works fine. Thank you for your efforts.

**Comment by TYsewyn** [comment]
You’re very welcome @juergenzimmermann. Thank YOU for testing it out and filing this issue! 🙂
