### ISSUE TITLE
BootstrapApplicationListener disables registerShutdownHook completely

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-commons#62]
https://github.com/spring-cloud/spring-cloud-commons/commit/5d7f18f91fc8e0ca46f40d5254ac74b51a2ff625 has disabled the shutdownHook of the original application in order not to overlap with the bootstrap context, but then https://github.com/spring-cloud/spring-cloud-commons/commit/96ec2d32ea0467abab26b33776667cb7c37533d3 has disabled the shutdown hook of the bootstrap context too, thus removing the mechanism completely.

**Comment by dsyer** [comment]
Is it better to revert 5d7f18f then?

**Comment by mbogoevici** [comment]
Yeah, I added a PR that does exactly that ... https://github.com/spring-cloud/spring-cloud-commons/pull/63

**Comment by dsyer** [comment]
Thanks.
