### ISSUE TITLE
RestartEndpoint cannot be enabled using 'management.endpoints.web.exposure.include'

### ISSUE THREAD

**Issue by hansenc** [spring-cloud/spring-cloud-commons#622]
Using version 2.1.3.RELEASE.

`org.springframework.cloud.context.restart.RestartEndpoint` cannot be enabled via `management.endpoints.web.exposure.include=restart` or `management.endpoints.web.exposure.include=*`.

Is this intentional behavior (due to the nature of this endpoint) or a bug? Other cloud endpoints are enabled using this configuration, e.g. ConsulEndpoint from the Spring Cloud Consul project).

To enable it, you can use `management.endpoint.restart.enabled: true` (note the singular `endpoint` versus the plural above).

**Comment by hansenc** [comment]
Ah, I think this should be reported in [Spring Boot](https://github.com/spring-projects/spring-boot) instead. Sorry about that.

**Comment by hansenc** [comment]
Actually, I'm not sure where this belongs or if it's a bug, so let me know.

**Comment by spencergibb** [comment]
Enabling an endpoint and exposing it are two separate things.
