### ISSUE TITLE
[Enhancement] consider zone aware loadbalancer

### ISSUE THREAD

**Issue by bilak** [spring-cloud/spring-cloud-commons#632]
Please consider implementing zone aware loadbalancer.
For example with eureka it's possible to define zones in which are services located (where they are running), however currently it's not possible to loadbalance based on zones (currently only roundrobin is supported).

If I can somehow help with implementation let me know.

Thanks

**Comment by OlgaMaciaszek** [comment]
Thanks @bilak Will be working on it this week.

**Comment by bilak** [comment]
Are you going to implement it based on discovery service or would it be possible to configure balancer with static IP addresses and zone metadata?

**Comment by spencergibb** [comment]
It will be based on the discovery client, but it can be setup via configuration.
