### ISSUE TITLE
DiscoveryClientHealthIndicator active but discovery client not initialized

### ISSUE THREAD

**Issue by dkroehan** [spring-cloud/spring-cloud-commons#633]
We just updated to `Spring Boot 2.2.0` and also moved to the `Hoxton` Release Train.

We have the following integration test for our custom health checks:

```
@RunWith(SpringRunner.class)
@EnableAutoConfiguration
@SpringBootTest(classes = {LivenessCheckAutoConfiguration.class}, webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@TestPropertySource(properties = {"management.endpoint.health.custom: false"})
public class CustomReadinessCheckDisabledIntTest {

    @Autowired
    private TestRestTemplate restTemplate;

    @Test
    public void testCustomHealthCheckDisabled() {
        String body = this.restTemplate.getForObject("/health", String.class);
        assertThat(body, is(notNullValue()));

        assertThat(body, is("{\"status\":\"UP\",\"components\":{\"ping\":{\"status\":\"UP\"}}}"));
    }
}
```

We also have the following properties set:
        `management.health.defaults.enabled: false` and `management.health.ping.enabled: true`

Since the `Hoxton.M3` Release the `DiscoveryClientHealthIndicator` is now active which results in the test to fail with:

```
java.lang.AssertionError:
Expected: is "{\"status\":\"UP\",\"components\":{\"ping\":{\"status\":\"UP\"}}}"
     but: was "{\"status\":\"UP\",\"components\":{\"discoveryComposite\":{\"description\":\"Discovery Client not initialized\",\"status\":\"UNKNOWN\",\"components\":{\"discoveryClient\":{\"description\":\"Discovery Client not initialized\",\"status\":\"UNKNOWN\"}}},\"ping\":{\"status\":\"UP\"}}}"
```

**Is this intended behaviour or a bug?**
Should the `DiscoveryClientHealthIndicator` be affected by `management.health.defaults.enabled: false`?
There was a related change in the Spring Boot 2.2.0 Update: See: https://github.com/spring-projects/spring-boot/issues/17926 and https://github.com/spring-projects/spring-boot/issues/18676

**If it is an issue:**
We tracked it down to the `DiscoveryClientHealthIndicator` bean that is registered in `CommonsClientAutoConfiguration.DiscoveryLoadBalancerConfiguration`.

In `Greenwich.SR2` and `Hoxton.M2` the `CommonsClientAutoConfiguration.DiscoveryLoadBalancerConfiguration` is not loaded, because of:

```
   CommonsClientAutoConfiguration.DiscoveryLoadBalancerConfiguration:
      Did not match:
         - @ConditionalOnBean (types: org.springframework.cloud.client.discovery.DiscoveryClient; SearchStrategy: all) did not find any beans of type org.springframework.cloud.client.discovery.DiscoveryClient (OnBeanCondition)
      Matched:
         - @ConditionalOnClass found required class 'org.springframework.boot.actuate.health.HealthIndicator' (OnClassCondition)
         - @ConditionalOnProperty (spring.cloud.discovery.enabled) matched (OnPropertyCondition)

```

Now this bean is loaded due the change of the `@AutoConfigureBefore` in  `SimpleDiscoveryClientAutoConfiguration`.
See: https://github.com/spring-cloud/spring-cloud-commons/blob/c437379857a9ee1c58b9ee565263a6b90ef53b24/spring-cloud-commons/src/main/java/org/springframework/cloud/client/discovery/simple/SimpleDiscoveryClientAutoConfiguration.java#L43

**Comment by OlgaMaciaszek** [comment]
Hello @dkroehan , I think this is something that the team has to discuss. 

In the meantime, as stated in the docs:

> Commons creates a Spring Boot `HealthIndicator` that `DiscoveryClient` implementations can participate in by implementing `DiscoveryHealthIndicator`.
To disable the composite `HealthIndicator`, set `spring.cloud.discovery.client.composite-indicator.enabled=false`.
A generic `HealthIndicator` based on `DiscoveryClient` is auto-configured (`DiscoveryClientHealthIndicator`).

Would that work as a workaround for you?

**Comment by dkroehan** [comment]
Yes, the workaround works for us. So far we used `spring.cloud.discovery.enabled=false` in our tests.

**Comment by spencergibb** [comment]
fixed in previous commits
