### ISSUE TITLE
SC loadBalancer : Cache manager fails to update in case downstream service goes down 

### ISSUE THREAD

**Issue by nofelkad** [spring-cloud/spring-cloud-commons#642]
ConcurrentHashMap used for caching ServiceInstance does not get update it self as services goes and come.
No provision for TTL.

Tried using redis as cache, no luck as DefaultServiceInstance is not serializable.
Caused by: java.io.NotSerializableException: org.springframework.cloud.client.DefaultServiceInstance

**Comment by spencergibb** [comment]
duplicates #638
