### ISSUE TITLE
Webclient is not mentioned in comments

### ISSUE THREAD

**Issue by riteshbhambhani** [spring-cloud/spring-cloud-commons#645]
**Describe the bug**
This annotation is also required with WebClient but the comments are misleading

**Sample**
The application throws UKNOWN Host with Eureka server if the LoadBalanced annotation is not used but the comments are only mentioning rest template

**Comment by spencergibb** [comment]
can you please provide the error you are referring to?

**Comment by riteshbhambhani** [comment]
Hi Spenser. 
The comment on the annotation is: 
/**
 * Annotation to mark a RestTemplate bean to be configured to use a LoadBalancerClient.
 * @author Spencer Gibb
 */

This only mentions RestTemplate and I believe causes confusion when I used WebClient. The suggestion is to include the WebClient as well in the comments.
