### ISSUE TITLE
Spring Cloud Loadbalancer: Expose API for `Request` or "hint"

### ISSUE THREAD

**Issue by andersenleo** [spring-cloud/spring-cloud-commons#647]
**Is your feature request related to a problem? Please describe.**

As described in a previous feature request (in the netflix-ribbon project): https://github.com/spring-cloud/spring-cloud-netflix/issues/3009 -- we have a need to implement a stateful loadbalancer based on various criterias. 

Basically - in order to pick the correct service-instance we need to pass along a "hint" (or, in Netflix Ribbon, "key") to the load-balancer implementation. As far as I can tell there's really no way of doing that in the new Loadbalancer feature in Spring Cloud?

**Describe the solution you'd like**

See the proposal in the original ticket. If it's also possible to pass along information about the source request to allow the load-balancer implementation to, for example - extract a "key" from a header or query parameter, it would be even more useful.

**Describe alternatives you've considered**

Hacking around the limitations using ThreadLocal - but that won't work with the Reactive LoadBalancer (which seems to be the core abstraction).
request here.

**Comment by OlgaMaciaszek** [comment]
Thanks for reporting this. We should make this available, indeed. I don't think we want to modify the `ReactiveLoadBalancer` interface, but we could probably handle it via the `Publisher<Response<T>> chose(Request request)` method.

**Comment by spencergibb** [comment]
That's exactly what the `choose(Request)` is for
