### ISSUE TITLE
Unable to override environment using spring.cloud.config.env or spring.profiles.active

### ISSUE THREAD

**Issue by LakshmiVaishak** [spring-cloud/spring-cloud-commons#655]
Tried setting spring.profiles.active: dev for downloading dev based configurations from config server. Resolved by changing the application.yml file to bootstrap.yml file. It would have been better if its mentioned in the configuration guide site. Or is it a mistake made by me?

**Comment by ryanjbaxter** [comment]
Fixed via b7bef1d
