### ISSUE TITLE
A simplified way of adjusting Spring Cloud LoadBalancer config

### ISSUE THREAD

**Issue by OlgaMaciaszek** [spring-cloud/spring-cloud-commons#660]
Think of an easier way of switching between `ServiceInstanceListSupplier` and `ReactorLoadBalancer` implementations, without the users having to create hierarchies of delegate beans in custom configs.

**Comment by spencergibb** [comment]
A couple of ideas: a few predefined hierarchies enabled by a property, or a property that is a list of classes and we enable to hierarchy using reflection.

**Comment by OlgaMaciaszek** [comment]
Adding a builder API and preselected configurations backed by properties.

**Comment by OlgaMaciaszek** [comment]
Done.
