### ISSUE TITLE
Replacing the CompositePropertySource with separate BootstrapPropertySource instances broke the Spring Cloud Kubernetes property reload functionality

### ISSUE THREAD

**Issue by mzeijen** [spring-cloud/spring-cloud-commons#664]
The [implementation](https://github.com/ryanjbaxter/spring-cloud-commons/commit/8ec99f22296800bfe47bc9380afde65e798016de) of issue #611 has broken the Spring Cloud Kubernetes property reload functionality.
The reason is that `CompositePropertySource` is no longer used but instead every external property source, like the `ConfigMapPropertySource`, is put into a separate `BootstrapPropertySource`.

The BootstrapPropertySource hides the actual class of the property source (e.g. `ConfigMapPropertySource`) and only exposes the backing source (for `ConfigMapPropertySource` it's a `Map`). Because it's no longer possible to identify the property source based on the class, Spring Cloud Kubernetes is unable to find the `ConfigMapPropertySource`, which breaks its reload functionality.  In Spring Cloud Kubernetes the [ConfigurationChangeDetector](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/master/spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/reload/ConfigurationChangeDetector.java#L138) class contains the code that tries to find its property sources.

To me it seems that the change in Spring Cloud Commons isn't backwards compatible.

**Comment by spencergibb** [comment]
Closing if favor of https://github.com/spring-cloud/spring-cloud-kubernetes/issues/519
