### ISSUE TITLE
Suggest open the BootstrapPropertySource

### ISSUE THREAD

**Issue by yuhuangbin** [spring-cloud/spring-cloud-commons#671]
First, locate a `AcmPropertySource` by [AcmPropertySourceLocator](https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alicloud-acm/src/main/java/com/alibaba/alicloud/acm/bootstrap/AcmPropertySourceLocator.java), and we want get the `AcmPropertySource` by [AcmPropertySourceRepository](https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alicloud-acm/src/main/java/com/alibaba/alicloud/acm/AcmPropertySourceRepository.java#L44).
So , Suggest open the [BootstrapPropertySource](https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/config/PropertySourceBootstrapConfiguration.java#L268) and provide `p`'s get method.

**Comment by spencergibb** [comment]
Can you tell me why you want to do this?

**Comment by yuhuangbin** [comment]
> Can you tell me why you want to do this?
In some scenarios, we need to get a custom `PropertySource`,
But the `BootstrapPropertySource` is not public.
