### ISSUE TITLE
What's the effect of DiscoveryClient#getOrder

### ISSUE THREAD

**Issue by eacdy** [spring-cloud/spring-cloud-commons#673]
I wonder how to use the  `org.springframework.cloud.client.discovery.DiscoveryClient#getOrder` .
And when to use it.

@ryanjbaxter @spencergibb

**Comment by ryanjbaxter** [comment]
It was used to order the discovery clients used in a composite discovery client

https://github.com/spring-cloud/spring-cloud-commons/issues/304

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
