### ISSUE TITLE
Load balancer server statistics

### ISSUE THREAD

**Issue by PiotrDudkiewicz-TomTom** [spring-cloud/spring-cloud-commons#674]
I'm migrating my project from ribbon to spring cloud load balancer.
Our custom load balancing rule relies heavily on server stats (`com.netflix.loadbalancer.ServerStats`).
Is such feature planned for spring cloud load balancer?
Could you give me a hint what would be the most straightforward way to implement this using current codebase?
I found `org.springframework.cloud.client.loadbalancer.reactive.Response.onComplete` method but it's never called and `CompletionContext` doesn't contain response object (which can be useful for extracting some additional stats)

**Comment by ryanjbaxter** [comment]
I dont believe so 

@OlgaMaciaszek

**Comment by OlgaMaciaszek** [comment]
I'm currently working on [this issue](https://github.com/spring-cloud/spring-cloud-commons/issues/629) that will add the ping server verification mechanism. However, indeed, a stats mechanism would present way more options. I will mark it as `for team discussion` and we will see if and when we could add it to our backlog.
