### ISSUE TITLE
Make writable env actuator endpoint opt in

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-commons#681]
Change the default of `management.endpoint.env.post.enabled` to false.

**Comment by marbon87** [comment]
Hi @spencergibb , please to such changes in major-releases :)
Such a change was unexpected in a SR-release

**Comment by spencergibb** [comment]
It was a security concern that we felt couldn't wait.

**Comment by filpano** [comment]
@spencergibb Is there possibly a discussion pertaining to this decision? We enable writable /env Endpoints rather judiciously for our services and I would be very interested in learning why this was a big enough security concern that it warranted a semi-breaking change!
