### ISSUE TITLE
LoadBalancer: Add Sticky LB implementation.

### ISSUE THREAD

**Issue by OlgaMaciaszek** [spring-cloud/spring-cloud-commons#689]
To allow for functional backwards compatibility for SC Zookeeper.

**Comment by fitzoh** [comment]
Any thoughts/directions on implementation on this?

Cookie/session based routing vs client IP hashing?
Some other approach?

**Comment by neelimaj97** [comment]
Any inputs on when it will get implemented

**Comment by OlgaMaciaszek** [comment]
@neelimaj97 planning to have it for the 2020.0.0 GA release. 

@fitzoh I was thinking about an implementation of `ReactorServiceInstanceLoadBalancer` that during the first invocation would choose an instance, set it in a variable and later redirects all the calls to that same instance, similarly to the [original Zookeeper implementation](https://github.com/spring-cloud/spring-cloud-zookeeper/blob/2.2.x/spring-cloud-zookeeper-discovery/src/main/java/org/springframework/cloud/zookeeper/discovery/dependency/StickyRule.java). It's a good time to discuss approaches, however, so if you think a different approach would be better, feel free to outline it here for discussion. Would you be interested in submitting a PR?

**Comment by neelimaj97** [comment]
@OlgaMaciaszek Shouldnt only the requests in the same session go to the same instance? So if different users are accessing the same app, it would go to different instances rather than loading on one same instance

**Comment by fitzoh** [comment]
That implementation does not appear to align with my assumptions about what sticky load balance behavior entails either.

The implementation above appears to say that all requests (regardless of the user making them) will end up at the same backend, with no requests hitting other backens until it rotates.

I was expecting an implementation that would ensure that a given user always ends on the same server, but that traffic is (somewhat) evenly distributed amongst the available backends.

**Comment by andaziar** [comment]
Hi Olga! This kind of functionality is what we tried to achieve with our suggestion in #672 and our definition of "sticky" load balancing is in line with what @fitzoh said previously: "a given user always ends on the same server". However I would like to add that the user might be "re-balanced" to another service instance if the instance i.e. goes down. 

And if we agree that that is what we mean by "sticky" then I don't think that the load balancer implementation (e.g. `ReactorServiceInstanceLoadBalancer `) should store any reference to a specific service instance. We could instead implement this, as described in #672, by letting a `ReactorLoadBalancerFilterFunction ` extract the appropriate key from incoming request, which could be like a `user_id` that describes the affinity between user and service instance, and then fire that off in a new `org.springframework.cloud.client.loadbalancer.reactive.Request` towards our LB, which could perhaps perform a selection based on a 

`Mono<ServiceInstance> select(Object balanceKey, Flux<ServiceInstance> instances)` function that developers could implement themselves?

**Comment by fitzoh** [comment]
Threw an example implementation of the session/cookie based approach in #764.

**Comment by OlgaMaciaszek** [comment]
@fitzoh @andaziar  Primarily, this issue was related to recreating the existing LB Sticky implementation that worked in Zookeeper + Ribbon to work with the new stack, simply for achieving feature parity and backwards-compatibility.

However, I  do think the mechanism suggested by you would be more useful. I'm thinking it might be a good idea to add the backwards-compatible version (for example, `StickyRuleLegacy`) to the `Hoxton` release train and the new one cookie-based version to `2020.0.0` if we need to add backwards-incompatible changes in `ReactorExchangeFilterFunction` to make it work and to both if not. Wdyt?

CC @spencergibb

**Comment by varna909** [comment]
spencergibb  - Could you please let me know if LB implementation with sticky session is complete? If you could point to documentation on the usage that would be great.

**Comment by OlgaMaciaszek** [comment]
It was started by an individual contributor (see: https://github.com/spring-cloud/spring-cloud-commons/pull/764). Have asked if they would like to finish it and submit it.

**Comment by OlgaMaciaszek** [comment]
Fixed with https://github.com/spring-cloud/spring-cloud-commons/pull/862/.
