### ISSUE TITLE
Why RestartListener?

### ISSUE THREAD

**Issue by HashZhang** [spring-cloud/spring-cloud-commons#693]
I used a listener watching ApplicationPreparedEvent to trigger some other registration to third party services, but I found this event was published several times while starting the application because of `RestartListener`:

	@Override
	public void onApplicationEvent(ApplicationEvent input) {
		if (input instanceof ApplicationPreparedEvent) {
			this.event = (ApplicationPreparedEvent) input;
			if (this.context == null) {
				this.context = this.event.getApplicationContext();
			}
		}
		else if (input instanceof ContextRefreshedEvent) {
			if (this.context != null && input.getSource().equals(this.context)
					&& this.event != null) {
				this.context.publishEvent(this.event);
			}
		}
		else {
			if (this.context != null && input.getSource().equals(this.context)) {
				this.context = null;
				this.event = null;
			}
		}
	}

I wonder why the ApplicationPreparedEvent should be re-published, kindly waiting for your response, thanks

**Comment by spencergibb** [comment]
We create a bootstrap application context. This publishes additional events

**Comment by HashZhang** [comment]
This Listener causes the ApplicationPreparedEvent being published twice (one is by `SpringApplication`, the other one is `RestartListener`) to the same listeners while starting both the bootstrap and the application context, I am confused that why it is not a waste of time that the same listeners are called twice

**Comment by spencergibb** [comment]
You'll need to check that the context in the event is not the bootstrap context

**Comment by HashZhang** [comment]
Thanks for the response. But even if I check the  context in the event is not the bootstrap context, for application context the ApplicationPreparedEvent is published twice (one is by `SpringApplication`, the other one is `RestartListener`)

**Comment by spencergibb** [comment]
Use am atomic Boolean to see that the event is only consumed once?

**Comment by HashZhang** [comment]
That's a way to do that. But I am confused about why there is a RestartListener, why not remove it?

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
