### ISSUE TITLE
API is unclear as to what is loadbalanced

### ISSUE THREAD

**Issue by pablo53** [spring-cloud/spring-cloud-commons#699]
Following the example:

```
public class MyClass {
    @Autowired
    private ReactorLoadBalancerExchangeFilterFunction lbFunction;

    public Mono<String> doOtherStuff() {
        return WebClient.builder().baseUrl("http://stores")
            .filter(lbFunction)
            .build()
            .get()
            .uri("/stores")
            .retrieve()
            .bodyToMono(String.class);
    }
}
```

What is really loadbalanced in the above, when we pass a URL with baseUrl(...) method EXPLICITLY? Assuming I have 3 instances of an external service, ```http://stores1:8080```, ```http://stores2:18080```, and ```http://stores3:28080```, how does the above "Load Balancer" know about them?

**Comment by spencergibb** [comment]
Either dynamically from service discovery or via configuration. Are you using service discovery?

**Comment by pablo53** [comment]
Yes, service discovery is in use. So, do You mean baseUrl should be provided with the service name instead?

What if the service discovery is non-default Eureka (note that Eureka has died a few years ago)? Or even not Consul? Can we somehow provide a list of URL's to the load balancer to pick one?

**Comment by OlgaMaciaszek** [comment]
If you are using a Service Discovery that Spring Cloud provides integration for (for example, Eureka, Consul or Zookeeper), if you have appropriate Spring Cloud Starter for that integration in your app, Service Discovery will be used underneath. You can use the [`SimpleDiscoveryClient`](https://cloud.spring.io/spring-cloud-static/spring-cloud-commons/2.2.2.RELEASE/reference/html/#simplediscoveryclient) to pass instance configuration in properties, instead. If you go with this approach, we recommend [configuring LoadBalancer to run instance health-checks](https://cloud.spring.io/spring-cloud-static/spring-cloud-commons/2.2.2.RELEASE/reference/html/#instance-health-check-for-loadbalancer).
