### ISSUE TITLE
Endpoint ID 'service-registry' contains invalid characters, please migrate to a valid format

### ISSUE THREAD

**Issue by nkonev** [spring-cloud/spring-cloud-commons#700]
I have this warn message in console when I use Spring Boot 2.2.5 and latest Spring Cloud Hoxton SR3

[Here](https://github.com/nkonev/spring-cloud-gateway-reactive-lb-consul/tree/endpoint-warning) is repository

![Снимок экрана_2020-03-06_02-13-58](https://user-images.githubusercontent.com/3160384/76034507-2b7f3200-5f50-11ea-9eb6-2c8cbc1064cf.png)

**Comment by spencergibb** [comment]
Duplicates #458
