### ISSUE TITLE
SimpleReactiveDiscoveryClient and KubernetesReactiveDiscoveryClient are not interchangeable

### ISSUE THREAD

**Issue by juri8** [spring-cloud/spring-cloud-commons#706]
`KubernetesReactiveDiscoveryClient` returns a Flux in `getServices` (and `getInstances`) that is re-evaluated every time it is subscribed. The `SimpleReactiveDiscoveryClient` on the other hand returns a Flux that is built by `Flux.fromIterable` which causes that it doesn't recognize configuration changes.

Is that intended? In my case, the `SimpleReactiveDiscoveryClient` instance is not configured at the time `getServices` is called for the first time which causes an empty Flux being returned all the time.

observed in Hoxton.SR1.

**Comment by spencergibb** [comment]
Simple reactive gets its configuration from config files. You may be using it before it's been initialized but without more details I can't know.

**Comment by juri8** [comment]
> Simple reactive gets its configuration from config files. You may be using it before it's been initialized but without more details I can't know.

You're right, it seems I'm using it before it gets initialized. Whatever - I developed a fix which I intend to contribute soon.

**Comment by juri8** [comment]
I believe this issue is very much the same as #687 , I'll give it a try

**Comment by spencergibb** [comment]
Duplicates #687

**Comment by juri8** [comment]
I tested and can confirm that this is not a duplicate of #687
