### ISSUE TITLE
using log4j2 -  ERROR: Cannot set level: WARN for 'null'

### ISSUE THREAD

**Issue by cforce** [spring-cloud/spring-cloud-commons#71]
Starting my server i have ERROR message many times:

ERROR org.springframework.cloud.logging.LoggingRebinder (LoggingRebinder.java:77) - Cannot set level: WARN for 'null'

**Comment by dsyer** [comment]
I never saw that. Can you share a minimal project that reproduces the problem? What makes you think it is a Spring Cloud issue?

**Comment by cforce** [comment]
can't set up that project easily .. but maybe i can help to indentigy the cause


logging:
  level:
    ROOT: WARN

```java
private void setLogLevel(LoggingSystem system, Environment environment, String name,
			String level) {
		try {
			if (name.equalsIgnoreCase("root")) {
				name = null;
			}
			level = environment.resolvePlaceholders(level);
			system.setLogLevel(name, LogLevel.valueOf(level));
		}
		catch (RuntimeException ex) {
			this.logger.error("Cannot set level: " + level + " for '" + name + "'");
		}
	}

```

- name is set to null cause equals root
Then loj4j2 Method trys to get logger (getLoggerConfig() ) for "null" and runs into null pointer

```java
@Override
	public void setLogLevel(String loggerName, LogLevel logLevel) {
		Level level = LEVELS.get(logLevel);
		LoggerConfig loggerConfig = getLoggerConfig(loggerName);
		if (loggerConfig == null) {
			loggerConfig = new LoggerConfig(loggerName, level, true);
			getLoggerContext().getConfiguration().addLogger(loggerName, loggerConfig);
		}
		else {
			loggerConfig.setLevel(level);
		}
		getLoggerContext().updateLoggers();
	}

private LoggerConfig getLoggerConfig(String loggerName) {
		return getLoggerContext().getConfiguration().getLoggers().get(loggerName);<<<<<<
	}
```


- getLoggerContext().getConfiguration().getLoggers().get(null) !!!!   That causes the null pointer

**Comment by cforce** [comment]
It seems that 
 com.netflix.discovery: OFF

does not work either and i supposed it should.

ERROR org.springframework.cloud.logging.LoggingRebinder (LoggingRebinder.java:77) - Cannot set level: false for 'com.netflix.discovery'

**Comment by dsyer** [comment]
The line with the NPE is actually in Spring Boot, so I'm not so sure it is a problem here. See here: https://github.com/spring-projects/spring-boot/issues/4808

**Comment by cforce** [comment]
tx. looking foward for the fix.
