### ISSUE TITLE
RestartEndpoint cannot be autowired

### ISSUE THREAD

**Issue by brunomendola** [spring-cloud/spring-cloud-commons#710]
**Describe the bug**

Since Spring Cloud Hoxton.SR3, autowiring RestartEndpoint which was working with Hoxton.SR2, no longer works.

The endpoint is enabled with the following property:

`management.endpoint.restart.enabled: true`

The startup fails with the following cause:
`NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.cloud.context.restart.RestartEndpoint' available: expected at least 1 bean which qualifies as autowire candidate.`

**Sample**

https://github.com/brunomendola/spring-cloud-restartendpoint-demo

**Comment by spencergibb** [comment]
Can you start with `--debug=true` and attach the auto configuration report?

**Comment by brunomendola** [comment]
I think I found out what may have happened, looks like a mix of breaking changes in Spring Boot (2.2.x) and Actuator:

1. Each individual endpoint can be enabled or disabled. This controls whether or not the endpoint is created and its bean exists in the application context. To be remotely accessible an endpoint also has to be exposed via JMX or HTTP. (https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-endpoints)
1. By default, this feature _(JMX)_ is not enabled and can be turned on by setting the configuration property `spring.jmx.enabled` to `true`. (https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-jmx)
1. As the test context framework caches context, JMX is disabled by default to prevent identical components to register on the same domain. (https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-testing-spring-boot-applications-jmx)

So.... the endpoints must also be exposed, via HTTP or JMX. Since I just want to use the RestartEndpoint programmatically, I'll go with JMX.

To make it work in production, the following properties must be set in application.yml:

```yaml
spring:
  jmx.enabled: true
management:
  endpoint.restart.enabled: true
```

All JMX endpoints are exposed by default, but if you customized the `management.endpoints.jmx.exposure.include` property with a list of endpoints (the default value is `*`), you will need to also add `restart`.

**This is not enough to make it also work in a Spring Boot test!**
To make it work in a Spring Boot test, you must annotate the test with `@SpringBootTest(properties = "spring.jmx.enabled=true")`, because the value in application.yml is always overridden by default with `false`.

What I really can't explain is why it works with Spring Boot 2.2.5.RELEASE and Spring Cloud Hoxton.SR2.

Maybe it would be useful to mention the issue in the release notes.

**Comment by brunomendola** [comment]
I found the related issue on actuator: https://github.com/spring-projects/spring-boot/issues/18814

It is a documentation issue, so yes... the endpoint MUST be exposed, via HTTP or JMX.
