### ISSUE TITLE
No log4j2 configuration file found if name is log4j2-spring.xml 

### ISSUE THREAD

**Issue by cforce** [spring-cloud/spring-cloud-commons#72]
According to doc https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-logging.html the name shall work with "log4j2-spring.xml". but only does with "log4j2.xml"

**Comment by spencergibb** [comment]
Does this have something to do with spring-cloud? Seems like maybe this should be a boot issue.

**Comment by cforce** [comment]
yes, your right
