### ISSUE TITLE
spring-cloud-context turns off banner

### ISSUE THREAD

**Issue by aladzhov** [spring-cloud/spring-cloud-commons#723]
https://github.com/spring-cloud/spring-cloud-commons/blob/4119a9c138f8e2c8e98aa518bc10d121ff701c22/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/BootstrapApplicationListener.java#L187

**Comment by spencergibb** [comment]
Only for bootstrap. It will work normally.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
