### ISSUE TITLE
[Question] BootstrapConfiguration exclusion

### ISSUE THREAD

**Issue by dsibilio** [spring-cloud/spring-cloud-commons#726]
Is there a way to exclude a specific BootstrapConfiguration declared in a META-INF/spring.factories file with the org.springframework.cloud.bootstrap.BootstrapConfiguration key?

I wasn't able to find any documentation about it, even though I see the org.springframework.cloud.bootstrap.BootstrapConfiguration annotation has an exclude field, it is not clear to me exactly how it should be used.

**Comment by spencergibb** [comment]
Please don't cross post. Closing in favor of https://stackoverflow.com/questions/61083747/spring-cloud-how-to-exclude-bootstrapconfiguration
