### ISSUE TITLE
ReactiveLoadBalancer hangs console app

### ISSUE THREAD

**Issue by SledgeHammer01** [spring-cloud/spring-cloud-commons#728]
I have a console application that is using com.playtika.reactivefeign:feign-reactor-cloud2:2.0.2. This is using ReactiveLoadBalancer. On my Spring Boot console app, this prevents the console app from shutting down. Something is keeping the process alive. If I don't use the load balancer and hardcode the url to localhost:8080, the app shuts down fine.

This is opposed to com.playtika.reactivefeign:feign-reactor-cloud:2.0.2 which uses the Netflix loadbalancer and has the dreaded Illegal State Exception : Shutdown in Progress due to ShutdownEnabledTimer.

**Comment by ryanjbaxter** [comment]
`com.playtika.reactivefeign:feign-reactor-cloud` is not part of Spring Cloud so I am not sure what we will be able to do about that.  Can you reproduce the issue without using that project?

**Comment by SledgeHammer01** [comment]
> `com.playtika.reactivefeign:feign-reactor-cloud` is not part of Spring Cloud so I am not sure what we will be able to do about that. Can you reproduce the issue without using that project?

Yes, I understand. I'm using ReactiveLoadBalancer.Factory for the load balancer however. Assuming there is a threadpool, no? If the threadpool is not shutdown, it will keep a process alive. It doesn't hang with DynamicServerListLoadBalancer. That one has the shutdown hook exception though. Should I open this over at Playtika instead?

**Comment by spencergibb** [comment]
If you can recreate the hanging without feign reactivate keep it here. Otherwise open it there.

**Comment by SledgeHammer01** [comment]
> If you can recreate the hanging without feign reactivate keep it here. Otherwise open it there.

Bypassing the load balancer and using an absolute address exits cleanly. Only using ReactiveLoadBalancer hangs. I ran in debug mode and viewed the threads:

* bunch of Deamon threads for reactor-http-nio
* 1 for DiscoveryClient-CacheRefreshExecutor
* 1 for DiscoveryClient-HeartBeatExecutor
* 1 regular thread for DestroyJavaVM
* 1 threadpool still running named pool-1-thread-1

pool-1-thread-1, is that you guys? It is my understanding that if you don't shutdown the threadpool, the app can't exit cleanly, no?

When I terminated the threadpool, the app closed.

**Comment by lohner** [comment]
I had a similar issue with a Spring Boot (2.3.0.RELEASE) application using `spring-cloud-starter-openfeign` (Hoxton.SR5): Shutdown via actuator POST /actuator/shutdown left a dangling non-daemon thread `pool-1-thread-2`. I traced that down to originate in the `com.stoyanr:evictor` library that is used in the Spring Cloud Load Balancer cache implementation.
Specifically the [DelayedTaskEvictionScheduler](https://github.com/stoyanr/Evictor/blob/master/src/main/java/com/stoyanr/evictor/scheduler/DelayedTaskEvictionScheduler.java) used in the [DefaultLoadBalancerCache](https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/cache/DefaultLoadBalancerCache.java#L68-L95) creates a default `ScheduledThreadPoolExecutor` (using non-daemon threads) that only gets shutdown when `EvictionScheduler::shutdown` is called which seems to be missing in `DefaultLoadBalancerCache` (according to the [JavaDocs](https://github.com/stoyanr/Evictor/blob/master/src/main/java/com/stoyanr/evictor/EvictionScheduler.java#L77-L85) the evictors client code is responsible to call the `shutdown()` method).

I guess the `DefaultLoadBalancerCache` should therefore either shut down the eviction scheduler properly or supply a custom `ScheduledExecutorService` using a `ThreadFactory` that creates daemon threads.

**Comment by lohner** [comment]
I should add: my workaround was to disable the load balancer cache. Shutting down the application then worked fine :)

**Comment by spencergibb** [comment]
Thanks for the update. Should be relatively straight forward to clean up

**Comment by OlgaMaciaszek** [comment]
@SledgeHammer01 @lohner Will work on a solution with daemon threads. If any of you is able to provide a sample that reproduces the issue for tests, that will be very helpful, as I was not able to reproduce the issue locally.

**Comment by philippn** [comment]
@OlgaMaciaszek Here you can see a quick example: https://github.com/philippn/demo-gh-728

**Comment by lohner** [comment]
I also just created an example app: https://github.com/lohner/spring-cloud-commons-issue728

Just launch via "gradle bootRun" and from a second terminal try "curl localhost:8888/" followed by "curl -X POST localhost:8888/actuator/shutdown". This will result in a dangling pool-1-thread-1 non-daemon thread.

Thanks!

**Comment by OlgaMaciaszek** [comment]
@philippn @lohner Thanks a lot, will look today.
