### ISSUE TITLE
LoadBalancer: add an ability to supply custom load-balancer strategy into context

### ISSUE THREAD

**Issue by Fetsivalen** [spring-cloud/spring-cloud-commons#730]
**Is your feature request related to a problem? Please describe.**
It can be useful in a few cases:
* some load-balancer strategies not implemented yet
* some case-specific logic needs to have custom ReactorServiceInstanceLoadBalancer.

In this case, would be great to have an ability to supply custom login via bean in context and allow to enable it for the specific client via configuration properties.

For example in SCG the I have a lot of routes and want to supply a custom load-balanced algorithm (let it be sticky in this case) and keep default round-robin for others.

As a can see for not I have to add
```
@LoadBalancerClients(defaultConfiguration = MyCustomLoadbalanserConfiguration.class)
```
And Implement custom configuration with factory methods.

**Describe the solution you'd like**
It would be cool to have smth like:

```
    @Bean
    @Primary
    public ReactorServiceInstanceLoadBalancer loadBalancerStrategy(List<ReactorServiceInstanceLoadBalancer> availableLoadBalancers,
                                                                   Environment environment,
                                                                   LoadBalancerClientFactory loadBalancerClientFactory) {
        String name = environment.getProperty(LoadBalancerClientFactory.PROPERTY_NAME);
         String loadnalancerStrategyOption = environment.getProperty(LoadBalancerClientFactory.NAMESPACE + "." + name + ".strategy");
        ReactorServiceInstanceLoadBalancer loadBalancerStrategy = availableLoadBalancers.stream()
                .filter(strategy -> strategy.getLoadbalancerStrategyName().equals(loadnalancerStrategyOption))
                .findFirst()
                .orElseGet(() -> new RoundRobinLoadBalancer());
        // setters based binding seems ok in the case since instance supplier and serviceId are defined during child context creation
loadBalancerStrategy.setServiceInstanceListProvider(loadBalancerClientFactory.getLazyProvider(name,
                ServiceInstanceListSupplier.class));
        loadBalancerStrategy.setInstanceId(loadBalancerStrategy);
        return loadBalancerStrategy;
    }

```
and place it in `LoadBalancerClientConfiguration`

It will allow using properties to define a load-balanced strategy and supply an additional one via the context.
Of course, the implementation should be a little bit different to address backward-compatibility but I think the one supplied here is enough to illustrate intention.

**Describe alternatives you've considered**
There are definitely a lot of other ways to implement a "factory".

**Comment by spencergibb** [comment]
Our current discussion is in #672

**Comment by Fetsivalen** [comment]
as far as I understand from that thread it is more about how to choose implementation based on the request, while my proposal was about how to choose the load-balancer algorithm during context creation.
But it seems I need to wait until that ticket will be resolved.

**Comment by OlgaMaciaszek** [comment]
Also related to: https://github.com/spring-cloud/spring-cloud-commons/issues/660.

**Comment by OlgaMaciaszek** [comment]
Reopening, so we can include it in team discussion.

**Comment by OlgaMaciaszek** [comment]
Since the same result can be obtained by adding the default configuration, we don't think there's a need for a different solution for the same use-case.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by Fetsivalen** [comment]
Ok, thanks for info, closing this issue ticket than
