### ISSUE TITLE
Opt-in for running in the bootstrap context rather than running by default

### ISSUE THREAD

**Issue by snicoll** [spring-cloud/spring-cloud-commons#737]
I have an `EnvironmentPostProcessor` that checks if the user has configured something (`my.token`). If the property does not exist, it can infer a default automatically. The result of that is to add a property source to the environment with the token as well as another key (`my.server`) used to locate the fallback server to use.

When the Spring Cloud bootstrap context is enabled, this breaks in a non subtle way due to the fact the `EnvironmentPostProcessor` is invoked twice. Here is an interesting scenario:

* `application.properties` set `my.token`
* the `EnvironmentPostProcessor` runs in the boostrap context, the environment does not contain application.properties so the customiztion of the user is not found. A new property source is added with  `my.token` and `my.server`.
* It runs again (in the application context), find the existing token and does nothing

You think that the environment post processor has done what it's supposed to but he has actually overwritten `my.server` with the fallback! I should add this example has nothing to so whatsoever with Spring Cloud but it can run in an application that uses Spring Cloud.

While some `EnvionmentPostProcessor` could run regardless of the application as they perform generic tasks, some are actually not expecting to:

1. Be invoked twice
2. Be invoked with an environment that does not represent the environment of the application.

Can you please consider make that mechanism opt-in?

**Comment by spencergibb** [comment]
See also #608

**Comment by spencergibb** [comment]
We've plans to rework bootstrap during this major release cycle

**Comment by snicoll** [comment]
Here is [a sample](https://github.com/snicoll-scratches/test-context-boostrap-env) that demonstrates the problem I've described above. 

Can you please tell me how I can know that my `EnvironmentPostProcessor` is running in the bootstrap context? That code has no dependency on Spring Cloud for the record.

**Comment by snicoll** [comment]
For the record, I've resorted to check for the presence of a  `PropertySource` named `bootstrap`. Once the project I have has an optional dependency on Spring Cloud, I'll add an integration test that validates this concretely.

**Comment by spencergibb** [comment]
From what I can see, the workaround implemented will need to stay in place until #608. So closing favor of that issue.

**Comment by snicoll** [comment]
Actually that workaround does not work at all for the reasons described in #608. Even when I am running in the proper "context", the property sources have not been loaded yet so I can't inspect the environment to figure out if the user configured the token or not.

Can we please reopen this issue to research a workaround (or maybe one already exists?)

**Comment by spencergibb** [comment]
Your work around doesn't work?

**Comment by snicoll** [comment]
I've summarized that https://github.com/spring-cloud/spring-cloud-commons/issues/608#issuecomment-626340364 - Let's forget about  reopening this issue as the scope is different, sorry for the noise here. I just meant to say that the workaround does not work.
