### ISSUE TITLE
If @RefreshScope is added, @Scheduled does not work any more

### ISSUE THREAD

**Issue by RaviH** [spring-cloud/spring-cloud-commons#74]
The code works fine if @RefreshScope is not added on top of class, but when I add it under @Component annotation the method is not called any more.
I use spring boot 1.2.4.RELEASE. Also, tried with 1.3.1.RELEASE. Same result.

```
//@RefreshScope //Uncomment to break the runner
@Component
class Runner1 {

    @Value('${developer:Runner1}')
    private String developerName;

    public String getDeveloperName() {
        return developerName
    }

    @Scheduled(fixedDelayString = '${runner1.sleep:1000}', initialDelayString = '${runner1.initialDelay:1000}')
    public void main() {
        println("In runner one: developer name: $developerName")
    }
}

```
**Notice**: application.properties has:
```
spring.aop.proxyTargetClass=true
spring.aop.proxy-target-class=true
```

Attached is the sample project. To recreate the issue uncomment `@RefreshScope` 
[spring-config-client-sample.zip](https://github.com/spring-cloud/spring-cloud-commons/files/68744/spring-config-client-sample.zip)

Please let me know if you need anything else.

**Comment by dsyer** [comment]
I can reproduce this problem with a much simpler project than the one you posted (which I couldn't import into Eclipse). The issue is that the `@RefreshScope` bean is never instantiated because nothing depends on it (it is lazy because of the scope). Without the scope the bean is instantiated normally during startup. You can work around it easily by just adding an `@Autowired` field or method somewhere that injects the bean into something else (like a config class).

**Comment by RaviH** [comment]
Hi Dave, 

Thank you for researching this. I tested by having the beans with `@Scheduled` annoation injected into `AppConfig` and it works mostly except the change in property value is not reflected in `fixedDelayString` and `initialDelayString` within `@Scheduled`. So `sleepTime` and `run` variables are updated but not the values in `@Scheduled` annotation.

```
    @Value('${purgeOldRecords.run}')
    private boolean run

    @Value('${purgeOldRecords.sleep}')
    private long sleepTime

    @Scheduled(fixedDelayString = '${purgeOldRecords.sleep}', initialDelayString = '${purgeOldRecords.initialDelay}')
```

Does that make sense? Can you please help me with that?

**Comment by edeandrea** [comment]
Not sure if there was any traction on this. Still seems to be an issue with spring boot 1.4.2.

**Comment by spencergibb** [comment]
@edeandrea if you think there is a bug, please open a new issue, not one that was closed last year.
