### ISSUE TITLE
Beans declared in Bootstrap configuration are not destroyed

### ISSUE THREAD

**Issue by Aloren** [spring-cloud/spring-cloud-commons#752]
When defining a bean in bootstrap configuration, it's destroy method is not called at shutdown.

Sample:

```
@Configuration
public class BootstrapConfiguration {

    @Bean(destroyMethod = "destroy")
    public Amazing amazing() {
        return new Amazing();
    }

    public static class Amazing {

        public void destroy() {
            System.out.println("Destroyed!");
        }
    }
}
```

spring.factories
```
org.springframework.cloud.bootstrap.BootstrapConfiguration=org.github.test.BootstrapConfiguration
```

I've found that shutdown hook was disabled for bootstrap context via this commit: https://github.com/spring-cloud/spring-cloud-commons/commit/96ec2d32ea0467abab26b33776667cb7c37533d3#diff-ffd4ed2e59b54e6acb4b4f3a088f9e31. I suppose this is the one that breaks destroy mechanism.

**Comment by spencergibb** [comment]
My guess is this will only be handled with our rework of bootstrap for 3.0

**Comment by Aloren** [comment]
Okay.
Could you please check whether this could be a good workaround then?
https://github.com/testcontainers/testcontainers-spring-boot/pull/292/files

**Comment by spencergibb** [comment]
It seems like an ok work around. In 3.0.x bootstrap is no longer enabled by default.
