### ISSUE TITLE
Add @ConditionalOnMissingBean to SimpleDiscoveryProperties

### ISSUE THREAD

**Issue by shollander** [spring-cloud/spring-cloud-commons#759]
According to the Spring Boot documentation, all auto configuration classes are supposed to be non-invasive. That is to say they back off in the presence of existing beans using `@ConditionalOnMissingBean` and the like. `SimpleDiscoveryClientAutoConfiguration` does not follow these requirements.

**Comment by spencergibb** [comment]
There's no hard and fast rule. We define a composite discovery client for users to inject their own at a different order.

**Comment by spencergibb** [comment]
What are you trying to do that this is preventing?

**Comment by shollander** [comment]
I programatically create the `SimpleDiscoveryProperties` object due to limitations of Spring Boot yaml properties files.

**Comment by spencergibb** [comment]
What limitations? You should probably use a EnvironmentPostProcessor.

**Comment by shollander** [comment]
I need to dynamically determine the uri based on other properties. I would be able to do it in yaml if SpEL was supported, but unfortunately it is not. I could probably also use an EnvironmentPostProcessor, but would rather not since that adds more complexity to the setup (i.e. need to have spring.factories file, etc.).

**Comment by spencergibb** [comment]
PRs welcome
