### ISSUE TITLE
Loadbalancer - allow custom instance alive checker

### ISSUE THREAD

**Issue by ztomic** [spring-cloud/spring-cloud-commons#763]
[HealthCheckServiceInstanceListSupplier](https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/HealthCheckServiceInstanceListSupplier.java) is currently using `WebClient` for checking if  `ServiceInstance` is alive. In my project I'm not using webflux for anything so to use health check I should add `spring-boot-starter-webflux` only for that.

I know that `RestTemplate` should not probably be supported here because of announced moving from `RestTemplate` to `WebClient`, but could you consider something like additional constructor for `HealthCheckServiceInstanceListSupplier` with for e.g. `Function<ServiceInstance, Mono<Boolean>> aliveChecker`? With this additional constructor (or some better way, with `WebClient` optional) someone could implement that function with `RestTemplate` or implement some additional checks if needed.

**Comment by Luckyfox1111** [comment]
I'm gonna work on this for the OSD...hope it's okay
