### ISSUE TITLE
Actuator restart endpoint not found on Spring Boot 2.3.0

### ISSUE THREAD

**Issue by Stephen-X** [spring-cloud/spring-cloud-commons#770]
**Describe the bug**
The actuator endpoint `/restart` cannot be found (`404 NOT FOUND`) after enabling it in `application.properties`.

**Sample**
Just go to https://start.spring.io/, and generate a Spring Boot 2.3.0 application with Spring Web, Actuator and Cloud Bootstrap (`Hoxton.SR5`). Add the following configs to `application.properties`:

```
management.endpoints.web.base-path=/
management.endpoint.restart.enabled=true
server.port=8080
```

Run the app and make a `POST` call to http://localhost:8080/restart. The server will give a 404 error.

**Comment by spencergibb** [comment]
You also need to expose them per the boot docs https://docs.spring.io/spring-boot/docs/2.3.0.RELEASE/reference/html/production-ready-features.html#production-ready-endpoints-exposing-endpoints

**Comment by Stephen-X** [comment]
Thanks, it's working now. Do you think the team can provide a bit more details in the documentation here: https://cloud.spring.io/spring-cloud-static/spring-cloud-commons/2.2.2.RELEASE/reference/html/#endpoints?
