### ISSUE TITLE
Provide a reference application using Spring Boot + Spring Cloud

### ISSUE THREAD

**Issue by donhuvy** [spring-cloud/spring-cloud-commons#774]
I seen 14.1k stars for `eShopOnContainers` repository. https://github.com/dotnet-architecture/eShopOnContainers . We struggle create a microservices system what use Spring Boot + Spring Cloud.

We need a reference application like `eShopOnContainers` in .NET world for Java Spring (Boot + Cloud + ecosystem) world.

**Comment by spencergibb** [comment]
Have you looked at any of the apps in https://github.com/spring-cloud-samples?

**Comment by donhuvy** [comment]
Thank @spencergibb for replying. I known these separate examples.  14100 ⭐ for a reference app is a strong motivation we can follow 🚀  

🌏  From our practices, we need about 6 weeks for building a microservices system (use Spring Boot + Spring Cloud), even harder when we try to using Reactive (we must given up idea Spring Boot Microservices Reactive because it is very complex system).

**Comment by spencergibb** [comment]
This is probably the closes we have https://github.com/spring-cloud-samples/brewery

**Comment by donhuvy** [comment]
Thank @spencergibb ! The repository is helpful, however, have a official reference app is better.

**Comment by spencergibb** [comment]
That is an official reference app, I guess I'm not sure of the difference.

**Comment by donhuvy** [comment]
I just known about this. I close my idea.
