### ISSUE TITLE
Clarify whether to use cache for Spring Cloud LoadBalancer with Eureka Discovery Client

### ISSUE THREAD

**Issue by stefanocke** [spring-cloud/spring-cloud-commons#775]
The documentation says at https://cloud.spring.io/spring-cloud-static/spring-cloud-commons/2.2.2.RELEASE/reference/html/#loadbalancer-cache-configuration:

> 

Although the basic, non-cached, implementation is useful for prototyping and testing, it’s much less efficient than the cached versions, so we recommend always using the cached version in production.
--

While this might be true in general, the cache is probably not necessary at all, if LoadBalancer is used together with Eureka Discovery Client, since it has its own cache. For details, see for example https://github.com/spring-cloud/spring-cloud-netflix/issues/373#issuecomment-110331739. The description there is for Ribbon + Eureka, but is IMHO also applicable for Spring Cloud LB.

Since Eureka is still the mainly supported case, it should be clarified whether to use cache is necessary. Cache might increase size / footprint of the application, especially since we get a log warning to include Caffeine instead of default one. 

Another point besides footprint is ZonePreferenceServiceInstanceListSupplier. AFAIU, this filter happens before caching. So, caching might increase the time until it is recognized that a zone has no healthy instances anymore and other zones are considered for routing.

**Comment by spencergibb** [comment]
PRs welcome

**Comment by OlgaMaciaszek** [comment]
thanks, @stefanocke  `Since Eureka is still the mainly supported case,` - this is not exactly the case (we treat Eureka equally as all supported Service Registries), however, I agree it makes sense to add these considerations to docs. Would you like to submit a PR?

**Comment by stefanocke** [comment]
@OlgaMaciaszek , yes I would like too. 
But could you give me an hint what is your opinion on this matter? Would you suggest to disable caching in Spring Cloud LB in this case?

Even if Eureka is not the mainly supported case, it is certainly an important one.
So I guess you would have some suggestion.

**Comment by OlgaMaciaszek** [comment]
I would actually still suggest using cache on LB side, just to avoid sending a request to Eureka each time and the associated waits. But we should add information on Eureka caching as a `NOTE` and let the users take it into account (they might choose to opt out of, reduce the cache times it or adjust eureka cache settings).

**Comment by antechrestos** [comment]
@OlgaMaciaszek What is the expected change about that? Some upgrade of the documentation telling that applications using eureka discovery does not need adding cafeine as eureka discovery client has its own cache ? Maybe upgrade the start up warning not to be logged in eureka context?

**Comment by OlgaMaciaszek** [comment]
@antechrestos  The warning about Caffeine cache is sth else - there's a cache added anyway, just a concurrent-map-with-ttl-backed. The problem is with this excerpt from the doc cited in the description. In the case of Eureka, it makes sense to use its caching rather than the LoadBalancer one.

**Comment by antechrestos** [comment]
@OlgaMaciaszek si basically it would just be adding a side note informing the developper that it makes sens to disable caching when some is done by used discover client such as eureka, to prevent double caching for instance

**Comment by OlgaMaciaszek** [comment]
Yes, exactly. However, @tiffany-chien is already adding this.

**Comment by sachinbhapkar** [comment]
Do we need to use cache for Spring Cloud LoadBalancer with Eureka Server too?

**Comment by OlgaMaciaszek** [comment]
Hello, @sachinbhapkar, could you please clarify your question. SC LoadBalancer is a client-side solution.

**Comment by sachinbhapkar** [comment]
Hi @OlgaMaciaszek, we have eureka server as a spring boot app, and getting this warn in logs:
`WARN  o.s.c.l.c.LoadBalancerCacheAutoConfiguration$LoadBalancerCaffeineWarnLogger - Spring Cloud LoadBalancer is currently working with the default cache. While this cache implementation is useful for development and tests, it's recommended to use Caffeine cache in production.You can switch to using Caffeine cache, by adding it and org.springframework.cache.caffeine.CaffeineCacheManager to the classpath.`

**Comment by OlgaMaciaszek** [comment]
Did you add the ` If you are not creating any `@LoadBalanced` beans or using the `LoadBalancerExchangeFilterFunction` directly, you do not need to do anything. If you do, you should probably read up the docs on LoadBalancer caching and improve your setup for production.

**Comment by sachinbhapkar** [comment]
we don't have any @LoadBalanced or LoadBalancerExchangeFilterFunction configurations in our Eureka Server setup. Could you provide more insight into whether these are relevant for server-side implementations? Thanks.

**Comment by OlgaMaciaszek** [comment]
Typically no, sometimes users have some custom scenarios.
