### ISSUE TITLE
Bootstrap context created during refresh should not see property sources registered in main context

### ISSUE THREAD

**Issue by ghost** [spring-cloud/spring-cloud-commons#776]
**Describe the bug**
When a context refresh is triggered, the environment of current application context is copied and passed to `BootstrapApplicationListener`.

`BootstrapApplicationListener` add the property sources of the copied environment to its context:

```java
for (PropertySource<?> source : environment.getPropertySources()) {
    bootstrapProperties.addLast(source);
}
```

Thus bootstrap context created during refresh can see properties imported by main application context, which is inconsistent as the initial bootstrap context can't see these properties.
In my opinion, the purpose of context refresh is trying to simulate an application restart, so the bootstrap context should remain same with the initial one.

Also, as the document of `BootstrapApplicationListener` says:

```java
/**
 * A listener that prepares a SpringApplication (e.g. populating its Environment) by
 * delegating to {@link ApplicationContextInitializer} beans in a separate bootstrap
 * context. The bootstrap context is a SpringApplication created from sources defined in
 * spring.factories as {@link BootstrapConfiguration}, and initialized with external
 * config taken from "bootstrap.properties" (or yml), instead of the normal
 * "application.properties".
 *
 * @author Dave Syer
 *
 */

I think bootstrap context should do as the docs says.
```

I'm using spring-cloud-context 1.2.5.RELEASE, which is quite an old version, but the newest version seems remain same behaviour.

**Comment by spencergibb** [comment]
What problems is this causing?

**Comment by zhanwh9** [comment]
It makes bootstrap context created during refresh see extra properties from config service, application.properties, etc.
As a result, properties in bootstrap.properties can be overriden, which causes inconsistent behaviour.
For example, set `eureka.client.register-with-eureka=false` for bootstrap phase and set `eureka.client.register-with-eureka=true` in application.properties. When a refresh occurs, bootstrap context will register itself to eureka, which is not expected.
