### ISSUE TITLE
Documentation related to spring-cloud-loadbalancer-starter links to a Github user instead of a project

### ISSUE THREAD

**Issue by Alos** [spring-cloud/spring-cloud-commons#777]
**Describe the bug**
The documentation in [spring-cloud-loadbalancer-starter](https://cloud.spring.io/spring-cloud-commons/reference/html/#spring-cloud-loadbalancer-starter) references:

```
Spring Cloud LoadBalancer starter includes Spring Boot Caching and Evictor.
```

The Evictor link points to https://github.com/stoyanr

**Comment by spencergibb** [comment]
Should point to https://github.com/stoyanr/Evictor. This work should be done on the 2.2.x branch.

**Comment by ahmedmq** [comment]
Can this be assigned to me please?  I would like to do a first commit to Spring Cloud

**Comment by spencergibb** [comment]
It's been assigned

**Comment by ahmedmq** [comment]
@spencergibb I opened a PR here: #782

**Comment by OlgaMaciaszek** [comment]
Fixed with https://github.com/spring-cloud/spring-cloud-commons/pull/782
