### ISSUE TITLE
How to prevent listener from firing in bootstrap context

### ISSUE THREAD

**Issue by pawelszymczyk** [spring-cloud/spring-cloud-commons#78]
Hi 

This issue is continuation of https://github.com/spring-cloud/spring-cloud-config/issues/314. 

I think I have to describe the situation more precisely.

As I mentioned before I have a application based on Spring-boot and I have a [CommandLinePropertiesApplicationListener](https://github.com/pawelszymczyk/spring-cloud-config-example/blob/master/src/main/java/pl/pawel/CommandLinePropertiesApplicationListener.java) that listens on ApplicationEnvironmentPreparedEvent events. The listener adds `JOptCommandLinePropertySource` which reads `-environment` program argument and bind it into externalized configuration properties - [ApplicationProperties](https://github.com/pawelszymczyk/spring-cloud-config-example/blob/master/src/main/java/pl/pawel/ApplicationProperties.java). 

This properties are injected into [ConfigurationServiceClientBootstrap](https://github.com/pawelszymczyk/spring-cloud-config-example/blob/master/src/main/java/pl/pawel/ConfigurationServiceClientBootstrap.java) class which is creating as `org.springframework.cloud.bootstrap.BootstrapConfiguration`:

```
# Bootstrap components
org.springframework.cloud.bootstrap.BootstrapConfiguration=\
pl.pawel.ConfigurationServiceClientBootstrap
```

This configuration reads variable `environment` from ApplicationProperties and do some things according this property (eg. find URI to Configuration Service via Discovery Service).
The problem is that `bootstrapInProgress` phase overridden ApplicationProperties values. 

Everything I mention here is showed in some tiny application created specially for this issue: https://github.com/pawelszymczyk/spring-cloud-config-example. 
You can run it by executing unit test from class: [CommandLinePropertiesApplicationListenerTest](https://github.com/pawelszymczyk/spring-cloud-config-example/blob/master/src/test/java/pl/pawel/CommandLinePropertiesApplicationListenerTest.java). 
Test is failing now, to fix it you can uncomment line containing `if (event.getEnvironment().getPropertySources().contains("bootstrapInProgress"))` here: 

https://github.com/pawelszymczyk/spring-cloud-config-example/blob/master/src/main/java/pl/pawel/CommandLinePropertiesApplicationListener.java#L25

Hope this helps :)

**Comment by dsyer** [comment]
Thanks for the sample, that was very helpful in showing what was happening in your project. If I were you I would just make sure that your listener only runs once, and since you have given it a very high order it will then only run in the main context. Example:

```
    @Override
    public void onApplicationEvent(ApplicationEnvironmentPreparedEvent event) {
        ConfigurableEnvironment environment = event.getEnvironment();
        MutablePropertySources propertySources = environment.getPropertySources();
        if (!propertySources.contains("beforeEnvironmentPreparedDefaults")) {
            if (event.getArgs().length > 0) {
                propertySources.addFirst(cmdLinePropertySource(event.getArgs()));
            }
            propertySources.addLast(defaultProperties());
            String environmentName = environment.getProperty(ENVIRONMENT_PROPERTY);
            if (environmentName != null) {
                environment.addActiveProfile(environmentName);
            }
        }
    }
```

I believe the test in your sample project will pass with that implementation and there is no leakage of implementation detail (it works just as well in a non-Spring Cloud app).

**Comment by pawelszymczyk** [comment]
Thanks for response, I will check it in few days :)
