### ISSUE TITLE
Customize load balancer/filter to route(forward) single request to all the the active instances of the service

### ISSUE THREAD

**Issue by asharani-m** [spring-cloud/spring-cloud-commons#780]
I have API Gateway  with Eureka as service discovery, spring load balancer as LB . 
I have 2 instances of a service 'first-service-1' and 'first-service-2' with endpoint say "updateRules"
Whenever there is a call to "updateRules", apigateway has to route the request to all the  active services .In this case to both  'first-service-1' and 'first-service-2'
However, LB will be used for other points as usual . above customization is only for single endpoint.

Is there a way to do this?
I was able to customize GatewayFilter to route the request to one of the manually selected service.
But how to forward the request to multiple  active services?
Any suggestion will be great

Thanks

**Comment by spencergibb** [comment]
gateway does not support sending the same request to multiple services.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
