### ISSUE TITLE
Hoxton.SR5 doc does not say it supports Spring Boot 2.3.x

### ISSUE THREAD

**Issue by longqinsi** [spring-cloud/spring-cloud-commons#781]
In [the online documentation of Spring Cloud Hoxton.SR5](https://cloud.spring.io/spring-cloud-static/Hoxton.SR5/reference/html/), the supported Spring Boot Version is 2.2.1.RELEASE, but in a blog post [Spring Cloud Greenwich.SR6, Hoxton.SR5 and 2020.0.0-M2 (aka Ilford) are Available](https://spring.io/blog/2020/06/01/spring-cloud-greenwich-sr6-hoxton-sr5-and-2020-0-0-m2-aka-ilford-are-available), there is a statement "Hoxton.SR5 is compatible with both Spring Boot 2.3.x and 2.2.x". Please fix the bug in the online documentation.

**Comment by OlgaMaciaszek** [comment]
Hoxton is no longer supported. Closing.
