### ISSUE TITLE
RefreshScope with Scheduled Annotation when tracing is enabled

### ISSUE THREAD

**Issue by winster** [spring-cloud/spring-cloud-commons#790]
A refresh scoped bean with Scheduled annotation does not cancel current scheduled task upon refresh when tracing libraries are present in the classpath (could be sleuth or opentracing-jaeger).

A sample application is given here https://github.com/winster/SpringSchedulerDynamic

Please note that it works as expected if tracing is not there. (A new scheduled task is created and current one is canceled)

Adding some information on debug starting from RefreshScope::refreshAll

**1. Without tracing library**

```
RefreshScope::refreshAll -> GenericScope::destroy -> DisposableBeanAdapater::run -> DisposableBeanAdapater::destroy

this.beanPostProcessors = ScheduledAnnotationBeanPostProcessor, ApplicationListenerDetector
```
**2. With tracing library**

```
RefreshScope::refreshAll -> GenericScope::destroy -> DisposableBeanAdapater::run -> DisposableBeanAdapater::destroy

this.beanPostProcessors = ApplicationListenerDetector

```

It is noted that `ScheduledAnnotationBeanPostProcessor::postProcessBeforeDestruction` is not invoked in this case

And if `opentracing.spring.cloud.scheduled.enabled` is set as `false`, it works as expected

**Comment by spencergibb** [comment]
I think the appropriate action is to not have `@RefreshScope` on an `@Scheduled` bean.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
