### ISSUE TITLE
(Load balancer) SSL properties don't apply to health check

### ISSUE THREAD

**Issue by rougou** [spring-cloud/spring-cloud-commons#808]
I have a Spring Cloud Gateway application. (Hoxton.SR7, Spring Boot 2.3.2)
For my local environment I have configured the following properties:

```
spring.cloud.gateway.httpclient.ssl.trusted-x509-certificates=classpath:ssl/api.cer
spring.cloud.loadbalancer.configurations=health-check
spring.cloud.discovery.client.simple.instances.myapi[0].uri=https://localhost:9992
```

If I disable the health check, everything works as expected. With the health check enabled, I get an SSL handshake error.
So it seems the ssl configuration isn't applied for the health check, but is applied for the api call itself, even though both naturally point to the same service. Is this expected behavior?

The following manual configuration works, although I'm not really that comfortable with it.

```
@Configuration
@Builder
public class MyApiLoadBalancingConfig {

	private final WebClient.Builder loadBalancedWebClientBuilder;

	private final HttpClient gatewayHttpClient;

	@Bean
	@Primary
	public ServiceInstanceListSupplier discoveryClientServiceInstanceListSupplier(
			ConfigurableApplicationContext context) {
		WebClient webClient = loadBalancedWebClientBuilder
			.clientConnector(new ReactorClientHttpConnector(gatewayHttpClient))
			.build();
		return ServiceInstanceListSupplier.builder()
			.withDiscoveryClient()
			.withCaching()
			.withHealthChecks(webClient)
			.build(context);
	}
}
```

**Comment by spencergibb** [comment]
`server.ssl.*` are a spring boot feature and only apply to application servers (Tomcat, jetty, etc...).

**Comment by rougou** [comment]
@spencergibb 
Yes, you're right. Sorry about the confusion.
`spring.cloud.gateway.httpclient.ssl.trusted-x509-certificates` is the property I was after. So this seems like a gateway-specific setting. Still, I can't help but feel there should be a way for this to work together.

**Comment by rougou** [comment]
After playing around with Eureka, Spring Boot Admin Server, etc., I've come to the conclusion I'm going to run into the same problem everywhere. So I guess I'm better off disabling ssl on the api apps, at least for the local development environment (which I want to just work without messing with environment settings).

**Comment by rougou** [comment]
FYI, disabling ssl for the downstream api's also didn't work as expected do to the following issue:
https://github.com/spring-cloud/spring-cloud-gateway/issues/1842
