### ISSUE TITLE
Unresolved directive in spring-cloud.adoc

### ISSUE THREAD

**Issue by php-coder** [spring-cloud/spring-cloud-commons#81]
When I'm opening doc (http://projects.spring.io/spring-cloud/spring-cloud.html) I see the error at the end of the page: `Unresolved directive in spring-cloud.adoc - include::../../../security/src/main/asciidoc/spring-cloud-security.adoc[]`

(I didn't find a proper place of reporting this issue.)

**Comment by dsyer** [comment]
Thanks. Fixed here: https://github.com/spring-cloud-samples/scripts/commit/2defc021f0355fac39ef78a98eb1d3e8a2fde328.
