### ISSUE TITLE
Property source decryption not working in Ilford

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-commons#815]
The existing tests all use legacy property source processing (bootstrap context), so there is nothing to indicate that it is meant to be working yet out of the box, but I think maybe we should make sure it does work for backwards compatibility.

**Comment by dsyer** [comment]
I noticed a new feature in Spring Boot 2.4 - there's a `BootstrapRegistry` (kind of like a little DI framework) in the `EnvironmentPostProcessors`. Maybe that can be used to set up the decrypted properties? Could maybe even use a "legacy" Bootstrap application context to back the suppliers registered with the `BootstrapRegistry`.

**Comment by spencergibb** [comment]
I've already used it here https://github.com/spring-cloud/spring-cloud-zookeeper/blob/master/spring-cloud-zookeeper-config/src/main/java/org/springframework/cloud/zookeeper/config/ZookeeperConfigDataLocationResolver.java#L84-L91

**Comment by spencergibb** [comment]
This was definitely on my radar already in some TODO list somewhere, so thanks for creating the issue.

**Comment by marcingrzejszczak** [comment]
Is this connected to https://github.com/spring-cloud/spring-cloud-commons/pull/703 ?

**Comment by marcingrzejszczak** [comment]
Ah ok, I see that `EncryptionIntegrationTests` when disabling the legacy processing doesn't work
