### ISSUE TITLE
Document SimpleDiscoveryClient

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-commons#821]
This will show how to use SimpleDiscoveryClient (properties driven discovery client). in conjunction with spring cloud loadbalancer

**Comment by spencergibb** [comment]
See here for sample https://github.com/spring-cloud/spring-cloud-commons/blob/e1c570af07839951276ec6df2c0ac90588fcc151/spring-cloud-commons/src/test/java/org/springframework/cloud/client/discovery/composite/CompositeDiscoveryClientTests.java#L42-L45

**Comment by OlgaMaciaszek** [comment]
Already done [here](https://docs.spring.io/spring-cloud-commons/docs/current/reference/html/#simplediscoveryclient).

**Comment by ShouZhiDuan** [comment]
tahks

**Comment by ShouZhiDuan** [comment]
thanks

**Comment by ffroliva** [comment]
Hi,

I am running into an the following issue:

I have a microservice `serviceA` and I use feign client to access it from other microservice.

During development, I want to rely on `SimpleDiscoveryClient` to get an instance of the service running in my docker daemon.

if I configure `spring.cloud.discovery.client.simple.instances.serviceA[0].uri=http://localhost:8081` then `SimpleDiscoveryClient` recognizes the service and feign client works.

If I try to configure  `SimpleDiscoveryClient` using `yaml` as bellow it doesn't recognize the service:

```yaml
spring:
    discovery:
      client:
        simple:
          instances:
            serviceA:
              - uri: "http://localhost:9595"
```

This doesnt make sense to me. Am I missing something? 

I don`t want to have a `application.properties` and `application.yml` just for that.

Am I missing something?
