### ISSUE TITLE
Can't seem to Actuator refresh a PropertySource that access an external resource after bean creation

### ISSUE THREAD

**Issue by dzou** [spring-cloud/spring-cloud-commons#833]
Working on [Spring Cloud GCP](https://github.com/spring-cloud/spring-cloud-gcp), our project offers a Secret Manager PropertySource which will query an external secret store and load secrets into your app as properties.

We are interested in looking into if it's possible to refresh the value of the properties through Spring Actuator with the `/refresh` endpoint.

We are having some trouble though, it looks like the `ContextRefresher` [recreates the application context but then closes it after](https://github.com/spring-cloud/spring-cloud-commons/blob/00668991a4cf3f40e137d6a13959a653e3f8e310/spring-cloud-context/src/main/java/org/springframework/cloud/context/refresh/LegacyContextRefresher.java#L91). So the secret manager client bean which connects to the secret store gets created but then closed before any new secrets can be retrieved by the property source. (Our Property Source is not enumerable, we will query for secrets when they are requested by `@Value(...)` or placeholders in `.properties` files which is why querying for all the secrets on bean creation doesn't work for us).

Here's a snippet of our code below, we did manage to get it to work if we added `@Bean(destroyMethod = "")`; however this is probably not the correct solution as I think it would cause a memory leak.

```
	@Bean(destroyMethod = "")  // This would fix the problem, but probably cause memory leak over time.
	@ConditionalOnMissingBean
	public SecretManagerServiceClient secretManagerClient() throws IOException {
		SecretManagerServiceSettings settings = SecretManagerServiceSettings.newBuilder()
				.setCredentialsProvider(this.credentialsProvider)
				.setHeaderProvider(new UserAgentHeaderProvider(GcpSecretManagerBootstrapConfiguration.class))
				.build();

		return SecretManagerServiceClient.create(settings);
	}

        // This is the property source locator that depends on the client being alive
	@Bean
	@ConditionalOnMissingBean
	public SecretManagerPropertySourceLocator secretManagerPropertySourceLocator(SecretManagerServiceClient client) {
		SecretManagerPropertySourceLocator propertySourceLocator =
				new SecretManagerPropertySourceLocator(client, this.gcpProjectIdProvider);
		return propertySourceLocator;
	}
```

Is there a way for us to avoid recreating the `secretManagerClient` bean on a refresh? Curious what recommendations you might have for us to get this to work. 

cc/ @meltsufin @elefeint

**Comment by furlongce** [comment]
Is there an update on this? I'm running into the same problem when trying to use Spring Boot Admin to a property value

**Comment by dzou** [comment]
Hmm, maybe this problem is too esoteric or I didn't word it properly.

But just imagine you have a `PropertySource` where everytime you call [`propertySource.getProperty(..)`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/env/PropertySource.html#getProperty-java.lang.String-) it makes some RPCs via a client connection to get the properties (like imagine accessing property values through a database connection; in our case it's via GRPC). 

If I understand this correctly, Actuator doesn't support this use-case because it will copy and then destroy the application context (and thereby destroy the client object connection used by the property source). Actuator assumes that the property source should cache all of the properties it will use when the property source is constructed (which is why the application context is destroyed). And then `getProperty` just gets values from a cached Map.

However, this approach doesn't seem to work in the case where the property source is *non-enumerable* meaning that you don't know what properties are available to the user and can be cached when the property source is constructed. Or in the case of accessing a secret store, you do not want to build a cache of secrets in memory for security purposes.

**Comment by spencergibb** [comment]
@dzou this is one of the issues with the legacy bootstrap approach. Has spring-cloud-gcp migrated to the new `ConfigData` approach (`spring.config.import`)?

**Comment by dzou** [comment]
@spencergibb -- Ah we have not done that migration yet, but thanks for letting us know.

If migrating to `spring-config-import` is the solution then you can just mark this as closed, we can perform the migration on our end.

**Comment by spencergibb** [comment]
Ok, feel free to comment if there are other issues.
