### ISSUE TITLE
BootstrapApplicationListener throws exception when I create a subclass of SpringApplication

### ISSUE THREAD

**Issue by drtrang** [spring-cloud/spring-cloud-commons#839]
**Describe the bug**

Spring Cloud: Greenwich.SR6

Details: I create a subclass of `SpringApplication` so that I can override some methods which is provided, like `postProcessApplicationContext()`, and add `attributes` field for `MySpringApplication`:

```java
public class MySpringApplication extends SpringApplication {

    private final Map<String, Object> attributes = new ConcurrentHashMap<>();

    public void setAttribute(String name, @Nullable Object value) {
        // do something
    }

    public Object getAttribute(String name) {
        // do something
    }

    @Override
    protected void postProcessApplicationContext(ConfigurableApplicationContext context) {
        // do something
    }

}
```

```java
@SpringBootApplication
public class SimpleApplication {

    public static void main(String[] args) {
        MySpringApplication.run(SimpleApplication.class, args);
    }

}
```

In my code, `MySpringApplication` must be used, but the problem is `BootstrapApplicationListener` will create a new `SpringApplication` but not a `MySpringApplication`, so it throws exception when I get `MySpringApplication`:

```java
public class MyListener implements ApplicationListener<ApplicationStartedEvent> {

    @Override
    public void onApplicationEvent(ApplicationStartedEvent event) {
        Assert.isInstanceOf(MySpringApplication.class, event.getSpringApplication(),
                "Class is not 'MySpringApplication'");
        MySpringApplication application = (MySpringApplication) event.getSpringApplication();
    }

}
```

Please let me know what to do?

**Sample**
not have

**Comment by spencergibb** [comment]
ignore the bootstrap `SpringApplication`. Going forward, bootstrap will not be needed for many cases and this won't be an issue.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
