### ISSUE TITLE
Context refresh reloads bootstrap context

### ISSUE THREAD

**Issue by symposion** [spring-cloud/spring-cloud-commons#845]
If I fire a RefreshEvent (or otherwise trigger the RefreshScope.refresh behaviour), internally spring creates an "empty" SpringBootApplication based on a copy of the current environment in order to be able to reload the environment and then copy any changed values over to the existing environment. This seems quite heavyweight, but I guess there are complexities around the dependencies of some of the property sources that make this necessary. The problem (for me) with it is that this "empty" Spring boot application actually reloads the entire bootstrap context inside it - which is absolutely not what I want when I'm just trying to refresh the one or two beans I've marked as having RefreshScope. In particular, I'm using this : https://github.com/Playtika/testcontainers-spring-boot for my integration testing, so reloading my bootstrap context entails firing up a whole bunch of docker containers just to throw them away again.

Given that items in the bootstrap context often do set properties into the environment to affect things in the main context, I guess this isn't trivial to solve. Ideally it would be possible to somehow treat the bootstrap context and/or  the property sources it produces as immutable, and thus avoid having to completely rebuild them just to reload changed items into the environment. This might also help clarify/solve the issue in https://github.com/spring-cloud/spring-cloud-commons/issues/844

Testcase here: https://github.com/symposion/spring-test/tree/double-refresh - note the double output of the message from the bootstrap context.

**Comment by spencergibb** [comment]
Indeed this is why we worked with the boot team to create the new `spring.config.import` functionality which bypasses the legacy bootstrap context. This is why bootstrap is considered legacy now and is disabled by default in spring cloud 2020.0.x
