### ISSUE TITLE
RefreshScope: add health indicator for initialization errors

### ISSUE THREAD

**Issue by mafr** [spring-cloud/spring-cloud-commons#85]
I use a Spring bean annotated with `@RequestScope` that injects config properties into JSR-303 validated attributes. I've noticed that I can break my application by making an error in my `application.yml` file and triggering "/refresh" via Spring Boot's actuator. I don't get any error message, neither from the actuator, the health check endpoint, nor from the logs. The only error indication I get is that my `@RestController` returns an Internal Server Error.

Best case, I would expect Spring Cloud to keep the old bean, but at least an error message from the actuator endpoint and a health check failure would be useful.

I've tested this on Angel.SR6 with Spring Boot 1.2.8.

**Comment by dsyer** [comment]
In Brixton you would get an error from the /refresh endpoint. The health check doesn't know about it though, so that's an interesting idea.

**Comment by mafr** [comment]
Fantastic, thank you!
