### ISSUE TITLE
org.springframework.cloud.context.properties.ConfigurationPropertiesBeans

### ISSUE THREAD

**Issue by shidajiangshan** [spring-cloud/spring-cloud-commons#851]
**Describe the bug**
Please provide details of the problem, including the version of Spring Cloud that you
are using. 

After spring-boot update from 2.3.5RELEASE to 2.4.0, org.springframework.boot.context.properties.ConfigurationBeanFactoryMetadata changed from @Deprecated to remove.
, caused spring-cloud org.springframework.cloud.context.properties.ConfigurationPropertiesBeans#setBeanMetaDataStore has wrong params.
But spring-cloud has not remove the empty and deprecated methed yet with update from Hoxton.SR8 to Hoxton.SR9, cauesed error while invoking getDeclaredMethod.
Now, I try to rewrite and remove setBeanMetaDataStore method.
Waiting for update version to fix the bug officially or some ways better.

**Sample**
If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

**Comment by spencergibb** [comment]
Hoxton will not be compatible with boot 2.4

https://github.com/spring-cloud/spring-cloud-release/milestones
