### ISSUE TITLE
Support HikariCP for RefreshScope

### ISSUE THREAD

**Issue by charlesxucheng** [spring-cloud/spring-cloud-commons#853]
**Is your feature request related to a problem? Please describe.**
I saw that the [Spring Cloud Commons doc](https://docs.spring.io/spring-cloud-commons/docs/2.2.4.RELEASE/reference/html/#refresh-scope) mentions:

> If you hava a DataSource bean that is a HikariDataSource, it can not be refreshed. It is the default value for spring.cloud.refresh.never-refreshable. Choose a different DataSource implementation if you need it to be refreshed.

Since HikariCP is the default CP solution for Spring Boot, can support be added to allow HikariCP datasource be refreshed?

**Comment by spencergibb** [comment]
No. The hikari implementation prevents it from being refreshable.
