### ISSUE TITLE
Decrypted values from environment variables not being picked up

### ISSUE THREAD

**Issue by tanob** [spring-cloud/spring-cloud-commons#87]
Given a Spring bean like this:

```java
@Component
public class Foo {
    private final String fooPassword;

    @Autowired
    public Foo(@Value("${foo.password}") String fooPassword) {
        System.out.println("foo password is " + fooPassword);
        this.fooPassword = fooPassword;
    }
}
```

when we run the app providing an `ENCRYPT_KEY` and an encrypted value for `foo.password` using the relaxed binding ([reference 1](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-relaxed-binding) and [reference 2](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-application-property-files)) through `FOO_PASSWORD`, it is not printing the decrypted value for `foo.password`:

```
$ ENCRYPT_KEY=foo FOO_PASSWORD={cipher}23cd3b5b92db6791c531fda2e2bdd51f2dd3d94d9f1de7b5ba932b5501dd72fc ./gradlew bootRun | grep "foo password is"
foo password is {cipher}23cd3b5b92db6791c531fda2e2bdd51f2dd3d94d9f1de7b5ba932b5501dd72fc
```

The expected output would be:

```
foo password is mypassword
```

The same works if we change the environment variable name to match the dot-syntax one:

```
$ env ENCRYPT_KEY=foo foo.password={cipher}23cd3b5b92db6791c531fda2e2bdd51f2dd3d94d9f1de7b5ba932b5501dd72fc ./gradlew bootRun | grep "foo password is"
foo password is mypassword
```

(Notice I'm using the `env` command to be able to pass an env variable with a dot in the name, [more info here](http://unix.stackexchange.com/a/93533))

You can see the full example here:
https://github.com/tanob/spring-relaxed-binding-and-decrypted-values

**Comment by dsyer** [comment]
This is nothing to do with encryption is it? You can't bind `FOO_VALUE` to `foo.value` with an `@Value`. Relaxed binding is a Spring Boot feature and `@Value` is from Spring Core. And none  of it is relevant for encryption or Spring Cloud.

**Comment by dsyer** [comment]
I see from the PR that you are making cunning use of `SystemEnvironmentPropertySource`. I'm not sure that's entirely kosher, but I'll have a think about it.

**Comment by tanob** [comment]
> You can't bind FOO_VALUE to foo.value with an `@Value`.

@dsyer Yes, you can, it's a feature in Spring Core:

https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/core/env/SystemEnvironmentPropertySource.java#L24-L36

Though I see that relaxed binding (Spring Boot) and `SystemEnvironmentPropertySource` (Spring Core) are different implementations for a similar goal: make it possible to override a property key from different sources (yaml, properties, command line, env variables) using the appropriate key syntax for that source. Maybe they need to me unified and merged into Spring Core?

Leaving that aside, what concerns do you have on using `SystemEnvironmentPropertySource` for now?

**Comment by dsyer** [comment]
My main concern is that properties that are not from the system environment might be in a `PropertySource` of type `SystemEnvironmentPropertySource`. I'm half way to thinking it's OK, but you know you can always use `@ConfigurationProperties` instead.
