### ISSUE TITLE
Misspelling in the LoadBalancer documentation

### ISSUE THREAD

**Issue by sergey-morenets** [spring-cloud/spring-cloud-commons#875]
**Describe the bug**

It seems that current version of Spring Cloud Commons 3.0.0 contains a misspelling:
https://docs.spring.io/spring-cloud-commons/docs/3.0.0-SNAPSHOT/reference/html/#rest-template-loadbalancer-client

This text states: 
`A load-balanced RestTemplate can be configured to retry failed requests. By default, this logic is disabled. For the non-reactive version (with RestTemplate), you can enable it by adding Spring Retry to your application’s classpath. For the reactive version (with WebTestClient), you need to set spring.cloud.loadbalancer.retry.enabled=false`.

I assume that the correct version would be (since we want to enable retry logic):
`you need to set spring.cloud.loadbalancer.retry.enabled=true.`

**Comment by OlgaMaciaszek** [comment]
That's right, @sergey-morenets . Thanks for reporting. Fixing it now.
