### ISSUE TITLE
Spring Cloud didn't find any configurations in bootstrap.yml

### ISSUE THREAD

**Issue by artemio77** [spring-cloud/spring-cloud-commons#876]
Spring Boot Version - 2.4.1
Spring Cloud Version- 2020.0.0-RC1
my bootstrap.yml content 
```
    spring:
      profiles:
        active: local
```

output:

![image](https://user-images.githubusercontent.com/25565701/103181344-c151c800-48a8-11eb-8833-15fb724db9c3.png)

And same application on dowgraded spring versions:
Spring Boot Version - 2.3.7.RELEASE
Spring Cloud Version- HOXTON.SR9

![image](https://user-images.githubusercontent.com/25565701/103181368-0f66cb80-48a9-11eb-8078-4f6e3ff88195.png)
 
It's work fine.

So on versions Spring Boot Version - 2.4.1 and Spring Cloud Version- 2020.0.0-RC1:
AR - spring profile must be local
ER - spring profile have default value

**Comment by spencergibb** [comment]
2020.0.0 has been released. See https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2020.0-Release-Notes#breaking-changes

**Comment by artemio77** [comment]
> 2020.0.0 has been released. See https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2020.0-Release-Notes#breaking-changes

So, have i right meaning about this? I must alway specify this property To re-enable by properties set spring.cloud.bootstrap.enabled=true in all my spring cloud services. To be onest, Its was not clearly for me.

**Comment by spencergibb** [comment]
The property is one way. spring-cloud-starter-bootstrap is another, or use `spring.config.import`

**Comment by artemio77** [comment]
> The property is one way. spring-cloud-starter-bootstrap is another, or use `spring.config.import`

Okay, thank you for support. I think we can close this issue.
