### ISSUE TITLE
Documentation issue with @LoadBalanced WebClient

### ISSUE THREAD

**Issue by sergey-morenets** [spring-cloud/spring-cloud-commons#877]
**Describe the bug**

Current version of documentation(https://docs.spring.io/spring-cloud-commons/docs/3.0.0-SNAPSHOT/reference/html) clearly states about using @LoadBalanced WebClient:

```
@Configuration
public class MyConfiguration {

    @Bean
    @LoadBalanced
    public WebClient.Builder loadBalancedWebClientBuilder() {
        return WebClient.builder();
    }
}

public class MyClass {
    @Autowired
    private WebClient.Builder webClientBuilder;

    public Mono<String> doOtherStuff() {
        return webClientBuilder.build().get().uri("http://stores/stores")
                        .retrieve().bodyToMono(String.class);
    }
}
```

However this code will not work if DiscoveryClientServiceInstanceListSupplier service supplier is used. Because it requires loadbalancer.client.name property initialized. I couldn't find any mentions about this property in the documentation.

Another thing is that creating new WebClient instance per request is quite expensive.  It's possible to declare a WebClient bean explicitly:

```
    @Bean
    public WebClient webClient(ReactorLoadBalancerExchangeFilterFunction loadBalancerExchangeFilterFunction) {
        return WebClient.builder()
                .filter(loadBalancerExchangeFilterFunction)
                .build();
    }
```

And it'd be nice to mention this use-case in the documentation as well.

**Comment by OlgaMaciaszek** [comment]
The configuration does work out of the box with the LB starter. You can see [this working sample](https://github.com/spring-cloud-samples/spring-cloud-intro-demo/blob/master/card-service/src/main/java/org/example/cardservice/config/RestTemplateConfig.java) as a reference. Also, the other setup is shown [here](https://docs.spring.io/spring-cloud-commons/docs/current/reference/html/#webflux-with-reactive-loadbalancer).

**Comment by sergey-morenets** [comment]
> 
> 
> The configuration does work out of the box with the LB starter. You can see [this working sample](https://github.com/spring-cloud-samples/spring-cloud-intro-demo/blob/master/card-service/src/main/java/org/example/cardservice/config/RestTemplateConfig.java) as a reference. Also, the other setup is shown [here](https://docs.spring.io/spring-cloud-commons/docs/current/reference/html/#webflux-with-reactive-loadbalancer).

Hi @OlgaMaciaszek 

Thank you for the answer but the provided working sample is about RestTemplate and my question was about WebClient.
Regarding the proposed setup chapter  - that's fine. But again the code in the chapter will create new WebClient instance per HTTP request. This might be resource consuming so creating WebClient bean will be more efficient solution.

**Comment by OlgaMaciaszek** [comment]
@sergey-morenets feel free to provide a PR with the suggested documentation change and we will review it.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
