### ISSUE TITLE
encrypt.fail-on-error Ignored by DecryptEnvironmentPostProcessor 

### ISSUE THREAD

**Issue by agisbert** [spring-cloud/spring-cloud-commons#882]
### Old behavior - _Hoxton, Greenwich, Finchley..._ 
The old `EnvironmentDecryptApplicationInitializer` bean creation process took into account the `encrypt.fail-on-error` property by calling `setFailOnError`: 

_**EncryptionBootstrapConfiguration**_
```
	@Bean
	public EnvironmentDecryptApplicationInitializer environmentDecryptApplicationListener(
			ConfigurableApplicationContext context, KeyProperties keyProperties) {
		TextEncryptor encryptor;
		try {
			encryptor = context.getBean(TextEncryptor.class);
		}
		catch (NoSuchBeanDefinitionException e) {
			encryptor = new FailsafeTextEncryptor();
		}
		EnvironmentDecryptApplicationInitializer listener = new EnvironmentDecryptApplicationInitializer(encryptor);
		listener.setFailOnError(keyProperties.isFailOnError());
		return listener;
	}
```

### Current behavior - _2020.0.0_
The new `DecryptEnvironmentPostProcessor` however doesn't make use of a custom initialization/creation, and by the time it tries to decrypt all the encrypted properties, the value of `AbstractEnvironmentDecrypt#failOnError` attribute has its default value (**true**). 

As opposed to the previous implementation, It creates the text encryptor on the fly right before decrypting the properties (methods `DecryptEnvironmentPostProcessor#postProcessEnvironment` & `DecryptEnvironmentPostProcessor#getTextEncryptor`) but misses to call `setFailOnError` with the `keyProperties.isFailOnError()` value.

Then, of course, when decrypting with a no/wrong key, it throws the exception even when `encrypt.fail-on-error` is set to **false**. 

**_AbstractEnvironmentDecrypt_**
```
	protected String decrypt(TextEncryptor encryptor, String key, String original) {
		String value = original.substring(ENCRYPTED_PROPERTY_PREFIX.length());
		try {
			value = encryptor.decrypt(value);
			if (logger.isDebugEnabled()) {
				logger.debug("Decrypted: key=" + key);
			}
			return value;
		}
		catch (Exception e) {
			String message = "Cannot decrypt: key=" + key;
			if (logger.isDebugEnabled()) {
				logger.warn(message, e);
			}
			else {
				logger.warn(message);
			}
			if (this.failOnError) {
				throw new IllegalStateException(message, e);
			}
			return "";
		}
	}
```

## SUGGESTION
The fix could be based on:

1. Creating a `DecryptEnvironmentPostProcessor` default constructor, performing the configuration in the same fashion as the old `EnvironmentDecryptApplicationInitializer` (calling setFailOnError and creating the encryptors)
2. Hooking into the `DecryptEnvironmentPostProcessor#getTextEncryptor` and calling `setFailOnError`

**Comment by spencergibb** [comment]
It would need to be the 2nd option. `AbstractEnvironmentDecrypt` already has a `setFailOnError()` method.

**Comment by agisbert** [comment]
@spencergibb, I´ll submit a PR by today, if ok for you?

**Comment by spencergibb** [comment]
Sorry @agisbert, I already had a fix and was just running a build.
