### ISSUE TITLE
BootstrapApplicationListener creates a new context and ignores previous context's applicationStartup 

### ISSUE THREAD

**Issue by cr-kobyisrael** [spring-cloud/spring-cloud-commons#884]
**Describe the bug**
I'm using Spring cloud version 3.0.0 with spring boot 2.4.1, when trying to use the [new actuator startup endpoint](https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-application-startup-tracking) along with the spring-cloud-starter-bootstrap (for configuration from consul), error is thrown since [StartupEndpoint](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/startup/StartupEndpointAutoConfiguration.java#L47) depends on the BufferingApplicationStartup. 

Problem is in [BootstrapApplicationListener.java](https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/BootstrapApplicationListener.java#L197) builder ignoring previous ApplicationStartup

**Sample**
Pretty straight forward, add spring-cloud-starter-bootstrap dependency, add the [BufferingApplicationStartup](https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-application-startup-tracking) after i run the app, it fails with the error:

> Parameter 0 of method startupEndpoint in org.springframework.boot.actuate.autoconfigure.startup.StartupEndpointAutoConfiguration required a bean of type 'org.springframework.boot.context.metrics.buffering.BufferingApplicationStartup' that could not be found.

**Comment by spencergibb** [comment]
Is there a reason you are using `spring-cloud-starter-bootstrap` and not `spring.config.import=consul:`?

**Comment by cr-kobyisrael** [comment]
No special reason, tried that as well, same result, missing BufferingApplicationStartup bean, but this time i do see bootstrap is not kicking in. can't find where we register BufferingApplicationStartup as bean.

Relevant logs: 

> StartupEndpointAutoConfiguration matched:
      - ApplicationStartup configured applicationStartup is of type BufferingApplicationStartup. (StartupEndpointAutoConfiguration.ApplicationStartupCondition)
      - @ConditionalOnAvailableEndpoint found property management.endpoint.startup.enabled with value true; @ConditionalOnAvailableEndpoint marked as exposed by a 'management.endpoints.web.exposure' property (OnAvailableEndpointCondition)

> org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.boot.context.metrics.buffering.BufferingApplicationStartup' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}

**Comment by spencergibb** [comment]
When you tried `spring.config.import` did you remove `spring-cloud-starter-bootstrap`?

**Comment by cr-kobyisrael** [comment]
I did remove the spring-cloud-starter-bootstrap, also totally removed the bootstrap.yml and made sure i hit [this line](https://github.com/spring-cloud/spring-cloud-commons/blob/v3.0.0/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/BootstrapApplicationListener.java#L100)

**Comment by spencergibb** [comment]
At that point spring cloud isn't involved. https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-application-startup-tracking

**Comment by cr-kobyisrael** [comment]
That makes sense, i'll open an issue in spring boot repo, thanks!
