### ISSUE TITLE
Spring Boot 2.4 config file processing changed cause issue

### ISSUE THREAD

**Issue by wuzhefang** [spring-cloud/spring-cloud-commons#885]
According to the new config file processing in spring boot 2.4

file: spring-cloud-commons/spring-cloud-context/src/main/resources/META-INF/spring.factories

```
org.springframework.cloud.bootstrap.BootstrapConfiguration=\
org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration,\
```

Could not loaded correctly,  because the new processing just load the class with the right type. In this case, it should be under org.springframework.context.ApplicationContextInitializer

modify to:

```
org.springframework.context.ApplicationContextInitializer=\
org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration
```

should fix this.

And I think maybe there are several places like this need to be repared. Hope to focus on this in the furture versions.

**Comment by spencergibb** [comment]
No. See https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2020.0-Release-Notes#breaking-changes
