### ISSUE TITLE
`defaultProperties` property source is not propagated to the new context created in the LegacyContextRefresher for refreshing properties

### ISSUE THREAD

**Issue by mzeijen** [spring-cloud/spring-cloud-commons#892]
Bug introduced with Spring Cloud Context version: 3.0.0

When the `LegacyContextRefresher` is used to refresh the Spring environment properties, the temporary context created by the LegacyContextRefresher, does no longer get the `defaultProperties` property source propagated from the original environment. 

The reason for this is because the `properties` method of the `SpringApplicationBuilder` is now used to provide the `spring.cloud.bootstrap.enabled=true` property to the builder. This results in the `defaultProperties` property source from the copied environment to be overwritten by a new property map containing only the `spring.cloud.bootstrap.enabled` property.

To put this in sequence (with line references to the code):

- [`LegacyContextRefresher#updateEnvironment`](https://github.com/spring-cloud/spring-cloud-commons/blob/v3.0.1/spring-cloud-context/src/main/java/org/springframework/cloud/context/refresh/LegacyContextRefresher.java#L45) get called to update the environment
- It calls the [`addConfigFilesToEnvironment`](https://github.com/spring-cloud/spring-cloud-commons/blob/v3.0.1/spring-cloud-context/src/main/java/org/springframework/cloud/context/refresh/LegacyContextRefresher.java#L49) method
- [The `copyEnvironment` is used](https://github.com/spring-cloud/spring-cloud-commons/blob/v3.0.1/spring-cloud-context/src/main/java/org/springframework/cloud/context/refresh/LegacyContextRefresher.java#L52) to copy the `defaultProperties` and `commandLineArgs` property sources from the environment of the real context
- A `SpringApplicationBuilder` is created and it gets that copied environment but also the  `spring.cloud.bootstrap.enabled=true` property [via the `properties` build method](https://github.com/spring-cloud/spring-cloud-commons/blob/v3.0.1/spring-cloud-context/src/main/java/org/springframework/cloud/context/refresh/LegacyContextRefresher.java#L54).
- [The `builder.run()` is called](https://github.com/spring-cloud/spring-cloud-commons/blob/v3.0.1/spring-cloud-context/src/main/java/org/springframework/cloud/context/refresh/LegacyContextRefresher.java#L60) to build the temporary context and in this method:
   - the environment is prepared where it configures the property sources
   - [here it is checked if the `SpringApplicationBuilder` has any properties](https://github.com/spring-projects/spring-boot/blob/v2.4.2/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/SpringApplication.java#L516)
   - because the `spring.cloud.bootstrap.enabled=true` property is set on the `SpringApplicationBuilder` [it will create a new `DefaultPropertiesPropertySource`](https://github.com/spring-projects/spring-boot/blob/v2.4.2/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/DefaultPropertiesPropertySource.java#L71) and overwrite the one from the copied environment. Thus the original default properties are lost.

The solution would be to provide the `spring.cloud.bootstrap.enabled=true` via other means, for instance by adding it to the default properties of the copied environment, instead of using the `properties` method of the `SpringApplicationBuilder`.

**Comment by slyoldfox** [comment]
Also spend 3 hours to find this same case. I am not sure if this is a spring-cloud bug or also a spring-boot bug. Seems to me that `DefaultPropertiesPropertySource` might want to merge if another `DefaultPropertiesPropertySource` exists?

Could this be confirmed or am I doing something wrong, any workarounds? @philwebb

**Comment by philwebb** [comment]
@slyoldfox I think that makes sense. I don't think we ever considered the scenario before. I've raised https://github.com/spring-projects/spring-boot/issues/25408
