### ISSUE TITLE
Problem with `RefreshScope`, updating only once

### ISSUE THREAD

**Issue by ShubhraShrivastava45** [spring-cloud/spring-cloud-commons#894]
Hi,
I am using Springboot 2.1.2 Release and spring.cloud.version Greenwich.SR1.
But the beans marked with @RefreshScope are refreshed only once.
I see other threads where it is mentioned it is resolved in 2.0.* Release and Spring cloud Finchley, and need to set the spring.bus.cloud.id .
I have added this proeprty in application.properties, but still my beans are refreshed only once.
Can you please tell is it resolved in 2.1.2 release also, and what should be done to resolve this.

**Comment by spencergibb** [comment]
Greenwich is no longer supported. Please update to 2020.0.1 and boot 2.4.x and try again.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by ShubhraShrivastava45** [comment]
Thanks..I will try with above suggestions
