### ISSUE TITLE
HikariDataSource is not treated as never-refreshable when proxied twice

### ISSUE THREAD

**Issue by ovgusev** [spring-cloud/spring-cloud-commons#898]
**Describe the bug**
If HikariDataSource bean gets AOP-proxied more than once, the spring-cloud *rebind* opertaion doesnt treat it as never-refreshable.

**Suggested solution**
In method *org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder#rebind(java.lang.String)* is used *ProxyUtils#getTargetObject* to identifiy the class of target-bean.
We suggest to implement *ProxyUtils#getUltimateTargetObject* to get initial bean recursively. And switch logic of never-refreshable HikariDataSource to it.

**Comment by spencergibb** [comment]
PR?

**Comment by ovgusev** [comment]
Done https://github.com/spring-cloud/spring-cloud-commons/pull/907
