### ISSUE TITLE
spring-cloud-loadbalancer: refetching of instances does not work when repeated health checking is enabled

### ISSUE THREAD

**Issue by rchigvintsev** [spring-cloud/spring-cloud-commons#899]
**spring-cloud-loadbalancer-3.0.0**

When health checking is enabled (property `spring.cloud.loadbalancer.configurations` is set to `health-check`) and it is repeated (property `spring.cloud.loadbalancer.health-check.repeat-health-check` is set to `true`) `HealthCheckServiceInstanceListSupplier` is not able to refetch service instances (property `spring.cloud.loadbalancer.health-check.refetch-instances` is set to `true`): instance providing `Flux` is executed only once.

Possible solution is to call `.repeatWhen` right after `Flux.defer(delegate)` in the constructor of `HealthCheckServiceInstanceListSupplier`.

**Comment by OlgaMaciaszek** [comment]
@rchigvintsev thanks for reporting this. Indeed, it's a bug.
