### ISSUE TITLE
Create ServiceRegistry interface with register/unregister

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-commons#9]

**Comment by dsyer** [comment]
I would argue that register/unregister is a "registry" concern not a "discovery" concern. New interface?

**Comment by spencergibb** [comment]
Sure `s-c-commons-client-registry.Registry`?   I don't like that `client` is in the package structure in commons.

**Comment by dsyer** [comment]
`ServiceRegistry` is what most people call it I guess? We can take the "client" out of the package name if you prefer, but isn't it better to be explicit about that (in case someone thinks they can use that package to implement a server)?

**Comment by spencergibb** [comment]
`ServiceRegistry` it is.  I was worried about having "client" in the package, just second guessing myself.

**Comment by spencergibb** [comment]
hmm, there doesn't seem to be a way to arbitrarily register services with eureka v1.  All their usage of statics limits registration to the current instance.  I saw register looking something like

```
public void register(ServerInstance);
```
