### ISSUE TITLE
Add support for query parameters in loadbalancer health-check

### ISSUE THREAD

**Issue by wpstan** [spring-cloud/spring-cloud-commons#906]
`spring.cloud.loadbalancer.health-check.path.default=/api/test?view=monitor`
When I configured the path with a special character `?` 。it was automatically converted to a URI encoding %3F,  causing the request to fail.

How to solve this problem?
thanks

**Comment by spencergibb** [comment]
It is probably because of how we construct the full URL in `ServiceInstanceListSupplierBuilder` assumes the path is just that, a path, not a path and request parameters (which are very distinct from a URI perspective).

**Comment by njoysubho** [comment]
Hello,
Is it fine if I take this issue and try to solve it ?

**Comment by OlgaMaciaszek** [comment]
@njoysubho yes, please go ahead and submit a PR.

**Comment by njoysubho** [comment]
[PR](https://github.com/spring-cloud/spring-cloud-commons/pull/982) submitted. Thanks.

**Comment by OlgaMaciaszek** [comment]
Fixed with https://github.com/spring-cloud/spring-cloud-commons/commit/de32d2b68c6f980c44855406a4c4fdd6e20f2fb6.
