### ISSUE TITLE
loadbalancer: configuring ServiceInstanceListSupplier as shown in documentation causes no instances being discovered 

### ISSUE THREAD

**Issue by alfonz19** [spring-cloud/spring-cloud-commons#922]
In provided minimal example if ServiceInstanceListSupplier is **not** configured, and instances are configured in properties files as:

spring.cloud.discovery.client.simple.instances.complicated[0].uri=http://localhost:8886
spring.cloud.discovery.client.simple.instances.complicated[1].uri=http://localhost:8887

it **will work**. The all configuration provided by me is:

```
    @Bean
    public LoadBalancerClientFactory loadBalancerClientFactory() {
        return new LoadBalancerClientFactory();
    }

    @Bean
    public ReactorLoadBalancerExchangeFilterFunction loadBalancerExchangeFilterFunction(LoadBalancerProperties properties) {
        return new ReactorLoadBalancerExchangeFilterFunction(loadBalancerClientFactory(), properties);
    }
```

and webclient call looks like:

```
    WebClient webClient = WebClient.builder()
                .baseUrl("http://complicated/test-consumer")
                .filter(lbFunction)
                .build();
        
        ...
        webClient.post()
                .body(Mono.just(e), String.class)
                .retrieve()
                .bodyToMono(String.class)
        ...
```

Now if I add this bean:

```
    @Bean
    public ServiceInstanceListSupplier instanceSupplier(ConfigurableApplicationContext context) {
        return ServiceInstanceListSupplier.builder()
                .withDiscoveryClient()
                .withHealthChecks()
                .build(context);
    }
```

it stop working, because:

```
o.s.c.l.core.RoundRobinLoadBalancer      : No servers available for service: complicated
eactorLoadBalancerExchangeFilterFunction : LoadBalancer does not contain an instance for the service complicated
```

I can see, that "complicated" serviceId is being registered, and added to Environment, but I can also see, that:

`this.serviceId = environment.getProperty(PROPERTY_NAME);`

in `org.springframework.cloud.loadbalancer.core.DiscoveryClientServiceInstanceListSupplier#DiscoveryClientServiceInstanceListSupplier(org.springframework.cloud.client.discovery.ReactiveDiscoveryClient, org.springframework.core.env.Environment)`

will be evaluated as null **after** this property has been set into environment, thus while I have `ServiceInstances` configured, I'm asking for correct `serviceId` and given `serviceId` has configuration in `environment`, for some reason it is not found out and no ServiceInstances are returned, failing the whole flow.

I tried to ask on stackoverflow as wall, but so far no response (https://stackoverflow.com/questions/66534708/configuring-spring-cloud-loadbalancer-without-autoconfiguration). If this is normal behavior, please explain / consider to document using full example how to correctly configure it. As it is super unclear from documentation / all tutorials (most of them by 3rd party) on web, and source code is super-super super complicated for what it does to be able to find out, what is misaligned.

https://github.com/alfonz19/loadbalancer-minimal-example

**Comment by OlgaMaciaszek** [comment]
@alfonz19  The LoadBalancer config should not be in a `@Configuration`-annotated class; instead, it should be a class passed for config via `@LoadBalancerClient` or `@LoadBalancerClients` annotation, as described [here](https://docs.spring.io/spring-cloud-commons/docs/current/reference/html/#custom-loadbalancer-configuration). It probably makes sense to stress that in the documentation, though, - will do it. 

Also, the only bean you need to instantiate is the `ServiceInstanceListSupplier` (if you add `spring-cloud-starter-loadbalancer`, `LoadBalancerClientFactory`, and `ReactorLoadBalancerExchangeFilterFunction` will be instantiated by the starter).

So your LB config class will look like so:

```
public class AppConfig {

    @Bean
    public ServiceInstanceListSupplier instanceSupplier(ConfigurableApplicationContext context) {
        return ServiceInstanceListSupplier.builder()
                .withDiscoveryClient()
                .withHealthChecks()
                .build(context);
    }

}
```

and your `@Configuration` class (in the case of this mini-sample, probably `Main.java`), will have the following annotation: `@LoadBalancerClients(defaultConfiguration = AppConfig.class)`.

Then if you enable health-checks in the `complicated` instances, it should work without any problems.
