### ISSUE TITLE
Any plans about adding out of the box support for refresh on file changes?

### ISSUE THREAD

**Issue by zeldigas** [spring-cloud/spring-cloud-commons#924]
**Is your feature request related to a problem? Please describe.**
I'm currently working on deploying my app to k8s and would like to use it's ConfigMap and Secrets feature to provide configuration params. Prior to that I used consul to distribute app configs and spring-cloud-consul-config to get yaml from consul. Reload functionality was widely used as well (really handy for logging reconfiguration in runtime)

From what I can see by reading through the docs, if I want to preserve "hot-reload" functionality, reliable option so far is to use spring-cloud-kubernetes-config with api approach to read config maps.

While this works, it requires extra RBAC configuration for k8s api and I'd say looks like an overkill especially given the fact that the only added value is monitoring of configmap change, compared to `spring.config.import` introduced recently (if we are talking only about configuration part).

**Describe the solution you'd like**
I'd like to have a built-in feature to enable monitoring changes of configuration sourced from files specified in `spring.config.import`, (potentially via some flag that enables this functionality). This would allow me to simply specify config location like this:
```
spring.config.import=configtree:/etc/secrets,/etc/config/application.yml
spring.cloud.config-import.reload-on-file-changes=true
```
And be sure that config refreshed, e.g. via `contextRefresher.refresh()` call when `/etc/config/application.yml` provided from config map or some secret in `/etc/secrets` dir will change 

**Describe alternatives you've considered**
1. [Configuration watcher](https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/#spring-cloud-kubernetes-configuration-watcher) can be an option, but deploying a dedicated container for this simple task looks like too much effort (as it also requires same RBAC configuration + exposing actuator endpoint or configuring config bus)
2. I'm also considering doing a simple external library that would watch for configtree dirs and individual files and trigger context refresher

**Additional context**
Reference docs about configuring k8s config lib: https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/#propertysource-reload

There is a disclaimer that this functionality is deprecated, but I'm not sure if api reload is also planned to be removed in future

**Comment by ryanjbaxter** [comment]
The current solution is to use the Configuration watcher.  We added this solution because that way only that app needs the RBAC configuration instead of every app needing it.  We have no plans to add a file watcher in Spring Cloud Commons but it is certainly something you can add yourself.

**Comment by zeldigas** [comment]
@ryanjbaxter thank you for reply. Maybe you can clarify one thing that is not clear to me - if ConfigMap access via api and it's dynamic reload is completely deprecated feature in spring-cloud-kubernetes that is scheduled for removal in one of next releases? From [docs](https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/#propertysource-reload) it's not clear to me.

The reason I'm asking is that current approach looks fine in case when dynamic reload is requried, compared to Configuration watcher deployment, so I wonder can we safely use it further or soon (or not) I'd have to make a choice configuration watcher or another solution (e.g. custom file watcher for mounts)

**Comment by ryanjbaxter** [comment]
> if ConfigMap access via api and it's dynamic reload is completely deprecated feature in spring-cloud-kubernetes that is scheduled for removal in one of next releases?

Yes it is and the configuration watcher is the replacement.

**Comment by zeldigas** [comment]
@ryanjbaxter thank you for clarifications. Given that I'll evaluate approach with monitoring of mounted files from config map.
