### ISSUE TITLE
Property type is ignored when loading encryption keystore

### ISSUE THREAD

**Issue by bberto** [spring-cloud/spring-cloud-commons#953]
Property `encrypt.key-store.type` is ignored when loading encryption keystore. The keystore type is retrieved from file extension (eg: .pkcs12).

Can be easily reproduced using these settings:
```
encrypt:
  key-store:
    type: PKCS12
    alias: encrypt
    location: classpath:encrypt.p12
    password: 123456
```

That leads to this exception:
```
java.lang.IllegalStateException: Cannot load keys from store: class path resource [encrypt.p12]
...
Caused by: java.security.KeyStoreException: p12 not found
...
Caused by: java.security.NoSuchAlgorithmException: p12 KeyStore not available
```

I think the root cause is here:
https://github.com/spring-cloud/spring-cloud-commons/blob/6ed50fcbc7ab9e41eac5eb4641cde952fa81823e/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/encrypt/TextEncryptorUtils.java#L123

and can be solved using a different `KeyStoreKeyFactory` constructor (including type as parameter):
https://github.com/dsyer/spring-security-rsa/blob/d194f8969083af6987904f05eaf12b2dbae642a7/src/main/java/org/springframework/security/rsa/crypto/KeyStoreKeyFactory.java#L52

**Comment by ryanjbaxter** [comment]
What version of Spring Cloud?

If you have a fix, would you be interested in contributing the fix?

**Comment by bberto** [comment]
Tester with 2020.0.2 release train.

PR provided
