### ISSUE TITLE
Offer support for Gradle's platform feature

### ISSUE THREAD

**Issue by fdw** [spring-cloud/spring-cloud-commons#959]
**Is your feature request related to a problem? Please describe.**
Besides the Dependency Management plugin, Spring Boot also offers support for Gradle's own Platform feature: https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/htmlsingle/#managing-dependencies.gradle-bom-support

While it has a smaller feature set, it seems to also be quicker in resolving dependencies. As we don't need the additional features, it would be nice to use Platform directly.

**Describe the solution you'd like**
We would like to see support for Gradle's Platform to enforce dependency versions, as it is supposed to be quicker than the Dependency Management plugin.

**Describe alternatives you've considered**
We're currenctly using the Dependency Management Plugin, and it is working, but slow.

**Comment by spencergibb** [comment]
I'm afraid I don't know what that would look like on our side. We don't do anything gradle specific. We don't offer a gradle plugin for the constant of group,artifact,version. Using gradle platform should just work.
