### ISSUE TITLE
@RefreshScope doesn't affect @Scheduled methods

### ISSUE THREAD

**Issue by sqshq** [spring-cloud/spring-cloud-commons#97]
I'm using Cloud Config Server and Client. Everything works perfectly, except dynamic properties refresh in @Scheduled methods. 

Here is a Controller and scheduled method (all in one class, for clear example):

```java
@RestController
@RefreshScope
public class NotificationController {

	@Value("${delay.value}")
	private String value;

	@RequestMapping(path = "/value", method = RequestMethod.GET)
	public String getValue() {
		return value;
	}

	@Scheduled(fixedDelayString = "${delay.value}")
	public void print() {
		System.out.println(value);
	}
}

```

When I update `delay.value` in Config Server and refresh Client with `curl -XPOST http://localhost:8080/refresh`, I can see that change with controller `getValue()` method.

But `print()` method continues printing old value with the same delay.

It doesn't seem to me as expected behavior, and I can't find this limitation [in documentation](http://projects.spring.io/spring-cloud/spring-cloud.html#_refresh_scope).

If it is not a known issue, I can share a minimal sample project.

**Comment by dsyer** [comment]
It's a known issue and it can't be fixed in Spring Cloud as far as I know. The scheduling infrastructure doesn't know that you want to change the trigger and it is the trigger that needs to be refreshed not the bean with the `@Scheduled` annotation. If you want, we can document the limitation.

I think you can achieve your goal by configuring the trigger manually and making that into a bean in `@RefreshScope`.

**Comment by sqshq** [comment]
Ok, thank you for clearing that up. I'll configure my trigger manually.

**Comment by magaton** [comment]
Could you provide an example how to configure the trigger manually?

**Comment by dsyer** [comment]
Look at `SchedulingConfigurer` (javadocs are fairly clear, but you can probably find samples on the interweb as well if you want to copy-paste).

**Comment by winster** [comment]
I know it is closed, but I managed to use Scheduled and RefreshScope together with the help of RefreshScopeRefreshedEvent. You can find a sample app here https://github.com/winster/SpringSchedulerDynamic

But after adding tracing libraries to the classpath, the old triggers are not terminated.
