### ISSUE TITLE
healthcheck uri on different port than service instance port

### ISSUE THREAD

**Issue by RaphC** [spring-cloud/spring-cloud-commons#976]
Hi all,

I'm using "simple" spring-cloud-loadbalancer with bootiful service which has different ports between management and server. In the current version of spring-cloud-loadbalancer (Hoxton.SR11) we have no mean to define a health check port which is not the "uri" port (or port attribute) of the service instance. 

It would be nice to define either an absolute health-check uri per service (even per simple instance. Not necessary for service registry backed client) or define a health-check port.

As a workaround, we override HealthCheckServiceInstanceListSupplier to compute a custom health check uri.

Do you have any suggestion to achieve this ?

Regards

**Comment by OlgaMaciaszek** [comment]
Hi @MarneusCalgarXP - you're right, it should be better documented. Would you like to submit a documentation PR with this information?

**Comment by RaphC** [comment]
Hi @OlgaMaciaszek, I guess you talk about another issue. What do you mean about documentation ? 
Regards

**Comment by OlgaMaciaszek** [comment]
Yes, @RaphC , sorry, that comment was supposed to go to a different issue.

**Comment by OlgaMaciaszek** [comment]
@RaphC thanks for submitting this. Makes sense - will add this option.

**Comment by OlgaMaciaszek** [comment]
Actually, I'm thinking it's a good first issue, so I'm going to mark it as such and see if someone from the community would like to give it a try.

**Comment by RaphC** [comment]
Thanks @OlgaMaciaszek

**Comment by OlgaMaciaszek** [comment]
> However I wonder how you managed to "override HealthCheckServiceInstanceListSupplier" as this class is directly instanciated by `ServiceInstanceListSupplierBuilder` with no way to override it :-/

@ngmip You can [provide custom configuration](https://docs.spring.io/spring-cloud-commons/docs/current/reference/html/#custom-loadbalancer-configuration).

**Comment by OlgaMaciaszek** [comment]
Since there are no PRs from first-time contributors for this issue so far and I would like to get into the upcoming release, I will get this issue done this week.

**Comment by RaphC** [comment]
Thank you @OlgaMaciaszek.
