### ISSUE TITLE
LoggingRebinder requires logging levels to be in upper case

### ISSUE THREAD

**Issue by wilkinsona** [spring-cloud/spring-cloud-commons#98]
Spring Boot logging level is case-insensitive, and also coerces `false` to `OFF`. `LoggingRebinder` should provide the same behaviour.

See spring-projects/spring-boot#5327

**Comment by shakuzen** [comment]
@dsyer Is there a commit related to this or was it closed by mistake?

**Comment by dsyer** [comment]
7eccbc4ba
