### ISSUE TITLE
DecryptEnvironmentPostProcessor does not work for legacy processing.

### ISSUE THREAD

**Issue by Fachher** [spring-cloud/spring-cloud-commons#980]
**Describe the bug**
Spring cloud version: 2020.0.0

When spring.config.use-legacy-processing is set to true, DecryptEnvironmentPostProcessor does not decrypt properties. 

Scenario: Currently I am upgrading our spring boot application from 2.3.11.RELEASE to 2.5.2. We are doing it in two steps. In our first step we want to keep our profiles as they are before fixing it in step two. Therefor we are using legacy processing in our first step. 

Our assumption: This should not change the way how spring cloud decrypt our properties. Currently it does not work. Thanks to our test, we found it before deploying to production.

**Comment by ryanjbaxter** [comment]
We do not support Boot 2.5.x yet, can you try with Boot 2.4.x?  If you are able to reproduce it please provide a sample.

**Comment by Fachher** [comment]
Could you please explain, why you are checking here for the legacy flag been set?

`if (bootstrapEnabled(environment) || **useLegacyProcessing(environment)**) {
			return;
}`

In a second project where we haven't postponed the restructuring of the spring profiles, the latest Spring Boot version works without any problems.

**Comment by ryanjbaxter** [comment]
Because I believe in the bootstrap and legacy processing case we use this class
https://github.com/spring-cloud/spring-cloud-commons/blob/087b94a905c5428c89e4db22a6a284999d5d0a7d/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/encrypt/EnvironmentDecryptApplicationInitializer.java#L46

**Comment by Fachher** [comment]
Okay thank you @ryanjbaxter.
I have enabled spring.cloud.bootstrap.enabled=true and now it is working.
