### ISSUE TITLE
Spring Cloud commons how to change ServiceInstanceMetadata

### ISSUE THREAD

**Issue by huifer** [spring-cloud/spring-cloud-commons#998]
Spring Cloud commons how to change ServiceInstanceMetadata

**Comment by OlgaMaciaszek** [comment]
That depends on the Service Discovery tool you use. For example, for Eureka, you can set `eureka.instance.metadata-map.property=value` via properties.

**Comment by huifer** [comment]
If it depends on Service Discovery, I would feel that this is a behavior made by Service Discovery independently and whether it is necessary to put it in Spring Cloud Commons for unified processing

**Comment by OlgaMaciaszek** [comment]
Yes, it does - it depends on particular SD implementations. We allow using it, but the metadata values belong to service instance data, which is something managed by Service Discovery. In Spring Cloud, we use this data for load-balancing, routing, etc., but the source of truth is always SD.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by huifer** [comment]
Ok, you can close this, I think [the](github.com/spring-cloud/spring-cloud-commons/issues/999) discussion here is more valuable
